import { ExpansionCandidate } from '../validator';

/**
 * Batch 6: 시큐어 코딩 실무 시나리오 & 취약점 방어 (공식 실기 범위 9.2)
 * 목표: 20문항 엄선 (출제각도: SCENARIO, SHORT_CODE, COMPARISON, IDENTIFICATION 등)
 */
export const BATCH6_CANDIDATES: ExpansionCandidate[] = [
  {
    id: 'EXP26_SEC_001',
    subject: '신기술/보안',
    category: '시큐어 코딩',
    subCategory: 'SQL 인젝션 방어',
    type: 'SHORT_ANSWER',
    question: '동적 SQL 생성 시 사용자 입력값으로 인한 SQL 삽입(SQL Injection) 공격을 원천 차단하기 위해, SQL 문장을 미리 데이터베이스에 컴파일해 두고 사용자 입력값을 위치 지정자(?)에 파라미터(바인드 변수)로만 안전하게 매핑하는 자바 인터페이스 객체는 무엇인가?',
    answer: ['PreparedStatement', '프리페어드 스테이트먼트'],
    explanation: 'PreparedStatement는 쿼리 구조를 사전에 컴파일하여 사용자 입력 문자열이 SQL 명령어나 연산자로 해석되는 것을 완벽히 방어합니다.',
    difficulty: 'EASY',
    keywords: ['PreparedStatement', '바인드변수', 'SQL인젝션방어'],
    source: '2026 실기 핵심 보강',
    angle: 'SHORT_CODE',
    targetSubUnit: '9.2',
  },
  {
    id: 'EXP26_SEC_002',
    subject: '신기술/보안',
    category: '시큐어 코딩',
    subCategory: '크로스 사이트 스크립팅 방어',
    type: 'SHORT_ANSWER',
    question: 'XSS(Cross Site Scripting) 공격을 방지하기 위해 웹 브라우저가 스크립트 코드로 해석할 수 있는 위험한 특수문자(<, >, &, ", \' 등)를 &lt;, &gt;, &amp;, &quot;와 같은 안전한 대체 문자로 변환하는 보안 처리 기법을 무엇이라 하는가?',
    answer: ['HTML 치환', 'HTML 엔티티 변환', 'HTML 인코딩', 'HTML 이스케이프'],
    explanation: 'HTML Entity Encoding(HTML 치환/인코딩)은 사용자가 입력한 악의적인 자바스크립트 태그가 브라우저에서 실행되지 않고 단순 텍스트로 안전하게 렌더링되도록 합니다.',
    difficulty: 'EASY',
    keywords: ['HTML 치환', 'HTML 인코딩', 'XSS방어'],
    source: '2026 실기 핵심 보강',
    angle: 'PROCESS_SEQUENCE',
    targetSubUnit: '9.2',
  },
  {
    id: 'EXP26_SEC_003',
    subject: '신기술/보안',
    category: '시큐어 코딩',
    subCategory: '사이트 간 요청 위조 방어',
    type: 'SHORT_ANSWER',
    question: 'CSRF(Cross Site Request Forgery) 공격을 방어하기 위해, 사용자의 정상 요청 시 서버가 매 세션 또는 폼 요청마다 예측 불가능한 임의의 고유 난수 값을 생성하여 폼에 은닉(hidden) 필드로 심고, 요청 시 제출된 값과 세션 값을 비교 검증하는 보안 토큰 기법은 무엇인가?',
    answer: ['CSRF 토큰', 'CSRF Token', '안티 CSRF 토큰'],
    explanation: 'CSRF 토큰은 공격자가 외부 피싱 사이트에서 피해자의 권한으로 변조된 위조 요청을 보내더라도 토큰 값을 알 수 없어 서버에서 차단되도록 방어합니다.',
    difficulty: 'EASY',
    keywords: ['CSRF 토큰', 'CSRF방어', '보안토큰'],
    source: '2026 실기 핵심 보강',
    angle: 'SCENARIO',
    targetSubUnit: '9.2',
  },
  {
    id: 'EXP26_SEC_004',
    subject: '신기술/보안',
    category: '시큐어 코딩',
    subCategory: '시간 및 상태 취약점',
    type: 'SHORT_ANSWER',
    question: '자원을 검사하는 시점(Time of Check)과 해당 자원을 실제로 사용하는 시점(Time of Use) 사이에 시간 차이가 발생하여, 공격자가 권한 검사 통과 후 실제 접근 전 사이에 파일 심볼릭 링크나 내용을 바꿔치기하는 취약점을 뜻하는 영문 약어는 무엇인가?',
    answer: ['TOCTOU', 'Time of Check to Time of Use'],
    explanation: 'TOCTOU는 멀티스레드나 파일 I/O 환경에서 동기화 락(Lock) 없이 검사 시점과 사용 시점 사이에 발생하는 대표적인 레이스 컨디션 취약점입니다.',
    difficulty: 'MEDIUM',
    keywords: ['TOCTOU', '경쟁상태', '시간상태취약점'],
    source: '2026 실기 핵심 보강',
    angle: 'TERM_FROM_DEFINITION',
    targetSubUnit: '9.2',
  },
  {
    id: 'EXP26_SEC_005',
    subject: '신기술/보안',
    category: '시큐어 코딩',
    subCategory: '메모리 보안 취약점',
    type: 'SHORT_ANSWER',
    question: 'C언어에서 메모리 동적 할당(malloc) 후 free() 함수로 반환된 메모리 포인터를 해제한 뒤에도 NULL로 초기화하지 않고 계속 참조하거나 재사용할 때 발생하는 치명적인 메모리 보안 취약점의 영문 명칭은 무엇인가?',
    answer: ['Use-After-Free', 'UAF', '해제된 메모리 재참조'],
    explanation: 'UAF(Use After Free) 취약점은 해제된 힙 메모리 영역에 공격자가 악의적인 코드를 덮어씌워 임의 코드 실행 권한을 획득하게 만듭니다.',
    difficulty: 'HARD',
    keywords: ['Use-After-Free', 'UAF', '메모리취약점'],
    source: '2026 실기 핵심 보강',
    angle: 'TERM_FROM_DEFINITION',
    targetSubUnit: '9.2',
  },
  {
    id: 'EXP26_SEC_006',
    subject: '신기술/보안',
    category: '시큐어 코딩',
    subCategory: '메모리 보안 취약점',
    type: 'SHORT_ANSWER',
    question: 'C언어의 문자열 복사 함수 중 버퍼 오버플로우 취약점을 유발하는 보안상 위험한 strcpy(), strcat() 대신, 복사할 최대 버퍼 크기(N)를 세 번째 인자로 명시하여 메모리 경계를 넘지 않도록 제한하는 안전한 함수는 무엇인가?',
    answer: ['strncpy', 'strncpy()'],
    explanation: 'strncpy() 및 strncat()은 지정한 바이트 수(n)만큼만 복사하여 할당된 대상 버퍼를 초과하는 스택 버퍼 오버플로우를 예방합니다.',
    difficulty: 'EASY',
    keywords: ['strncpy', '버퍼오버플로우방어', '안전한문자열함수'],
    source: '2026 실기 핵심 보강',
    angle: 'COMPARISON',
    targetSubUnit: '9.2',
  },
  {
    id: 'EXP26_SEC_007',
    subject: '신기술/보안',
    category: '시큐어 코딩',
    subCategory: '코드 오류 취약점',
    type: 'SHORT_ANSWER',
    question: '객체가 메모리상에 생성되지 않았거나 참조 대상이 존재하지 않는 포인터 변수(null)의 메소드나 멤버 필드에 접근하려 할 때 발생하며, 비정상적인 프로그램 강제 종료를 유발하는 대표적인 예외(Exception) 결함은 무엇인가?',
    answer: ['Null Pointer 역참조', 'Null Pointer Dereference', '널 포인터 역참조', 'NullPointerException'],
    explanation: 'Null Pointer 역참조는 객체 사용 전 null 체크(if (obj != null))를 누락했을 때 발생하며 서비스 거부(DoS) 상태를 유발합니다.',
    difficulty: 'EASY',
    keywords: ['Null Pointer 역참조', 'NullPointerException', '코드오류'],
    source: '2026 실기 핵심 보강',
    angle: 'TERM_FROM_DEFINITION',
    targetSubUnit: '9.2',
  },
  {
    id: 'EXP26_SEC_008',
    subject: '신기술/보안',
    category: '시큐어 코딩',
    subCategory: '입력데이터 검증',
    type: 'SHORT_ANSWER',
    question: 'printf(str); 과 같이 검증되지 않은 외부 사용자 입력 문자열을 포맷 제어 문자 지정 없이 출력 함수의 첫 번째 인자로 직접 전달했을 때, %x, %n 등의 변환 지정자를 악용하여 메모리 내용을 유출하거나 변조하는 공격은 무엇인가?',
    answer: ['포맷 스트링 공격', '포맷 스트링 취약점', 'Format String Attack'],
    explanation: '포맷 스트링(Format String) 취약점은 printf("%s", str); 처럼 포맷 지정자를 명시하지 않고 사용자 입력을 포맷 스트링 자체로 사용할 때 발생합니다.',
    difficulty: 'MEDIUM',
    keywords: ['포맷 스트링', 'Format String', 'printf'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '9.2',
  },
  {
    id: 'EXP26_SEC_009',
    subject: '신기술/보안',
    category: '시큐어 코딩',
    subCategory: '보안 기능',
    type: 'SHORT_ANSWER',
    question: '비밀번호를 일방향 해시 함수로 암호화할 때, 레인보우 테이블(Rainbow Table)을 이용한 역추적 사전 공격을 무력화하기 위해 원본 비밀번호에 임의의 고유한 난수 문자열을 덧붙여 해싱하는 기법을 무엇이라 하는가?',
    answer: ['솔트', '솔팅', 'Salt', 'Salting'],
    explanation: '솔트(Salt)는 해시 생성 전 비밀번호 뒤에 무작위 문자열을 붙여 동일한 비밀번호라도 완전히 다른 해시값이 생성되도록 보장합니다.',
    difficulty: 'EASY',
    keywords: ['솔트', '솔팅', 'Salt', '레인보우테이블방어'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '9.2',
  },
  {
    id: 'EXP26_SEC_010',
    subject: '신기술/보안',
    category: '시큐어 코딩',
    subCategory: '자원 관리',
    type: 'SHORT_ANSWER',
    question: '파일, 데이터베이스 커넥션, 네트워크 소켓 등의 시스템 자원을 열어 사용한 후 예외 발생이나 프로그램 종료 시 명시적으로 close()하여 시스템 자원의 고갈을 방지하지 못했을 때 발생하는 결함은 무엇인가?',
    answer: ['자원 누수', '메모리 누수', '자원 누출', 'Resource Leak'],
    explanation: '자원 누수(Resource Leak)는 파일 핸들이나 DB 커넥션 풀을 반환하지 않아 시스템 자원이 점진적으로 고갈되는 결함으로, try-with-resources나 finally 블록으로 방어합니다.',
    difficulty: 'EASY',
    keywords: ['자원 누수', 'Resource Leak', '메모리누수'],
    source: '2026 실기 핵심 보강',
    angle: 'CHARACTERISTIC',
    targetSubUnit: '9.2',
  },
  {
    id: 'EXP26_SEC_011',
    subject: '신기술/보안',
    category: '시큐어 코딩',
    subCategory: '입력데이터 검증',
    type: 'SHORT_ANSWER',
    question: '웹 파일 다운로드 기능에서 사용자 입력 경로에 [ ../ ] 또는 [ ..\\ ]와 같은 상위 디렉터리 이동 특수문자를 삽입하여 웹 루트 경로를 벗어나 서버의 민감한 시스템 파일(/etc/passwd 등)을 무단 조회하는 공격은 무엇인가?',
    answer: ['경로 조작', '경로 순회', '디렉터리 순회', 'Path Traversal', 'Directory Traversal'],
    explanation: '경로 순회(Directory Traversal / Path Traversal)는 파일 경로에 상위 디렉터리 참조 문자(../)를 필터링하지 않았을 때 서버의 임의 파일을 열람당하는 취약점입니다.',
    difficulty: 'EASY',
    keywords: ['경로 조작', '경로 순회', '디렉터리순회', 'Path Traversal'],
    source: '2026 실기 핵심 보강',
    angle: 'SCENARIO',
    targetSubUnit: '9.2',
  },
  {
    id: 'EXP26_SEC_012',
    subject: '신기술/보안',
    category: '시큐어 코딩',
    subCategory: '메모리 보안 취약점',
    type: 'SHORT_ANSWER',
    question: '정수형 변수에 할당 가능한 최댓값을 초과하는 연산 결과를 저장하려 할 때, 비트 부호가 반전되어 매우 작은 음수 값이 되거나 최소 한계값으로 순환(Wrap around)되어 메모리 할당 크기 검증을 우회하게 만드는 결함은 무엇인가?',
    answer: ['정수 오버플로우', 'Integer Overflow'],
    explanation: '정수 오버플로우(Integer Overflow)는 큰 양수가 음수로 변하거나 0에 가까운 값으로 축소되어 버퍼 크기 검사를 무력화시킵니다.',
    difficulty: 'EASY',
    keywords: ['정수 오버플로우', 'Integer Overflow', '메모리결함'],
    source: '2026 실기 핵심 보강',
    angle: 'TERM_FROM_DEFINITION',
    targetSubUnit: '9.2',
  },
  {
    id: 'EXP26_SEC_013',
    subject: '신기술/보안',
    category: '시큐어 코딩',
    subCategory: '보안 기능',
    type: 'SHORT_ANSWER',
    question: '암호화 키, 세션 ID, 비밀번호 솔트 생성 시 표준 `java.util.Random`처럼 시드값이 예측 가능한 의사난수 대신, 운영체제의 엔트로피 풀을 사용하여 암호학적으로 예측 불가능한 안전한 난수를 생성하는 자바 클래스는 무엇인가?',
    answer: ['SecureRandom'],
    explanation: '시큐어 코딩에서는 시퀀스가 쉽게 추측되는 일반 난수 발생기 대신 암호학적으로 안전한 SecureRandom 클래스를 사용할 것을 의무화합니다.',
    difficulty: 'MEDIUM',
    keywords: ['SecureRandom', '안전한난수', '난수발생기'],
    source: '2026 실기 핵심 보강',
    angle: 'SHORT_CODE',
    targetSubUnit: '9.2',
  },
  {
    id: 'EXP26_SEC_014',
    subject: '신기술/보안',
    category: '시큐어 코딩',
    subCategory: '에러 처리 취약점',
    type: 'SHORT_ANSWER',
    question: '서버 애플리케이션에서 예외나 에러가 발생했을 때, 에러 로그와 스택 트레이스(Stack Trace), 데이터베이스 쿼리 에러 메시지를 사용자의 웹 브라우저 화면에 그대로 노출함으로써 내부 시스템 구조와 DB 테이블 정보를 공격자에게 노출시키는 취약점은 무엇인가?',
    answer: ['오류 메시지 정보 노출', '정보 노출', '오류 정보 노출'],
    explanation: '오류 메시지를 통해 DB 구조, 프레임워크 버전, 파일 절대 경로가 노출되면 2차 공격의 빌미가 되므로 사용자에게는 일반적인 안내 페이지를 보여주어야 합니다.',
    difficulty: 'EASY',
    keywords: ['오류 메시지 정보 노출', '스택트레이스', '에러처리'],
    source: '2026 실기 핵심 보강',
    angle: 'SCENARIO',
    targetSubUnit: '9.2',
  },
  {
    id: 'EXP26_SEC_015',
    subject: '신기술/보안',
    category: '시큐어 코딩',
    subCategory: '보안 기능',
    type: 'SHORT_ANSWER',
    question: '소스코드 내부에 데이터베이스 접속 비밀번호나 암호화 대칭키 값을 직접 평문 문자열 상수로 하드코딩(Hardcoding)해 두었을 때, 소스코드 유출 시 전체 시스템이 장악당하는 취약점을 방지하기 위한 안전한 키 관리 방식은 무엇인가?',
    answer: ['환경 변수', '환경 변수 설정', '외부 설정 파일', '키 관리 시스템'],
    explanation: '패스워드와 시크릿 키는 소스코드에 하드코딩하지 않고 환경 변수(Environment Variables)나 암호화된 외부 설정 파일/KMS에 분리 보관해야 합니다.',
    difficulty: 'EASY',
    keywords: ['환경 변수', '하드코딩방지', '키관리'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '9.2',
  },
  {
    id: 'EXP26_SEC_016',
    subject: '신기술/보안',
    category: '시큐어 코딩',
    subCategory: '캡슐화 취약점',
    type: 'SHORT_ANSWER',
    question: '객체지향 설계에서 클래스 내부의 중요한 멤버 변수를 private으로 선언하더라도, 외부에서 호출하는 Getter 메소드가 객체 내부의 가변 배열(Array) 참조값을 그대로 반환할 때 외부에서 배열 내용을 직접 변조할 수 있는 취약점을 방어하기 위한 안전한 반환 기법은 무엇인가?',
    answer: ['방어적 복사', '복사본 반환', 'Defensive Copy'],
    explanation: '방어적 복사(Defensive Copying)는 내부 가변 객체를 외부에 전달할 때 원본 참조가 아닌 clone()이나 새로운 복사본을 만들어 반환하는 시큐어 코딩 기법입니다.',
    difficulty: 'HARD',
    keywords: ['방어적 복사', 'Defensive Copy', '캡슐화'],
    source: '2026 실기 핵심 보강',
    angle: 'CHARACTERISTIC',
    targetSubUnit: '9.2',
  },
  {
    id: 'EXP26_SEC_017',
    subject: '신기술/보안',
    category: 'SW개발 보안 설계',
    subCategory: '보안 메커니즘',
    type: 'SHORT_ANSWER',
    question: '사용자 또는 주체(Subject)가 정보 시스템에 자신이라고 주장하는 식별자(ID)를 제시하고, 암호나 생체 정보를 통해 본인이 맞는지 그 신원을 증명하는 보안 통제 단계를 무엇이라 하는가?',
    answer: ['인증', 'Authentication', '사용자 인증'],
    explanation: '인증(Authentication)은 신원 확인 단계이며, 인증된 사용자에게 자원에 대한 접근 권한을 부여하는 단계는 인가(Authorization)입니다.',
    difficulty: 'EASY',
    keywords: ['인증', 'Authentication', '보안3A'],
    source: '2026 실기 핵심 보강',
    angle: 'COMPARISON',
    targetSubUnit: '9.1',
  },
  {
    id: 'EXP26_SEC_018',
    subject: '신기술/보안',
    category: 'SW개발 보안 설계',
    subCategory: '보안 메커니즘',
    type: 'SHORT_ANSWER',
    question: '인증된 주체가 시스템의 특정 파일이나 디렉터리, 기능 등 보호된 리소스에 대해 접근할 수 있는 권한이 있는지 확인하고 실행 허가를 내리는 보안 통제 단계를 무엇이라 하는가?',
    answer: ['인가', '권한 부여', 'Authorization'],
    explanation: '인가(Authorization)는 특정 자원에 대한 접근 권한 부여 단계로, 접근통제 정책(DAC, MAC, RBAC 등)에 따라 결정됩니다.',
    difficulty: 'EASY',
    keywords: ['인가', 'Authorization', '권한부여'],
    source: '2026 실기 핵심 보강',
    angle: 'COMPARISON',
    targetSubUnit: '9.1',
  },
  {
    id: 'EXP26_SEC_019',
    subject: '신기술/보안',
    category: '시큐어 코딩',
    subCategory: '입력데이터 검증',
    type: 'SHORT_ANSWER',
    question: '서버 측 입력값 검증 방식 중, 위험한 문자나 금지어 목록을 정의하여 차단하는 블랙리스트(Blacklist) 방식에 비해, 허용 가능한 안전한 문자 형식과 길이 규칙만을 명시하여 그 외의 모든 입력을 거부하는 훨씬 안전한 검증 방식은 무엇인가?',
    answer: ['화이트리스트', '화이트리스트 방식', 'Whitelist'],
    explanation: '화이트리스트(Whitelist) 검증은 새로운 우회 공격 패턴이 등장하더라도 허용 규칙 이외의 모든 값을 차단하므로 시큐어 코딩의 기본 권장 사항입니다.',
    difficulty: 'EASY',
    keywords: ['화이트리스트', 'Whitelist', '입력값검증'],
    source: '2026 실기 핵심 보강',
    angle: 'COMPARISON',
    targetSubUnit: '9.2',
  },
  {
    id: 'EXP26_SEC_020',
    subject: '신기술/보안',
    category: '시큐어 코딩',
    subCategory: '세션 관리',
    type: 'SHORT_ANSWER',
    question: '웹 브라우저의 쿠키(Cookie) 탈취를 방지하기 위해 설정하는 보안 플래그 중, 자바스크립트의 `document.cookie` 객체를 통한 쿠키 접근을 원천 차단하여 XSS 공격에 의한 세션 하이재킹을 방어하는 플래그 속성은 무엇인가?',
    answer: ['HttpOnly', 'HttpOnly 플래그'],
    explanation: 'HttpOnly 쿠키 플래그는 브라우저 스크립트의 접근을 막아 쿠키 유출을 방어하며, 암호화 전송(HTTPS)을 강제하는 것은 Secure 플래그입니다.',
    difficulty: 'EASY',
    keywords: ['HttpOnly', '쿠키보안', '세션하이재킹방어'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '9.2',
  },
];
