import { ExpansionCandidate } from '../validator';

/**
 * Batch 5: 현행 시스템 분석 & UI 설계 및 프로토타이핑 (공식 실기 범위 1.1, 6.1, 6.2)
 * 기존 커버리지: 1.1 (THIN 2문항), 6.1 (THIN 4문항), 6.2 (THIN 2문항)
 * 목표: 20문항 엄선 (출제각도: COMPARISON, PROCESS_SEQUENCE, IDENTIFICATION, SCENARIO 등)
 */
export const BATCH5_CANDIDATES: ExpansionCandidate[] = [
  {
    id: 'EXP26_UI_001',
    subject: '소프트웨어설계',
    category: '현행 시스템 분석',
    subCategory: '분석 대상 및 고려사항',
    type: 'SHORT_ANSWER',
    question: '신규 시스템을 개발하기 전 현행 시스템의 운영체제(OS)를 분석할 때 검토해야 하는 주요 고려사항 중, 장기간 시스템 운영 시 패치 및 정기 업그레이드 지원, 오픈소스 커뮤니티나 벤더사의 지원 가능 여부를 평가하는 항목은 무엇인가?',
    answer: ['기술 지원', '기술지원', '기술 지원 여부'],
    explanation: '운영체제 및 DBMS 도입 분석 시 핵심 고려사항은 신뢰도(가용성), 성능, 기술 지원, 구축 및 라이선스 비용, 주변 기기 지원 여부입니다.',
    difficulty: 'EASY',
    keywords: ['기술지원', '운영체제분석', '현행시스템분석'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '1.1',
  },
  {
    id: 'EXP26_UI_002',
    subject: '소프트웨어설계',
    category: '현행 시스템 분석',
    subCategory: '분석 절차',
    type: 'SHORT_ANSWER',
    question: '현행 시스템 파악 절차는 총 3단계로 진행된다. 1단계(시스템 구성, 기능, 인터페이스 파악)와 3단계(하드웨어 및 네트워크 구성 파악) 사이의 [2단계]에서 파악해야 하는 대상 2가지는 무엇인가?',
    answer: ['아키텍처, 소프트웨어', '아키텍처 및 소프트웨어', '아키텍처, 소프트웨어 구성'],
    explanation: '현행 시스템 파악 절차는 1단계(시스템 구성/기능/인터페이스) → 2단계(아키텍처/소프트웨어 구성) → 3단계(하드웨어/네트워크 구성) 순입니다.',
    difficulty: 'MEDIUM',
    keywords: ['현행시스템절차', '아키텍처', '소프트웨어구성'],
    source: '2026 실기 핵심 보강',
    angle: 'PROCESS_SEQUENCE',
    targetSubUnit: '1.1',
  },
  {
    id: 'EXP26_UI_003',
    subject: '소프트웨어설계',
    category: '현행 시스템 분석',
    subCategory: 'DBMS 분석 고려사항',
    type: 'SHORT_ANSWER',
    question: '현행 시스템의 DBMS 분석 시, 24시간 365일 무중단 서비스가 요구되는 환경에서 장애 발생 시 백업 및 이중화(Clustering)를 통해 서비스 다운타임을 최소화할 수 있는 능력을 평가하는 핵심 지표는 무엇인가?',
    answer: ['가용성', '신뢰도', '가용성(Availability)'],
    explanation: 'DBMS 분석의 가용성(Availability/신뢰도)은 고가용성(HA, High Availability) 솔루션 및 데이터 복제 기능을 평가합니다.',
    difficulty: 'EASY',
    keywords: ['가용성', '신뢰도', 'DBMS분석'],
    source: '2026 실기 핵심 보강',
    angle: 'CHARACTERISTIC',
    targetSubUnit: '1.1',
  },
  {
    id: 'EXP26_UI_004',
    subject: '소프트웨어설계',
    category: '화면 설계',
    subCategory: 'UI 설계 도구 비교',
    type: 'SHORT_ANSWER',
    question: '기획 초기 단계에서 페이지의 세부 디자인(색상, 폰트, 그래픽)을 배제하고, 레이아웃과 정보의 뼈대(구조)만을 선과 박스로 간단히 스케치하여 화면 구성을 협의하는 도구를 무엇이라 하는가?',
    answer: ['와이어프레임', 'Wireframe'],
    explanation: '와이어프레임(Wireframe)은 시각적 그래픽 요소를 최소화하고 화면의 정보 구조와 레이아웃 골격만을 빠르게 기획하는 도구입니다.',
    difficulty: 'EASY',
    keywords: ['와이어프레임', 'Wireframe', 'UI레이아웃'],
    source: '2026 실기 핵심 보강',
    angle: 'COMPARISON',
    targetSubUnit: '6.2',
  },
  {
    id: 'EXP26_UI_005',
    subject: '소프트웨어설계',
    category: '화면 설계',
    subCategory: 'UI 설계 도구 비교',
    type: 'SHORT_ANSWER',
    question: '와이어프레임보다 발전하여 실제 완성될 화면과 동일하게 색상, 타이포그래피, 로고, 아이콘 등의 시각적 그래픽 디자인을 정적으로 완성한 정적 결과물을 무엇이라 하는가? (동작/인터랙션은 포함되지 않음)',
    answer: ['목업', 'Mockup', '목업(Mockup)'],
    explanation: '목업(Mockup)은 실제 제품의 시각적 형태를 충실하게 보여주는 정적인 비기능적 디자인 산출물입니다.',
    difficulty: 'EASY',
    keywords: ['목업', 'Mockup', 'UI디자인'],
    source: '2026 실기 핵심 보강',
    angle: 'COMPARISON',
    targetSubUnit: '6.2',
  },
  {
    id: 'EXP26_UI_006',
    subject: '소프트웨어설계',
    category: '화면 설계',
    subCategory: 'UI 설계 도구 비교',
    type: 'SHORT_ANSWER',
    question: '와이어프레임 화면 레이아웃과 함께 각 UI 컴포넌트의 기능 정의, 이벤트 처리 방식, 화면 간 전환 흐름, 예외 처리 로직을 개발자가 구현할 수 있도록 상세히 명세한 최종 기획 산출물은 무엇인가?',
    answer: ['스토리보드', 'Storyboard'],
    explanation: '스토리보드(Storyboard)는 디자이너와 개발자가 화면을 보고 그대로 구현할 수 있도록 화면 설계와 기능 명세를 완전하게 결합한 문서입니다.',
    difficulty: 'EASY',
    keywords: ['스토리보드', 'Storyboard', '기능명세'],
    source: '2026 실기 핵심 보강',
    angle: 'COMPARISON',
    targetSubUnit: '6.2',
  },
  {
    id: 'EXP26_UI_007',
    subject: '소프트웨어설계',
    category: '화면 설계',
    subCategory: 'UI 설계 도구 비교',
    type: 'SHORT_ANSWER',
    question: '정적 화면에 버튼 클릭, 화면 전환, 애니메이션 등의 인터랙션을 실제로 적용하여 사용자가 직접 조작하고 사용성을 검증해 볼 수 있도록 동적으로 제작된 시제품을 무엇이라 하는가?',
    answer: ['프로토타입', 'Prototype'],
    explanation: '프로토타입(Prototype)은 사용자와 이해관계자가 실제 앱처럼 인터랙션을 테스트하고 피드백을 신속히 얻기 위해 제작되는 동적 모델입니다.',
    difficulty: 'EASY',
    keywords: ['프로토타입', 'Prototype', '인터랙션'],
    source: '2026 실기 핵심 보강',
    angle: 'COMPARISON',
    targetSubUnit: '6.2',
  },
  {
    id: 'EXP26_UI_008',
    subject: '소프트웨어설계',
    category: '화면 설계',
    subCategory: 'UI 설계 4대 원칙',
    type: 'SHORT_ANSWER',
    question: 'UI 설계의 4대 원칙(직관성, 유효성, 학습성, 유연성) 중, 사용자가 특별한 매뉴얼을 읽거나 사전에 배우지 않고도 버튼의 모양이나 위치만 보고 그 기능과 조작 방법을 쉽게 이해할 수 있어야 함을 의미하는 원칙은 무엇인가?',
    answer: ['직관성', 'Intuitiveness'],
    explanation: '직관성(Intuitiveness)은 누구나 쉽게 이해하고 바로 사용할 수 있어야 한다는 원칙입니다.',
    difficulty: 'EASY',
    keywords: ['직관성', 'UI4대원칙', 'Intuitiveness'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '6.1',
  },
  {
    id: 'EXP26_UI_009',
    subject: '소프트웨어설계',
    category: '화면 설계',
    subCategory: 'UI 설계 4대 원칙',
    type: 'SHORT_ANSWER',
    question: 'UI 설계 4대 원칙 중, 사용자가 시스템을 통해 이루고자 하는 목표(예: 상품 결제, 정보 검색)를 오류 없이 정확하고 완벽하게 달성할 수 있도록 보장해야 한다는 원칙은 무엇인가?',
    answer: ['유효성', 'Effectiveness'],
    explanation: '유효성(Effectiveness)은 사용자의 목적과 과업을 정확하고 완전하게 달성할 수 있게 지원하는 원칙입니다.',
    difficulty: 'EASY',
    keywords: ['유효성', 'UI4대원칙', 'Effectiveness'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '6.1',
  },
  {
    id: 'EXP26_UI_010',
    subject: '소프트웨어설계',
    category: '화면 설계',
    subCategory: 'UI 설계 4대 원칙',
    type: 'SHORT_ANSWER',
    question: 'UI 설계 4대 원칙 중, 사용자의 다양한 개인적 요구사항을 수용할 수 있고, 사용자가 실수(오작동)를 저지르더라도 이를 되돌리거나(Undo) 오류를 쉽게 복구할 수 있도록 최대한 지원해야 한다는 원칙은 무엇인가?',
    answer: ['유연성', 'Flexibility'],
    explanation: '유연성(Flexibility)은 사용자의 인터랙션 취향을 포용하고 사용자의 실수를 안전하게 방어 및 복구해 주는 원칙입니다.',
    difficulty: 'EASY',
    keywords: ['유연성', 'UI4대원칙', 'Flexibility'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '6.1',
  },
  {
    id: 'EXP26_UI_011',
    subject: '소프트웨어설계',
    category: '화면 설계',
    subCategory: 'UI 설계 4대 원칙',
    type: 'SHORT_ANSWER',
    question: 'UI 설계 4대 원칙 중, 사용자가 처음 접하는 복잡한 시스템이라 할지라도 누구나 쉽고 빠르게 사용 방법을 익힐 수 있도록 설계해야 함을 의미하는 원칙은 무엇인가?',
    answer: ['학습성', 'Learnability'],
    explanation: '학습성(Learnability)은 사용자가 사용법을 쉽게 배울 수 있도록 표준화된 규칙과 가이드를 제공해야 한다는 원칙입니다.',
    difficulty: 'EASY',
    keywords: ['학습성', 'UI4대원칙', 'Learnability'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '6.1',
  },
  {
    id: 'EXP26_UI_012',
    subject: '소프트웨어설계',
    category: '화면 설계',
    subCategory: '사용자 모델링',
    type: 'SHORT_ANSWER',
    question: '사용자 중심 디자인(UCD)에서 실제 사용자의 인터뷰와 행동 패턴 데이터를 기반으로, 시스템을 사용할 대표적인 전형적 가상 인물을 설정하여 목표와 요구를 구체화하는 기법을 무엇이라 하는가?',
    answer: ['페르소나', 'Persona', '페르소나 기법'],
    explanation: '페르소나(Persona)는 목표 사용자의 인구통계학적 특성, 동기, 고충(Pain Point)을 가진 가상의 인격체를 만들어 디자인의 방향성을 잡는 기법입니다.',
    difficulty: 'EASY',
    keywords: ['페르소나', 'Persona', '사용자중심디자인'],
    source: '2026 실기 핵심 보강',
    angle: 'TERM_FROM_DEFINITION',
    targetSubUnit: '6.1',
  },
  {
    id: 'EXP26_UI_013',
    subject: '소프트웨어설계',
    category: '화면 설계',
    subCategory: '사용성 평가',
    type: 'SHORT_ANSWER',
    question: '사용성 전문가들이 야콥 닐슨(Jakob Nielsen)이 정립한 10가지 사용성 원칙(가이드라인)을 기준으로 시스템의 UI를 직접 점검하고 발견된 문제점을 평가하는 사용성 평가 기법은 무엇인가?',
    answer: ['휴리스틱 평가', '휴리스틱', 'Heuristic Evaluation'],
    explanation: '휴리스틱 평가(Heuristic Evaluation)는 적은 수의 전문가가 정형화된 사용성 원칙 체크리스트를 기반으로 UI의 결함을 빠르게 찾아내는 정성적 평가법입니다.',
    difficulty: 'MEDIUM',
    keywords: ['휴리스틱 평가', 'Heuristic Evaluation', '사용성평가'],
    source: '2026 실기 핵심 보강',
    angle: 'TERM_FROM_DEFINITION',
    targetSubUnit: '6.1',
  },
  {
    id: 'EXP26_UI_014',
    subject: '소프트웨어설계',
    category: '화면 설계',
    subCategory: '웹 표준 및 접근성',
    type: 'SHORT_ANSWER',
    question: '시각 장애인, 지체 장애인, 고령자 등 신체적·환경적 제약이 있는 사용자라도 비장애인과 동등하게 웹 사이트의 모든 정보에 접근하고 이용할 수 있도록 보장하는 개념을 무엇이라 하는가?',
    answer: ['웹 접근성', 'Web Accessibility'],
    explanation: '웹 접근성(Web Accessibility)은 스크린 리더 지원(대체 텍스트 제공), 키보드만으로 조작 가능, 깜빡임 방지 등의 지침을 준수하는 것을 의미합니다.',
    difficulty: 'EASY',
    keywords: ['웹 접근성', 'Web Accessibility', '장애인접근성'],
    source: '2026 실기 핵심 보강',
    angle: 'TERM_FROM_DEFINITION',
    targetSubUnit: '6.1',
  },
  {
    id: 'EXP26_UI_015',
    subject: '소프트웨어설계',
    category: '화면 설계',
    subCategory: '웹 표준 및 접근성',
    type: 'SHORT_ANSWER',
    question: 'HTML 문서에서 이미지 태그(<img>)에 시각 장애인을 위한 스크린 리더 프로그램이 해당 이미지의 내용을 음성으로 읽어줄 수 있도록 작성해야 하는 필수 속성의 이름은 무엇인가?',
    answer: ['alt', 'alt 속성'],
    explanation: 'alt(Alternative text) 속성은 이미지를 볼 수 없는 사용자와 이미지 로딩 실패 시 표시할 대체 텍스트를 제공합니다.',
    difficulty: 'EASY',
    keywords: ['alt', '대체텍스트', '웹접근성'],
    source: '2026 실기 핵심 보강',
    angle: 'SHORT_CODE',
    targetSubUnit: '6.1',
  },
  {
    id: 'EXP26_UI_016',
    subject: '소프트웨어설계',
    category: '화면 설계',
    subCategory: 'UI 인터랙션 패턴',
    type: 'SHORT_ANSWER',
    question: '웹 및 모바일 화면에서 기존 배경 페이지를 어둡게 처리하여 비활성화시키고, 최상단에 팝업창을 띄워 사용자가 해당 창을 닫거나 응답하기 전에는 기존 화면과 상호작용할 수 없도록 강제하는 대화상자 형태는 무엇인가?',
    answer: ['모달', '모달창', 'Modal', 'Modal Dialog'],
    explanation: '모달(Modal) 창은 사용자의 즉각적인 확인이나 중요한 입력을 요구할 때 배경과의 상호작용을 차단합니다. (배경을 조작할 수 있는 것은 모달리스/Modeless)',
    difficulty: 'EASY',
    keywords: ['모달', 'Modal', '대화상자'],
    source: '2026 실기 핵심 보강',
    angle: 'COMPARISON',
    targetSubUnit: '6.2',
  },
  {
    id: 'EXP26_UI_017',
    subject: '소프트웨어설계',
    category: '화면 설계',
    subCategory: '내비게이션 구조',
    type: 'SHORT_ANSWER',
    question: '전자상거래 사이트 등 복잡한 계층 구조를 가진 웹사이트에서 [ 홈 > 대분류 > 중분류 > 현재 상품명 ]과 같이 현재 페이지의 위치 경로를 시각적으로 보여주어 상위 경로로 쉽게 이동할 수 있게 해주는 내비게이션 요소를 무엇이라 하는가?',
    answer: ['브레드크럼', 'Breadcrumb', '브레드크럼즈'],
    explanation: '브레드크럼(Breadcrumb, 빵부스러기)은 헨젤과 그레텔 동화에서 유래한 내비게이션 UI로 사이트 내 위치 파악을 돕습니다.',
    difficulty: 'EASY',
    keywords: ['브레드크럼', 'Breadcrumb', '내비게이션'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '6.2',
  },
  {
    id: 'EXP26_UI_018',
    subject: '소프트웨어설계',
    category: '화면 설계',
    subCategory: '반응형 웹 디자인',
    type: 'SHORT_ANSWER',
    question: '하나의 웹 소스코드로 데스크톱 PC, 태블릿, 스마트폰 등 다양한 기기의 화면 크기(해상도)에 맞추어 레이아웃과 폰트 크기가 자동으로 유연하게 변환되도록 구현하는 웹 디자인 기법은 무엇인가?',
    answer: ['반응형 웹', '반응형 웹 디자인', 'Responsive Web'],
    explanation: '반응형 웹(Responsive Web)은 CSS 미디어 쿼리(Media Query)와 유동형 그리드(Fluid Grid)를 기반으로 다중 디바이스를 지원합니다.',
    difficulty: 'EASY',
    keywords: ['반응형 웹', 'Responsive Web', '미디어쿼리'],
    source: '2026 실기 핵심 보강',
    angle: 'TERM_FROM_DEFINITION',
    targetSubUnit: '6.2',
  },
  {
    id: 'EXP26_UI_019',
    subject: '소프트웨어설계',
    category: '화면 설계',
    subCategory: 'UI 설계 스타일',
    type: 'SHORT_ANSWER',
    question: '과거 스마트폰 초기에 실제 아날로그 사물(가죽 수첩, 책장, 계산기 질감)의 외형과 질감을 사실적으로 모사하여 디지털 인터페이스에 표현했던 시각 디자인 기법은 무엇인가?',
    answer: ['스큐어모피즘', 'Skeuomorphism', '스큐어모피즘(Skeuomorphism)'],
    explanation: '스큐어모피즘(Skeuomorphism)은 현실 사물의 질감을 모방하여 직관성을 높였으나, 점차 미니멀한 플랫 디자인(Flat Design)과 머티리얼 디자인으로 진화했습니다.',
    difficulty: 'MEDIUM',
    keywords: ['스큐어모피즘', 'Skeuomorphism', '플랫디자인'],
    source: '2026 실기 핵심 보강',
    angle: 'COMPARISON',
    targetSubUnit: '6.1',
  },
  {
    id: 'EXP26_UI_020',
    subject: '소프트웨어설계',
    category: '화면 설계',
    subCategory: 'UI 인터랙션 설계 원칙',
    type: 'SHORT_ANSWER',
    question: '사용자가 UI 버튼을 클릭하거나 폼을 제출했을 때, 시스템이 현재 요청을 처리 중임을 시각적/청각적으로 즉각 알려주어야 한다는 인터랙션 설계 원칙을 무엇이라 하는가?',
    answer: ['피드백', '피드백 제공', '시스템 피드백', 'Feedback'],
    explanation: '피드백(Feedback)은 사용자의 입력에 대해 로딩 스피너, 프로그레스 바, 사운드 등으로 시스템의 상태 변화를 인지시켜 불안감을 해소합니다.',
    difficulty: 'EASY',
    keywords: ['피드백', 'Feedback', '인터랙션원칙'],
    source: '2026 실기 핵심 보강',
    angle: 'CHARACTERISTIC',
    targetSubUnit: '6.1',
  },
];
