import { ExpansionCandidate } from '../validator';

/**
 * Batch 7: 소프트웨어 테스트 기법, 리팩터링 & 클린코드, UML 모델링 (공식 실기 범위 1.2, 7.1, 10.1)
 * 목표: 25문항 엄선 (출제각도: COMPARISON, IDENTIFICATION, SCENARIO, CHARACTERISTIC 등)
 */
export const BATCH7_CANDIDATES: ExpansionCandidate[] = [
  {
    id: 'EXP26_TST_001',
    subject: '소프트웨어설계',
    category: '애플리케이션 테스트 관리',
    subCategory: '화이트박스 테스트 커버리지',
    type: 'SHORT_ANSWER',
    question: '화이트박스 테스트의 구조적 커버리지 중, 프로그램 내의 모든 개별 조건식의 참(True)/거짓(False) 결과와 무관하게, 전체 복합 조건식의 결과(결정 포인트)가 최소한 한 번씩 참과 거짓을 모두 수행하도록 보장하는 커버리지는 무엇인가?',
    answer: ['결정 커버리지', '분기 커버리지', 'Decision Coverage', 'Branch Coverage'],
    explanation: '결정 커버리지(분기 커버리지)는 프로그램의 모든 조건문 분기 경로(True/False 방향)를 최소 한 번씩 실행합니다.',
    difficulty: 'EASY',
    keywords: ['결정 커버리지', '분기 커버리지', '구조적커버리지'],
    source: '2026 실기 핵심 보강',
    angle: 'COMPARISON',
    targetSubUnit: '7.1',
  },
  {
    id: 'EXP26_TST_002',
    subject: '소프트웨어설계',
    category: '애플리케이션 테스트 관리',
    subCategory: '화이트박스 테스트 커버리지',
    type: 'SHORT_ANSWER',
    question: '복합 조건식 전체의 결과와는 별개로, 조건식 내부에 포함된 각각의 개별 조건식(개별 명제)들이 독립적으로 최소한 한 번씩 참(True)과 거짓(False)의 결과를 갖도록 테스트 케이스를 설계하는 커버리지는 무엇인가?',
    answer: ['조건 커버리지', 'Condition Coverage'],
    explanation: '조건 커버리지(Condition Coverage)는 전체 결과와 무관하게 각 내부 개별 조건식이 참/거짓을 만족하는지 검증합니다.',
    difficulty: 'EASY',
    keywords: ['조건 커버리지', '개별조건식', '화이트박스테스트'],
    source: '2026 실기 핵심 보강',
    angle: 'COMPARISON',
    targetSubUnit: '7.1',
  },
  {
    id: 'EXP26_TST_003',
    subject: '소프트웨어설계',
    category: '애플리케이션 테스트 관리',
    subCategory: '화이트박스 테스트 커버리지',
    type: 'SHORT_ANSWER',
    question: '결정 커버리지와 조건 커버리지를 모두 만족하면서, 각 개별 조건식이 전체 복합 조건식의 결과에 독립적인 영향을 미치도록 설계하여 항공/국방 등 고신뢰성 임베디드 시스템에서 필수로 요구하는 커버리지의 약어는 무엇인가?',
    answer: ['MC/DC', 'MCDC', '변경 조건/결정 커버리지'],
    explanation: 'MC/DC(Modified Condition/Decision Coverage)는 개별 조건식이 다른 조건식에 영향받지 않고 전체 결정을 변경할 수 있음을 검증하는 최고 수준의 커버리지입니다.',
    difficulty: 'HARD',
    keywords: ['MC/DC', 'MCDC', '변경조건결정커버리지'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '7.1',
  },
  {
    id: 'EXP26_TST_004',
    subject: '소프트웨어설계',
    category: '애플리케이션 테스트 관리',
    subCategory: '블랙박스 테스트 기법',
    type: 'SHORT_ANSWER',
    question: '입력 조건의 유효 범위와 무효 범위를 대등한 그룹(클래스)으로 나눈 뒤, 각 동등 분할 그룹에서 대표값 하나씩을 추출하여 테스트 케이스를 설계하는 블랙박스 테스트 기법은 무엇인가?',
    answer: ['동등 분할', '동치 분할', '동등 분할 검사', 'Equivalence Partitioning'],
    explanation: '동등 분할(Equivalence Partitioning)은 입력 도메인을 상호 배타적인 클래스로 나누어 대표값을 시험함으로써 최소 비용으로 결함을 찾습니다.',
    difficulty: 'EASY',
    keywords: ['동등 분할', '동치 분할', '블랙박스테스트'],
    source: '2026 실기 핵심 보강',
    angle: 'TERM_FROM_DEFINITION',
    targetSubUnit: '7.1',
  },
  {
    id: 'EXP26_TST_005',
    subject: '소프트웨어설계',
    category: '애플리케이션 테스트 관리',
    subCategory: '블랙박스 테스트 기법',
    type: 'SHORT_ANSWER',
    question: '오류가 입력값의 중간보다 입력 조건의 최소값, 최대값, 경계 부근에서 집중적으로 발생한다는 점에 착안하여, 유효 범위의 바로 안쪽 값, 경계값, 바로 바깥쪽 값을 테스트 데이터로 선택하는 기법은 무엇인가?',
    answer: ['경계값 분석', '경계값 분석 기법', 'Boundary Value Analysis'],
    explanation: '경계값 분석(Boundary Value Analysis)은 등호 오류(<=, <)와 같은 오프바이원(Off-by-one) 결함을 찾아내는 가장 효과적인 블랙박스 기법입니다.',
    difficulty: 'EASY',
    keywords: ['경계값 분석', 'Boundary Value Analysis', '경계값'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '7.1',
  },
  {
    id: 'EXP26_TST_006',
    subject: '소프트웨어설계',
    category: '애플리케이션 테스트 관리',
    subCategory: '경험 기반 테스트 기법',
    type: 'SHORT_ANSWER',
    question: '사전에 정형화된 테스트 케이스 문서를 작성하지 않고, 테스터의 직관과 경험에 기반하여 테스트 대상을 탐색하면서 동시에 테스트를 설계하고 실행하며 결함을 찾아내는 경험 기반 기법은 무엇인가?',
    answer: ['탐색적 테스팅', '탐색적 테스트', 'Exploratory Testing'],
    explanation: '탐색적 테스팅(Exploratory Testing)은 테스트 계획, 설계, 실행이 동시에 순환적으로 이루어지며 시간 제약이 있을 때 매우 유용합니다.',
    difficulty: 'EASY',
    keywords: ['탐색적 테스팅', 'Exploratory Testing', '경험기반테스트'],
    source: '2026 실기 핵심 보강',
    angle: 'TERM_FROM_DEFINITION',
    targetSubUnit: '7.1',
  },
  {
    id: 'EXP26_TST_007',
    subject: '소프트웨어설계',
    category: '애플리케이션 성능 개선',
    subCategory: '리팩터링',
    type: 'SHORT_ANSWER',
    question: '소프트웨어의 외부 동작(기능과 결과)은 전혀 변경하지 않으면서, 내부 코드의 가독성을 높이고 복잡도를 낮추어 유지보수성을 향상시키는 코드 구조 개선 활동을 무엇이라 하는가?',
    answer: ['리팩터링', 'Refactoring', '리팩토링'],
    explanation: '리팩터링(Refactoring)은 결함을 수정하거나 새로운 기능을 추가하는 것이 아니라, 클린 코드를 위해 코드의 가독성과 설계를 개선하는 작업입니다.',
    difficulty: 'EASY',
    keywords: ['리팩터링', 'Refactoring', '코드개선'],
    source: '2026 실기 핵심 보강',
    angle: 'TERM_FROM_DEFINITION',
    targetSubUnit: '10.1',
  },
  {
    id: 'EXP26_TST_008',
    subject: '소프트웨어설계',
    category: '애플리케이션 성능 개선',
    subCategory: '코드 스멜(Code Smell)',
    type: 'SHORT_ANSWER',
    question: '마틴 파울러가 정의한 용어로, 당장 버그를 일으키지는 않지만 미래에 결함이나 유지보수 저하를 초래할 가능성이 높은 나쁜 냄새가 나는 잠재적 코드 결함 증상을 무엇이라 하는가?',
    answer: ['코드 스멜', 'Code Smell'],
    explanation: '코드 스멜(Code Smell)에는 중복 코드, 장황한 메소드(Long Method), 거대 클래스(Large Class), 산탄총 수술(Shotgun Surgery) 등이 있습니다.',
    difficulty: 'EASY',
    keywords: ['코드 스멜', 'Code Smell', '나쁜냄새'],
    source: '2026 실기 핵심 보강',
    angle: 'TERM_FROM_DEFINITION',
    targetSubUnit: '10.1',
  },
  {
    id: 'EXP26_TST_009',
    subject: '소프트웨어설계',
    category: '애플리케이션 성능 개선',
    subCategory: '코드 스멜 증상',
    type: 'SHORT_ANSWER',
    question: '하나의 요구사항이나 작은 변경 사항이 발생했을 때, 여러 개의 클래스나 모듈에 걸쳐 자잘한 수정 작업을 동시에 수행해야 하는 코드 스멜 증상을 무엇이라 하는가?',
    answer: ['산탄총 수술', '산탄총 수술(Shotgun Surgery)', 'Shotgun Surgery'],
    explanation: '산탄총 수술(Shotgun Surgery)은 변경이 발생할 때 수많은 곳을 흩어져 수정해야 하는 응집도 부족 증상입니다.',
    difficulty: 'MEDIUM',
    keywords: ['산탄총 수술', 'Shotgun Surgery', '코드스멜'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '10.1',
  },
  {
    id: 'EXP26_TST_010',
    subject: '소프트웨어설계',
    category: '요구사항 확인 및 모델링',
    subCategory: 'UML 관계',
    type: 'SHORT_ANSWER',
    question: 'UML 관계 중 전체(Whole)와 부분(Part)의 관계를 나타내며, 전체 객체가 소멸하더라도 부분 객체는 독립적으로 생존할 수 있는 약한 결합 형태의 포함 관계는 무엇인가?',
    answer: ['집약 관계', '집약', '집합 관계', 'Aggregation'],
    explanation: '집약 관계(Aggregation)는 빈 마름모(◇)로 표현되며, 전체 객체와 부분 객체가 독립적인 생명주기를 갖습니다.',
    difficulty: 'EASY',
    keywords: ['집약 관계', 'Aggregation', 'UML관계'],
    source: '2026 실기 핵심 보강',
    angle: 'COMPARISON',
    targetSubUnit: '1.2',
  },
  {
    id: 'EXP26_TST_011',
    subject: '소프트웨어설계',
    category: '요구사항 확인 및 모델링',
    subCategory: 'UML 관계',
    type: 'SHORT_ANSWER',
    question: 'UML 관계 중 전체 객체와 부분 객체의 생명주기가 완전히 일치하여, 전체 객체가 소멸하면 부분 객체도 함께 소멸하는 강한 결합 형태의 포함 관계는 무엇인가?',
    answer: ['합성 관계', '합성', 'Composition'],
    explanation: '합성 관계(Composition)는 채워진 마름모(◆)로 표현되며, 부분 객체가 전체 객체에 종속되어 생명주기를 같이합니다.',
    difficulty: 'EASY',
    keywords: ['합성 관계', 'Composition', 'UML관계'],
    source: '2026 실기 핵심 보강',
    angle: 'COMPARISON',
    targetSubUnit: '1.2',
  },
  {
    id: 'EXP26_TST_012',
    subject: '소프트웨어설계',
    category: '요구사항 확인 및 모델링',
    subCategory: 'UML 관계',
    type: 'SHORT_ANSWER',
    question: 'UML 관계 중 하위 사물이 상위 사물의 특징(속성과 메서드)을 물려받아 구체화하는 관계로, 객체지향의 상속(Inheritance) 개념을 표현하는 관계는 무엇인가?',
    answer: ['일반화 관계', '일반화', 'Generalization'],
    explanation: '일반화 관계(Generalization)는 실선과 속이 빈 삼각형 화살표(▷)로 표시하며 "is-a" 상속 관계를 나타냅니다.',
    difficulty: 'EASY',
    keywords: ['일반화 관계', 'Generalization', '상속관계'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '1.2',
  },
  {
    id: 'EXP26_TST_013',
    subject: '소프트웨어설계',
    category: '요구사항 확인 및 모델링',
    subCategory: 'UML 관계',
    type: 'SHORT_ANSWER',
    question: '사물이 할 수 있는 행동(인터페이스)을 선언하고, 다른 사물이 그 선언된 행동을 실제로 구현(Implements)하여 완결하는 관계를 무엇이라 하는가?',
    answer: ['실체화 관계', '실체화', 'Realization'],
    explanation: '실체화 관계(Realization)는 점선과 속이 빈 삼각형 화살표(▷)로 표시하며 인터페이스와 구현 클래스 간의 관계입니다.',
    difficulty: 'EASY',
    keywords: ['실체화 관계', 'Realization', '인터페이스구현'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '1.2',
  },
  {
    id: 'EXP26_TST_014',
    subject: '소프트웨어설계',
    category: '요구사항 확인 및 모델링',
    subCategory: 'UML 다이어그램 분류',
    type: 'SHORT_ANSWER',
    question: 'UML 다이어그램을 구조적(정적) 다이어그램과 행위적(동적) 다이어그램으로 나눌 때, 시스템의 컴포넌트 간 물리적 배치와 실행 하드웨어 노드(서버, 네트워크 장비) 구성을 표현하는 정적 다이어그램은 무엇인가?',
    answer: ['배치 다이어그램', '배치', 'Deployment Diagram'],
    explanation: '배치 다이어그램(Deployment Diagram)은 소프트웨어 모듈이 실제 어떤 물리적 컴퓨터(노드)에 할당되어 실행되는지 보여줍니다.',
    difficulty: 'EASY',
    keywords: ['배치 다이어그램', 'Deployment Diagram', '물리적배치'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '1.2',
  },
  {
    id: 'EXP26_TST_015',
    subject: '소프트웨어설계',
    category: '애플리케이션 테스트 관리',
    subCategory: '테스트 시각',
    type: 'SHORT_ANSWER',
    question: '소프트웨어 개발이 완료된 후, 개발자의 시각에서 명세서대로 올바르게 구현되었는지 점검하는 검증(Verification)과 대조적으로, 사용자(고객)의 시각에서 올바른 소프트웨어가 구축되었는지(사용자 요구 만족)를 평가하는 개념을 무엇이라 하는가?',
    answer: ['확인', 'Validation'],
    explanation: '검증(Verification)은 "규격서대로 잘 만들었는가(Are we building the product right?)"이고, 확인(Validation)은 "고객이 원하는 진짜 소프트웨어를 만들었는가(Are we building the right product?)"입니다.',
    difficulty: 'EASY',
    keywords: ['확인', 'Validation', '검증과확인'],
    source: '2026 실기 핵심 보강',
    angle: 'COMPARISON',
    targetSubUnit: '7.1',
  },
  {
    id: 'EXP26_TST_016',
    subject: '소프트웨어설계',
    category: '애플리케이션 테스트 관리',
    subCategory: '테스트 오라클',
    type: 'SHORT_ANSWER',
    question: '테스트 결과가 참인지 거짓인지를 판단하기 위해 사전에 정의된 참값을 제공하는 테스트 오라클 중, 모든 입력값에 대하여 기대하는 결과를 100% 완벽히 계산해 주는 가장 이상적인 오라클은 무엇인가?',
    answer: ['참 오라클', 'True Oracle'],
    explanation: '참 오라클(True Oracle)은 모든 입력에 대한 정답을 생성할 수 있는 오라클로, 주로 항공/미션 크리티컬 시스템에 적용됩니다.',
    difficulty: 'EASY',
    keywords: ['참 오라클', 'True Oracle', '테스트오라클'],
    source: '2026 실기 핵심 보강',
    angle: 'COMPARISON',
    targetSubUnit: '7.1',
  },
  {
    id: 'EXP26_TST_017',
    subject: '소프트웨어설계',
    category: '애플리케이션 테스트 관리',
    subCategory: '테스트 오라클',
    type: 'SHORT_ANSWER',
    question: '모든 입력에 대한 결과를 산출할 수 없어 특정 주요 입력값(특수값, 경계값 등)에 대해서만 정확한 결과를 확인하고 나머지는 추정하는 실용적인 오라클은 무엇인가?',
    answer: ['샘플링 오라클', 'Sampling Oracle'],
    explanation: '샘플링 오라클(Sampling Oracle)은 전수 검사가 불가능할 때 대표적인 표본 입력값에 대해서만 결과를 검증하는 오라클입니다.',
    difficulty: 'MEDIUM',
    keywords: ['샘플링 오라클', 'Sampling Oracle', '테스트오라클'],
    source: '2026 실기 핵심 보강',
    angle: 'COMPARISON',
    targetSubUnit: '7.1',
  },
  {
    id: 'EXP26_TST_018',
    subject: '소프트웨어설계',
    category: '애플리케이션 테스트 관리',
    subCategory: '테스트 하네스 구성요소',
    type: 'SHORT_ANSWER',
    question: '상향식 통합 테스트에서 하위 모듈은 이미 구현되어 있으나 상위 모듈이 아직 개발되지 않았을 때, 하위 모듈을 호출하고 매개변수를 전달하여 결과를 확인하기 위해 임시로 작성하는 상위 가상 모듈은 무엇인가?',
    answer: ['테스트 드라이버', '드라이버', 'Test Driver'],
    explanation: '테스트 드라이버(Test Driver)는 상위 모듈 역할을 대행하는 테스트 도구이며, 반대로 하위 모듈 역할을 대행하는 것은 테스트 스텁(Test Stub)입니다.',
    difficulty: 'EASY',
    keywords: ['테스트 드라이버', 'Test Driver', '상향식통합'],
    source: '2026 실기 핵심 보강',
    angle: 'COMPARISON',
    targetSubUnit: '7.1',
  },
  {
    id: 'EXP26_TST_019',
    subject: '소프트웨어설계',
    category: '애플리케이션 성능 개선',
    subCategory: '클린 코드 원칙',
    type: 'SHORT_ANSWER',
    question: '클린 코드(Clean Code) 작성 원칙 중, 코드 내부에 중복된 로직이나 동일한 표현식을 제거하고 공통 메소드로 추출하여 중복을 없애야 한다는 원칙은 무엇인가?',
    answer: ['중복 최소화', '중복 배제', '중복의 최소화'],
    explanation: '클린 코드의 5대 원칙은 가독성, 단순성, 의존성 배제, 중복 최소화, 추상화입니다.',
    difficulty: 'EASY',
    keywords: ['중복 최소화', '클린코드', '중복배제'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '10.1',
  },
  {
    id: 'EXP26_TST_020',
    subject: '소프트웨어설계',
    category: '애플리케이션 성능 개선',
    subCategory: '소스코드 품질 분석 도구',
    type: 'SHORT_ANSWER',
    question: '소스코드를 직접 실행하지 않고 코딩 표준 준수 여부, 잠재적 결함, 보안 취약점, 복잡도 등을 소스코드 텍스트 구조 분석을 통해 검사하는 분석 도구(예: SonarQube, PMD, Checkstyle)를 무엇이라 하는가?',
    answer: ['정적 분석 도구', '정적 분석', '정적 테스팅 도구', 'Static Analysis'],
    explanation: '정적 분석 도구(Static Code Analysis)는 컴파일이나 실행 없이 소스코드를 파싱하여 버그와 보안 결함을 조기에 검출합니다.',
    difficulty: 'EASY',
    keywords: ['정적 분석 도구', 'SonarQube', '정적분석'],
    source: '2026 실기 핵심 보강',
    angle: 'COMPARISON',
    targetSubUnit: '10.1',
  },
  {
    id: 'EXP26_TST_021',
    subject: '소프트웨어설계',
    category: '애플리케이션 테스트 관리',
    subCategory: '테스트 시각 및 인수 테스트',
    type: 'SHORT_ANSWER',
    question: '인수 테스트(Acceptance Test)의 두 가지 유형 중, 개발사 내부의 통제된 환경에서 실제 사용자가 개발자와 함께 참여하여 소프트웨어를 테스트하는 기법을 무엇이라 하는가?',
    answer: ['알파 테스트', 'Alpha Test'],
    explanation: '알파 테스트는 개발자의 통제 하에 내부에서 수행되고, 실제 통제되지 않은 고객 환경에서 다수의 사용자가 테스트하는 것은 베타 테스트(Beta Test)입니다.',
    difficulty: 'EASY',
    keywords: ['알파 테스트', 'Alpha Test', '인수테스트'],
    source: '2026 실기 핵심 보강',
    angle: 'COMPARISON',
    targetSubUnit: '7.1',
  },
  {
    id: 'EXP26_TST_022',
    subject: '소프트웨어설계',
    category: '애플리케이션 테스트 관리',
    subCategory: '테스트 결함 관리',
    type: 'SHORT_ANSWER',
    question: '발견된 결함이 시스템의 핵심 기능을 전면 마비시키거나 데이터 유실을 초래하는지, 아니면 단순한 UI 오탈자인지와 같이 결함이 시스템에 미치는 영향의 치명적 정도를 나타내는 척도는 무엇인가?',
    answer: ['결함 심각도', '심각도', 'Severity', '결함 심각도(Severity)'],
    explanation: '결함 심각도(Severity)는 시스템 기능에 미치는 기술적 영향도이며, 결함을 얼마나 빨리 수정해야 하는지 비즈니스적 긴급도를 나타내는 것은 결함 우선순위(Priority)입니다.',
    difficulty: 'MEDIUM',
    keywords: ['결함 심각도', 'Severity', '결함관리'],
    source: '2026 실기 핵심 보강',
    angle: 'COMPARISON',
    targetSubUnit: '7.1',
  },
  {
    id: 'EXP26_TST_023',
    subject: '소프트웨어설계',
    category: '요구사항 확인 및 모델링',
    subCategory: 'UML 다이어그램',
    type: 'SHORT_ANSWER',
    question: '객체들 간에 주고받는 메시지의 시간적 흐름과 생명선(Lifeline), 활성화 막대(Execution Occurrence)를 수직 시간축을 기준으로 표현하는 대표적인 동적 행위 다이어그램은 무엇인가?',
    answer: ['순차 다이어그램', '시퀀스 다이어그램', 'Sequence Diagram'],
    explanation: '순차 다이어그램(Sequence Diagram)은 객체 간의 메시지 교환 순서를 시간의 경과에 따라 명확히 시각화합니다.',
    difficulty: 'EASY',
    keywords: ['순차 다이어그램', '시퀀스 다이어그램', 'Sequence Diagram'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '1.2',
  },
  {
    id: 'EXP26_TST_024',
    subject: '소프트웨어설계',
    category: '애플리케이션 테스트 관리',
    subCategory: '테스트 원리',
    type: 'SHORT_ANSWER',
    question: '소프트웨어 테스트의 7대 원리 중, 동일한 테스트 케이스로 반복해서 테스트를 수행하면 더 이상 새로운 결함을 찾아낼 수 없으므로 주기적으로 테스트 케이스를 개선하고 변경해야 한다는 원리는 무엇인가?',
    answer: ['살충제 패러독스', 'Pesticide Paradox'],
    explanation: '살충제 패러독스(Pesticide Paradox)는 곤충이 동일한 살충제에 내성을 갖듯이 기존 테스트 케이스에 결함이 적응되어 새로운 결함 검출력이 떨어지는 현상입니다.',
    difficulty: 'EASY',
    keywords: ['살충제 패러독스', 'Pesticide Paradox', '테스트원리'],
    source: '2026 실기 핵심 보강',
    angle: 'TERM_FROM_DEFINITION',
    targetSubUnit: '7.1',
  },
  {
    id: 'EXP26_TST_025',
    subject: '소프트웨어설계',
    category: '애플리케이션 테스트 관리',
    subCategory: '테스트 원리',
    type: 'SHORT_ANSWER',
    question: '소프트웨어 테스트의 7대 원리 중, 대부분의 결함은 시스템 전체에 고르게 퍼져 있는 것이 아니라 소수의 특정 취약한 모듈(약 20%의 모듈)에 집중(약 80%의 결함)되어 발생한다는 원리는 무엇인가?',
    answer: ['결함 집중', '파레토 법칙', '결함 집중(Defect Clustering)'],
    explanation: '결함 집중(Defect Clustering / 파레토 법칙)은 결함이 많이 발견된 특정 모듈에 더 많은 추가 결함이 숨겨져 있을 확률이 높다는 원리입니다.',
    difficulty: 'EASY',
    keywords: ['결함 집중', '파레토 법칙', 'Defect Clustering'],
    source: '2026 실기 핵심 보강',
    angle: 'TERM_FROM_DEFINITION',
    targetSubUnit: '7.1',
  },
];
