import { ExpansionCandidate } from '../validator';

/**
 * Batch 2: 데이터 조작 프로시저 & 절차형 SQL & 고급 분석 SQL (공식 실기 범위 2.3, 8.2, 8.3)
 * 기존 커버리지: 2.3 (NONE 0문항), 8.3 (THIN 1문항)
 * 목표: 25문항 엄선 (출제각도: SHORT_SQL, PROCESS_SEQUENCE, COMPARISON, IDENTIFICATION 등)
 */
export const BATCH2_CANDIDATES: ExpansionCandidate[] = [
  {
    id: 'EXP26_SQL_001',
    subject: '데이터베이스구축',
    category: '고급 SQL 작성',
    subCategory: '윈도우 함수',
    type: 'SHORT_ANSWER',
    question: 'SQL 윈도우 순위 함수 중, 동일한 순위가 발생했을 때 중복 순위를 건너뛰지 않고 1위, 2위, 2위, 3위와 같이 연속된 순위를 부여하는 함수는 무엇인가?',
    answer: ['DENSE_RANK', 'DENSE_RANK()'],
    explanation: 'RANK()는 1위, 2위, 2위, 4위처럼 중복 순위만큼 건너뛰지만, DENSE_RANK()는 순위의 공백 없이 1위, 2위, 2위, 3위로 순위를 연속 부여합니다.',
    difficulty: 'EASY',
    keywords: ['DENSE_RANK', '윈도우함수', '순위함수'],
    source: '2026 실기 핵심 보강',
    angle: 'COMPARISON',
    targetSubUnit: '8.2',
  },
  {
    id: 'EXP26_SQL_002',
    subject: '데이터베이스구축',
    category: '고급 SQL 작성',
    subCategory: '윈도우 함수',
    type: 'SHORT_ANSWER',
    question: 'SQL 윈도우 순위 함수 중, 동일한 순위(동점)가 존재하더라도 고유한 순위 번호를 무조건 1부터 1씩 차례대로 매기는 함수는 무엇인가?',
    answer: ['ROW_NUMBER', 'ROW_NUMBER()'],
    explanation: 'ROW_NUMBER()는 동순위를 인정하지 않고 정렬 순서에 따라 고유한 연속 일련번호(1, 2, 3, 4...)를 각 행에 부여합니다.',
    difficulty: 'EASY',
    keywords: ['ROW_NUMBER', '윈도우함수', '일련번호'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '8.2',
  },
  {
    id: 'EXP26_SQL_003',
    subject: '데이터베이스구축',
    category: '고급 SQL 작성',
    subCategory: '윈도우 함수',
    type: 'SHORT_ANSWER',
    question: 'SQL 윈도우 함수 중, 현재 행을 기준으로 지정된 오프셋만큼 이전 행의 컬럼 값을 가져오는 함수를 쓰시오. (예: 바로 앞 이전 달 매출액 조회)',
    answer: ['LAG', 'LAG()'],
    explanation: 'LAG()는 현재 행보다 앞에 위치한 행의 데이터를 참조하는 함수이며, 반대로 이후 행을 참조하는 함수는 LEAD()입니다.',
    difficulty: 'MEDIUM',
    keywords: ['LAG', '윈도우함수', '이전행'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '8.2',
  },
  {
    id: 'EXP26_SQL_004',
    subject: '데이터베이스구축',
    category: '고급 SQL 작성',
    subCategory: '윈도우 함수',
    type: 'SHORT_ANSWER',
    question: 'SQL 윈도우 함수 중, 현재 행을 기준으로 다음 행(이후 위치한 행)의 데이터를 조회할 때 사용하는 함수는 무엇인가?',
    answer: ['LEAD', 'LEAD()'],
    explanation: 'LEAD() 함수는 현재 행의 뒤에 있는 N번째 행의 값을 읽어올 때 사용합니다.',
    difficulty: 'MEDIUM',
    keywords: ['LEAD', '윈도우함수', '다음행'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '8.2',
  },
  {
    id: 'EXP26_SQL_005',
    subject: '데이터베이스구축',
    category: '고급 SQL 작성',
    subCategory: '그룹 함수',
    type: 'SHORT_ANSWER',
    question: 'GROUP BY 절과 함께 쓰여 지정된 컬럼의 계층적 순서(오른쪽에서 왼쪽으로 컬럼을 하나씩 제거)에 따라 단계별 소계(Subtotal)와 최종 총계(Grand Total)를 산출하는 그룹 함수는 무엇인가?',
    answer: ['ROLLUP', 'ROLLUP()'],
    explanation: 'ROLLUP(A, B)는 (A, B)별 집계, (A)별 소계, 전체 총계를 계층적으로 생성합니다.',
    difficulty: 'EASY',
    keywords: ['ROLLUP', '그룹함수', '소계'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '8.2',
  },
  {
    id: 'EXP26_SQL_006',
    subject: '데이터베이스구축',
    category: '고급 SQL 작성',
    subCategory: '그룹 함수',
    type: 'SHORT_ANSWER',
    question: 'GROUP BY 절에서 명시된 모든 컬럼들의 가능한 모든 조합(2의 N승 개 다차원 집계)에 대해 소계 및 총계를 생성하는 다차원 집계 그룹 함수는 무엇인가?',
    answer: ['CUBE', 'CUBE()'],
    explanation: 'CUBE(A, B)는 결합 가능한 모든 경우의 수[(A, B), (A), (B), ()]에 대해 다차원 집계를 수행합니다.',
    difficulty: 'MEDIUM',
    keywords: ['CUBE', '그룹함수', '다차원집계'],
    source: '2026 실기 핵심 보강',
    angle: 'COMPARISON',
    targetSubUnit: '8.2',
  },
  {
    id: 'EXP26_SQL_007',
    subject: '데이터베이스구축',
    category: '고급 SQL 작성',
    subCategory: '그룹 함수',
    type: 'SHORT_ANSWER',
    question: 'GROUP BY 절에서 사용자가 집계하고자 하는 컬럼 그룹의 조합을 개별적으로 직접 나열하여 원하는 단위의 집계만을 선택적으로 산출할 수 있게 해주는 SQL 그룹 함수는 무엇인가?',
    answer: ['GROUPING SETS', 'GROUPING SETS()'],
    explanation: 'GROUPING SETS(A, B)는 평등한 관계에서 A별 집계와 B별 집계를 개별적으로 UNION ALL한 결과를 효율적으로 구합니다.',
    difficulty: 'MEDIUM',
    keywords: ['GROUPING SETS', '그룹함수'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '8.2',
  },
  {
    id: 'EXP26_SQL_008',
    subject: '데이터베이스구축',
    category: '절차형 SQL',
    subCategory: 'PL/SQL 기본 구조',
    type: 'SHORT_ANSWER',
    question: '오라클 PL/SQL 블록의 3대 구성 섹션 중, 프로시저 내부에서 사용할 변수, 상수, 커서(Cursor)를 선언하는 선택적 시작 섹션의 키워드는 무엇인가?',
    answer: ['DECLARE', 'DECLARE절'],
    explanation: 'PL/SQL 블록은 선언부(DECLARE), 실행부(BEGIN ~ END), 예외처리부(EXCEPTION)로 구성됩니다.',
    difficulty: 'EASY',
    keywords: ['DECLARE', 'PL/SQL', '선언부'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '2.3',
  },
  {
    id: 'EXP26_SQL_009',
    subject: '데이터베이스구축',
    category: '절차형 SQL',
    subCategory: 'PL/SQL 커서(Cursor)',
    type: 'SHORT_ANSWER',
    question: '복수 개의 행을 반환하는 SELECT 쿼리의 결과 집합을 한 행씩 순차적으로 읽어와 처리하기 위한 PL/SQL 커서(Cursor)의 생명주기 4단계를 순서대로 쓰시오. [선언 → (    ) → 패치 → (    )]',
    answer: ['오픈, 클로즈', 'OPEN, CLOSE', '열기, 닫기'],
    explanation: '명시적 커서 제어 4단계는 DECLARE(선언) → OPEN(열기/실행) → FETCH(한 행 읽기) → CLOSE(닫기/자원해제)입니다.',
    difficulty: 'MEDIUM',
    keywords: ['커서', 'OPEN', 'CLOSE', 'FETCH'],
    source: '2026 실기 핵심 보강',
    angle: 'PROCESS_SEQUENCE',
    targetSubUnit: '2.3',
  },
  {
    id: 'EXP26_SQL_010',
    subject: '데이터베이스구축',
    category: '절차형 SQL',
    subCategory: 'PL/SQL 커서 속성',
    type: 'SHORT_ANSWER',
    question: 'PL/SQL 커서에서 FETCH 문을 수행했을 때 더 이상 읽어올 행(Row)이 존재하지 않으면 TRUE를 반환하는 커서 상태 속성의 키워드는 무엇인가?',
    answer: ['%NOTFOUND', 'NOTFOUND'],
    explanation: '%NOTFOUND 속성은 커서에서 마지막 FETCH 결과 반환된 행이 없을 때 TRUE가 되어 루프 탈출 조건(EXIT WHEN 커서명%NOTFOUND)으로 사용됩니다.',
    difficulty: 'MEDIUM',
    keywords: ['%NOTFOUND', '커서속성', 'FETCH'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '2.3',
  },
  {
    id: 'EXP26_SQL_011',
    subject: '데이터베이스구축',
    category: '절차형 SQL',
    subCategory: 'PL/SQL 커서 속성',
    type: 'SHORT_ANSWER',
    question: 'PL/SQL 커서나 SQL 문 실행 후, 지금까지 성공적으로 FETCH 되었거나 DML에 의해 영향을 받은 행의 총 개수를 반환하는 커서 속성은 무엇인가?',
    answer: ['%ROWCOUNT', 'ROWCOUNT'],
    explanation: '%ROWCOUNT는 현재까지 읽어들인 행의 수 또는 INSERT/UPDATE/DELETE로 수정된 레코드 수를 반환합니다.',
    difficulty: 'MEDIUM',
    keywords: ['%ROWCOUNT', '커서속성', '행수'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '2.3',
  },
  {
    id: 'EXP26_SQL_012',
    subject: '데이터베이스구축',
    category: '절차형 SQL',
    subCategory: '트리거(Trigger)',
    type: 'SHORT_ANSWER',
    question: '특정 테이블에 INSERT, UPDATE, DELETE 등의 이벤트가 발생할 때 실행되는 트리거 중, 변경되는 각 데이터 행마다 개별적으로 한 번씩 실행되도록 지정하는 SQL 절은 무엇인가?',
    answer: ['FOR EACH ROW'],
    explanation: 'FOR EACH ROW 절을 지정하면 문장 단위가 아닌 영향을 받는 행 단위로 트리거가 실행되는 행 트리거(Row Trigger)가 됩니다.',
    difficulty: 'EASY',
    keywords: ['FOR EACH ROW', '행트리거', '트리거'],
    source: '2026 실기 핵심 보강',
    angle: 'SHORT_SQL',
    targetSubUnit: '2.3',
  },
  {
    id: 'EXP26_SQL_013',
    subject: '데이터베이스구축',
    category: '절차형 SQL',
    subCategory: '트리거(Trigger)',
    type: 'SHORT_ANSWER',
    question: '행 트리거(FOR EACH ROW)에서 INSERT 또는 UPDATE 문에 의해 새롭게 입력되거나 수정되어 들어오는 컬럼의 변경 후 값을 참조할 때 사용하는 가상 콜론 변수는 무엇인가?',
    answer: [':NEW', 'NEW'],
    explanation: '행 트리거에서 :NEW는 새로 갱신될 값을 가리키고, :OLD는 변경 이전의 기존 값을 가리킵니다. (DELETE 문에서는 :OLD만 유효)',
    difficulty: 'EASY',
    keywords: [':NEW', 'NEW', '트리거변수'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '2.3',
  },
  {
    id: 'EXP26_SQL_014',
    subject: '데이터베이스구축',
    category: '절차형 SQL',
    subCategory: '객체 비교',
    type: 'SHORT_ANSWER',
    question: '데이터베이스 절차형 객체 중, 저장 프로시저(Stored Procedure)와 달리 실행 후 단 하나의 결과를 반드시 RETURN 문을 통해 반환해야 하며, 일반 SELECT 쿼리문 내부에서도 호출 가능한 객체는 무엇인가?',
    answer: ['사용자 정의 함수', '사용자 정의 함수(User-Defined Function)', 'Function'],
    explanation: '사용자 정의 함수(User Defined Function)는 수식이나 표현식의 일부로 사용되며 단일 값을 반드시 RETURN해야 합니다.',
    difficulty: 'EASY',
    keywords: ['사용자 정의 함수', 'Function', 'RETURN'],
    source: '2026 실기 핵심 보강',
    angle: 'COMPARISON',
    targetSubUnit: '2.3',
  },
  {
    id: 'EXP26_SQL_015',
    subject: '데이터베이스구축',
    category: 'SQL 최적화',
    subCategory: '옵티마이저(Optimizer)',
    type: 'SHORT_ANSWER',
    question: 'DBMS 옵티마이저의 두 가지 유형 중, 테이블 통계 정보나 데이터 분포를 고려하지 않고 미리 정해진 우선순위 규칙에 따라 실행 계획을 세우는 방식을 무엇이라 하는가?',
    answer: ['RBO', '규칙 기반 옵티마이저', 'Rule Based Optimizer'],
    explanation: 'RBO(Rule-Based Optimizer, 규칙 기반 옵티마이저)는 인덱스 유무, 연산자 종류 등의 고정된 15개 우선순위 룰에 따라 경로를 결정합니다.',
    difficulty: 'EASY',
    keywords: ['RBO', '규칙 기반 옵티마이저', '옵티마이저'],
    source: '2026 실기 핵심 보강',
    angle: 'COMPARISON',
    targetSubUnit: '8.3',
  },
  {
    id: 'EXP26_SQL_016',
    subject: '데이터베이스구축',
    category: 'SQL 최적화',
    subCategory: '옵티마이저(Optimizer)',
    type: 'SHORT_ANSWER',
    question: '테이블 및 인덱스의 레코드 수, 블록 수, 카디널리티 등 카탈로그 통계 정보를 바탕으로 쿼리 수행에 필요한 비용(CPU 및 I/O)을 예측하여 최적의 실행 계획을 선택하는 현대적인 옵티마이저는 무엇인가?',
    answer: ['CBO', '비용 기반 옵티마이저', 'Cost Based Optimizer'],
    explanation: 'CBO(Cost-Based Optimizer, 비용 기반 옵티마이저)는 데이터 카탈로그 통계 정보를 기반으로 가장 적은 소요 비용이 드는 실행 계획을 선택합니다.',
    difficulty: 'EASY',
    keywords: ['CBO', '비용 기반 옵티마이저', '옵티마이저'],
    source: '2026 실기 핵심 보강',
    angle: 'COMPARISON',
    targetSubUnit: '8.3',
  },
  {
    id: 'EXP26_SQL_017',
    subject: '데이터베이스구축',
    category: 'SQL 최적화',
    subCategory: '인덱스 스캔 방식',
    type: 'SHORT_ANSWER',
    question: '인덱스 리프 블록에서 특정 검색 조건에 해당하는 시작점부터 종료점까지만 수평적으로 탐색하여 조건에 맞는 행만 효율적으로 읽어내는 가장 대표적인 인덱스 검색 방식은 무엇인가?',
    answer: ['Index Range Scan', '인덱스 범위 스캔', '인덱스 레인지 스캔'],
    explanation: 'Index Range Scan은 루트 블록에서 수직 탐색 후 리프 블록에서 필요한 범위만큼만 스캔하는 표준적인 인덱스 스캔 방식입니다.',
    difficulty: 'MEDIUM',
    keywords: ['Index Range Scan', '인덱스범위스캔', '인덱스스캔'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '8.3',
  },
  {
    id: 'EXP26_SQL_018',
    subject: '데이터베이스구축',
    category: 'SQL 최적화',
    subCategory: '인덱스 스캔 방식',
    type: 'SHORT_ANSWER',
    question: '테이블의 전체 데이터를 인덱스를 거치지 않고 처음부터 끝까지 모든 블록을 순차적으로 읽어내는 스캔 방식을 무엇이라 하는가? (대용량 배치 작업이나 테이블 데이터 대부분을 읽을 때 유리)',
    answer: ['Full Table Scan', '테이블 전체 스캔', 'Table Full Scan'],
    explanation: 'Full Table Scan(테이블 풀 스캔)은 인덱스를 타지 않고 데이터 세그먼트의 전체 블록을 멀티블록 I/O로 빠르게 읽는 방식입니다.',
    difficulty: 'EASY',
    keywords: ['Full Table Scan', '테이블풀스캔', 'FTS'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '8.3',
  },
  {
    id: 'EXP26_SQL_019',
    subject: '데이터베이스구축',
    category: '기본 및 고급 SQL',
    subCategory: '집합 연산자',
    type: 'SHORT_ANSWER',
    question: '두 개의 SELECT 결과를 하나로 결합할 때, UNION과 달리 중복 행 제거 및 정렬(SORT) 작업을 수행하지 않고 모든 결과 행을 그대로 합쳐서 출력하는 집합 연산자는 무엇인가?',
    answer: ['UNION ALL'],
    explanation: 'UNION은 중복을 제거하기 위해 내부적인 정렬 부하가 발생하지만, UNION ALL은 중복 제거 없이 바로 병합하므로 성능상 훨씬 빠릅니다.',
    difficulty: 'EASY',
    keywords: ['UNION ALL', '집합연산자', '중복허용'],
    source: '2026 실기 핵심 보강',
    angle: 'COMPARISON',
    targetSubUnit: '8.2',
  },
  {
    id: 'EXP26_SQL_020',
    subject: '데이터베이스구축',
    category: '고급 SQL 작성',
    subCategory: '서브쿼리 연산자',
    type: 'SHORT_ANSWER',
    question: '서브쿼리 연산자 중 서브쿼리의 결과로 반환되는 레코드가 단 하나라도 존재하는지 여부만을 판별하여 참(TRUE) 또는 거짓(FALSE)을 반환하는 조건 키워드는 무엇인가?',
    answer: ['EXISTS'],
    explanation: 'EXISTS는 서브쿼리 결과가 1건이라도 발견되는 즉시 true를 반환하고 검색을 멈추므로 IN보다 대용량 데이터에서 성능이 우수합니다.',
    difficulty: 'EASY',
    keywords: ['EXISTS', '서브쿼리', '존재여부'],
    source: '2026 실기 핵심 보강',
    angle: 'SHORT_SQL',
    targetSubUnit: '8.2',
  },
  {
    id: 'EXP26_SQL_021',
    subject: '데이터베이스구축',
    category: '기본 SQL 작성',
    subCategory: '테이블 제약조건',
    type: 'SHORT_ANSWER',
    question: '테이블 생성(CREATE TABLE) 시 특정 컬럼에 입력되는 값이 정의된 논리적 조건식(예: 나이 >= 19)을 반드시 만족해야 하도록 제한하는 무결성 제약조건 키워드는 무엇인가?',
    answer: ['CHECK', 'CHECK 제약조건'],
    explanation: 'CHECK 제약조건은 데이터 입력/수정 시 특정 컬럼 값이 도메인 유효 범위에 속하는지 조건식으로 검증합니다.',
    difficulty: 'EASY',
    keywords: ['CHECK', '제약조건', '도메인무결성'],
    source: '2026 실기 핵심 보강',
    angle: 'SHORT_SQL',
    targetSubUnit: '8.1',
  },
  {
    id: 'EXP26_SQL_022',
    subject: '데이터베이스구축',
    category: '고급 SQL 작성',
    subCategory: '상관 서브쿼리',
    type: 'SHORT_ANSWER',
    question: '서브쿼리가 메인쿼리의 컬럼 값을 참조하여 실행되고, 메인쿼리의 각 행마다 서브쿼리가 반복 수행되는 상호 의존적인 형태의 서브쿼리를 무엇이라 하는가?',
    answer: ['상관 서브쿼리', '상호 연관 서브쿼리', 'Correlated Subquery'],
    explanation: '상관 서브쿼리(Correlated Subquery)는 서브쿼리 내부에서 메인쿼리의 별칭(Alias)을 참조하여 행 단위로 계산을 반복합니다.',
    difficulty: 'MEDIUM',
    keywords: ['상관 서브쿼리', 'Correlated Subquery', '서브쿼리'],
    source: '2026 실기 핵심 보강',
    angle: 'TERM_FROM_DEFINITION',
    targetSubUnit: '8.2',
  },
  {
    id: 'EXP26_SQL_023',
    subject: '데이터베이스구축',
    category: 'SQL 최적화',
    subCategory: '힌트(Hint)',
    type: 'SHORT_ANSWER',
    question: '개발자가 SQL 쿼리문 안에 특수 주석(/*+ ... */) 형태로 작성하여, 옵티마이저의 기본 실행 계획 대신 특정 인덱스 사용이나 조인 방식을 강제로 유도하는 명령을 무엇이라 하는가?',
    answer: ['힌트', '옵티마이저 힌트', 'Hint'],
    explanation: '힌트(Hint)는 SQL 문 내부에 작성되어 옵티마이저에게 강제로 실행 경로(인덱스 지정, 풀테이블 스캔, 조인 순서 등)를 지시합니다.',
    difficulty: 'EASY',
    keywords: ['힌트', 'Hint', '옵티마이저힌트'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '8.3',
  },
  {
    id: 'EXP26_SQL_024',
    subject: '데이터베이스구축',
    category: '기본 SQL 작성',
    subCategory: '테이블 데이터 삭제',
    type: 'SHORT_ANSWER',
    question: '테이블의 모든 데이터를 삭제할 때, DELETE 문과 달리 트랜잭션 로그를 남기지 않고 즉시 공간을 반환하며 롤백(ROLLBACK)이 불가능한 DDL 명령어는 무엇인가?',
    answer: ['TRUNCATE', 'TRUNCATE TABLE'],
    explanation: 'TRUNCATE는 DDL 명령어로 테이블 구조는 남긴 채 모든 행을 일괄 삭제하며, 시스템 로그 기록을 최소화하여 성능이 매우 빠릅니다.',
    difficulty: 'EASY',
    keywords: ['TRUNCATE', 'DELETE비교', 'DDL'],
    source: '2026 실기 핵심 보강',
    angle: 'COMPARISON',
    targetSubUnit: '8.1',
  },
  {
    id: 'EXP26_SQL_025',
    subject: '데이터베이스구축',
    category: 'SQL 최적화',
    subCategory: '실행 계획(Execution Plan)',
    type: 'SHORT_ANSWER',
    question: '옵티마이저가 사용자가 작성한 SQL 문을 실행하기 위해 수립한 처리 경로(테이블 접근 순서, 인덱스 사용, 조인 기법 등)를 시각적으로 확인하기 위해 실행하는 데이터베이스 명령어를 쓰시오.',
    answer: ['EXPLAIN PLAN', 'EXPLAIN'],
    explanation: 'EXPLAIN PLAN 문은 옵티마이저가 생성한 실행 계획을 PLAN_TABLE 등에 기록하여 성능 튜닝 시 조회할 수 있게 합니다.',
    difficulty: 'MEDIUM',
    keywords: ['EXPLAIN PLAN', '실행계획', 'SQL튜닝'],
    source: '2026 실기 핵심 보강',
    angle: 'SHORT_SQL',
    targetSubUnit: '8.3',
  },
];
