import { ExpansionCandidate } from '../validator';

/**
 * Batch 3: 연계 데이터 & 인터페이스 설계 / 보안 / 검증 (공식 실기 범위 3.1, 3.3, 5.1, 5.2, 5.3)
 * 기존 커버리지: 3.3 (NONE 0문항), 5.2 (NONE 0문항), 5.3 (THIN 1문항), 3.1 (THIN 4문항)
 * 목표: 25문항 엄선 (출제각도 다양화: COMPARISON, IDENTIFICATION, SCENARIO, CHARACTERISTIC 등)
 */
export const BATCH3_CANDIDATES: ExpansionCandidate[] = [
  {
    id: 'EXP26_INT_001',
    subject: '소프트웨어설계',
    category: '인터페이스 설계 및 연계',
    subCategory: '연계 데이터 표준',
    type: 'SHORT_ANSWER',
    question: '송수신 시스템 간 데이터 교환 시, 속성-값 쌍(Key-Value Pair)과 배열 자료형으로 구성되어 XML보다 구문 분석(Parsing)이 빠르고 데이터 용량이 작은 경량 텍스트 교환 포맷은 무엇인가?',
    answer: ['JSON', 'JavaScript Object Notation'],
    explanation: 'JSON은 자바스크립트 객체 표기법에서 파생된 경량 텍스트 포맷으로, 사람이 읽기 쉽고 웹 API 통신에서 사실상 표준으로 사용됩니다.',
    difficulty: 'EASY',
    keywords: ['JSON', '연계데이터', '경량데이터'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '3.1',
  },
  {
    id: 'EXP26_INT_002',
    subject: '소프트웨어설계',
    category: '인터페이스 설계 및 연계',
    subCategory: '연계 데이터 표준',
    type: 'SHORT_ANSWER',
    question: 'W3C에서 개발한 다목적 마크업 언어로, 사용자가 새로운 태그를 임의로 정의할 수 있으며 데이터와 그 구조를 동시에 설명할 수 있는 표준 교환 포맷은 무엇인가?',
    answer: ['XML', 'Extensible Markup Language'],
    explanation: 'XML은 확장 가능한 마크업 언어로, 플랫폼 독립적인 데이터 기술과 전자문서 표준화(SOAP, SVG 등)에 널리 활용됩니다.',
    difficulty: 'EASY',
    keywords: ['XML', '마크업언어', '연계데이터'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '3.1',
  },
  {
    id: 'EXP26_INT_003',
    subject: '소프트웨어설계',
    category: '인터페이스 설계 및 연계',
    subCategory: '연계 데이터 표준',
    type: 'SHORT_ANSWER',
    question: '구성 설정(Configuration) 파일이나 CI/CD 파이프라인 명세에 주로 쓰이며, 괄호 대신 공백 들여쓰기(Indentation)를 사용하여 가독성을 극대화한 사람이 읽기 쉬운 데이터 직렬화 언어는 무엇인가?',
    answer: ['YAML', 'YML'],
    explanation: 'YAML(YAML Ain\'t Markup Language)은 XML과 JSON에 비해 작성과 판독이 직관적이어서 쿠버네티스(k8s), Docker Compose, GitHub Actions 설정 파일에 광범위하게 쓰입니다.',
    difficulty: 'EASY',
    keywords: ['YAML', '들여쓰기', '데이터직렬화'],
    source: '2026 실기 핵심 보강',
    angle: 'CHARACTERISTIC',
    targetSubUnit: '3.1',
  },
  {
    id: 'EXP26_INT_004',
    subject: '소프트웨어설계',
    category: '인터페이스 검증',
    subCategory: '인터페이스 테스트 자동화 도구',
    type: 'SHORT_ANSWER',
    question: '다양한 환경(OS, 네트워크 장비 등)에서 분산된 테스트를 수행하기 위해 서비스 데몬 형태로 실행되며, 컴포넌트 간의 분산 테스트 및 재사용을 지원하는 서비스 지향 테스트 프레임워크는 무엇인가?',
    answer: ['STAF'],
    explanation: 'STAF(Software Testing Automation Framework)는 분산 환경에서 테스트 수행 및 제어를 데몬 기반으로 통합 지원하는 자동화 프레임워크입니다.',
    difficulty: 'MEDIUM',
    keywords: ['STAF', '테스트자동화', '분산테스트'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '5.3',
  },
  {
    id: 'EXP26_INT_005',
    subject: '소프트웨어설계',
    category: '인터페이스 검증',
    subCategory: '인터페이스 테스트 자동화 도구',
    type: 'SHORT_ANSWER',
    question: '웹 기반의 위키(Wiki) 인터페이스를 활용하여, 비기술자인 고객이나 업무 분석가가 테이블(Table) 형태로 작성한 인수 조건을 그대로 자동화 테스트 케이스로 실행해 주는 도구는 무엇인가?',
    answer: ['FitNesse'],
    explanation: 'FitNesse(핏네스)는 웹 기반 위키 페이지의 표(Table) 형식을 테스트 스크립트로 직접 변환하여 실행하는 인수 테스트 자동화 도구입니다.',
    difficulty: 'MEDIUM',
    keywords: ['FitNesse', '위키', '인수테스트'],
    source: '2026 실기 핵심 보강',
    angle: 'CHARACTERISTIC',
    targetSubUnit: '5.3',
  },
  {
    id: 'EXP26_INT_006',
    subject: '소프트웨어설계',
    category: '인터페이스 검증',
    subCategory: '인터페이스 테스트 자동화 도구',
    type: 'SHORT_ANSWER',
    question: 'FitNesse의 장점(테스트 협업)과 STAF의 장점(서비스 데몬 기반 분산 환경 지원)을 결합하여 네이버(NHN)에서 오픈소스로 개발한 통합 테스트 프레임워크는 무엇인가?',
    answer: ['NTAF'],
    explanation: 'NTAF(NHN Test Automation Framework)는 FitNesse와 STAF를 결합하여 웹 환경과 분산 환경 테스트를 모두 만족하도록 개발된 프레임워크입니다.',
    difficulty: 'HARD',
    keywords: ['NTAF', 'STAF', 'FitNesse'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '5.3',
  },
  {
    id: 'EXP26_INT_007',
    subject: '소프트웨어설계',
    category: '인터페이스 성능 및 모니터링',
    subCategory: 'APM 도구',
    type: 'SHORT_ANSWER',
    question: '운영 중인 애플리케이션의 성능 병목 지점, 리소스 사용률(CPU/메모리), 트랜잭션 응답 시간, 장애 로그 등을 실시간으로 모니터링하고 분석하는 성능 관리 도구의 영문 약어는 무엇인가?',
    answer: ['APM', 'Application Performance Monitoring', 'Application Performance Management'],
    explanation: 'APM(Application Performance Management / Monitoring, 예: 제니퍼, 스카우터, 와탭)은 시스템 장애 예방과 성능 튜닝에 필수적인 도구입니다.',
    difficulty: 'EASY',
    keywords: ['APM', '애플리케이션성능관리', '모니터링'],
    source: '2026 실기 핵심 보강',
    angle: 'TERM_FROM_DEFINITION',
    targetSubUnit: '5.3',
  },
  {
    id: 'EXP26_INT_008',
    subject: '소프트웨어설계',
    category: '인터페이스 보안',
    subCategory: '통신 구간 암호화',
    type: 'SHORT_ANSWER',
    question: 'IP 계층(3계층)에서 IP 패킷을 암호화하고 무결성을 보장하는 보안 프로토콜 슈트로, 무결성과 송신처 인증을 제공하는 AH 프로토콜과 패킷 페이로드 암호화까지 제공하는 ESP 프로토콜로 구성된 기술은 무엇인가?',
    answer: ['IPSec', 'IPsec'],
    explanation: 'IPSec(IP Security)은 전송 계층 아래의 네트워크 계층에서 동작하여 상위 프로토콜 수정 없이 종단 간 보안 터널(VPN 등)을 구현합니다.',
    difficulty: 'EASY',
    keywords: ['IPSec', 'AH', 'ESP', '네트워크보안'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '3.3',
  },
  {
    id: 'EXP26_INT_009',
    subject: '소프트웨어설계',
    category: '인터페이스 보안',
    subCategory: 'IPSec 동작 모드',
    type: 'SHORT_ANSWER',
    question: 'IPSec의 두 가지 동작 모드 중, 원본 IP 패킷 전체(헤더 포함)를 암호화하고 새로운 New IP 헤더를 덧붙여 라우터 간 VPN 터널 구축에 주로 사용되는 모드는 무엇인가?',
    answer: ['터널 모드', 'Tunnel Mode', '터널모드'],
    explanation: 'IPSec 터널 모드는 원본 IP 패킷 전체를 캡슐화하여 게이트웨이(방화벽/VPN) 간 통신에 쓰이며, 종단 호스트 간 통신에서 페이로드만 암호화하는 것은 전송 모드(Transport Mode)입니다.',
    difficulty: 'MEDIUM',
    keywords: ['터널 모드', 'Tunnel Mode', 'IPSec'],
    source: '2026 실기 핵심 보강',
    angle: 'COMPARISON',
    targetSubUnit: '3.3',
  },
  {
    id: 'EXP26_INT_010',
    subject: '소프트웨어설계',
    category: '인터페이스 보안',
    subCategory: '전송 계층 보안',
    type: 'SHORT_ANSWER',
    question: '전송 계층과 응용 계층 사이에서 안전한 암호화 통신을 제공하기 위해 넷스케이프가 개발한 SSL(Secure Sockets Layer)을 IETF에서 표준화하여 발전시킨 프로토콜의 약어는 무엇인가?',
    answer: ['TLS', 'Transport Layer Security'],
    explanation: 'TLS(Transport Layer Security)는 웹(HTTPS), 메일(SMTPS) 등의 데이터 기밀성과 데이터 무결성을 제공하는 국제 표준 보안 프로토콜입니다.',
    difficulty: 'EASY',
    keywords: ['TLS', 'SSL', '전송계층보안'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '3.3',
  },
  {
    id: 'EXP26_INT_011',
    subject: '소프트웨어설계',
    category: '인터페이스 설계 및 연계',
    subCategory: '연계 메커니즘',
    type: 'SHORT_ANSWER',
    question: '송신 시스템의 데이터베이스에서 수신 시스템의 원격 데이터베이스에 직접 접속하여 데이터를 조회하거나 조작할 수 있도록 DBMS 자체에서 제공하는 원격 연결 객체를 무엇이라 하는가?',
    answer: ['DB Link', '데이터베이스 링크', 'DB 링크'],
    explanation: 'DB Link(데이터베이스 링크)는 DBMS 간에 네트워크를 통해 원격 테이블에 직접 접근(예: SELECT * FROM emp@remote_db)할 수 있도록 제공하는 메커니즘입니다.',
    difficulty: 'EASY',
    keywords: ['DB Link', 'DB링크', '데이터베이스링크'],
    source: '2026 실기 핵심 보강',
    angle: 'TERM_FROM_DEFINITION',
    targetSubUnit: '3.3',
  },
  {
    id: 'EXP26_INT_012',
    subject: '소프트웨어설계',
    category: '인터페이스 설계 및 연계',
    subCategory: '연계 메커니즘',
    type: 'SHORT_ANSWER',
    question: '송신 시스템의 데이터베이스와 수신 시스템의 데이터베이스 사이의 데이터 불일치를 방지하고, 송신 테이블의 변경(INSERT/UPDATE/DELETE) 사항을 실시간 또는 주기적으로 상대 DB 테이블에 복제해 주는 객체 기법은 무엇인가?',
    answer: ['DB 연결', 'DB Connection Pool', 'DB 복제', 'DB 커넥션'],
    explanation: '데이터베이스 연결 및 연계 테이블 복제(Replication/Trigger 기반)는 배치 또는 실시간 데이터 동기화에 사용됩니다.',
    difficulty: 'MEDIUM',
    keywords: ['DB연계', '데이터동기화'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '3.3',
  },
  {
    id: 'EXP26_INT_013',
    subject: '소프트웨어설계',
    category: '인터페이스 설계 및 연계',
    subCategory: '연계 메커니즘',
    type: 'SHORT_ANSWER',
    question: '웹 브라우저와 웹 서버 간의 비동기적 데이터 교환 기술로, 전체 페이지를 새로고침하지 않고도 백그라운드에서 서버와 JSON/XML 데이터를 주고받아 화면 일부분만을 갱신할 수 있는 기술의 약어는 무엇인가?',
    answer: ['AJAX', 'Asynchronous JavaScript and XML'],
    explanation: 'AJAX(비동기 자바스크립트와 XML)는 XMLHttpRequest 또는 Fetch API를 사용하여 끊김 없는 부드러운 웹 사용자 인터페이스를 제공합니다.',
    difficulty: 'EASY',
    keywords: ['AJAX', '비동기통신', '웹인터페이스'],
    source: '2026 실기 핵심 보강',
    angle: 'TERM_FROM_DEFINITION',
    targetSubUnit: '5.1',
  },
  {
    id: 'EXP26_INT_014',
    subject: '소프트웨어설계',
    category: '인터페이스 설계 및 연계',
    subCategory: '웹 서비스 표준',
    type: 'SHORT_ANSWER',
    question: 'SOAP 기반 웹 서비스에서 제공하는 서비스의 구체적인 내용(메서드명, 매개변수, 반환값 타입, 네트워크 통신 프로토콜 및 엔드포인트 URL)을 XML 형식으로 기술한 인터페이스 명세 문서는 무엇인가?',
    answer: ['WSDL', 'Web Services Description Language'],
    explanation: 'WSDL은 웹 서비스가 어떤 기능을 제공하고 어떻게 호출해야 하는지 기술하는 표준 기술서이며, UDDI 등록소에 등록되어 검색됩니다.',
    difficulty: 'EASY',
    keywords: ['WSDL', '웹서비스', 'SOAP'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '5.2',
  },
  {
    id: 'EXP26_INT_015',
    subject: '소프트웨어설계',
    category: '인터페이스 설계 및 연계',
    subCategory: '웹 서비스 표준',
    type: 'SHORT_ANSWER',
    question: '전 세계의 비즈니스 및 웹 서비스 제공자들이 자신들의 WSDL 명세서를 등록하여 누구나 검색하고 공유할 수 있도록 해주는 XML 기반의 공개 등록소(디렉터리 서비스)는 무엇인가?',
    answer: ['UDDI', 'Universal Description, Discovery and Integration'],
    explanation: 'UDDI는 웹 서비스의 전화번호부와 같은 역할을 하는 범용 등록소 규격입니다.',
    difficulty: 'EASY',
    keywords: ['UDDI', '웹서비스등록소', '디렉터리'],
    source: '2026 실기 핵심 보강',
    angle: 'TERM_FROM_DEFINITION',
    targetSubUnit: '5.2',
  },
  {
    id: 'EXP26_INT_016',
    subject: '소프트웨어설계',
    category: '인터페이스 설계 및 연계',
    subCategory: '웹 서비스 아키텍처',
    type: 'SHORT_ANSWER',
    question: 'HTTP 프로토콜의 표준 메서드(GET, POST, PUT, DELETE)를 그대로 활용하여 자원(URI)에 대한 상태 변화를 처리하고, 무상태(Stateless)성과 캐시 기능을 기본적으로 지원하는 웹 아키텍처 스타일은 무엇인가?',
    answer: ['REST', 'Representational State Transfer', 'RESTful'],
    explanation: 'REST(Representational State Transfer)는 자원 지향 구조(ROA)로 URI를 통해 자원을 명시하고 HTTP Method로 행위를 정의합니다.',
    difficulty: 'EASY',
    keywords: ['REST', 'HTTP메서드', 'URI'],
    source: '2026 실기 핵심 보강',
    angle: 'CHARACTERISTIC',
    targetSubUnit: '5.2',
  },
  {
    id: 'EXP26_INT_017',
    subject: '소프트웨어설계',
    category: '인터페이스 설계 및 연계',
    subCategory: '연계 미들웨어',
    type: 'SHORT_ANSWER',
    question: '기업 내 서로 다른 이기종 시스템들 간의 결합도를 낮추기 위해, 중앙에 공통 버스를 두고 메시지 변환, 지능형 라우팅, 프로토콜 변환을 담당하여 느슨한 결합(Loose Coupling)을 제공하는 미들웨어 아키텍처는 무엇인가?',
    answer: ['ESB', 'Enterprise Service Bus'],
    explanation: 'ESB(Enterprise Service Bus)는 SOA(서비스 지향 아키텍처)의 핵심 뼈대로서 다양한 인터페이스 간 상호 운용성을 지원합니다.',
    difficulty: 'EASY',
    keywords: ['ESB', '버스아키텍처', 'SOA'],
    source: '2026 실기 핵심 보강',
    angle: 'TERM_FROM_DEFINITION',
    targetSubUnit: '3.3',
  },
  {
    id: 'EXP26_INT_018',
    subject: '소프트웨어설계',
    category: '인터페이스 설계 및 연계',
    subCategory: '인터페이스 명세서',
    type: 'SHORT_ANSWER',
    question: '송수신 시스템 간의 연계 방식을 정의할 때, 정해진 바이트 크기(고정 길이)나 구분자(Delimiter)를 기준으로 데이터 필드를 연속하여 일렬로 주고받는 정형화된 데이터 통신 단위를 무엇이라 하는가?',
    answer: ['전문', '전문 인터페이스', '전문(Telegram)'],
    explanation: '전문(Telegram) 방식은 금융권 및 공공기관 레거시 시스템에서 고속 대용량 거래 데이터 처리를 위해 주로 사용하는 고정 길이(Fixed Length) 또는 가변 길이 데이터 규격입니다.',
    difficulty: 'MEDIUM',
    keywords: ['전문', '전문인터페이스', '고정길이'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '5.2',
  },
  {
    id: 'EXP26_INT_019',
    subject: '소프트웨어설계',
    category: '인터페이스 오류 처리',
    subCategory: '예외 및 로깅',
    type: 'SHORT_ANSWER',
    question: '시스템 연계 중 네트워크 단절이나 대상 시스템 장애로 인해 전송이 실패했을 때, 데이터를 즉시 폐기하지 않고 보관했다가 일정 주기로 재전송을 시도하는 메커니즘을 무엇이라 하는가?',
    answer: ['재전송 메커니즘', '재시도', '재전송', 'Retry'],
    explanation: '재전송(Retry) 메커니즘은 일시적인 네트워크 순단이나 부하 상황에서 인터페이스 트랜잭션의 신뢰성과 데이터 유실 방지를 위해 필수적입니다.',
    difficulty: 'EASY',
    keywords: ['재전송', 'Retry', '장애처리'],
    source: '2026 실기 핵심 보강',
    angle: 'PROCESS_SEQUENCE',
    targetSubUnit: '3.3',
  },
  {
    id: 'EXP26_INT_020',
    subject: '소프트웨어설계',
    category: '인터페이스 성능',
    subCategory: '성능 지표',
    type: 'SHORT_ANSWER',
    question: '인터페이스 및 시스템 성능 측정 지표 중, 초당 시스템이 처리할 수 있는 트랜잭션(요청)의 건수를 나타내는 핵심 단위의 약어는 무엇인가?',
    answer: ['TPS', 'Transactions Per Second'],
    explanation: 'TPS(Transactions Per Second)는 시스템의 처리량(Throughput)을 나타내는 가장 대표적인 성능 지표입니다.',
    difficulty: 'EASY',
    keywords: ['TPS', '처리량', '성능지표'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '5.3',
  },
  {
    id: 'EXP26_INT_021',
    subject: '소프트웨어설계',
    category: '인터페이스 보안',
    subCategory: '보안 통신 프로토콜',
    type: 'SHORT_ANSWER',
    question: '기존의 텔넷(Telnet)이나 rlogin 등의 평문 전송 원격 접속 방식을 대체하기 위해, 강력한 공개키 암호화 기반으로 안전한 원격 쉘 명령 및 포트 포워딩을 제공하는 프로토콜은 무엇인가?',
    answer: ['SSH', 'Secure Shell'],
    explanation: 'SSH(Secure Shell, 포트 22)는 원격 서버 관리 시 패킷 스니핑을 방지하기 위한 표준 암호화 프로토콜입니다.',
    difficulty: 'EASY',
    keywords: ['SSH', '원격접속', '보안쉘'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '3.3',
  },
  {
    id: 'EXP26_INT_022',
    subject: '소프트웨어설계',
    category: '인터페이스 설계',
    subCategory: '인터페이스 요구사항 분석',
    type: 'SHORT_ANSWER',
    question: '개발할 시스템과 외부 시스템 간의 데이터 흐름 및 경계를 한눈에 파악하기 위해, 전체 시스템을 하나의 단일 프로세스로 두고 외부 엔티티(Entity)와의 입출력 데이터 흐름만을 표현한 DFD 최상위 다이어그램을 무엇이라 하는가?',
    answer: ['기본 시스템 모델', '배경도', 'Context Diagram'],
    explanation: '배경도(Context Diagram)는 DFD Level 0으로서 시스템 전체를 단일 프로세스로 나타내어 시스템의 외부 경계와 입출력을 정의합니다.',
    difficulty: 'MEDIUM',
    keywords: ['배경도', 'Context Diagram', 'DFD'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '5.1',
  },
  {
    id: 'EXP26_INT_023',
    subject: '소프트웨어설계',
    category: '인터페이스 검증',
    subCategory: '웹 UI 자동화 테스트 도구',
    type: 'SHORT_ANSWER',
    question: '다양한 웹 브라우저(크롬, 파이어폭스, 엣지 등) 상에서 사용자의 클릭, 입력, 화면 이동 동작을 스크립트로 기록하고 재생하여 웹 애플리케이션의 엔드투엔드(E2E) 인터페이스를 자동 검증하는 오픈소스 도구는 무엇인가?',
    answer: ['셀레니움', 'Selenium'],
    explanation: 'Selenium(셀레니움)은 웹 브라우저를 직접 제어하여 크로스 브라우징 및 인터페이스 회귀 테스트를 자동화하는 대표적인 도구입니다.',
    difficulty: 'EASY',
    keywords: ['셀레니움', 'Selenium', 'E2E테스트'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '5.3',
  },
  {
    id: 'EXP26_INT_024',
    subject: '소프트웨어설계',
    category: '인터페이스 보안',
    subCategory: 'API 인증 및 인가',
    type: 'SHORT_ANSWER',
    question: '제3자 애플리케이션(서드파티 앱)에 사용자의 비밀번호를 노출하지 않고도 특정 리소스에 대한 접근 권한(토큰 기반)을 안전하게 위임하고 인가하기 위한 개방형 표준 프로토콜은 무엇인가?',
    answer: ['OAuth', 'OAuth 2.0', '오스'],
    explanation: 'OAuth(특히 OAuth 2.0)는 구글/카카오 로그인 연동 등 현대 모바일 및 웹 서비스의 API 인가 표준입니다.',
    difficulty: 'EASY',
    keywords: ['OAuth', '토큰인가', 'API보안'],
    source: '2026 실기 핵심 보강',
    angle: 'TERM_FROM_DEFINITION',
    targetSubUnit: '3.3',
  },
  {
    id: 'EXP26_INT_025',
    subject: '소프트웨어설계',
    category: '인터페이스 설계 및 연계',
    subCategory: '연계 방식 분류',
    type: 'SHORT_ANSWER',
    question: '송신 시스템에서 요청을 보낸 후 수신 시스템으로부터 응답이 올 때까지 대기하지 않고 즉시 다음 작업을 진행하며, 메시지 큐(MQ)를 활용하여 시스템 간 결합도를 최소화하는 통신 방식을 무엇이라 하는가?',
    answer: ['비동기 방식', '비동기 통신', '비동기식', 'Asynchronous'],
    explanation: '비동기(Asynchronous) 통신은 송수신자 간의 시간적 결합도를 분리하여 처리량과 응답성을 극대화합니다. (대기하는 방식은 동기 방식)',
    difficulty: 'EASY',
    keywords: ['비동기 방식', '비동기통신', '메시지큐'],
    source: '2026 실기 핵심 보강',
    angle: 'COMPARISON',
    targetSubUnit: '5.2',
  },
];
