import { ExpansionCandidate } from '../validator';

/**
 * Batch 4: 데이터 전환 ETL & 서버 프로그램 및 배치 & 개발환경 구축 (공식 실기 범위 2.4, 4.1, 4.3)
 * 기존 커버리지: 2.4 (NONE 0문항), 4.1 (THIN 2문항), 4.3 (THIN 2문항)
 * 목표: 25문항 엄선 (출제각도: COMPARISON, PROCESS_SEQUENCE, IDENTIFICATION, CHARACTERISTIC 등)
 */
export const BATCH4_CANDIDATES: ExpansionCandidate[] = [
  {
    id: 'EXP26_DEV_001',
    subject: '데이터베이스구축',
    category: '데이터 전환 및 이관',
    subCategory: 'ETL 프로세스',
    type: 'SHORT_ANSWER',
    question: '원천 시스템(Source)의 데이터베이스나 파일로부터 필요한 데이터를 추출하고, 목적 시스템의 형식에 맞게 변환 및 정제한 후 데이터 웨어하우스나 목적 DB에 적재하는 일련의 과정을 나타내는 영문 3글자 약어는 무엇인가?',
    answer: ['ETL', 'Extract, Transform, Load'],
    explanation: 'ETL(Extract, Transform, Load)은 데이터 이관, 데이터 웨어하우스 구축 및 데이터 레이크 적재의 핵심 프로세스입니다.',
    difficulty: 'EASY',
    keywords: ['ETL', '데이터추출', '데이터변환', '데이터적재'],
    source: '2026 실기 핵심 보강',
    angle: 'TERM_FROM_DEFINITION',
    targetSubUnit: '2.4',
  },
  {
    id: 'EXP26_DEV_002',
    subject: '데이터베이스구축',
    category: '데이터 전환 및 이관',
    subCategory: '데이터 전환 절차',
    type: 'SHORT_ANSWER',
    question: '데이터 전환 절차 중 원천 시스템의 테이블 및 컬럼과 목적 시스템의 테이블 및 컬럼 간의 1:1, 1:N, N:M 대응 관계 및 변환 규칙을 상세하게 기술한 설계 문서를 무엇이라 하는가?',
    answer: ['데이터 매핑 정의서', '데이터 매핑', '매핑 정의서', 'Mapping Specification'],
    explanation: '데이터 매핑 정의서는 원천 데이터가 목적지 데이터의 어떤 컬럼으로 어떤 변환 로직(타입 변환, 코드 매핑 등)을 거쳐 들어가는지 명시한 필수 산출물입니다.',
    difficulty: 'MEDIUM',
    keywords: ['데이터매핑', '매핑정의서', '데이터전환'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '2.4',
  },
  {
    id: 'EXP26_DEV_003',
    subject: '데이터베이스구축',
    category: '데이터 전환 및 이관',
    subCategory: '데이터 정제',
    type: 'SHORT_ANSWER',
    question: '원천 데이터에 존재하는 결측치, 이상치, 오탈자, 형식 불일치, 중복 데이터 등의 오류를 식별하고 수정하여 데이터의 정확성과 일관성을 확보하는 일련의 품질 개선 작업을 무엇이라 하는가?',
    answer: ['데이터 정제', '데이터 클렌징', 'Data Cleansing'],
    explanation: '데이터 정제(Data Cleansing)는 변환 및 적재 전에 데이터의 오류를 정제하여 이관 실패를 예방하고 데이터 품질을 확보합니다.',
    difficulty: 'EASY',
    keywords: ['데이터 정제', '데이터 클렌징', 'Data Cleansing'],
    source: '2026 실기 핵심 보강',
    angle: 'TERM_FROM_DEFINITION',
    targetSubUnit: '2.4',
  },
  {
    id: 'EXP26_DEV_004',
    subject: '데이터베이스구축',
    category: '데이터 전환 및 이관',
    subCategory: '데이터 전환 검증',
    type: 'SHORT_ANSWER',
    question: '데이터 전환 완료 후, 원천 데이터의 건수와 목적 시스템에 적재된 데이터의 총 건수(Count) 및 주요 금액/수량의 합계(Sum), 해시값(Checksum)을 대조하여 데이터 유실이 없는지 확인하는 검증 방식을 무엇이라 하는가?',
    answer: ['로그 검증', '정합성 검증', '데이터 정합성 검증', '건수 검증'],
    explanation: '데이터 전환 정합성 검증은 전환 전후의 총 건수, 집계 합계(Sum/Hash), 로그 대조를 통해 완벽한 이관 여부를 판정합니다.',
    difficulty: 'MEDIUM',
    keywords: ['데이터정합성', '로그검증', '데이터검증'],
    source: '2026 실기 핵심 보강',
    angle: 'CHARACTERISTIC',
    targetSubUnit: '2.4',
  },
  {
    id: 'EXP26_DEV_005',
    subject: '정보시스템구축관리',
    category: '서버 프로그램 구현',
    subCategory: '배치 프로그램 특성',
    type: 'SHORT_ANSWER',
    question: '배치(Batch) 프로그램이 반드시 만족해야 하는 5대 필수 요건 중, 대용량의 데이터를 처리하는 도중 예기치 않은 오류나 시스템 중단이 발생하더라도 중복 실행이나 유실 없이 정상 복구될 수 있어야 함을 의미하는 특성은 무엇인가?',
    answer: ['견고성', 'Robustness', '안정성'],
    explanation: '배치 프로그램의 필수 5대 요건은 대용량 데이터, 자동화, 견고성(오류 발생 시 대처), 신뢰성/안정성(오류 없는 추적), 성능입니다.',
    difficulty: 'MEDIUM',
    keywords: ['견고성', '배치프로그램', '배치5대요건'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '4.3',
  },
  {
    id: 'EXP26_DEV_006',
    subject: '정보시스템구축관리',
    category: '서버 프로그램 구현',
    subCategory: '배치 스케줄러',
    type: 'SHORT_ANSWER',
    question: '유닉스 및 리눅스 운영체제에서 백그라운드 데몬(crond)으로 동작하며, 분, 시, 일, 월, 요일의 5가지 시간 필드 표현식을 사용하여 주기적인 배치 작업 실행을 자동 예약해 주는 도구는 무엇인가?',
    answer: ['크론', 'Cron', 'crontab'],
    explanation: 'cron(크론)은 crontab 설정 파일을 통해 특정 시간/주기마다 쉘 스크립트나 명령어를 자동 실행해 주는 표준 작업 스케줄러입니다.',
    difficulty: 'EASY',
    keywords: ['크론', 'Cron', 'crontab', '배치스케줄러'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '4.3',
  },
  {
    id: 'EXP26_DEV_007',
    subject: '정보시스템구축관리',
    category: '서버 프로그램 구현',
    subCategory: '배치 스케줄러',
    type: 'SHORT_ANSWER',
    question: '자바(Java) 엔터프라이즈 환경에서 정교한 작업 스케줄링을 지원하며, Job, Trigger, Scheduler 인터페이스를 기반으로 다중 서버 간 클러스터링 및 실패 복구(Failover) 기능을 제공하는 대표적인 오픈소스 스케줄러 프레임워크는 무엇인가?',
    answer: ['쿼츠', 'Quartz', 'Quartz 스케줄러'],
    explanation: 'Quartz는 스프링 프레임워크 등과 손쉽게 연동되는 자바 표준 배치/작업 스케줄러 라이브러리입니다.',
    difficulty: 'MEDIUM',
    keywords: ['Quartz', '쿼츠', '자바스케줄러'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '4.3',
  },
  {
    id: 'EXP26_DEV_008',
    subject: '정보시스템구축관리',
    category: '서버 프로그램 구현',
    subCategory: '계층형 아키텍처 객체',
    type: 'SHORT_ANSWER',
    question: '소프트웨어 계층 간(예: 컨트롤러와 서비스, 클라이언트와 서버)에 데이터를 전달하기 위해 사용되는 객체로, 별도의 비즈니스 로직 없이 속성(필드)과 그에 대한 Getter/Setter 메소드만을 포함하는 순수 데이터 전달용 객체는 무엇인가?',
    answer: ['DTO', 'Data Transfer Object'],
    explanation: 'DTO(Data Transfer Object)는 프로세스 간 네트워크 호출 횟수를 줄이기 위해 여러 데이터를 하나로 묶어 전송하는 객체입니다.',
    difficulty: 'EASY',
    keywords: ['DTO', 'Data Transfer Object', '데이터전달객체'],
    source: '2026 실기 핵심 보강',
    angle: 'COMPARISON',
    targetSubUnit: '4.3',
  },
  {
    id: 'EXP26_DEV_009',
    subject: '정보시스템구축관리',
    category: '서버 프로그램 구현',
    subCategory: '계층형 아키텍처 객체',
    type: 'SHORT_ANSWER',
    question: 'DTO와 유사하게 데이터를 담고 있으나, 특정 비즈니스 값을 나타내며 한 번 생성되면 내부 상태가 절대 변하지 않는 불변성(Immutability)을 가지며 속성 값들이 모두 같으면 동일한 객체로 취급되는 객체는 무엇인가?',
    answer: ['VO', 'Value Object'],
    explanation: 'VO(Value Object)는 값 자체를 표현하는 객체로, Setter가 제공되지 않는 불변(Immutable) 객체이며 equals()와 hashCode()를 재정의하여 값 동등성을 비교합니다.',
    difficulty: 'EASY',
    keywords: ['VO', 'Value Object', '불변객체'],
    source: '2026 실기 핵심 보강',
    angle: 'COMPARISON',
    targetSubUnit: '4.3',
  },
  {
    id: 'EXP26_DEV_010',
    subject: '정보시스템구축관리',
    category: '서버 프로그램 구현',
    subCategory: '계층형 아키텍처 객체',
    type: 'SHORT_ANSWER',
    question: '데이터베이스에 접근하여 데이터의 삽입, 조회, 수정, 삭제(CRUD) 작업을 전담 수행하는 객체로, 비즈니스 로직과 데이터 접근 로직을 분리하기 위해 사용하는 객체 패턴의 약어는 무엇인가?',
    answer: ['DAO', 'Data Access Object'],
    explanation: 'DAO(Data Access Object)는 데이터베이스 커넥션 관리 및 SQL 실행을 캡슐화하여 서비스 계층이 저수준 데이터베이스 API에 종속되지 않도록 분리합니다.',
    difficulty: 'EASY',
    keywords: ['DAO', 'Data Access Object', '데이터접근객체'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '4.3',
  },
  {
    id: 'EXP26_DEV_011',
    subject: '정보시스템구축관리',
    category: '개발환경 구축',
    subCategory: '서버 인프라 역할 분리',
    type: 'SHORT_ANSWER',
    question: '클라이언트의 HTTP 요청을 직접 받아 정적 콘텐츠(HTML, CSS, 이미지 파일)를 고속으로 전달하고, 동적 처리가 필요한 요청은 뒤단의 WAS로 전달(프록시)하는 서버(예: Apache HTTP Server, Nginx)를 무엇이라 하는가?',
    answer: ['웹 서버', 'Web Server', 'WS'],
    explanation: '웹 서버(Web Server)는 정적 리소스 응답과 로드밸런싱/리버스 프록시를 전담하여 WAS의 연산 부담을 줄여줍니다.',
    difficulty: 'EASY',
    keywords: ['웹 서버', 'Web Server', '정적콘텐츠'],
    source: '2026 실기 핵심 보강',
    angle: 'COMPARISON',
    targetSubUnit: '4.1',
  },
  {
    id: 'EXP26_DEV_012',
    subject: '정보시스템구축관리',
    category: '개발환경 구축',
    subCategory: '서버 인프라 역할 분리',
    type: 'SHORT_ANSWER',
    question: '웹 서버로부터 동적 요청을 전달받아 서블릿(Servlet), JSP, 비즈니스 로직, 데이터베이스 연동 및 트랜잭션 관리 등을 수행하는 서버 프로그램(예: Apache Tomcat, WebLogic, Jeus)을 무엇이라 하는가?',
    answer: ['WAS', '웹 애플리케이션 서버', 'Web Application Server'],
    explanation: 'WAS(Web Application Server)는 웹 컨테이너(서블릿 컨테이너)를 내장하여 동적 비즈니스 연산 및 DB 처리를 수행합니다.',
    difficulty: 'EASY',
    keywords: ['WAS', 'Web Application Server', '웹애플리케이션서버'],
    source: '2026 실기 핵심 보강',
    angle: 'COMPARISON',
    targetSubUnit: '4.1',
  },
  {
    id: 'EXP26_DEV_013',
    subject: '정보시스템구축관리',
    category: '개발환경 구축',
    subCategory: '형상관리(SCM)',
    type: 'SHORT_ANSWER',
    question: '소프트웨어 개발 과정에서 소스코드, 설계 문서, 라이브러리 등의 모든 변경 사항을 체계적으로 추적하고 통제하는 활동으로, 식별 → (    ) → 감사 → 기록의 4가지 주요 활동으로 구성되는 관리를 무엇이라 하는가?',
    answer: ['형상 통제', '통제', '형상통제', 'Configuration Control'],
    explanation: '소프트웨어 형상관리 4대 활동은 형상 식별 → 형상 통제(변경 승인 및 반영) → 형상 감사(무결성 공식 검증) → 형상 기록/보고입니다.',
    difficulty: 'MEDIUM',
    keywords: ['형상통제', '형상관리', 'SCM'],
    source: '2026 실기 핵심 보강',
    angle: 'PROCESS_SEQUENCE',
    targetSubUnit: '4.1',
  },
  {
    id: 'EXP26_DEV_014',
    subject: '정보시스템구축관리',
    category: '개발환경 구축',
    subCategory: '형상관리 도구 유형',
    type: 'SHORT_ANSWER',
    question: '형상관리 도구의 유형 중, 중앙 서버에 모든 소스코드가 저장되어 개발자들은 중앙 서버에 접속하여 체크아웃/커밋을 수행해야 하며 네트워크 연결이 끊기면 버전 관리가 불가능한 클라이언트/서버 방식의 대표 도구는 무엇인가?',
    answer: ['SVN', '서브버전', 'Subversion'],
    explanation: 'SVN(Apache Subversion)은 중앙 집중형 클라이언트/서버 형상관리 도구입니다. (로컬 저장소를 갖는 것은 Git 등 분산형 도구)',
    difficulty: 'EASY',
    keywords: ['SVN', 'Subversion', '중앙집중형'],
    source: '2026 실기 핵심 보강',
    angle: 'COMPARISON',
    targetSubUnit: '4.1',
  },
  {
    id: 'EXP26_DEV_015',
    subject: '정보시스템구축관리',
    category: '개발환경 구축',
    subCategory: '형상관리 도구 유형',
    type: 'SHORT_ANSWER',
    question: '리눅스 토발즈가 개발한 분산 버전 관리 시스템(DVCS)으로, 개발자마다 전체 프로젝트 히스토리가 담긴 로컬 저장소를 복제(Clone)하여 오프라인에서도 완전한 커밋과 브랜치 작업이 가능한 도구는 무엇인가?',
    answer: ['Git', '깃'],
    explanation: 'Git은 분산 버전 관리 시스템으로 빠른 브랜칭, 오프라인 작업, P2P 동기화가 가능합니다.',
    difficulty: 'EASY',
    keywords: ['Git', '깃', '분산버전관리'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '4.1',
  },
  {
    id: 'EXP26_DEV_016',
    subject: '데이터베이스구축',
    category: '데이터 전환 및 이관',
    subCategory: 'ETL 프로세스 변형',
    type: 'SHORT_ANSWER',
    question: '빅데이터 클라우드 환경에서 대용량 데이터를 처리할 때, 데이터 추출(Extract) 후 별도의 중간 서버에서 변환하지 않고 먼저 대상 데이터 레이크/웨어하우스에 원본 그대로 적재(Load)한 후 분산 엔진의 컴퓨팅 파워로 목적지 내부에서 직접 변환(Transform)을 수행하는 데이터 파이프라인 아키텍처는 무엇인가?',
    answer: ['ELT', 'Extract, Load, Transform'],
    explanation: 'ELT는 클라우드 데이터 웨어하우스(Snowflake, BigQuery 등)의 막강한 병렬 처리 성능을 활용하기 위해 ETL의 변환과 적재 순서를 바꾼 현대적 패턴입니다.',
    difficulty: 'MEDIUM',
    keywords: ['ELT', '데이터파이프라인', '빅데이터적재'],
    source: '2026 실기 핵심 보강',
    angle: 'COMPARISON',
    targetSubUnit: '2.4',
  },
  {
    id: 'EXP26_DEV_017',
    subject: '정보시스템구축관리',
    category: '서버 프로그램 구현',
    subCategory: '스프링 프레임워크 핵심',
    type: 'SHORT_ANSWER',
    question: '객체가 자신이 사용할 의존 객체를 직접 new 생성자로 생성하지 않고, 외부 컨테이너(IoC 컨테이너)로부터 생성된 인스턴스를 주입받아 객체 간의 결합도를 낮추는 객체지향 디자인 원칙의 약어는 무엇인가?',
    answer: ['DI', '의존성 주입', 'Dependency Injection'],
    explanation: 'DI(Dependency Injection, 의존성 주입)는 스프링의 핵심 철학으로 모듈 간의 결합도를 느슨하게 하고 단위 테스트를 용이하게 합니다.',
    difficulty: 'EASY',
    keywords: ['DI', '의존성주입', '스프링'],
    source: '2026 실기 핵심 보강',
    angle: 'TERM_FROM_DEFINITION',
    targetSubUnit: '4.3',
  },
  {
    id: 'EXP26_DEV_018',
    subject: '정보시스템구축관리',
    category: '서버 프로그램 구현',
    subCategory: '스프링 프레임워크 핵심',
    type: 'SHORT_ANSWER',
    question: '로깅, 보안, 트랜잭션 관리와 같이 애플리케이션의 여러 모듈에 공통적으로 나타나는 횡단 관심사(Cross-Cutting Concerns)를 핵심 비즈니스 로직과 분리하여 모듈화하는 프로그래밍 패러다임의 약어는 무엇인가?',
    answer: ['AOP', '관점 지향 프로그래밍', 'Aspect Oriented Programming'],
    explanation: 'AOP(Aspect Oriented Programming, 관점 지향 프로그래밍)는 공통 횡단 기능을 별도의 Aspect로 분리하여 코드 중복을 제거합니다.',
    difficulty: 'EASY',
    keywords: ['AOP', '관점지향', '횡단관심사'],
    source: '2026 실기 핵심 보강',
    angle: 'TERM_FROM_DEFINITION',
    targetSubUnit: '4.3',
  },
  {
    id: 'EXP26_DEV_019',
    subject: '정보시스템구축관리',
    category: '서버 프로그램 구현',
    subCategory: 'ORM 프레임워크',
    type: 'SHORT_ANSWER',
    question: '관계형 데이터베이스의 테이블과 객체지향 프로그래밍 언어의 클래스 간의 불일치(패러다임 불일치)를 해결하기 위해, 객체와 관계형 테이블을 자동으로 매핑해 주는 기술의 약어는 무엇인가?',
    answer: ['ORM', 'Object Relational Mapping', '객체 관계 매핑'],
    explanation: 'ORM(Object-Relational Mapping, 예: JPA, 하이버네이트)은 개발자가 SQL을 직접 작성하지 않고 객체 모델 중심으로 DB를 다룰 수 있게 해줍니다.',
    difficulty: 'EASY',
    keywords: ['ORM', 'JPA', '객체관계매핑'],
    source: '2026 실기 핵심 보강',
    angle: 'TERM_FROM_DEFINITION',
    targetSubUnit: '4.3',
  },
  {
    id: 'EXP26_DEV_020',
    subject: '정보시스템구축관리',
    category: '개발환경 구축',
    subCategory: 'IDE 도구',
    type: 'SHORT_ANSWER',
    question: '코드 편집기, 컴파일러, 디버거, 그래픽 사용자 인터페이스(GUI) 빌더 등 소프트웨어 개발에 필요한 다양한 도구들을 하나의 통합된 프로그램 안에서 제공하는 소프트웨어 환경의 영문 약어는 무엇인가?',
    answer: ['IDE', '통합 개발 환경', 'Integrated Development Environment'],
    explanation: 'IDE(Integrated Development Environment, 예: Eclipse, IntelliJ, VS Code)는 소프트웨어 개발 생산성을 극대화하는 통합 개발 도구입니다.',
    difficulty: 'EASY',
    keywords: ['IDE', '통합개발환경', '개발도구'],
    source: '2026 실기 핵심 보강',
    angle: 'TERM_FROM_DEFINITION',
    targetSubUnit: '4.1',
  },
  {
    id: 'EXP26_DEV_021',
    subject: '데이터베이스구축',
    category: '데이터 전환 및 이관',
    subCategory: '데이터 이관 전략',
    type: 'SHORT_ANSWER',
    question: '기존 시스템을 일시적으로 전면 중단(다운타임)시킨 상태에서 주말이나 야간의 정해진 시간 동안 전체 데이터를 일괄 전환하는 방식으로, 구조가 단순하고 비용이 적게 들지만 전환 실패 시 리스크가 큰 이관 전략은 무엇인가?',
    answer: ['빅뱅 방식', '빅뱅 전환', 'Big Bang'],
    explanation: '빅뱅(Big Bang) 전환 방식은 시스템 전체를 한 번에 전환하는 방식으로 소규모 시스템에 적합하며 다운타임이 발생합니다. (반대는 단계적 전환 방식)',
    difficulty: 'MEDIUM',
    keywords: ['빅뱅 방식', 'Big Bang', '데이터전환전략'],
    source: '2026 실기 핵심 보강',
    angle: 'COMPARISON',
    targetSubUnit: '2.4',
  },
  {
    id: 'EXP26_DEV_022',
    subject: '데이터베이스구축',
    category: '데이터 전환 및 이관',
    subCategory: '데이터 이관 전략',
    type: 'SHORT_ANSWER',
    question: '기존 시스템과 신규 시스템을 일정 기간 동안 동시에 병행 운영하면서, 업무 영역이나 모듈별로 데이터를 점진적으로 전환하여 리스크를 최소화하지만 유지비용이 많이 드는 이관 전략은 무엇인가?',
    answer: ['단계적 전환', '단계적 방식', '점진적 전환'],
    explanation: '단계적 전환 방식(Phased Approach)은 대규모 미션 크리티컬 시스템에서 무중단 전환과 위험 분산을 위해 채택됩니다.',
    difficulty: 'MEDIUM',
    keywords: ['단계적 전환', '점진적 전환', '데이터이관'],
    source: '2026 실기 핵심 보강',
    angle: 'COMPARISON',
    targetSubUnit: '2.4',
  },
  {
    id: 'EXP26_DEV_023',
    subject: '정보시스템구축관리',
    category: '서버 프로그램 구현',
    subCategory: '배치 프로그램 특성',
    type: 'SHORT_ANSWER',
    question: '배치(Batch) 프로그램의 5대 요건 중, 사용자의 개입(사용자 입력 대기 등) 없이 정해진 시각이나 조건에 따라 시스템 스스로 자동으로 시작되고 완료되어야 함을 뜻하는 요건은 무엇인가?',
    answer: ['자동화', 'Automation'],
    explanation: '배치 프로그램은 심야 시간대나 정기 스케줄에 사람의 수작업 개입 없이 무인 실행되어야 하므로 자동화가 필수입니다.',
    difficulty: 'EASY',
    keywords: ['자동화', 'Automation', '배치요건'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '4.3',
  },
  {
    id: 'EXP26_DEV_024',
    subject: '정보시스템구축관리',
    category: '개발환경 구축',
    subCategory: '형상관리(SCM)',
    type: 'SHORT_ANSWER',
    question: '형상관리의 기준이 되는 시점으로, 소프트웨어 개발 생명주기의 특정 단계(요구분석, 설계 등)가 공식적으로 검토되고 승인되어 이후의 변경을 엄격히 통제하기 위한 기준선을 무엇이라 하는가?',
    answer: ['기준선', '베이스라인', 'Baseline'],
    explanation: '베이스라인(Baseline, 기준선)은 공식적으로 승인된 형상 항목들의 집합으로, 변경 제어 위원회(CCB)의 공식 승인을 통해서만 변경될 수 있습니다.',
    difficulty: 'EASY',
    keywords: ['베이스라인', '기준선', 'Baseline', '형상관리'],
    source: '2026 실기 핵심 보강',
    angle: 'TERM_FROM_DEFINITION',
    targetSubUnit: '4.1',
  },
  {
    id: 'EXP26_DEV_025',
    subject: '정보시스템구축관리',
    category: '개발환경 구축',
    subCategory: '형상관리 조직',
    type: 'SHORT_ANSWER',
    question: '형상 항목에 대한 변경 요청이 발생했을 때, 변경의 타당성과 영향을 평가하고 변경 승인 또는 반려 여부를 공식적으로 심의·결정하는 조직 위원회의 영문 약어는 무엇인가?',
    answer: ['CCB', '형상통제위원회', 'Configuration Control Board'],
    explanation: 'CCB(Configuration Control Board, 형상 통제 위원회)는 무분별한 소프트웨어 설계 변경을 방지하고 변경에 따른 일정과 비용 영향을 승인하는 최고 의사결정 기구입니다.',
    difficulty: 'EASY',
    keywords: ['CCB', '형상통제위원회', '형상관리'],
    source: '2026 실기 핵심 보강',
    angle: 'TERM_FROM_DEFINITION',
    targetSubUnit: '4.1',
  },
];
