import { ExpansionCandidate } from '../validator';

/**
 * Batch 1: 제품소프트웨어 패키징 & 저작권/라이선스 (공식 실기 범위 12.1, 12.2)
 * 기존 커버리지: NONE (0문항) -> 완전 신규 구축
 * 목표: 25문항 엄선 (출제각도 다양화: COMPARISON, PROCESS_SEQUENCE, SCENARIO, CHARACTERISTIC 등)
 */
export const BATCH1_CANDIDATES: ExpansionCandidate[] = [
  {
    id: 'EXP26_PKG_001',
    subject: '소프트웨어설계',
    category: '제품소프트웨어 패키징',
    subCategory: '디지털 저작권 관리(DRM)',
    type: 'SHORT_ANSWER',
    question: '디지털 저작권 관리(DRM)의 구성요소 중, 라이선스를 발급하고 암호화된 콘텐츠의 사용 권한과 이용 규칙을 통제 및 관리하는 핵심 서버 기관을 무엇이라 하는가?',
    answer: ['클리어링하우스', 'Clearinghouse'],
    explanation: '클리어링하우스(Clearinghouse)는 DRM 시스템에서 사용자의 권한을 확인하고 디지털 콘텐츠의 복호화 키 및 라이선스를 발급·관리하는 핵심 기관입니다.',
    difficulty: 'MEDIUM',
    keywords: ['DRM', '클리어링하우스', 'Clearinghouse', '라이선스'],
    source: '2026 실기 핵심 보강',
    angle: 'TERM_FROM_DEFINITION',
    targetSubUnit: '12.2',
  },
  {
    id: 'EXP26_PKG_002',
    subject: '소프트웨어설계',
    category: '제품소프트웨어 패키징',
    subCategory: '디지털 저작권 관리(DRM)',
    type: 'SHORT_ANSWER',
    question: 'DRM 구성요소 중 사용자의 단말 장치(PC, 스마트폰 등)에 설치되어, 인가된 사용자만이 라이선스 규칙에 따라 콘텐츠를 복호화하고 재생할 수 있도록 통제하는 프로그램을 무엇이라 하는가?',
    answer: ['DRM 컨트롤러', 'DRM Controller', '컨트롤러'],
    explanation: 'DRM 컨트롤러(Controller)는 사용자 단말에서 라이선스 정보에 따라 암호화된 콘텐츠를 복호화하고 안전한 재생 및 복제 방지를 수행하는 소프트웨어 모듈입니다.',
    difficulty: 'MEDIUM',
    keywords: ['DRM', 'DRM 컨트롤러', '단말'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '12.2',
  },
  {
    id: 'EXP26_PKG_003',
    subject: '소프트웨어설계',
    category: '제품소프트웨어 패키징',
    subCategory: '저작권 보호 기술',
    type: 'SHORT_ANSWER',
    question: '디지털 콘텐츠에 눈에 띄지 않게 저작권자의 서명이나 고유 정보를 삽입하는 기술로, 불법 배포된 파일에서 원본 소유자를 증명하기 위해 쓰이는 기술과, 구매자의 식별 정보를 삽입하여 불법 유포 경로를 추적하는 기술을 [워터마킹 / 핑거프린팅] 순서대로 각각 쓰시오.',
    answer: ['워터마킹, 핑거프린팅', '디지털 워터마킹, 핑거프린팅'],
    explanation: '워터마킹(Watermarking)은 제작자(저작권자)의 정보를 은닉하여 소유권을 증명하고, 핑거프린팅(Fingerprinting)은 구매자/사용자의 정보를 은닉하여 불법 유포자를 추적합니다.',
    difficulty: 'HARD',
    keywords: ['워터마킹', '핑거프린팅', '저작권보호'],
    source: '2026 실기 핵심 보강',
    angle: 'COMPARISON',
    targetSubUnit: '12.2',
  },
  {
    id: 'EXP26_PKG_004',
    subject: '소프트웨어설계',
    category: '제품소프트웨어 패키징',
    subCategory: '보안 역공학 방지',
    type: 'SHORT_ANSWER',
    question: '소프트웨어 프로그램의 실행 코드를 위변조하려는 행위를 감지하고, 변조가 감지되면 실행을 즉시 중단하거나 코드를 스스로 파괴하여 소프트웨어를 보호하는 보안 방어 기술을 무엇이라 하는가?',
    answer: ['탬퍼 프루핑', 'Tamper Proofing', '템퍼 프루핑'],
    explanation: '탬퍼 프루핑(Tamper Proofing)은 실행 바이너리의 무결성을 검증하여 역공학, 디버깅, 코드 패치 등의 불법 위변조 행위를 무력화하는 기술입니다.',
    difficulty: 'MEDIUM',
    keywords: ['탬퍼 프루핑', 'Tamper Proofing', '위변조방지'],
    source: '2026 실기 핵심 보강',
    angle: 'TERM_FROM_DEFINITION',
    targetSubUnit: '12.2',
  },
  {
    id: 'EXP26_PKG_005',
    subject: '소프트웨어설계',
    category: '오픈소스 라이선스',
    subCategory: '라이선스 특성 비교',
    type: 'SHORT_ANSWER',
    question: '자유 소프트웨어 재단(FSF)에서 제정한 대표적인 카피레프트(Copyleft) 라이선스로, 이 라이선스가 적용된 코드를 수정하거나 결합하여 배포할 경우 파생 저작물의 소스코드도 반드시 동일한 라이선스로 공개해야 하는 라이선스는 무엇인가?',
    answer: ['GPL', 'General Public License', 'GNU GPL'],
    explanation: 'GPL(General Public License)은 엄격한 전염성(Viral) 카피레프트 라이선스로, 파생 소프트웨어 배포 시 반드시 전체 소스코드를 공개해야 합니다.',
    difficulty: 'EASY',
    keywords: ['GPL', '오픈소스', '카피레프트', 'FSF'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '12.2',
  },
  {
    id: 'EXP26_PKG_006',
    subject: '소프트웨어설계',
    category: '오픈소스 라이선스',
    subCategory: '라이선스 특성 비교',
    type: 'SHORT_ANSWER',
    question: 'GPL의 엄격한 소스코드 공개 의무를 완화하여, 해당 라이브러리를 단순 링크(동적/정적 링크)하여 개발한 응용 프로그램은 소스코드를 공개하지 않아도 되도록 허용한 오픈소스 라이선스는 무엇인가?',
    answer: ['LGPL', 'Lesser General Public License', 'GNU LGPL'],
    explanation: 'LGPL(Lesser GPL)은 라이브러리 자체를 수정했을 때만 수정 코드를 공개하고, 단순히 링크하여 사용하는 독점 상용 소프트웨어의 소스코드는 비공개로 유지할 수 있습니다.',
    difficulty: 'MEDIUM',
    keywords: ['LGPL', '라이브러리링크', '오픈소스'],
    source: '2026 실기 핵심 보강',
    angle: 'COMPARISON',
    targetSubUnit: '12.2',
  },
  {
    id: 'EXP26_PKG_007',
    subject: '소프트웨어설계',
    category: '오픈소스 라이선스',
    subCategory: '라이선스 고지 의무',
    type: 'SHORT_ANSWER',
    question: '아파치 소프트웨어 재단에서 만든 라이선스로, 소스코드 공개 의무는 없으나 재배포 시 저작권 고지, 라이선스 사본 포함, 특허권 부여 명시, 수정 사항 안내를 요구하는 라이선스는 무엇인가?',
    answer: ['Apache', 'Apache License', '아파치 라이선스', 'Apache 2.0'],
    explanation: 'Apache 라이선스(특히 Apache 2.0)는 상용 소프트웨어에 소스 공개 의무 없이 자유롭게 활용할 수 있으나, 저작권/특허권/수정사항 고지 의무를 가집니다.',
    difficulty: 'EASY',
    keywords: ['Apache', '아파치', '오픈소스라이선스'],
    source: '2026 실기 핵심 보강',
    angle: 'CHARACTERISTIC',
    targetSubUnit: '12.2',
  },
  {
    id: 'EXP26_PKG_008',
    subject: '소프트웨어설계',
    category: '오픈소스 라이선스',
    subCategory: '라이선스 특성 비교',
    type: 'SHORT_ANSWER',
    question: '매사추세츠 공과대학교에서 개발된 라이선스로, 소프트웨어의 무상 이용, 수정, 배포 및 상용화가 자유로우며 저작권 고지문과 면책 조항만 포함하면 소스코드 공개 의무가 전혀 없는 대표적인 퍼미시브 라이선스는 무엇인가?',
    answer: ['MIT', 'MIT License', 'MIT 라이선스'],
    explanation: 'MIT 라이선스는 매우 관대한(Permissive) 오픈소스 라이선스로, 저작권 및 면책 조항 고지만 유지하면 상용 판매나 소스 비공개 배포가 완전 자유롭습니다.',
    difficulty: 'EASY',
    keywords: ['MIT', 'MIT라이선스', '오픈소스'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '12.2',
  },
  {
    id: 'EXP26_PKG_009',
    subject: '소프트웨어설계',
    category: '제품소프트웨어 빌드/배포',
    subCategory: '빌드 자동화 도구',
    type: 'SHORT_ANSWER',
    question: '자바 진영의 빌드 자동화 도구 중, XML 기반의 설정 파일(build.xml)을 사용하며 태스크(Task) 기반의 절차적 스크립트 작성 방식으로 유연하지만 의존성 자동 관리 기능이 약한 고전적인 도구는 무엇인가?',
    answer: ['Ant', 'Apache Ant', '앤트'],
    explanation: 'Apache Ant는 XML 기반의 절차적 빌드 도구로 규칙이 정해져 있지 않고 자유로우나, 외부 라이브러리 의존성 자동 해결 기능이 부족하여 이후 Maven으로 발전했습니다.',
    difficulty: 'MEDIUM',
    keywords: ['Ant', 'build.xml', '빌드도구'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '12.1',
  },
  {
    id: 'EXP26_PKG_010',
    subject: '소프트웨어설계',
    category: '제품소프트웨어 빌드/배포',
    subCategory: '빌드 자동화 도구',
    type: 'SHORT_ANSWER',
    question: '프로젝트 객체 모델(POM) 개념을 도입하여 중앙 저장소를 통한 의존성 자동 관리와 표준 프로젝트 생명주기(Lifecycle)를 제공하며, 설정 파일로 pom.xml을 사용하는 아파치 빌드 도구는 무엇인가?',
    answer: ['Maven', 'Apache Maven', '메이븐'],
    explanation: 'Maven은 pom.xml에 선언된 라이브러리 및 플러그인을 원격 저장소에서 자동으로 다운로드하고 빌드/테스트/패키징 표준 생명주기를 관리합니다.',
    difficulty: 'EASY',
    keywords: ['Maven', '메이븐', 'pom.xml', 'POM'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '12.1',
  },
  {
    id: 'EXP26_PKG_011',
    subject: '소프트웨어설계',
    category: '제품소프트웨어 빌드/배포',
    subCategory: '빌드 자동화 도구',
    type: 'SHORT_ANSWER',
    question: 'Ant의 유연성과 Maven의 의존성 관리 장점을 결합한 빌드 도구로, Groovy 또는 Kotlin 기반의 DSL(Domain Specific Language) 스크립트를 사용하고 안드로이드 공식 빌드 시스템으로 채택된 도구는 무엇인가?',
    answer: ['Gradle', '그래들'],
    explanation: 'Gradle(그래들)은 build.gradle 파일을 통해 직관적인 스크립팅이 가능하며, 빌드 캐시 및 증분 빌드(Incremental Build)를 지원하여 Maven보다 월등히 빠릅니다.',
    difficulty: 'EASY',
    keywords: ['Gradle', '그래들', 'Groovy', 'Kotlin', 'DSL'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '12.1',
  },
  {
    id: 'EXP26_PKG_012',
    subject: '소프트웨어설계',
    category: '제품소프트웨어 패키징',
    subCategory: '배포 문서화',
    type: 'SHORT_ANSWER',
    question: '소프트웨어 제품의 신규 버전이 배포될 때, 고객과 사용자에게 배포 날짜, 버전 번호, 신규 추가 기능, 버그 수정 내역, 알려진 문제점 등을 체계적으로 기록하여 전달하는 공식 문서를 무엇이라 하는가?',
    answer: ['릴리즈 노트', 'Release Notes', '릴리스 노트'],
    explanation: '릴리즈 노트(Release Notes)는 소프트웨어 릴리즈 주기마다 릴리즈 정보, 요구사항 변경, 결함 수정, 개선 사항 등을 명시한 핵심 사용자 문서입니다.',
    difficulty: 'EASY',
    keywords: ['릴리즈 노트', 'Release Notes', '배포문서'],
    source: '2026 실기 핵심 보강',
    angle: 'TERM_FROM_DEFINITION',
    targetSubUnit: '12.1',
  },
  {
    id: 'EXP26_PKG_013',
    subject: '소프트웨어설계',
    category: '제품소프트웨어 패키징',
    subCategory: '패키징 포맷 비교',
    type: 'SHORT_ANSWER',
    question: '자바(Java) 애플리케이션의 패키징 확장자 중, 웹 애플리케이션 서비스에 필요한 서블릿(Servlet), JSP, XML 설정(web.xml) 및 정적 웹 리소스를 포함하여 WAS에 단독 배포할 수 있는 압축 아카이브 포맷은 무엇인가?',
    answer: ['WAR', 'Web Application Archive'],
    explanation: 'WAR(Web Application Archive)는 서블릿 및 JSP 기반 웹 애플리케이션의 표준 배포 패키지 포맷입니다. (일반 자바 클래스 라이브러리는 JAR)',
    difficulty: 'EASY',
    keywords: ['WAR', 'JAR', '패키징', '아카이브'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '12.1',
  },
  {
    id: 'EXP26_PKG_014',
    subject: '소프트웨어설계',
    category: '제품소프트웨어 패키징',
    subCategory: '패키징 프로세스',
    type: 'SHORT_ANSWER',
    question: '소프트웨어 패키징 작업의 순서 중 다음 빈칸에 들어갈 올바른 단계를 쓰시오: [ 기능 식별 → 모듈화 → 빌드 도구 설정 → (    ) → 배포본 구성 및 패키징 ]',
    answer: ['빌드 및 테스트', '빌드/테스트', '빌드', '컴파일 및 테스트'],
    explanation: '제품 소프트웨어 패키징 프로세스는 기능 식별 → 모듈화 → 빌드 도구 설정 → 빌드 및 테스트 수행 → 최종 배포본 패키징 및 릴리즈 노트 작성 순으로 진행됩니다.',
    difficulty: 'MEDIUM',
    keywords: ['패키징순서', '빌드', '테스트'],
    source: '2026 실기 핵심 보강',
    angle: 'PROCESS_SEQUENCE',
    targetSubUnit: '12.1',
  },
  {
    id: 'EXP26_PKG_015',
    subject: '소프트웨어설계',
    category: '제품소프트웨어 패키징',
    subCategory: '디지털 저작권 관리(DRM)',
    type: 'SHORT_ANSWER',
    question: 'DRM 기술에서 저작권 원본 콘텐츠(오디오, 비디오, 문서, SW)를 암호화하고 메타데이터(저작권 식별자, 배포 규칙 등)를 결합하여 배포 가능한 보안 규격 파일로 생성하는 소프트웨어 도구를 무엇이라 하는가?',
    answer: ['패키저', 'Packager', 'DRM 패키저'],
    explanation: 'DRM 패키저(Packager)는 콘텐츠 제공자가 원본 콘텐츠를 인코딩 및 암호화하여 보안 헤더와 라이선스 통제 메타데이터를 결합시키는 구성요소입니다.',
    difficulty: 'MEDIUM',
    keywords: ['패키저', 'Packager', 'DRM'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '12.2',
  },
  {
    id: 'EXP26_PKG_016',
    subject: '소프트웨어설계',
    category: '제품소프트웨어 패키징',
    subCategory: '디지털 저작권 관리(DRM)',
    type: 'SHORT_ANSWER',
    question: '암호화된 DRM 콘텐츠와 해당 콘텐츠를 복호화할 수 있는 보안 라이선스를 안전하게 격리 보관하고 무단 외부 유출을 방지하기 위해 생성되는 보안 영역을 무엇이라 하는가?',
    answer: ['보안 컨테이너', 'Security Container'],
    explanation: '보안 컨테이너(Security Container)는 불법 복제나 가로채기로부터 보호하기 위해 암호화된 콘텐츠 및 관련 제어 정보를 담는 안전한 보호 상자입니다.',
    difficulty: 'MEDIUM',
    keywords: ['보안 컨테이너', 'Security Container', 'DRM'],
    source: '2026 실기 핵심 보강',
    angle: 'TERM_FROM_DEFINITION',
    targetSubUnit: '12.2',
  },
  {
    id: 'EXP26_PKG_017',
    subject: '소프트웨어설계',
    category: '오픈소스 라이선스',
    subCategory: '라이선스 고지 의무',
    type: 'SHORT_ANSWER',
    question: '버클리 캘리포니아 대학에서 발표한 오픈소스 라이선스로, 소스코드 공개 의무가 없고 상용 소프트웨어 결합이 자유로우나 초기 버전의 광고 조항(광고 시 명시)이 존재했던 대표적인 퍼미시브 라이선스는 무엇인가?',
    answer: ['BSD', 'BSD License', 'BSD 라이선스'],
    explanation: 'BSD 라이선스는 수정본 배포 시 소스코드 공개 의무가 없는 자유로운 라이선스입니다. (현대 개정판에서는 광고 조항이 삭제됨)',
    difficulty: 'MEDIUM',
    keywords: ['BSD', '버클리', '오픈소스'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '12.2',
  },
  {
    id: 'EXP26_PKG_018',
    subject: '소프트웨어설계',
    category: '제품소프트웨어 패키징',
    subCategory: '릴리즈 노트 작성 항목',
    type: 'SHORT_ANSWER',
    question: '릴리즈 노트 작성 항목 중, 버그를 수정하기 전에 해당 결함이 발생하는 환경과 오류 발생 과정을 순서대로 재현할 수 있도록 기술하는 항목을 무엇이라 하는가?',
    answer: ['재현 단계', '재현 절차', 'Steps to Reproduce'],
    explanation: '릴리즈 노트의 문제 재현 단계(Steps to Reproduce)는 어떤 절차를 거쳤을 때 버그가 발생했는지 명확히 기록하여 수정 여부를 검증할 수 있도록 돕습니다.',
    difficulty: 'MEDIUM',
    keywords: ['릴리즈노트', '재현단계', '결함'],
    source: '2026 실기 핵심 보강',
    angle: 'CHARACTERISTIC',
    targetSubUnit: '12.1',
  },
  {
    id: 'EXP26_PKG_019',
    subject: '소프트웨어설계',
    category: '제품소프트웨어 패키징',
    subCategory: '버전 관리 및 배포',
    type: 'SHORT_ANSWER',
    question: '소프트웨어 버전 관리에서 [주 버전(Major).부 버전(Minor).패치 버전(Patch)] 체계를 따를 때, 기존 버전과 호환되지 않는 큰 기능 변경이나 API 수정이 발생했을 때 올려야 하는 버전 위치의 명칭은 무엇인가?',
    answer: ['메이저', 'Major', '주 버전'],
    explanation: '시맨틱 버저닝(Semantic Versioning)에서 하위 호환성이 깨지는 변경은 Major, 하위 호환 기능을 추가할 때는 Minor, 버그 수정은 Patch 버전을 올립니다.',
    difficulty: 'EASY',
    keywords: ['메이저', '시맨틱버저닝', 'Major'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '12.1',
  },
  {
    id: 'EXP26_PKG_020',
    subject: '소프트웨어설계',
    category: '제품소프트웨어 빌드/배포',
    subCategory: 'CI/CD 지속적 통합 및 배포',
    type: 'SHORT_ANSWER',
    question: '개발자들이 작성한 코드를 중앙 공유 저장소에 매일 빈번하게 통합(Merge)하고, 자동화된 빌드와 단위 테스트를 수행하여 통합 과정의 오류를 조기에 발견하는 소프트웨어 공학 실천법의 약어는 무엇인가?',
    answer: ['CI', '지속적 통합', 'Continuous Integration'],
    explanation: 'CI(Continuous Integration, 지속적 통합)는 자동화된 빌드와 테스트를 통해 코드 충돌과 결함을 조기에 발견하는 현대적인 개발 실천 방식입니다.',
    difficulty: 'EASY',
    keywords: ['CI', '지속적 통합', '빌드자동화'],
    source: '2026 실기 핵심 보강',
    angle: 'TERM_FROM_DEFINITION',
    targetSubUnit: '12.1',
  },
  {
    id: 'EXP26_PKG_021',
    subject: '소프트웨어설계',
    category: '제품소프트웨어 빌드/배포',
    subCategory: 'CI/CD 지속적 통합 및 배포',
    type: 'SHORT_ANSWER',
    question: 'CI 단계를 통과하여 빌드 및 검증된 소프트웨어를 스테이징 환경 또는 실제 프로덕션(운영) 환경에 사람의 개입 없이 자동으로 배포하는 기법의 약어는 무엇인가?',
    answer: ['CD', '지속적 배포', 'Continuous Deployment', 'Continuous Delivery'],
    explanation: 'CD(Continuous Delivery / Continuous Deployment)는 검증된 패키지를 테스트베드 또는 실서버에 자동화된 파이프라인으로 안전하게 배포하는 방식입니다.',
    difficulty: 'EASY',
    keywords: ['CD', '지속적 배포', 'Continuous Deployment'],
    source: '2026 실기 핵심 보강',
    angle: 'TERM_FROM_DEFINITION',
    targetSubUnit: '12.1',
  },
  {
    id: 'EXP26_PKG_022',
    subject: '소프트웨어설계',
    category: '제품소프트웨어 패키징',
    subCategory: '보안 역공학 방지',
    type: 'SHORT_ANSWER',
    question: '소프트웨어의 컴파일된 바이너리나 바이트코드를 리버스 엔지니어링 도구(디컴파일러 등)로 분석하기 어렵도록 변수명, 클래스명을 무의미한 문자로 바꾸고 제어 흐름을 복잡하게 꼬는 기법을 무엇이라 하는가?',
    answer: ['코드 난독화', '난독화', 'Obfuscation', '코드 난독화 도구'],
    explanation: '코드 난독화(Code Obfuscation)는 프로그램의 실행 로직 기능은 동일하게 유지하면서 코드의 가독성을 극단적으로 떨어뜨려 지적 재산권 유출을 막는 기술입니다.',
    difficulty: 'EASY',
    keywords: ['코드 난독화', '난독화', 'Obfuscation'],
    source: '2026 실기 핵심 보강',
    angle: 'TERM_FROM_DEFINITION',
    targetSubUnit: '12.2',
  },
  {
    id: 'EXP26_PKG_023',
    subject: '소프트웨어설계',
    category: '제품소프트웨어 패키징',
    subCategory: '패키징 산출물',
    type: 'SHORT_ANSWER',
    question: '소프트웨어 설치 시 사용자가 프로그램을 손쉽게 설치할 수 있도록 설치 경로 지정, 바탕화면 바로가기 생성, 레지스트리 등록 등의 일련의 설치 작업을 자동화해 주는 도구를 무엇이라 하는가?',
    answer: ['인스톨러', '설치 프로그램', 'Installer'],
    explanation: '인스톨러(Installer)는 패키징된 소프트웨어를 대상 사용자의 시스템 환경에 맞게 자동 전개 및 구성해 주는 패키징 배포 도구입니다.',
    difficulty: 'EASY',
    keywords: ['인스톨러', 'Installer', '설치프로그램'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '12.1',
  },
  {
    id: 'EXP26_PKG_024',
    subject: '소프트웨어설계',
    category: '제품소프트웨어 패키징',
    subCategory: '배포 환경 격리',
    type: 'SHORT_ANSWER',
    question: '배포 과정에서 애플리케이션과 이를 실행하는 데 필요한 런타임 환경, 라이브러리, 시스템 도구를 하나의 이미지로 패키징하여 호스트 OS 커널을 공유하며 프로세스 수준에서 격리 실행하는 경량화 기술은 무엇인가?',
    answer: ['컨테이너', 'Container', '도커 컨테이너'],
    explanation: '컨테이너(Container, e.g. Docker)는 하이퍼바이저 가상머신(VM)보다 훨씬 가볍고 시작 시간이 빠르며 일관된 패키징 및 배포 환경을 보장합니다.',
    difficulty: 'EASY',
    keywords: ['컨테이너', 'Container', '패키징배포'],
    source: '2026 실기 핵심 보강',
    angle: 'CHARACTERISTIC',
    targetSubUnit: '12.1',
  },
  {
    id: 'EXP26_PKG_025',
    subject: '소프트웨어설계',
    category: '제품소프트웨어 패키징',
    subCategory: '릴리즈 노트 작성 항목',
    type: 'SHORT_ANSWER',
    question: '릴리즈 노트 작성 항목 중, 해당 버전에서 아직 해결되지 않아 향후 업데이트에서 수정 예정이며 사용자가 주의해야 할 버그나 기능적 제약사항을 기재하는 항목의 명칭은 무엇인가?',
    answer: ['알려진 문제점', 'Known Issues', '알려진 문제'],
    explanation: '알려진 문제점(Known Issues)은 소프트웨어 배포 시점에 파악되었으나 릴리즈 일정 등으로 인해 해결하지 못한 잔여 결함과 회피 방법(Workaround)을 명시합니다.',
    difficulty: 'MEDIUM',
    keywords: ['알려진 문제점', 'Known Issues', '릴리즈노트'],
    source: '2026 실기 핵심 보강',
    angle: 'IDENTIFICATION',
    targetSubUnit: '12.1',
  },
];
