import { Question } from "../../src/types/question";

export const IS_QUESTIONS: Question[] = [
  {
    id: "MEMO_IS_015",
    subject: "정보시스템구축관리",
    category: "소프트웨어 테스트",
    subCategory: "화이트박스 커버리지",
    type: "SHORT_ANSWER",
    question: "프로그램의 각 분기문(조건문)에서 전체 조건식의 참(True)과 거짓(False)이 적어도 한 번씩 실행되도록 테스트 케이스를 설계하는 검증 기준의 명칭을 쓰시오.",
    answer: ["분기 커버리지", "결정 커버리지", "Branch Coverage", "Decision Coverage"],
    explanation: "분기(결정) 커버리지는 if문의 조건식 전체가 참과 거짓을 모두 경험하도록 합니다. 구문 커버리지보다 엄격합니다.",
    difficulty: "EASY",
    keywords: ["화이트박스", "분기커버리지", "결정커버리지", "참거짓"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_016",
    subject: "정보시스템구축관리",
    category: "소프트웨어 테스트",
    subCategory: "화이트박스 커버리지",
    type: "SHORT_ANSWER",
    question: "전체 조건식의 결과와 상관없이, 전체 조건식 내에 포함된 개별 조건식(개별 조건) 각각이 참(True)과 거짓(False)을 적어도 한 번씩 갖도록 하는 검증 기준의 명칭을 쓰시오.",
    answer: ["조건 커버리지", "Condition Coverage"],
    explanation: "조건 커버리지는 개별 조건들의 참/거짓을 검증하지만, 전체 조건식의 최종 참/거짓을 모두 만족시키지 못할 수도 있습니다.",
    difficulty: "MEDIUM",
    keywords: ["화이트박스", "조건커버리지", "개별조건"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_017",
    subject: "정보시스템구축관리",
    category: "소프트웨어 테스트",
    subCategory: "화이트박스 커버리지",
    type: "SHORT_ANSWER",
    question: "개별 조건식이 다른 개별 조건식의 영향을 받지 않고 독립적으로 전체 조건식의 결과에 영향을 미치도록 설계하는 화이트박스 커버리지의 영문 약어를 쓰시오.",
    answer: ["MC/DC", "MCDC", "Modified Condition/Decision Coverage", "변형 조건 결정 커버리지"],
    explanation: "MC/DC는 항공, 자동차, 원자력 등 고신뢰성 안전 필수 소프트웨어 검증에 의무적으로 요구되는 매우 엄격한 기준입니다.",
    difficulty: "HARD",
    keywords: ["화이트박스", "MC/DC", "MCDC", "독립적영향"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_018",
    subject: "정보시스템구축관리",
    category: "소프트웨어 테스트",
    subCategory: "블랙박스 기법",
    type: "SHORT_ANSWER",
    question: "입력값의 전체 범위를 유효한 입력값과 무효한 입력값의 상호 배타적인 영역(클래스)으로 분할하고 각 영역에서 대표값을 추출하여 테스트하는 기법의 명칭을 쓰시오.",
    answer: ["동등 분할", "동치 분할", "Equivalence Partitioning", "동등 분할 기법", "동치 분할 기법"],
    explanation: "동등 분할(동치 분할)은 적은 수의 대표값으로 전체 범위를 대표할 수 있다는 가정을 바탕으로 하는 블랙박스 테스트 기법입니다.",
    difficulty: "EASY",
    keywords: ["블랙박스", "동등분할", "동치분할", "대표값"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_019",
    subject: "정보시스템구축관리",
    category: "소프트웨어 테스트",
    subCategory: "블랙박스 기법",
    type: "SHORT_ANSWER",
    question: "입력 조건(원인)과 그에 따른 출력 결과(결과) 사이의 논리적 관계를 체계적으로 분석하여 불리언 그래프를 작성하고 이를 바탕으로 테스트 케이스를 도출하는 기법을 쓰시오.",
    answer: ["원인 결과 그래프", "Cause-Effect Graphing", "원인-결과 그래프"],
    explanation: "원인-결과 그래프 기법은 복잡한 비즈니스 로직과 여러 조건 간의 상호작용 조합을 테스트할 때 효과적입니다.",
    difficulty: "MEDIUM",
    keywords: ["블랙박스", "원인결과그래프", "Cause-Effect"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_020",
    subject: "정보시스템구축관리",
    category: "소프트웨어 테스트",
    subCategory: "블랙박스 기법",
    type: "SHORT_ANSWER",
    question: "테스터의 풍부한 경험, 직관, 과거 오류 데이터에 기반하여 프로그램에서 결함이 발생하기 쉬운 부분을 추측하여 테스트 케이스를 작성하는 기법의 명칭을 쓰시오.",
    answer: ["오류 예측", "오류 예측 기법", "Error Guessing", "오류 추측"],
    explanation: "오류 예측(Error Guessing)은 공식 명세서에 나오지 않는 비정형적이고 극단적인 상황의 버그를 빠르게 찾아낼 때 유용합니다.",
    difficulty: "EASY",
    keywords: ["블랙박스", "오류예측", "경험기반", "ErrorGuessing"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_021",
    subject: "정보시스템구축관리",
    category: "소프트웨어 테스트",
    subCategory: "통합 테스트 도구",
    type: "SHORT_ANSWER",
    question: "하향식(Top-Down) 통합 테스트 시, 아직 구현되지 않은 하위 모듈을 대신하여 상위 모듈의 호출에 임시 응답을 반환해 주는 가상의 더미 모듈 명칭을 쓰시오.",
    answer: ["스텁", "테스트 스텁", "Stub", "Test Stub"],
    explanation: "하향식 통합은 주 모듈(루트)부터 아래로 내려가며 아직 없는 하위 모듈 자리에 스텁(Stub)을 배치합니다. 상향식은 드라이버(Driver)를 씁니다.",
    difficulty: "EASY",
    keywords: ["통합테스트", "스텁", "Stub", "하향식"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_022",
    subject: "정보시스템구축관리",
    category: "소프트웨어 테스트",
    subCategory: "통합 테스트 도구",
    type: "SHORT_ANSWER",
    question: "상향식(Bottom-Up) 통합 테스트 시, 최하위 모듈을 먼저 시험하기 위해 상위 제어 모듈 역할을 대신하여 하위 모듈에 테스트 데이터를 전달하고 결과를 받는 임시 소프트웨어의 명칭을 쓰시오.",
    answer: ["드라이버", "테스트 드라이버", "Driver", "Test Driver"],
    explanation: "상향식 통합은 가장 말단 모듈부터 검증하므로 이를 구동해 줄 테스트 드라이버(Test Driver)가 필수적입니다.",
    difficulty: "EASY",
    keywords: ["통합테스트", "드라이버", "Driver", "상향식"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_023",
    subject: "정보시스템구축관리",
    category: "소프트웨어 테스트",
    subCategory: "테스트 원리",
    type: "SHORT_ANSWER",
    question: "동일한 테스트 케이스로 반복해서 테스트하면 더 이상 새로운 결함을 찾아낼 수 없으므로, 주기적으로 테스트 케이스를 점검하고 개선해야 한다는 테스트 원리의 명칭을 쓰시오.",
    answer: ["살충제 패러독스", "Pesticide Paradox", "살충제 역설"],
    explanation: "살충제 패러독스는 농약에 내성이 생기는 현상에 빗댄 원리로 테스트 케이스의 지속적인 갱신 필요성을 강조합니다.",
    difficulty: "EASY",
    keywords: ["테스트원리", "살충제패러독스", "PesticideParadox"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_024",
    subject: "정보시스템구축관리",
    category: "소프트웨어 테스트",
    subCategory: "테스트 원리",
    type: "SHORT_ANSWER",
    question: "소프트웨어의 결함을 모두 제거하여 오류가 전혀 없더라도, 사용자의 요구사항이나 비즈니스 목적을 충족하지 못하면 품질이 높다고 볼 수 없다는 테스트 원리의 명칭을 쓰시오.",
    answer: ["오류 부재의 궤변", "오류 부재의 역설", "Absence of Errors Fallacy"],
    explanation: "오류 부재의 궤변은 결함 제로보다 사용자의 실제 요구 만족과 가치 제공이 더 본질적임을 나타냅니다.",
    difficulty: "EASY",
    keywords: ["테스트원리", "오류부재의궤변", "요구사항충족"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_025",
    subject: "정보시스템구축관리",
    category: "소프트웨어 테스트",
    subCategory: "테스트 유형",
    type: "SHORT_ANSWER",
    question: "새로운 기능 추가나 버그 수정 등의 코드 변경 이후, 이미 검증되었던 기존 기능들이 부작용(Side Effect)으로 깨지거나 새로운 결함이 생기지 않았는지 다시 확인하는 반복 테스트의 명칭을 쓰시오.",
    answer: ["회귀 테스트", "리그레션 테스트", "Regression Test", "회귀 시험"],
    explanation: "회귀 테스트는 CI/CD 자동화 파이프라인에서 빌드마다 자동 실행되어 변경으로 인한 퇴행을 방지합니다.",
    difficulty: "EASY",
    keywords: ["테스트유형", "회귀테스트", "RegressionTest", "부작용검증"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_026",
    subject: "정보시스템구축관리",
    category: "소프트웨어 테스트",
    subCategory: "인수 테스트",
    type: "SHORT_ANSWER",
    question: "개발 조직 내부에서 통제된 개발 환경 하에 개발자와 사용자가 함께 수행하는 사전 인수 테스트의 명칭을 쓰시오.",
    answer: ["알파 테스트", "Alpha Test"],
    explanation: "알파 테스트는 통제된 내부 환경에서 치러지며, 이후 실제 사용자들의 실제 환경에서 비통제 상태로 수행되는 것은 베타 테스트(Beta Test)입니다.",
    difficulty: "EASY",
    keywords: ["인수테스트", "알파테스트", "AlphaTest", "통제환경"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_027",
    subject: "정보시스템구축관리",
    category: "소프트웨어 테스트",
    subCategory: "인수 테스트",
    type: "SHORT_ANSWER",
    question: "선정된 실제 최종 사용자나 잠재 고객들이 실제 운영 환경에서 소프트웨어를 사용해보며 결함을 발견하고 피드백을 주는 공개 필드 테스트의 명칭을 쓰시오.",
    answer: ["베타 테스트", "Beta Test"],
    explanation: "베타 테스트는 다양한 하드웨어 및 실사용자 시나리오 환경에서 예기치 않은 오류를 사전에 수집합니다.",
    difficulty: "EASY",
    keywords: ["인수테스트", "베타테스트", "BetaTest", "실운영환경"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_028",
    subject: "정보시스템구축관리",
    category: "비용 산정 기법",
    subCategory: "COCOMO",
    type: "SHORT_ANSWER",
    question: "보헴(Boehm)이 제안한 COCOMO 모델의 프로젝트 유형 중, 5만 라인(50 KDSI) 이하의 소규모 소프트웨어 개발에 적용되는 기본 유형의 명칭을 쓰시오.",
    answer: ["조직형", "기본형", "Organic", "오가닉"],
    explanation: "COCOMO 규모 유형: 조직형(Organic, 5만 이하) → 반분리형(Semi-detached, 30만 이하) → 내장형(Embedded, 30만 초과 고신뢰 시스템).",
    difficulty: "EASY",
    keywords: ["COCOMO", "조직형", "Organic", "비용산정"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_029",
    subject: "정보시스템구축관리",
    category: "비용 산정 기법",
    subCategory: "COCOMO",
    type: "SHORT_ANSWER",
    question: "COCOMO 모델의 유형 중 항공, 미사일, 군사, 원자력 등 초대형 복합 시스템으로 30만 라인(300 KDSI) 이상의 고난도 시스템 개발에 적용되는 유형의 명칭을 쓰시오.",
    answer: ["내장형", "임베디드", "Embedded"],
    explanation: "내장형(Embedded)은 엄격한 제약조건과 신뢰성이 요구되는 대규모 프로젝트에 적용됩니다.",
    difficulty: "EASY",
    keywords: ["COCOMO", "내장형", "Embedded", "대규모"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_030",
    subject: "정보시스템구축관리",
    category: "비용 산정 기법",
    subCategory: "기능점수",
    type: "SHORT_ANSWER",
    question: "소프트웨어의 기능적 요구사항을 사용자가 요구하는 데이터 기능(ILF, EIF)과 트랜잭션 기능(EI, EO, EQ)의 5대 유형으로 식별하여 규모를 정량화하는 기법의 명칭 또는 영문 약어를 쓰시오.",
    answer: ["기능 점수", "기능점수", "기능점수 모형", "FP", "Function Point"],
    explanation: "기능점수(FP)는 알브레히트(Albrecht)가 고안하였으며 언어나 기술에 독립적인 소프트웨어 규모 측정 국제 표준입니다.",
    difficulty: "EASY",
    keywords: ["비용산정", "기능점수", "FunctionPoint", "FP"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_031",
    subject: "정보시스템구축관리",
    category: "프로젝트 일정 관리",
    subCategory: "일정 단축",
    type: "SHORT_ANSWER",
    question: "프로젝트 일정을 단축하기 위해 임계 경로 상의 활동에 추가 자원(인력 투입, 야근, 장비 추가)을 투입하여 기간을 줄이는 기법의 영문 명칭을 쓰시오.",
    answer: ["크래싱", "크래싱 기법", "Crashing", "공정 압축"],
    explanation: "Crashing은 일정 단축을 위해 비용(자원)을 추가 지출합니다. 반면 선후 관계의 작업을 병행 수행하여 리스크를 감수하고 단축하는 것은 Fast Tracking입니다.",
    difficulty: "MEDIUM",
    keywords: ["일정단축", "Crashing", "크래싱", "추가자원투입"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_032",
    subject: "정보시스템구축관리",
    category: "프로젝트 일정 관리",
    subCategory: "일정 단축",
    type: "SHORT_ANSWER",
    question: "원래 순차적으로 수행되어야 할 작업들을 동시에 병행(Overlap)하여 진행함으로써 추가 비용 없이 일정을 앞당기는 일정 단축 기법의 영문 명칭을 쓰시오.",
    answer: ["패스트 트래킹", "Fast Tracking", "병행 수행", "패스트트래킹"],
    explanation: "Fast Tracking은 재작업(Rework)과 품질 저하의 위험이 따를 수 있습니다.",
    difficulty: "MEDIUM",
    keywords: ["일정단축", "FastTracking", "패스트트래킹", "병행수행"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_033",
    subject: "정보시스템구축관리",
    category: "형상 관리",
    subCategory: "활동",
    type: "SHORT_ANSWER",
    question: "소프트웨어 생명주기 동안 관리 대상이 되는 형상 항목(Configuration Item)을 구분하고 고유 식별 번호와 이름을 부여하는 형상 관리 활동의 명칭을 쓰시오.",
    answer: ["형상 식별", "Configuration Identification"],
    explanation: "형상 관리 4대 활동: 형상 식별 → 형상 통제(변경 승인) → 형상 감사(무결성 검토) → 형상 기록/보고.",
    difficulty: "EASY",
    keywords: ["형상관리", "형상식별", "Identification"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_034",
    subject: "정보시스템구축관리",
    category: "형상 관리",
    subCategory: "조직",
    type: "SHORT_ANSWER",
    question: "형상 항목에 대한 변경 요청을 공식적으로 검토, 평가, 승인하거나 기각하는 책임을 맡은 조직의 영문 약어를 쓰시오.",
    answer: ["CCB", "Configuration Control Board", "형상 통제 위원회", "형상통제위원회"],
    explanation: "CCB는 베이스라인이 확정된 이후 발생하는 모든 소프트웨어 변경의 타당성을 심의하고 승인합니다.",
    difficulty: "EASY",
    keywords: ["형상관리", "CCB", "형상통제위원회"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_035",
    subject: "정보시스템구축관리",
    category: "품질 표준",
    subCategory: "ISO 25010",
    type: "SHORT_ANSWER",
    question: "ISO/IEC 25010 소프트웨어 제품 품질 모델의 8대 품질 특성 중 명시된 조건에서 시스템이 손상 없이 필요한 만큼 정상 작동 상태를 유지하는 능력을 뜻하는 특성의 명칭을 쓰시오.",
    answer: ["신뢰성", "Reliability"],
    explanation: "ISO 25010 8대 특성: 기능 적합성, 성능 효율성, 호환성, 사용성, 신뢰성, 보안성, 유지보수성, 이식성.",
    difficulty: "EASY",
    keywords: ["품질표준", "ISO25010", "신뢰성", "Reliability"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_036",
    subject: "정보시스템구축관리",
    category: "품질 표준",
    subCategory: "ISO 25010",
    type: "SHORT_ANSWER",
    question: "ISO/IEC 25010 품질 특성 중 소프트웨어가 다른 하드웨어나 운영체제 등 다양한 환경으로 쉽게 전환될 수 있는 특성의 명칭을 쓰시오.",
    answer: ["이식성", "Portability"],
    explanation: "이식성(Portability)은 적응성(Adaptability), 설치성(Installability), 대체성(Replaceability)을 부특성으로 포함합니다.",
    difficulty: "EASY",
    keywords: ["품질표준", "ISO25010", "이식성", "Portability"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_037",
    subject: "정보시스템구축관리",
    category: "프로세스 평가",
    subCategory: "SPICE",
    type: "SHORT_ANSWER",
    question: "소프트웨어 프로세스 개선 및 역량 수준을 6단계(레벨 0~5)로 평가하기 위한 국제 표준(ISO/IEC 15504)의 약칭을 쓰시오.",
    answer: ["SPICE", "스파이스", "ISO 15504"],
    explanation: "SPICE(Software Process Improvement and Capability dEtermination)는 프로세스 능력 수준을 불완전(0) ~ 최적화(5) 6단계로 판정합니다.",
    difficulty: "MEDIUM",
    keywords: ["품질표준", "SPICE", "ISO15504", "역량평가"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_038",
    subject: "정보시스템구축관리",
    category: "재해 복구",
    subCategory: "지표",
    type: "SHORT_ANSWER",
    question: "IT 시스템 및 서비스 장애 발생 시점부터 서비스가 다시 정상 가동될 때까지 허용되는 최대 복구 시간을 뜻하는 지표의 영문 약어를 쓰시오.",
    answer: ["RTO", "Recovery Time Objective", "목표 복구 시간"],
    explanation: "RTO(Recovery Time Objective)는 복구하는 데 걸리는 시간 목표이고, 데이터 손실 허용 시점은 RPO(Recovery Point Objective)입니다.",
    difficulty: "EASY",
    keywords: ["재해복구", "RTO", "RecoveryTimeObjective", "복구시간"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_039",
    subject: "정보시스템구축관리",
    category: "재해 복구",
    subCategory: "지표",
    type: "SHORT_ANSWER",
    question: "재해나 시스템 장애 발생 시 비즈니스가 감내할 수 있는 최대 데이터 손실 허용 시점(과거 백업 시점 기준)을 뜻하는 지표의 영문 약어를 쓰시오.",
    answer: ["RPO", "Recovery Point Objective", "목표 복구 시점"],
    explanation: "RPO가 0이라는 것은 실시간 동기화 복제를 통해 단 1초의 데이터 유실도 용납하지 않음을 의미합니다.",
    difficulty: "EASY",
    keywords: ["재해복구", "RPO", "RecoveryPointObjective", "데이터손실허용"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_040",
    subject: "정보시스템구축관리",
    category: "재해 복구 센터",
    subCategory: "사이트 유형",
    type: "SHORT_ANSWER",
    question: "주 센터와 원격 재해 복구 센터의 모든 데이터와 시스템을 실시간 액티브-액티브(Active-Active)로 완벽히 복제하여 재해 시 RTO가 사실상 0(즉시)인 사이트 유형을 쓰시오.",
    answer: ["미러 사이트", "Mirror Site", "미러사이트"],
    explanation: "재해복구 사이트 4단계: Mirror Site(실시간 복제, RTO 즉시) > Hot Site(대기 상태, RTO 수시간) > Warm Site(중요 자원 보유, RTO 수일) > Cold Site(장소/기본전원만 보유, RTO 수주).",
    difficulty: "MEDIUM",
    keywords: ["재해복구", "미러사이트", "MirrorSite", "RTO=0"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_041",
    subject: "정보시스템구축관리",
    category: "재해 복구 센터",
    subCategory: "사이트 유형",
    type: "SHORT_ANSWER",
    question: "주 센터와 동일한 하드웨어와 소프트웨어가 대기(Standby) 상태로 상시 가동되고 있어 재해 발생 시 수 시간 이내에 서비스를 복구할 수 있는 사이트 유형을 쓰시오.",
    answer: ["핫 사이트", "Hot Site", "핫사이트"],
    explanation: "Hot Site는 동기/비동기 방식으로 데이터를 백업받으며 상시 스탠바이 상태를 유지합니다.",
    difficulty: "EASY",
    keywords: ["재해복구", "핫사이트", "HotSite", "수시간복구"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_042",
    subject: "정보시스템구축관리",
    category: "스토리지 시스템",
    subCategory: "스토리지 아키텍처",
    type: "SHORT_ANSWER",
    question: "기존 LAN 네트워크의 대역폭 한계를 극복하기 위해 서버와 스토리지 사이에 광채널(Fibre Channel) 고속 전용 네트워크를 구축하여 블록 레벨 I/O를 제공하는 스토리지망의 영문 약어를 쓰시오.",
    answer: ["SAN", "Storage Area Network"],
    explanation: "SAN은 서버와 스토리지를 고속 파이버 채널 스위치로 연결하는 블록 단위 스토리지 네트워크입니다. 파일 공유용은 NAS(Network Attached Storage)입니다.",
    difficulty: "EASY",
    keywords: ["스토리지", "SAN", "광채널", "블록스토리지"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_043",
    subject: "정보시스템구축관리",
    category: "스토리지 시스템",
    subCategory: "RAID",
    type: "SHORT_ANSWER",
    question: "데이터를 여러 디스크에 나누어 저장(스트라이핑)하여 읽기/쓰기 성능을 극대화하지만, 패리티(중복)가 없어 디스크 하나만 고장 나도 전체 데이터가 유실되는 RAID 레벨을 쓰시오.",
    answer: ["RAID 0", "RAID-0", "레이드 0"],
    explanation: "RAID 0은 스트라이핑(Striping) 전용으로 장애 내구성이 없습니다. 미러링으로 안전성을 확보하는 것은 RAID 1입니다.",
    difficulty: "EASY",
    keywords: ["RAID", "RAID0", "스트라이핑", "무패리티"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_044",
    subject: "정보시스템구축관리",
    category: "스토리지 시스템",
    subCategory: "RAID",
    type: "SHORT_ANSWER",
    question: "최소 3개 이상의 디스크를 사용하여 데이터와 오류 검출용 패리티(Parity)를 모든 디스크에 분산 저장함으로써 디스크 1개 장애까지 복구 가능한 실무에서 가장 널리 쓰이는 RAID 레벨을 쓰시오.",
    answer: ["RAID 5", "RAID-5", "레이드 5"],
    explanation: "RAID 5는 패리티 분산 저장 방식을 사용하여 병목을 줄이고 디스크 1개 결함을 극복합니다.",
    difficulty: "EASY",
    keywords: ["RAID", "RAID5", "패리티분산", "최소3개"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_045",
    subject: "정보시스템구축관리",
    category: "IT 서비스 관리",
    subCategory: "SLA",
    type: "SHORT_ANSWER",
    question: "서비스 제공업체와 고객 간에 서비스 가용성(예: 99.9%), 응답 속도, 장애 처리 시간 등 제공할 서비스의 품질 수준을 공식적으로 명시하고 미달 시 보상 규정을 담은 계약서의 영문 약어를 쓰시오.",
    answer: ["SLA", "Service Level Agreement", "서비스 수준 협약서"],
    explanation: "SLA는 ITSM의 기초 계약이며 세부 달성 목표는 SLO(Service Level Objective), 측정 척도는 SLI(Service Level Indicator)입니다.",
    difficulty: "EASY",
    keywords: ["ITSM", "SLA", "서비스수준협약서"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_046",
    subject: "정보시스템구축관리",
    category: "업무 연속성",
    subCategory: "BCP",
    type: "SHORT_ANSWER",
    question: "화재, 지진 등 재난 발생 시에도 조직의 핵심 비즈니스 기능을 중단 없이 지속하거나 신속히 재개하기 위한 체계적인 비즈니스 연속성 계획의 영문 약어를 쓰시오.",
    answer: ["BCP", "Business Continuity Planning", "업무 연속성 계획"],
    explanation: "BCP는 업무 영향 분석(BIA)을 기초로 수립되며, IT 시스템 차원의 재해 복구 계획인 DRP(Disaster Recovery Plan)를 포함합니다.",
    difficulty: "EASY",
    keywords: ["업무연속성", "BCP", "BusinessContinuityPlanning"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_047",
    subject: "정보시스템구축관리",
    category: "소프트웨어 테스트",
    subCategory: "V-모델",
    type: "SHORT_ANSWER",
    question: "소프트웨어 개발 단계와 테스트 단계를 V자 형태로 매핑한 V-모델에서, 시스템의 요구사항 분석 단계에 대응되어 검증을 수행하는 최종 테스트 레벨의 명칭을 쓰시오.",
    answer: ["인수 테스트", "Acceptance Test"],
    explanation: "V-모델 매핑: 요구사항 분석 ↔ 인수 테스트, 시스템 설계 ↔ 시스템 테스트, 아키텍처/상세 설계 ↔ 통합 테스트, 모듈 코딩 ↔ 단위 테스트.",
    difficulty: "EASY",
    keywords: ["V모델", "인수테스트", "요구사항분석매핑"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_048",
    subject: "정보시스템구축관리",
    category: "소프트웨어 테스트",
    subCategory: "검증과 확인",
    type: "SHORT_ANSWER",
    question: "개발자의 관점에서 명세서대로 소프트웨어가 올바르게 구축되었는지를 점검하는 활동(Building the product right)을 뜻하는 용어의 명칭을 쓰시오.",
    answer: ["검증", "Verification"],
    explanation: "검증(Verification)은 '명세서대로 올바르게 만들었는가(개발자 관점)'이고, 확인(Validation)은 '사용자가 원하는 올바른 제품을 만들었는가(사용자 관점)'입니다.",
    difficulty: "MEDIUM",
    keywords: ["테스트", "검증", "Verification", "명세서일치"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_049",
    subject: "정보시스템구축관리",
    category: "소프트웨어 테스트",
    subCategory: "정적 테스트",
    type: "SHORT_ANSWER",
    question: "프로그램 코드를 실제로 실행하지 않고, 설계서나 소스 코드를 읽고 분석하여 결함을 찾아내는 기법(인스펙션, 워크스루 등)의 총칭을 쓰시오.",
    answer: ["정적 테스트", "정적 분석", "Static Testing", "Static Analysis"],
    explanation: "정적 테스트(인스펙션, 워크스루, 정적 코드 분석 도구)는 실행 전에 문법 오류나 코딩 표준 위반, 잠재 결함을 조기에 발견합니다.",
    difficulty: "EASY",
    keywords: ["테스트기법", "정적테스트", "실행없이검사", "인스펙션"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_050",
    subject: "정보시스템구축관리",
    category: "보안 개발 방법론",
    subCategory: "시큐어 코딩",
    type: "SHORT_ANSWER",
    question: "소프트웨어 개발 생명주기(SDLC) 전 과정에 걸쳐 보안 취약점을 예방하기 위해 마이크로소프트사가 개발한 보안 개발 생명주기 프레임워크의 영문 약어를 쓰시오.",
    answer: ["SDL", "MS-SDL", "Security Development Lifecycle"],
    explanation: "MS-SDL은 위협 모델링(STRIDE) 등을 포함하여 계획 단계부터 유지보수까지 보안을 강제하는 표준 프레임워크입니다.",
    difficulty: "MEDIUM",
    keywords: ["보안방법론", "SDL", "MS-SDL", "시큐어코딩"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_051",
    subject: "정보시스템구축관리",
    category: "위험 관리",
    subCategory: "대응 전략",
    type: "SHORT_ANSWER",
    question: "프로젝트 진행 중 발생할 수 있는 위험을 줄이기 위해 프로젝트 계획을 수정하거나 고위험 요구사항 기능을 제거하여 위험 자체를 원천적으로 없애는 대응 전략의 명칭을 쓰시오.",
    answer: ["회피", "위험 회피", "Avoidance", "Risk Avoidance"],
    explanation: "위험 대응 4대 전략: 회피(Avoid, 위험 원천 제거), 전가(Transfer, 보험/외주), 완화(Mitigate, 발생 확률/충격 감소), 수용(Accept, 결과 감내).",
    difficulty: "EASY",
    keywords: ["위험관리", "회피", "위험회피", "Avoidance"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_052",
    subject: "정보시스템구축관리",
    category: "위험 관리",
    subCategory: "대응 전략",
    type: "SHORT_ANSWER",
    question: "위험의 발생 확률이나 영향도를 낮추기 위해 사전 예방 조치를 취하거나 모니터링을 강화하는 가장 일반적인 위험 대응 전략의 명칭을 쓰시오.",
    answer: ["완화", "위험 완화", "Mitigation", "Risk Mitigation"],
    explanation: "완화(Mitigation)는 시스템 백업 수립, 백신 설치 등 잠재적 위험의 충격을 줄이는 조치입니다.",
    difficulty: "EASY",
    keywords: ["위험관리", "완화", "위험완화", "Mitigation"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_053",
    subject: "정보시스템구축관리",
    category: "정형 기술 검토",
    subCategory: "인스펙션",
    type: "SHORT_ANSWER",
    question: "원작성자가 아닌 다른 검토 전문가들이 체크리스트를 바탕으로 소스 코드나 명세서를 정밀하게 결함 식별하는 가장 공식적이고 체계적인 동료 검토 기법의 명칭을 쓰시오.",
    answer: ["인스펙션", "Inspection", "코드 인스펙션", "동료 검토"],
    explanation: "패이건(Fagan)이 제안한 인스펙션은 주재자(Moderator), 작성자, 낭독자, 기록자, 검토자 역할을 엄격히 나누어 결함을 색출합니다.",
    difficulty: "MEDIUM",
    keywords: ["품질검토", "인스펙션", "Inspection", "체크리스트"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_054",
    subject: "정보시스템구축관리",
    category: "정형 기술 검토",
    subCategory: "워크스루",
    type: "SHORT_ANSWER",
    question: "소프트웨어 개발 산출물의 작성자가 직접 동료들에게 작업물을 설명하고 안내하면서 비공식적으로 결함을 조기에 발견하고 검토하는 기법의 명칭을 쓰시오.",
    answer: ["워크스루", "Walkthrough", "워크스루 기법"],
    explanation: "워크스루(Walkthrough)는 인스펙션보다 덜 형식적이며 작성자가 주도하여 동료들의 피드백을 수집합니다.",
    difficulty: "EASY",
    keywords: ["품질검토", "워크스루", "Walkthrough", "작성자주도"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_055",
    subject: "정보시스템구축관리",
    category: "소프트웨어 테스트",
    subCategory: "성능 테스트",
    type: "SHORT_ANSWER",
    question: "시스템의 임계점 이상의 과도한 부하를 가하여 비정상적인 극한 상황에서 시스템이 어떻게 반응하고 복구(Failover)되는지 점검하는 테스트의 명칭을 쓰시오.",
    answer: ["스트레스 테스트", "Stress Test", "스트레스 시험", "한계 테스트"],
    explanation: "스트레스 테스트는 최대 한계 이상의 과부하를 주어 시스템의 붕괴점과 복구 능력을 평가합니다. 평상시 부하를 검증하는 것은 부하 테스트(Load Test)입니다.",
    difficulty: "EASY",
    keywords: ["성능테스트", "스트레스테스트", "StressTest", "극한부하"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_056",
    subject: "정보시스템구축관리",
    category: "소프트웨어 테스트",
    subCategory: "블랙박스 기법",
    type: "SHORT_ANSWER",
    question: "대부분의 결함이 두 입력 변수의 상호작용에서 비롯된다는 점에 착안하여, 모든 파라미터 값의 쌍(Pair)이 적어도 한 번씩 테스트되도록 케이스를 최소화하는 조합 기법의 명칭을 쓰시오.",
    answer: ["페어와이즈", "페어와이즈 테스트", "Pairwise", "Pairwise Testing"],
    explanation: "페어와이즈(Pairwise) 기법은 직교 배열표(Orthogonal Array) 등을 활용해 방대한 전체 조합 수를 획기적으로 줄여 테스트 효율을 극대화합니다.",
    difficulty: "HARD",
    keywords: ["블랙박스", "페어와이즈", "Pairwise", "2-way조합"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_057",
    subject: "정보시스템구축관리",
    category: "소프트웨어 테스트",
    subCategory: "테스트 유형",
    type: "SHORT_ANSWER",
    question: "시스템에 오류나 결함이 발생했을 때, 데이터 손실 없이 정상 상태로 신속히 복원되는지 점검하는 비기능 테스트의 명칭을 쓰시오.",
    answer: ["회복 테스트", "Recovery Testing", "복구 테스트"],
    explanation: "회복(Recovery) 테스트는 장애 발생 시 백업 복구 절차, 페일오버(Failover), 재기동 과정이 제대로 작동하는지 검증합니다.",
    difficulty: "EASY",
    keywords: ["비기능테스트", "회복테스트", "RecoveryTest"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_058",
    subject: "정보시스템구축관리",
    category: "비용 산정 기법",
    subCategory: "LOC",
    type: "SHORT_ANSWER",
    question: "원시 코드 라인 수(LOC)를 낙관치(a), 기대치(m), 비관치(b)로 추정할 때, (a + 4m + b) / 6 공식을 사용하여 산정하는 통계적 예측 모형의 약어를 쓰시오.",
    answer: ["PERT", "3점 산정", "PERT 공식"],
    explanation: "LOC 추정 시 3점 산정(PERT 기법)을 활용하면 편향을 줄이고 보다 신뢰성 있는 가중평균 라인 수를 계산할 수 있습니다.",
    difficulty: "MEDIUM",
    keywords: ["비용산정", "LOC", "3점산정", "PERT"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_059",
    subject: "정보시스템구축관리",
    category: "IT 서비스 관리",
    subCategory: "문제 관리",
    type: "SHORT_ANSWER",
    question: "반복 발생하는 인시던트(Incident)의 근본적인 원인(Root Cause)을 분석하고 영구적인 해결책이나 우회책(Workaround)을 마련하는 ITIL 프로세스의 명칭을 쓰시오.",
    answer: ["문제 관리", "Problem Management"],
    explanation: "인시던트 관리가 '서비스의 빠른 정상 복구'에 집중한다면, 문제 관리는 '장애의 근본 원인 제거와 재발 방지'에 집중합니다.",
    difficulty: "MEDIUM",
    keywords: ["ITIL", "문제관리", "근본원인", "ProblemManagement"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_060",
    subject: "정보시스템구축관리",
    category: "IT 서비스 관리",
    subCategory: "변경 관리",
    type: "SHORT_ANSWER",
    question: "IT 인프라나 시스템 구성 요소의 변경 작업으로 인해 발생할 수 있는 서비스 중단 리스크를 최소화하기 위해 변경 요청을 표준화된 절차로 평가·승인·일정 조율하는 프로세스의 명칭을 쓰시오.",
    answer: ["변경 관리", "Change Management"],
    explanation: "변경 관리(Change Management)는 정당한 변경만 안전하게 배포되도록 보장합니다.",
    difficulty: "EASY",
    keywords: ["ITIL", "변경관리", "ChangeManagement"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_061",
    subject: "정보시스템구축관리",
    category: "클라우드 운영",
    subCategory: "IaC",
    type: "SHORT_ANSWER",
    question: "수동 조작 대신 테라폼(Terraform)이나 앤서블(Ansible)처럼 코드를 통해 컴퓨팅 인프라(서버, 네트워크 등)를 선언하고 자동 프로비저닝하는 패러다임의 영문 약어를 쓰시오.",
    answer: ["IaC", "Infrastructure as Code", "코드형 인프라"],
    explanation: "IaC는 인프라 형상을 버전 관리할 수 있게 하며 환경 간 불일치를 없애고 자동화된 빠른 배포를 가능하게 합니다.",
    difficulty: "EASY",
    keywords: ["신기술", "IaC", "InfrastructureAsCode", "코드형인프라"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_062",
    subject: "정보시스템구축관리",
    category: "스토리지 시스템",
    subCategory: "NAS",
    type: "SHORT_ANSWER",
    question: "기존 이더넷 LAN 네트워크에 직접 스토리지를 연결하여 여러 서버나 클라이언트가 파일 단위(NFS, CIFS/SMB 프로토콜)로 데이터를 공유할 수 있는 스토리지 방식의 영문 약어를 쓰시오.",
    answer: ["NAS", "Network-Attached Storage", "네트워크 부착 스토리지"],
    explanation: "NAS는 파일 레벨 스토리지 공유를 제공하며 설치가 간편하고 비용이 저렴하지만 대규모 트래픽 시 LAN 병목이 발생할 수 있습니다.",
    difficulty: "EASY",
    keywords: ["스토리지", "NAS", "파일공유", "NFS"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_063",
    subject: "정보시스템구축관리",
    category: "소프트웨어 결함 관리",
    subCategory: "심각도",
    type: "SHORT_ANSWER",
    question: "소프트웨어 결함 측정 시 시스템 전체가 다운되거나 핵심 기능이 전혀 동작하지 않아 테스트 진행 자체가 불가능한 최고 등급 결함 심각도의 명칭을 쓰시오.",
    answer: ["치명적", "치명도", "Critical", "크리티컬", "Fatal"],
    explanation: "결함 심각도(Severity) 등급: 치명적(Critical/Fatal) → 주요 결함(Major) → 일반 결함(Normal) → 경미한 결함(Minor) → 단순 결함(Trivial).",
    difficulty: "MEDIUM",
    keywords: ["결함관리", "심각도", "Critical", "치명적"],
    source: "정보처리기사 실기 표준",
  },
  {
    id: "MEMO_IS_064",
    subject: "정보시스템구축관리",
    category: "개발 생명주기",
    subCategory: "애자일 선언",
    type: "SHORT_ANSWER",
    question: "애자일 선언문 4대 가치 중 '프로세스와 도구보다는 개인과 상호작용을', '포괄적인 문서보다는 동작하는 소프트웨어를', '계약 협상보다는 고객과의 협력을'에 이어 마지막 '계획을 따르기보다는 무엇에 대응하는 것'을 가치 있게 여기는지 쓰시오.",
    answer: ["변화", "변화에 대응", "변화 대응", "Responding to change"],
    explanation: "애자일 선언문: 계획을 따르기보다 변화에 대응하기를 더 가치 있게 여긴다(Responding to change over following a plan).",
    difficulty: "EASY",
    keywords: ["애자일", "애자일선언", "변화대응", "4대가치"],
    source: "정보처리기사 실기 표준",
  },
];
