import { Question } from '../../src/types/question';

export const BATCH_6_QUESTIONS: Question[] = [
  {
    id: 'EXP_DB2_001',
    subject: '데이터베이스구축',
    category: '트랜잭션 격리수준',
    type: 'SHORT_ANSWER',
    question: '트랜잭션 격리수준 중 다른 트랜잭션이 아직 COMMIT하지 않은 변경 중인 데이터를 읽을 수 있어 Dirty Read가 허용되는 가장 낮은 단계는 무엇인가?',
    answer: 'READ UNCOMMITTED',
    explanation: 'READ UNCOMMITTED는 락(Lock)을 걸지 않아 속도는 가장 빠르지만 데이터 일관성이 파괴될 수 있습니다.',
    difficulty: 'EASY',
    keywords: ['READ UNCOMMITTED', '격리수준', 'Dirty Read'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-isolation',
  },
  {
    id: 'EXP_DB2_002',
    subject: '데이터베이스구축',
    category: '트랜잭션 격리수준',
    type: 'SHORT_ANSWER',
    question: '대부분의 상용 RDBMS(Oracle, SQL Server 등)의 기본 격리수준으로, COMMIT이 완료된 유효한 데이터만 읽을 수 있어 Dirty Read를 방지하는 단계는 무엇인가?',
    answer: 'READ COMMITTED',
    explanation: 'READ COMMITTED는 커밋된 데이터만 읽어 Dirty Read를 막지만, 동일 트랜잭션 내 재조회 시 결과가 달라지는 Non-repeatable Read는 발생할 수 있습니다.',
    difficulty: 'EASY',
    keywords: ['READ COMMITTED', '기본격리수준', '커밋된데이터조회'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-isolation',
  },
  {
    id: 'EXP_DB2_003',
    subject: '데이터베이스구축',
    category: '트랜잭션 격리수준',
    type: 'SHORT_ANSWER',
    question: '하나의 트랜잭션 내에서 동일한 SELECT 쿼리를 여러 번 실행하더라도 항상 동일한 데이터를 반환하도록 스냅샷을 보장하는 MySQL(InnoDB) 기본 격리수준은 무엇인가?',
    answer: 'REPEATABLE READ',
    explanation: 'REPEATABLE READ는 트랜잭션 시작 시점의 스냅샷을 유지하여 Non-repeatable Read를 방지합니다.',
    difficulty: 'MEDIUM',
    keywords: ['REPEATABLE READ', '격리수준', '반복읽기보장'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-isolation',
  },
  {
    id: 'EXP_DB2_004',
    subject: '데이터베이스구축',
    category: '트랜잭션 격리수준',
    type: 'SHORT_ANSWER',
    question: '트랜잭션들이 완전히 순차적으로(직렬로) 실행되는 것처럼 완벽히 격리하여 Dirty Read, Non-repeatable Read, Phantom Read를 모두 차단하는 최고 격리수준은 무엇인가?',
    answer: 'SERIALIZABLE',
    explanation: 'SERIALIZABLE은 데이터 일관성을 100% 보장하지만 동시 처리 성능(Throughput)이 가장 떨어집니다.',
    difficulty: 'EASY',
    keywords: ['SERIALIZABLE', '최고격리수준', '직렬화'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-isolation',
  },
  {
    id: 'EXP_DB2_005',
    subject: '데이터베이스구축',
    category: '트랜잭션 이상현상',
    type: 'SHORT_ANSWER',
    question: '트랜잭션 A가 데이터를 수정한 후 COMMIT하기 전에 트랜잭션 B가 해당 수정본을 읽었으나, 이후 A가 ROLLBACK되어 B가 무효한 쓰레기 값을 보유하게 되는 이상현상은 무엇인가?',
    answer: 'Dirty Read',
    explanation: 'Dirty Read(오독)는 커밋되지 않은 미완성 변경 데이터를 읽을 때 발생합니다.',
    difficulty: 'EASY',
    keywords: ['Dirty Read', '오독', '트랜잭션이상현상'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-isolation',
  },
  {
    id: 'EXP_DB2_006',
    subject: '데이터베이스구축',
    category: '트랜잭션 이상현상',
    type: 'SHORT_ANSWER',
    question: '하나의 트랜잭션 내에서 같은 튜플을 두 번 조회하는 도중 다른 트랜잭션이 해당 튜플을 UPDATE 및 커밋하여 두 번의 조회 결과 값이 서로 달라지는 현상은 무엇인가?',
    answer: 'Non-repeatable Read',
    explanation: 'Non-repeatable Read(비반복 읽기)는 동일 트랜잭션 내에서 데이터 행의 값이 바뀌어 나타나는 현상입니다.',
    difficulty: 'MEDIUM',
    keywords: ['Non-repeatable Read', '비반복읽기', '트랜잭션이상'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-isolation',
  },
  {
    id: 'EXP_DB2_007',
    subject: '데이터베이스구축',
    category: '트랜잭션 이상현상',
    type: 'SHORT_ANSWER',
    question: '하나의 트랜잭션 내에서 동일한 범위(Range)의 쿼리를 두 번 실행했을 때, 다른 트랜잭션이 새로운 행을 INSERT 및 커밋하여 이전에 없던 유령 행이 나타나는 현상은 무엇인가?',
    answer: 'Phantom Read',
    explanation: 'Phantom Read(유령 읽기)는 범위 조건 검색 시 새로운 레코드가 불쑥 나타나거나 사라지는 현상입니다.',
    difficulty: 'MEDIUM',
    keywords: ['Phantom Read', '유령읽기', '범위검색이상'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-isolation',
  },
  {
    id: 'EXP_DB2_008',
    subject: '데이터베이스구축',
    category: '물리 데이터베이스',
    type: 'SHORT_ANSWER',
    question: '인덱스의 리프 블록(Leaf Block)이 실제 데이터 페이지와 일치하여 물리적으로 키 순서대로 정렬되어 저장되며, 테이블당 오직 1개만 생성 가능한 인덱스는 무엇인가?',
    answer: '클러스터드 인덱스',
    explanation: '클러스터드 인덱스(Clustered Index, 군집 인덱스)는 실제 데이터 행 자체가 인덱스 키 순서로 정렬되어 범위 검색(BETWEEN) 속도가 매우 뛰어납니다.',
    difficulty: 'EASY',
    keywords: ['클러스터드 인덱스', 'Clustered Index', '물리정렬'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-index',
  },
  {
    id: 'EXP_DB2_009',
    subject: '데이터베이스구축',
    category: '물리 데이터베이스',
    type: 'SHORT_ANSWER',
    question: '인덱스의 리프 블록에 실제 데이터 행 대신 데이터의 물리적 위치 주소(RID/ROWID)를 저장하여 테이블당 여러 개를 자유롭게 생성할 수 있는 인덱스는 무엇인가?',
    answer: '넌클러스터드 인덱스',
    explanation: '넌클러스터드 인덱스(Non-Clustered Index, 보조 인덱스)는 별도의 인덱스 페이지를 구성하여 실제 데이터 위치를 포인터로 가리킵니다.',
    difficulty: 'EASY',
    keywords: ['넌클러스터드 인덱스', 'Non-Clustered', 'ROWID'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-index',
  },
  {
    id: 'EXP_DB2_010',
    subject: '데이터베이스구축',
    category: '물리 데이터베이스',
    type: 'SHORT_ANSWER',
    question: '성별(남/여)이나 결제여부(Y/N)처럼 카디널리티(데이터 값의 종류)가 매우 적은 대용량 컬럼에 적합하며, 데이터를 0과 1의 비트 배열로 관리하는 인덱스는 무엇인가?',
    answer: '비트맵 인덱스',
    explanation: '비트맵 인덱스(Bitmap Index)는 카디널리티가 낮은 컬럼의 다중 조건 검색 및 대용량 DW(데이터웨어하우스) 배치 분석에 매우 효과적입니다.',
    difficulty: 'MEDIUM',
    keywords: ['비트맵 인덱스', 'Bitmap Index', '낮은카디널리티'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-index',
  },
  {
    id: 'EXP_DB2_011',
    subject: '데이터베이스구축',
    category: '물리 데이터베이스',
    type: 'SHORT_ANSWER',
    question: '데이터 파티셔닝(Partitioning) 기법 중 연속된 날짜(예: 2024년 1월, 2월 등)나 숫자 범위를 기준으로 대용량 테이블을 물리적으로 분할 저장하는 방식은 무엇인가?',
    answer: '범위 분할',
    explanation: '범위 분할(Range Partitioning)은 날짜나 시계열 데이터를 관리할 때 가장 보편적으로 쓰이는 파티셔닝 방식입니다.',
    difficulty: 'EASY',
    keywords: ['범위 분할', 'Range Partitioning', '파티셔닝'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-partitioning',
  },
  {
    id: 'EXP_DB2_012',
    subject: '데이터베이스구축',
    category: '물리 데이터베이스',
    type: 'SHORT_ANSWER',
    question: '데이터 파티셔닝 기법 중 파티션 키 컬럼에 해시 함수를 적용하여 연산된 결과값에 따라 데이터를 여러 파티션에 균등하게 분산 배치하는 방식은 무엇인가?',
    answer: '해시 분할',
    explanation: '해시 분할(Hash Partitioning)은 데이터의 고른 분산으로 특정 파티션에 병목이 집중되는 현상을 방지합니다.',
    difficulty: 'EASY',
    keywords: ['해시 분할', 'Hash Partitioning', '균등분산'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-partitioning',
  },
  {
    id: 'EXP_DB2_013',
    subject: '데이터베이스구축',
    category: '물리 데이터베이스',
    type: 'SHORT_ANSWER',
    question: '데이터 파티셔닝 기법 중 지역 코드(서울, 경기, 부산)나 지점 코드처럼 명시적으로 정해진 개별 값들의 목록을 기준으로 데이터를 분할하는 방식은 무엇인가?',
    answer: '목록 분할',
    explanation: '목록 분할(List Partitioning)은 고정된 특정 카테고리나 코드 목록별로 파티션을 매핑합니다.',
    difficulty: 'EASY',
    keywords: ['목록 분할', 'List Partitioning', '코드목록분할'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-partitioning',
  },
  {
    id: 'EXP_DB2_014',
    subject: '데이터베이스구축',
    category: '물리 데이터베이스',
    type: 'SHORT_ANSWER',
    question: '대용량 데이터를 효율적으로 관리하기 위해 1차로 범위 분할(Range)을 적용한 후 각 파티션 내부를 다시 해시 분할(Hash)로 세분화하는 2단계 복합 파티셔닝 방식은 무엇인가?',
    answer: '복합 분할',
    explanation: '복합 분할(Composite Partitioning)은 서브 파티셔닝(Sub-partitioning) 기술을 결합하여 대규모 데이터를 최적 관리합니다.',
    difficulty: 'MEDIUM',
    keywords: ['복합 분할', 'Composite Partitioning', '2단계분할'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-partitioning',
  },
  {
    id: 'EXP_DB2_015',
    subject: '데이터베이스구축',
    category: '정규화',
    type: 'SHORT_ANSWER',
    question: '복합 기본키 {학번, 과목코드} 중 기본키의 전체가 아니라 단지 {과목코드} 일부에만 특정 속성(과목명)이 종속되는 현상을 가리키는 용어는 무엇인가?',
    answer: '부분 함수 종속',
    explanation: '부분 함수 종속(Partial Functional Dependency)은 제2정규형(2NF)을 만족하기 위해 반드시 분리 제거해야 합니다.',
    difficulty: 'EASY',
    keywords: ['부분 함수 종속', 'Partial FD', '2NF대상'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-normalization',
  },
  {
    id: 'EXP_DB2_016',
    subject: '데이터베이스구축',
    category: '정규화',
    type: 'SHORT_ANSWER',
    question: '속성 X가 Y를 결정하고(X → Y), 다시 Y가 Z를 결정하여(Y → Z) 논리적으로 X가 Z를 결정하게 되는(X → Z) 종속 관계를 무엇이라 하는가?',
    answer: '이행적 함수 종속',
    explanation: '이행적 함수 종속(Transitive Functional Dependency)은 제3정규형(3NF)에서 별도 테이블로 분리 제거합니다.',
    difficulty: 'EASY',
    keywords: ['이행적 함수 종속', 'Transitive FD', '3NF대상'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-normalization',
  },
  {
    id: 'EXP_DB2_017',
    subject: '데이터베이스구축',
    category: '정규화',
    type: 'SHORT_ANSWER',
    question: '제3정규형을 만족하는 릴레이션에서 모든 결정자(Determinant)가 반드시 후보키(Candidate Key)가 되도록 강제하는 정규형은 무엇인가?',
    answer: 'BCNF',
    explanation: '보이스-코드 정규형(BCNF, Boyce-Codd Normal Form)은 후보키가 아닌 결정자를 제거하는 강한 제3정규형입니다.',
    difficulty: 'EASY',
    keywords: ['BCNF', 'Boyce-Codd', '결정자후보키'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-normalization',
  },
  {
    id: 'EXP_DB2_018',
    subject: '데이터베이스구축',
    category: '정규화',
    type: 'SHORT_ANSWER',
    question: '하나의 릴레이션 내에서 어떤 속성 X의 값 하나에 다른 속성 Y의 다중 값들이 독립적으로 대응되는 다치 종속(MVD)을 제거하는 정규형은 무엇인가?',
    answer: '제4정규형',
    explanation: '제4정규형(4NF)은 다치 종속(Multi-Valued Dependency, A ->> B)을 분리 제거하는 단계입니다.',
    difficulty: 'EASY',
    keywords: ['제4정규형', '4NF', '다치종속제거'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-normalization',
  },
  {
    id: 'EXP_DB2_019',
    subject: '데이터베이스구축',
    category: '정규화',
    type: 'SHORT_ANSWER',
    question: '테이블을 분해했다가 다시 무손실 조인할 때 원래 없던 이상한 거짓 튜플이 생기지 않도록 조인 종속성(JD)을 만족시키는 최고 수준의 정규형은 무엇인가?',
    answer: '제5정규형',
    explanation: '제5정규형(5NF, PJ/NF)은 조인 종속성(Join Dependency)을 제거하여 후보키만을 통해 무손실 분해/조인이 가능하도록 합니다.',
    difficulty: 'EASY',
    keywords: ['제5정규형', '5NF', '조인종속제거'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-normalization',
  },
  {
    id: 'EXP_DB2_020',
    subject: '데이터베이스구축',
    category: '데이터 모델링',
    type: 'SHORT_ANSWER',
    question: '데이터베이스 모델링 3단계 중 요구사항 명세서를 바탕으로 핵심 엔티티와 관계를 도출하여 개념적 스키마(개체-관계 다이어그램, ERD)를 생성하는 단계는 무엇인가?',
    answer: '개념적 설계',
    explanation: '개념적 설계(Conceptual Design)는 DBMS에 독립적인 추상화 단계로 핵심 산출물은 ERD입니다.',
    difficulty: 'EASY',
    keywords: ['개념적 설계', 'Conceptual Design', 'ERD'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-modeling',
  },
  {
    id: 'EXP_DB2_021',
    subject: '데이터베이스구축',
    category: '데이터 모델링',
    type: 'SHORT_ANSWER',
    question: '데이터베이스 모델링 3단계 중 개념 스키마를 바탕으로 목표 RDBMS에 맞게 정규화를 수행하고 외래키와 테이블 스키마를 정의하는 단계는 무엇인가?',
    answer: '논리적 설계',
    explanation: '논리적 설계(Logical Design)는 정규화, 매핑 룰, 트랜잭션 인터페이스를 설계하는 단계입니다.',
    difficulty: 'EASY',
    keywords: ['논리적 설계', 'Logical Design', '정규화수행'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-modeling',
  },
  {
    id: 'EXP_DB2_022',
    subject: '데이터베이스구축',
    category: '데이터 모델링',
    type: 'SHORT_ANSWER',
    question: '데이터베이스 모델링 3단계 중 실제 특정 하드웨어 및 DBMS 엔진의 저장 구조를 고려하여 인덱스, 파티셔닝, 반정규화, 테이블스페이스를 설계하는 단계는 무엇인가?',
    answer: '물리적 설계',
    explanation: '물리적 설계(Physical Design)는 성능 향상을 위해 저장 장치 레코드 배치, 반정규화, 인덱스를 세부 설계합니다.',
    difficulty: 'EASY',
    keywords: ['물리적 설계', 'Physical Design', '인덱스및반정규화'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-modeling',
  },
  {
    id: 'EXP_DB2_023',
    subject: '데이터베이스구축',
    category: '키(Key)의 개념',
    type: 'SHORT_ANSWER',
    question: '릴레이션에서 튜플을 고유하게 식별할 수 있는 유일성(Uniqueness)은 만족하지만, 불필요한 속성이 포함되어 최소성(Minimality)은 만족하지 못하는 키는 무엇인가?',
    answer: '슈퍼키',
    explanation: '슈퍼키(Super Key)는 유일성만 만족합니다. 유일성과 최소성을 모두 만족하는 키는 후보키(Candidate Key)입니다.',
    difficulty: 'EASY',
    keywords: ['슈퍼키', 'Super Key', '유일성만만족'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-keys',
  },
  {
    id: 'EXP_DB2_024',
    subject: '데이터베이스구축',
    category: '키(Key)의 개념',
    type: 'SHORT_ANSWER',
    question: '여러 후보키(Candidate Key) 중에서 기본키(Primary Key)로 선택되지 못하고 남은 나머지 후보키들을 가리키는 용어는 무엇인가?',
    answer: '대체키',
    explanation: '대체키(Alternate Key, 보조키)는 언제든 기본키가 될 수 있는 자격을 갖춘 예비 후보키입니다.',
    difficulty: 'EASY',
    keywords: ['대체키', 'Alternate Key', '후보키잔여'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-keys',
  },
  {
    id: 'EXP_DB2_025',
    subject: '데이터베이스구축',
    category: '데이터 모델링',
    type: 'SHORT_ANSWER',
    question: '부모 엔티티의 기본키가 자식 엔티티의 기본키(PK)의 일부(구성원)로 그대로 상속되어 상속받는 엔티티 관계를 무엇이라 하는가?',
    answer: '식별 관계',
    explanation: '식별 관계(Identifying Relationship)는 부모 없이는 자식이 독립적으로 존재할 수 없는 강한 종속 관계이며 실선으로 표기합니다.',
    difficulty: 'EASY',
    keywords: ['식별 관계', 'Identifying', '실선표기'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-modeling',
  },
  {
    id: 'EXP_DB2_026',
    subject: '데이터베이스구축',
    category: '데이터 모델링',
    type: 'SHORT_ANSWER',
    question: '부모 엔티티의 기본키가 자식 엔티티의 일반 속성(외래키 FK)으로만 상속되어 자식 엔티티가 부모 없이도 독립적으로 존재 가능한 관계를 무엇이라 하는가?',
    answer: '비식별 관계',
    explanation: '비식별 관계(Non-identifying Relationship)는 약한 종속 관계이며 점선으로 표기합니다.',
    difficulty: 'EASY',
    keywords: ['비식별 관계', 'Non-identifying', '점선표기'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-modeling',
  },
  {
    id: 'EXP_DB2_027',
    subject: '데이터베이스구축',
    category: '데이터 무결성',
    type: 'SHORT_ANSWER',
    question: '데이터베이스의 기본키(Primary Key)는 어떠한 경우에도 NULL 값을 가질 수 없으며 릴레이션 내에서 중복될 수 없다는 무결성 규칙은 무엇인가?',
    answer: '개체 무결성',
    explanation: '개체 무결성(Entity Integrity)은 테이블 내의 모든 튜플을 유일하게 식별할 수 있도록 기본키가 유효한 값을 가져야 함을 규정합니다.',
    difficulty: 'EASY',
    keywords: ['개체 무결성', 'Entity Integrity', '기본키규칙'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-integrity',
  },
  {
    id: 'EXP_DB2_028',
    subject: '데이터베이스구축',
    category: '데이터 무결성',
    type: 'SHORT_ANSWER',
    question: '자식 릴레이션의 외래키(Foreign Key) 값은 반드시 참조하는 부모 릴레이션의 기본키 값과 동일하거나 또는 NULL이어야 한다는 무결성 규칙은 무엇인가?',
    answer: '참조 무결성',
    explanation: '참조 무결성(Referential Integrity)은 존재하지 않는 부모 레코드를 참조하는 고아 레코드(Orphan Record)의 발생을 차단합니다.',
    difficulty: 'EASY',
    keywords: ['참조 무결성', 'Referential Integrity', '외래키규칙'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-integrity',
  },
  {
    id: 'EXP_DB2_029',
    subject: '데이터베이스구축',
    category: '데이터 무결성',
    type: 'SHORT_ANSWER',
    question: '테이블의 특정 속성에 입력되는 모든 값은 그 속성에 정의된 허용 데이터 타입, 길이, 허용 값 목록(도메인)에 속해야 한다는 무결성 규칙은 무엇인가?',
    answer: '도메인 무결성',
    explanation: '도메인 무결성(Domain Integrity)은 속성 값의 타입, 형식, 범위(예: 나이는 양수)를 검증합니다.',
    difficulty: 'EASY',
    keywords: ['도메인 무결성', 'Domain Integrity', '허용범위'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-integrity',
  },
  {
    id: 'EXP_DB2_030',
    subject: '데이터베이스구축',
    category: '데이터베이스 회복',
    type: 'SHORT_ANSWER',
    question: '트랜잭션 회복 연산 중 장애 발생 시 트랜잭션의 변경 작업이 시작된 이후의 로그 기록을 바탕으로 취소(취소하여 원래대로 되돌림)하는 연산은 무엇인가?',
    answer: 'UNDO',
    explanation: 'UNDO(취소)는 완료되지 못한 미완성 트랜잭션의 수정을 취소하여 이전 상태로 복구합니다. 이미 COMMIT된 작업을 재실행하는 것은 REDO(재실행)입니다.',
    difficulty: 'EASY',
    keywords: ['UNDO', '취소연산', '회복'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-recovery',
  },
  {
    id: 'EXP_DB2_031',
    subject: '데이터베이스구축',
    category: '데이터베이스 회복',
    type: 'SHORT_ANSWER',
    question: '트랜잭션 회복 연산 중 이미 성공적으로 COMMIT 완료된 트랜잭션의 변경 내용이 장애로 디스크에 반영되지 못했을 때 로그를 바탕으로 재실행하여 반영하는 연산은 무엇인가?',
    answer: 'REDO',
    explanation: 'REDO(재실행)는 커밋된 트랜잭션의 영속성을 보장하기 위해 로그를 읽어 변경 사항을 디스크에 다시 씁니다.',
    difficulty: 'EASY',
    keywords: ['REDO', '재실행연산', '영속성보장'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-recovery',
  },
  {
    id: 'EXP_DB2_032',
    subject: '데이터베이스구축',
    category: '데이터베이스 회복',
    type: 'SHORT_ANSWER',
    question: '회복 기법 중 트랜잭션 수행 도중에는 변경 내용을 로그 파일에만 기록해두고, 트랜잭션이 완전히 COMMIT된 이후에만 실제 데이터베이스 디스크에 반영하는 기법은 무엇인가?',
    answer: '지연 갱신 기법',
    explanation: '지연 갱신(Deferred Update) 기법은 커밋 전까지 디스크를 수정하지 않으므로 장애 시 UNDO가 필요 없고 오직 REDO 연산만 수행합니다.',
    difficulty: 'MEDIUM',
    keywords: ['지연 갱신 기법', 'Deferred Update', 'REDO만수행'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-recovery',
  },
  {
    id: 'EXP_DB2_033',
    subject: '데이터베이스구축',
    category: '데이터베이스 회복',
    type: 'SHORT_ANSWER',
    question: '회복 기법 중 트랜잭션 수행 도중 발생한 변경 결과를 디스크에 즉시 반영하되, 장애 발생 시 커밋되지 않은 트랜잭션은 로그를 통해 UNDO하는 기법은 무엇인가?',
    answer: '즉시 갱신 기법',
    explanation: '즉시 갱신(Immediate Update) 기법은 디스크가 즉시 갱신되므로 미완료 트랜잭션에 대해서는 UNDO, 완료된 트랜잭션에 대해서는 REDO가 모두 필요합니다.',
    difficulty: 'MEDIUM',
    keywords: ['즉시 갱신 기법', 'Immediate Update', 'REDO와UNDO'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-recovery',
  },
  {
    id: 'EXP_DB2_034',
    subject: '데이터베이스구축',
    category: '데이터베이스 회복',
    type: 'SHORT_ANSWER',
    question: '로그 파일의 전체를 처음부터 끝까지 검색하지 않도록 주기적으로 주기억장치의 버퍼 내용을 디스크에 강제 플러시하고 검사점을 기록하여 회복 시간을 단축하는 기법은 무엇인가?',
    answer: '체크포인트 회복 기법',
    explanation: '체크포인트(Checkpoint, 검사점) 회복 기법은 장애 시 가장 최근의 검사점 이후의 로그만 검사하여 불필요한 REDO/UNDO 작업을 대폭 줄입니다.',
    difficulty: 'EASY',
    keywords: ['체크포인트 회복 기법', '검사점', 'Checkpoint'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-recovery',
  },
  {
    id: 'EXP_DB2_035',
    subject: '데이터베이스구축',
    category: '병행 제어',
    type: 'SHORT_ANSWER',
    question: '로킹(Locking) 단위가 너무 클 때(예: 데이터베이스 전체 잠금) 병행성(동시성 수준)은 어떻게 되는가 (높아진다 / 낮아진다)?',
    answer: '낮아진다',
    explanation: '로킹 단위가 커지면 관리할 락의 수는 줄어 오버헤드는 감소하지만, 다른 트랜잭션들이 접근하지 못해 병행성(동시성)은 급격히 낮아집니다.',
    difficulty: 'EASY',
    keywords: ['낮아진다', '로킹단위', '병행성감소'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-concurrency',
  },
  {
    id: 'EXP_DB2_036',
    subject: '데이터베이스구축',
    category: '병행 제어',
    type: 'SHORT_ANSWER',
    question: '로킹 단위가 너무 작을 때(예: 레코드나 필드 단위 잠금) 시스템이 관리해야 할 락(Lock)의 총 개수와 오버헤드는 어떻게 되는가 (증가한다 / 감소한다)?',
    answer: '증가한다',
    explanation: '로킹 단위가 세밀해질수록 동시 처리성은 극대화되지만, 관리해야 할 락 테이블의 크기와 관리 오버헤드는 크게 증가합니다.',
    difficulty: 'EASY',
    keywords: ['증가한다', '로킹단위오버헤드'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-concurrency',
  },
  {
    id: 'EXP_DB2_037',
    subject: '데이터베이스구축',
    category: '병행 제어',
    type: 'SHORT_ANSWER',
    question: '공유 락(Shared Lock, S-Lock)이 걸려있는 데이터에 대해 다른 트랜잭션이 추가로 획득할 수 있는 락은 공유 락(S)인가 배타 락(X)인가?',
    answer: '공유 락',
    explanation: '공유 락은 읽기 전용 락으로 다른 트랜잭션의 동시 읽기(S-Lock)는 허용하지만, 데이터 수정을 위한 배타 락(Exclusive Lock, X-Lock)은 허용하지 않습니다.',
    difficulty: 'EASY',
    keywords: ['공유 락', 'Shared Lock', 'S-Lock호환성'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-concurrency',
  },
  {
    id: 'EXP_DB2_038',
    subject: '데이터베이스구축',
    category: '병행 제어',
    type: 'SHORT_ANSWER',
    question: '2단계 로킹 규약(2PL)에서 트랜잭션은 락을 새롭게 획득하기만 하고 해제는 절대 할 수 없는 단계를 무엇이라 하는가?',
    answer: '확장 단계',
    explanation: '2PL은 락을 획득만 하는 확장 단계(Growing Phase)와 락을 해제만 하는 축소 단계(Shrinking Phase)로 엄격히 구분됩니다.',
    difficulty: 'EASY',
    keywords: ['확장 단계', 'Growing Phase', '2PL'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-concurrency',
  },
  {
    id: 'EXP_DB2_039',
    subject: '데이터베이스구축',
    category: '분산 데이터베이스',
    type: 'SHORT_ANSWER',
    question: '분산 데이터베이스 투명성(Transparency) 중 사용자가 데이터베이스가 물리적으로 어느 지역의 어느 서버에 저장되어 있는지 알 필요 없이 논리적 이름만으로 접근할 수 있는 특성은 무엇인가?',
    answer: '위치 투명성',
    explanation: '위치 투명성(Location Transparency)은 사이트의 물리적 위치가 질의문에 영향을 주지 않는 특성입니다.',
    difficulty: 'EASY',
    keywords: ['위치 투명성', 'Location Transparency', '분산투명성'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-distributed',
  },
  {
    id: 'EXP_DB2_040',
    subject: '데이터베이스구축',
    category: '분산 데이터베이스',
    type: 'SHORT_ANSWER',
    question: '분산 데이터베이스 투명성 중 하나의 큰 테이블이 여러 세부 파티션 조각으로 나뉘어 여러 노드에 분산 저장되어 있더라도 사용자는 마치 단일 테이블인 것처럼 조회할 수 있는 특성은 무엇인가?',
    answer: '분할 투명성',
    explanation: '분할 투명성(Fragmentation Transparency)은 단편화 구조를 사용자로부터 은닉합니다.',
    difficulty: 'EASY',
    keywords: ['분할 투명성', 'Fragmentation Transparency', '단편화은닉'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-distributed',
  },
  {
    id: 'EXP_DB2_041',
    subject: '데이터베이스구축',
    category: '분산 데이터베이스',
    type: 'SHORT_ANSWER',
    question: '분산 데이터베이스 투명성 중 데이터의 성능과 신뢰성을 위해 동일한 데이터가 여러 사이트에 복제되어 상주하더라도 사용자는 단 하나의 사본만 존재하는 것처럼 사용하는 특성은 무엇인가?',
    answer: '복제 투명성',
    explanation: '복제 투명성(Replication Transparency)은 여러 복제본 간의 일관성 동기화 작업을 시스템이 백그라운드에서 처리합니다.',
    difficulty: 'EASY',
    keywords: ['복제 투명성', 'Replication Transparency', '사본관리'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-distributed',
  },
  {
    id: 'EXP_DB2_042',
    subject: '데이터베이스구축',
    category: '분산 데이터베이스',
    type: 'SHORT_ANSWER',
    question: '분산 데이터베이스 투명성 중 특정 노드의 서버나 통신 네트워크에 장애가 발생하더라도 전체 데이터베이스 시스템의 트랜잭션 무결성이 유지되는 특성은 무엇인가?',
    answer: '장애 투명성',
    explanation: '장애 투명성(Failure Transparency)은 국소적 하드웨어/통신 장애에도 불구하고 시스템이 올바르게 작업을 완수하도록 보장합니다.',
    difficulty: 'EASY',
    keywords: ['장애 투명성', 'Failure Transparency', '내고장성'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-distributed',
  },
  {
    id: 'EXP_DB2_043',
    subject: '데이터베이스구축',
    category: '분산 시스템 이론',
    type: 'SHORT_ANSWER',
    question: '에릭 브루어(Eric Brewer)의 CAP 정리에서 3대 특성 중 네트워크 분할 장애가 발생하더라도 정상 노드들이 즉시 응답을 반환할 수 있어야 한다는 가용성의 영문 약칭은 무엇인가?',
    answer: 'A',
    explanation: 'CAP 정리는 일관성(Consistency: C), 가용성(Availability: A), 분할 내구성(Partition Tolerance: P) 중 동시 2가지만 충족 가능함을 증명한 이론입니다.',
    difficulty: 'EASY',
    keywords: ['A', 'Availability', '가용성', 'CAP정리'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-nosql',
  },
  {
    id: 'EXP_DB2_044',
    subject: '데이터베이스구축',
    category: 'NoSQL 데이터베이스',
    type: 'SHORT_ANSWER',
    question: 'NoSQL 데이터 모델 중 Redis, Memcached처럼 가장 단순한 구조로 키와 값의 일대일 매핑만을 지원하여 초고속 조회가 가능한 유형은 무엇인가?',
    answer: 'Key-Value',
    explanation: 'Key-Value 모델은 데이터 구조가 가장 단순하여 캐싱 및 세션 저장소로 광범위하게 쓰입니다.',
    difficulty: 'EASY',
    keywords: ['Key-Value', '키값저장소', 'NoSQL유형'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-nosql',
  },
  {
    id: 'EXP_DB2_045',
    subject: '데이터베이스구축',
    category: 'NoSQL 데이터베이스',
    type: 'SHORT_ANSWER',
    question: 'NoSQL 데이터 모델 중 MongoDB, CouchDB처럼 JSON, BSON, XML 등의 유연한 계층형 문서 형식으로 데이터를 저장하고 검색하는 유형은 무엇인가?',
    answer: '문서형 데이터베이스',
    explanation: '문서형(Document Store) NoSQL은 스키마리스(Schema-less) 특성으로 복합 중첩 객체를 유연하게 저장합니다.',
    difficulty: 'EASY',
    keywords: ['문서형 데이터베이스', 'Document Store', 'MongoDB'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-nosql',
  },
  {
    id: 'EXP_DB2_046',
    subject: '데이터베이스구축',
    category: '반정규화',
    type: 'SHORT_ANSWER',
    question: '정규화된 시스템에서 빈번한 조인(Join)으로 인한 성능 저하를 해결하기 위해 시스템의 일관성을 일부 희생하고 의도적으로 중복, 병합을 수행하는 기법은 무엇인가?',
    answer: '반정규화',
    explanation: '반정규화(De-normalization, 역정규화)는 데이터 조회 성능 향상을 목적으로 테이블 병합, 컬럼 중복 등을 수행합니다.',
    difficulty: 'EASY',
    keywords: ['반정규화', '역정규화', '조인성능개선'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-denormalization',
  },
  {
    id: 'EXP_DB2_047',
    subject: '데이터베이스구축',
    category: '반정규화',
    type: 'SHORT_ANSWER',
    question: '반정규화 기법 중 한 테이블의 컬럼 수가 너무 많아(예: 100개 이상) 디스크 I/O 블록 경합이 발생할 때 컬럼 사용 빈도에 따라 테이블을 1:1로 수직 쪼개는 기법은 무엇인가?',
    answer: '테이블 수직 분할',
    explanation: '테이블 수직 분할(Vertical Partitioning)은 자주 조회되는 핵심 컬럼과 거의 조회되지 않는 컬럼을 분리하여 I/O 성능을 높입니다.',
    difficulty: 'MEDIUM',
    keywords: ['테이블 수직 분할', 'Vertical Partitioning', '반정규화'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-denormalization',
  },
  {
    id: 'EXP_DB2_048',
    subject: '데이터베이스구축',
    category: '반정규화',
    type: 'SHORT_ANSWER',
    question: '특정 테이블의 행(레코드) 수가 수천만 건에 달할 때 기간별 또는 지점별로 행 단위로 수평 쪼개어 별도의 테이블들로 분리하는 기법은 무엇인가?',
    answer: '테이블 수평 분할',
    explanation: '테이블 수평 분할(Horizontal Partitioning)은 행(레코드)을 기준으로 쪼개어 검색 범위를 축소시킵니다.',
    difficulty: 'EASY',
    keywords: ['테이블 수평 분할', 'Horizontal Partitioning', '반정규화'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-denormalization',
  },
  {
    id: 'EXP_DB2_049',
    subject: '데이터베이스구축',
    category: '데이터베이스 설계',
    type: 'SHORT_ANSWER',
    question: '데이터베이스의 상태를 변경시키는 작업의 논리적 기본 단위로, 원자성(A), 일관성(C), 격리성(I), 영속성(D)의 4대 특성을 갖는 개념은 무엇인가?',
    answer: '트랜잭션',
    explanation: '트랜잭션(Transaction)은 전부 실행되거나 전부 취소(All or Nothing)되어야 하는 작업의 완전한 논리 단위입니다.',
    difficulty: 'EASY',
    keywords: ['트랜잭션', 'Transaction', 'ACID'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-transaction',
  },
  {
    id: 'EXP_DB2_050',
    subject: '데이터베이스구축',
    category: '데이터베이스 설계',
    type: 'SHORT_ANSWER',
    question: '관계형 데이터베이스 릴레이션에서 속성(Attribute)들의 총 개수를 나타내는 용어는 무엇인가?',
    answer: '디그리',
    explanation: '디그리(Degree, 차수)는 속성의 개수입니다. 튜플(행)의 총 개수는 카디널리티(Cardinality, 기수)입니다.',
    difficulty: 'EASY',
    keywords: ['디그리', 'Degree', '차수', '속성수'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-theory',
  },
];
