import { Question } from '../../src/types/question';

export const BATCH_4_QUESTIONS: Question[] = [
  {
    id: 'EXP_SE2_001',
    subject: '소프트웨어설계',
    category: '시스템 연계',
    type: 'SHORT_ANSWER',
    question: 'EAI(엔터프라이즈 애플리케이션 통합) 구축 유형 중 단일 접점인 중앙 허브를 통해 시스템들을 통합하여 유지보수는 용이하지만 허브 장애 시 전체가 마비될 수 있는 중앙 집중형 토폴로지는 무엇인가?',
    answer: '허브 앤 스포크',
    explanation: '허브 앤 스포크(Hub & Spoke)는 중앙 허브가 모든 통신을 중개하므로 확장성이 좋지만 중앙 허브가 단일 실패 지점(SPOF)이 될 수 있습니다.',
    difficulty: 'EASY',
    keywords: ['허브 앤 스포크', 'Hub & Spoke', 'EAI'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-eai',
  },
  {
    id: 'EXP_SE2_002',
    subject: '소프트웨어설계',
    category: '시스템 연계',
    type: 'SHORT_ANSWER',
    question: 'EAI 구축 유형 중 애플리케이션 사이에 미들웨어 통신 버스를 두고 데이터 교환을 수행하여 뛰어난 확장성과 대용량 처리가 가능한 토폴로지는 무엇인가?',
    answer: '메시지 버스',
    explanation: '메시지 버스(Message Bus)는 공통 버스 파이프라인을 통해 각 애플리케이션 어댑터가 통신하며 ESB(Enterprise Service Bus)의 기반이 됩니다.',
    difficulty: 'MEDIUM',
    keywords: ['메시지 버스', 'Message Bus', 'EAI'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-eai',
  },
  {
    id: 'EXP_SE2_003',
    subject: '소프트웨어설계',
    category: '시스템 연계',
    type: 'SHORT_ANSWER',
    question: '웹 서비스(Web Services) 3대 표준 기술 중 웹 서비스의 위치, 제공하는 메서드, 매개변수 등을 XML 형식으로 기술한 서비스 기술 언어의 약칭은 무엇인가?',
    answer: 'WSDL',
    explanation: 'WSDL(Web Services Description Language)은 웹 서비스의 상세 사양을 XML로 명세합니다. 메시지 전송 규약은 SOAP, 등록/검색소는 UDDI입니다.',
    difficulty: 'EASY',
    keywords: ['WSDL', 'Web Services Description Language', '웹서비스'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-webservice',
  },
  {
    id: 'EXP_SE2_004',
    subject: '소프트웨어설계',
    category: '시스템 연계',
    type: 'SHORT_ANSWER',
    question: '웹 서비스 3대 표준 기술 중 HTTP, HTTPS 등의 전송 프로토콜을 통해 XML 기반의 메시지를 분산 환경에서 교환하기 위한 경량 통신 프로토콜의 약칭은 무엇인가?',
    answer: 'SOAP',
    explanation: 'SOAP(Simple Object Access Protocol)은 XML 기반 메시지 봉투(Envelope, Header, Body) 구조를 사용하여 원격 객체를 호출합니다.',
    difficulty: 'EASY',
    keywords: ['SOAP', 'Simple Object Access Protocol', '웹서비스'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-webservice',
  },
  {
    id: 'EXP_SE2_005',
    subject: '소프트웨어설계',
    category: '시스템 연계',
    type: 'SHORT_ANSWER',
    question: '웹 서비스 3대 표준 기술 중 전 세계의 비즈니스와 제공되는 웹 서비스 목록을 공개 등록하고 검색할 수 있는 XML 기반의 비즈니스 레지스트리(저장소) 규격의 약칭은 무엇인가?',
    answer: 'UDDI',
    explanation: 'UDDI(Universal Description, Discovery and Integration)는 웹 서비스의 전화번호부 역할을 하는 표준 등록 저장소입니다.',
    difficulty: 'EASY',
    keywords: ['UDDI', 'Universal Description Discovery and Integration', '웹서비스'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-webservice',
  },
  {
    id: 'EXP_SE2_006',
    subject: '소프트웨어설계',
    category: '시스템 연계',
    type: 'SHORT_ANSWER',
    question: 'REST 아키텍처 원칙 중 서버가 클라이언트의 이전 요청 상태(세션 등)를 보관하지 않고, 각 요청을 독립적으로 처리해야 한다는 원칙은 무엇인가?',
    answer: '무상태성',
    explanation: '무상태성(Statelessness)은 서버가 클라이언트 컨텍스트를 저장하지 않음으로써 서버의 수평 확장성(Scale-out)을 극대화합니다.',
    difficulty: 'EASY',
    keywords: ['무상태성', 'Stateless', 'REST원칙'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-rest',
  },
  {
    id: 'EXP_SE2_007',
    subject: '소프트웨어설계',
    category: '시스템 연계',
    type: 'SHORT_ANSWER',
    question: 'RESTful API에서 리소스의 고유 식별자로 사용하는 URI와 함께, 리소스의 조회(Read) 작업을 요청할 때 사용하는 HTTP 표준 메서드는 무엇인가?',
    answer: 'GET',
    explanation: 'GET은 리소스 조회 메서드로 멱등성(Idempotency)과 안전성을 가집니다. 생성을 요청할 때는 POST를 씁니다.',
    difficulty: 'EASY',
    keywords: ['GET', 'HTTP메서드', 'RESTful'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-rest',
  },
  {
    id: 'EXP_SE2_008',
    subject: '소프트웨어설계',
    category: '시스템 연계',
    type: 'SHORT_ANSWER',
    question: 'RESTful API에서 기존 리소스의 전체 내용을 새로운 데이터로 교체(치환)하여 갱신할 때 사용하는 멱등성을 가진 HTTP 메서드는 무엇인가?',
    answer: 'PUT',
    explanation: 'PUT은 전체 리소스 교체 갱신 메서드이며 멱등성을 만족합니다. 리소스의 일부 속성만 부분 수정할 때는 PATCH를 사용합니다.',
    difficulty: 'EASY',
    keywords: ['PUT', 'HTTP메서드', '리소스갱신'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-rest',
  },
  {
    id: 'EXP_SE2_009',
    subject: '소프트웨어설계',
    category: '시스템 연계',
    type: 'SHORT_ANSWER',
    question: 'RESTful API에서 기존 리소스의 특정 필드나 일부 속성만을 선택적으로 수정할 때 사용하는 HTTP 메서드는 무엇인가?',
    answer: 'PATCH',
    explanation: 'PATCH는 리소스의 부분 변경(Partial Modification)을 수행하는 HTTP 메서드입니다.',
    difficulty: 'MEDIUM',
    keywords: ['PATCH', 'HTTP메서드', '부분수정'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-rest',
  },
  {
    id: 'EXP_SE2_010',
    subject: '소프트웨어설계',
    category: '시스템 연계',
    type: 'SHORT_ANSWER',
    question: '속성과 값의 쌍(Key-Value)으로 데이터를 표현하며 XML보다 용량이 작고 웹과 모바일 환경에서 널리 쓰이는 경량 데이터 교환 포맷의 약칭은 무엇인가?',
    answer: 'JSON',
    explanation: 'JSON(JavaScript Object Notation)은 인간이 읽기 쉽고 파싱 속도가 빠른 표준 텍스트 데이터 교환 형식입니다.',
    difficulty: 'EASY',
    keywords: ['JSON', 'JavaScript Object Notation', '데이터교환'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-dataformat',
  },
  {
    id: 'EXP_SE2_011',
    subject: '소프트웨어설계',
    category: '미들웨어',
    type: 'SHORT_ANSWER',
    question: '미들웨어 종류 중 분산 환경에서 송수신자 간에 큐(Queue) 방식의 비동기 메시지 전달을 지원하는 메시지 지향 미들웨어의 약칭은 무엇인가?',
    answer: 'MOM',
    explanation: 'MOM(Message-Oriented Middleware)은 비동기 큐잉을 통해 분산 시스템 간의 결합도를 낮추고 신뢰성 있는 메시지 전달을 보장합니다.',
    difficulty: 'MEDIUM',
    keywords: ['MOM', 'Message-Oriented Middleware', '비동기큐'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-middleware',
  },
  {
    id: 'EXP_SE2_012',
    subject: '소프트웨어설계',
    category: '미들웨어',
    type: 'SHORT_ANSWER',
    question: '미들웨어 종류 중 은행 결제나 항공 예약처럼 대규모 트랜잭션의 원자성과 무결성을 보장하고 부하 분산을 제어하는 트랜잭션 처리 모니터의 약칭은 무엇인가?',
    answer: 'TP-Monitor',
    explanation: 'TP-Monitor(Transaction Processing Monitor)는 대규모 분산 트랜잭션을 감시하고 ACID 속성을 엄격히 보장합니다.',
    difficulty: 'MEDIUM',
    keywords: ['TP-Monitor', '트랜잭션모니터', '미들웨어'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-middleware',
  },
  {
    id: 'EXP_SE2_013',
    subject: '소프트웨어설계',
    category: '미들웨어',
    type: 'SHORT_ANSWER',
    question: '미들웨어 종류 중 원격 네트워크 상의 컴퓨터에 위치한 프로시저나 함수를 로컬 컴퓨터의 함수처럼 원격 호출할 수 있게 해주는 기술의 약칭은 무엇인가?',
    answer: 'RPC',
    explanation: 'RPC(Remote Procedure Call, 원격 프로시저 호출)는 네트워크 세부 프로토콜을 숨기고 원격 함수를 손쉽게 호출하게 합니다.',
    difficulty: 'EASY',
    keywords: ['RPC', 'Remote Procedure Call', '원격함수호출'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-middleware',
  },
  {
    id: 'EXP_SE2_014',
    subject: '소프트웨어설계',
    category: '미들웨어',
    type: 'SHORT_ANSWER',
    question: '클라이언트의 요청을 받아 동적인 비즈니스 로직을 처리하고 데이터베이스와의 연동을 전담하는 서버 측 소프트웨어 인프라(예: 톰캣, 웹로직 등)의 약칭은 무엇인가?',
    answer: 'WAS',
    explanation: 'WAS(Web Application Server)는 정적 페이지만을 제공하는 일반 웹 서버(Apache 등)와 달리 비즈니스 로직과 서블릿 컨테이너를 구동합니다.',
    difficulty: 'EASY',
    keywords: ['WAS', 'Web Application Server', '웹애플리케이션서버'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-middleware',
  },
  {
    id: 'EXP_SE2_015',
    subject: '소프트웨어설계',
    category: '비용 산정',
    type: 'SHORT_ANSWER',
    question: '보헴(Boehm)이 제안한 COCOMO 모형의 소프트웨어 개발 유형 중 기관 내부 업무용 소프트웨어로 규모가 5만 라인(50 KDSI) 이하인 소규모 프로젝트 유형은 무엇인가?',
    answer: '조직형',
    explanation: '조직형(Organic Mode)은 경험 많은 팀이 친숙한 환경에서 개발하는 5만 라인 이하의 소규모 개발 유형입니다.',
    difficulty: 'EASY',
    keywords: ['조직형', 'Organic Mode', 'COCOMO'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-cost',
  },
  {
    id: 'EXP_SE2_016',
    subject: '소프트웨어설계',
    category: '비용 산정',
    type: 'SHORT_ANSWER',
    question: 'COCOMO 모형의 소프트웨어 개발 유형 중 트랜잭션 처리 시스템이나 OS처럼 30만 라인(300 KDSI) 이하의 중간 규모 개발 유형은 무엇인가?',
    answer: '반분리형',
    explanation: '반분리형(Semi-detached Mode)은 중간 수준의 규모와 복잡도를 가진 프로젝트 유형입니다.',
    difficulty: 'EASY',
    keywords: ['반분리형', 'Semi-detached Mode', 'COCOMO'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-cost',
  },
  {
    id: 'EXP_SE2_017',
    subject: '소프트웨어설계',
    category: '비용 산정',
    type: 'SHORT_ANSWER',
    question: 'COCOMO 모형의 소프트웨어 개발 유형 중 항공기 제어, 원자력 시스템처럼 엄격한 하드웨어 제약 조건과 30만 라인 이상의 대규모 시스템 개발 유형은 무엇인가?',
    answer: '내장형',
    explanation: '내장형(Embedded Mode)은 극도의 신뢰성과 하드웨어 종속성을 요구하는 초대형 임베디드 프로젝트 유형입니다.',
    difficulty: 'EASY',
    keywords: ['내장형', 'Embedded Mode', 'COCOMO'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-cost',
  },
  {
    id: 'EXP_SE2_018',
    subject: '소프트웨어설계',
    category: '비용 산정',
    type: 'SHORT_ANSWER',
    question: '소프트웨어 생명주기 전 과정에서 소요되는 인력의 노력 분포를 레일리-노든(Rayleigh-Norden) 곡선에 기초하여 예측하는 비용 산정 모형은 무엇인가?',
    answer: 'Putnam 모형',
    explanation: '푸트남(Putnam) 모형은 시간에 따른 인력 소요 곡선(Rayleigh-Norden)을 기초로 하며 대표 자동화 추정 도구로 SLIM이 있습니다.',
    difficulty: 'MEDIUM',
    keywords: ['Putnam 모형', '푸트남모형', '레일리노든곡선'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-cost',
  },
  {
    id: 'EXP_SE2_019',
    subject: '소프트웨어설계',
    category: '비용 산정',
    type: 'SHORT_ANSWER',
    question: '알브레히트(Albrecht)가 제안한 기능점수(FP) 기법에서 시스템 내부에서 유지 관리되는 사용자 식별 가능한 논리적 데이터 그룹을 가리키는 측정 요소의 약칭은 무엇인가?',
    answer: 'ILF',
    explanation: 'ILF(Internal Logical File, 내부 논리 파일)는 애플리케이션 경계 내부에서 관리되는 데이터 그룹입니다. 타 시스템에서 참조만 하는 것은 EIF(External Interface File)입니다.',
    difficulty: 'MEDIUM',
    keywords: ['ILF', 'Internal Logical File', '내부논리파일'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-cost',
  },
  {
    id: 'EXP_SE2_020',
    subject: '소프트웨어설계',
    category: '비용 산정',
    type: 'SHORT_ANSWER',
    question: '기능점수(FP) 기법에서 타 시스템에서 관리되지만 본 시스템이 참조(읽기) 목적으로 사용하는 외부 논리 파일 그룹의 약칭은 무엇인가?',
    answer: 'EIF',
    explanation: 'EIF(External Interface File, 외부 연계 파일)는 타 애플리케이션의 데이터를 인터페이스로 참조할 때 측정합니다.',
    difficulty: 'MEDIUM',
    keywords: ['EIF', 'External Interface File', '외부연계파일'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-cost',
  },
  {
    id: 'EXP_SE2_021',
    subject: '소프트웨어설계',
    category: '비용 산정',
    type: 'SHORT_ANSWER',
    question: '기능점수(FP) 트랜잭션 기능 중 외부에서 들어온 데이터나 제어 정보를 처리하여 내부 논리 파일(ILF)을 등록, 수정, 삭제하는 기능 요소의 약칭은 무엇인가?',
    answer: 'EI',
    explanation: 'EI(External Input, 외부 입력)는 사용자나 타 시스템이 데이터를 입력하여 시스템 내부 상태를 갱신하는 기능입니다.',
    difficulty: 'MEDIUM',
    keywords: ['EI', 'External Input', '외부입력'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-cost',
  },
  {
    id: 'EXP_SE2_022',
    subject: '소프트웨어설계',
    category: '비용 산정',
    type: 'SHORT_ANSWER',
    question: '기능점수(FP) 트랜잭션 기능 중 단순히 데이터를 검색하여 화면에 표시하되 계산이나 수학적 공식 가공 없이 그대로 조회하는 기능의 약칭은 무엇인가?',
    answer: 'EQ',
    explanation: 'EQ(External InQuiry, 외부 조회)는 계산 로직 없이 데이터를 찾아 반환합니다. 계산 로직이나 통계 파생 데이터가 포함되면 EO(External Output)입니다.',
    difficulty: 'MEDIUM',
    keywords: ['EQ', 'External Inquiry', '외부조회'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-cost',
  },
  {
    id: 'EXP_SE2_023',
    subject: '소프트웨어설계',
    category: '비용 산정',
    type: 'SHORT_ANSWER',
    question: '소프트웨어 개발 프로젝트에서 총 30,000 라인의 코드를 개발하려 할 때, 개발자 1명의 월간 생산성이 1,000 라인이라면 필요한 노력 인월(Man-Month) 수는 얼마인가?',
    answer: '30',
    explanation: 'Man-Month = 총 라인수(30,000) / 1인당 월 생산성(1,000) = 30 인월(M/M)입니다.',
    difficulty: 'EASY',
    keywords: ['30', 'Man-Month', '비용산정계산'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-cost',
  },
  {
    id: 'EXP_SE2_024',
    subject: '소프트웨어설계',
    category: '비용 산정',
    type: 'SHORT_ANSWER',
    question: '총 개발 노력이 50 Man-Month로 추정된 프로젝트에 5명의 개발자를 전담 투입한다면 프로젝트 소요 기간(개월)은 얼마인가?',
    answer: '10',
    explanation: '개발 기간 = 총 노력(50 M/M) / 투입 인원(5명) = 10개월입니다.',
    difficulty: 'EASY',
    keywords: ['10', '개발기간', 'Man-Month'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-cost',
  },
  {
    id: 'EXP_SE2_025',
    subject: '소프트웨어설계',
    category: '일정 관리',
    type: 'SHORT_ANSWER',
    question: '네트워크 기반 일정 관리 기법 중 프로젝트의 시작부터 종료까지의 모든 작업 경로 중 가장 긴 소요 시간이 걸리는 경로를 가리키는 용어는 무엇인가?',
    answer: '임계 경로',
    explanation: '임계 경로(Critical Path, 임계선)는 총 여유 시간(Float)이 0인 핵심 작업들의 경로로, 이 경로상의 작업이 하루라도 지연되면 전체 프로젝트 완료 일정이 지연됩니다.',
    difficulty: 'EASY',
    keywords: ['임계 경로', 'Critical Path', 'CPM'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-schedule',
  },
  {
    id: 'EXP_SE2_026',
    subject: '소프트웨어설계',
    category: '일정 관리',
    type: 'SHORT_ANSWER',
    question: '프로젝트 일정 계획 수립 도구 중 각 작업들의 시작일과 완료일을 수평 막대 그래프 형태로 표현하여 작업의 진행 상황을 한눈에 파악할 수 있는 차트는 무엇인가?',
    answer: '간트 차트',
    explanation: '간트 차트(Gantt Chart, 바 차트)는 시간 축에 따른 작업들의 일정과 진척도를 막대 형태로 시각화합니다.',
    difficulty: 'EASY',
    keywords: ['간트 차트', 'Gantt Chart', '일정관리차트'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-schedule',
  },
  {
    id: 'EXP_SE2_027',
    subject: '소프트웨어설계',
    category: '일정 관리',
    type: 'SHORT_ANSWER',
    question: 'PERT 일정 계산에서 비결정적 작업 기간을 산정하기 위해 활용하는 3점 추정치는 낙관치(a), 최빈치(m), 그리고 어떤 예측치인가?',
    answer: '비관치',
    explanation: 'PERT는 3점 추정치인 낙관치(a), 최빈치(m, 기대치), 비관치(b)를 이용해 기댓값 = (a + 4m + b) / 6 공식을 적용합니다.',
    difficulty: 'EASY',
    keywords: ['비관치', 'PERT', '3점추정'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-schedule',
  },
  {
    id: 'EXP_SE2_028',
    subject: '소프트웨어설계',
    category: '일정 관리',
    type: 'SHORT_ANSWER',
    question: '프로젝트 일정 지연을 만회하기 위해 추가 인력을 집중 투입하거나 야근, 외주 비용을 투입하여 임계 경로상의 작업 기간을 단축하는 기법은 무엇인가?',
    answer: '크래싱',
    explanation: '크래싱(Crashing, 공정 압축법)은 추가 자원을 투입해 일정을 줄이는 기법으로 비용 증가 위험이 있습니다. 순차 작업을 병렬로 겹쳐 수행하는 것은 패스트 트래킹(Fast-Tracking)입니다.',
    difficulty: 'MEDIUM',
    keywords: ['크래싱', 'Crashing', '일정단축기법'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-schedule',
  },
  {
    id: 'EXP_SE2_029',
    subject: '소프트웨어설계',
    category: '일정 관리',
    type: 'SHORT_ANSWER',
    question: '원래 순차적으로 진행되어야 할 후속 작업들을 앞당겨 선행 작업과 동시에 병렬로 진행시킴으로써 일정 기간을 단축하는 기법은 무엇인가?',
    answer: '패스트 트래킹',
    explanation: '패스트 트래킹(Fast Tracking, 공정 중첩법)은 비용은 추가되지 않지만 재작업(Rework) 위험이 커집니다.',
    difficulty: 'MEDIUM',
    keywords: ['패스트 트래킹', 'Fast Tracking', '공정중첩법'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-schedule',
  },
  {
    id: 'EXP_SE2_030',
    subject: '소프트웨어설계',
    category: '소프트웨어 공학',
    type: 'SHORT_ANSWER',
    question: '지연되는 소프트웨어 개발 프로젝트에 새로운 인력을 뒤늦게 추가 투입하는 것은 의사소통 비용을 폭증시켜 프로젝트를 더 지연시킬 뿐이라는 법칙은 무엇인가?',
    answer: '브룩스의 법칙',
    explanation: '브룩스의 법칙(Brooks\' Law)은 신규 인력 교육 및 커뮤니케이션 오버헤드로 인해 프로젝트가 더욱 지연된다는 경험적 법칙입니다.',
    difficulty: 'EASY',
    keywords: ['브룩스의 법칙', 'Brooks Law', '인력투입지연'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-laws',
  },
  {
    id: 'EXP_SE2_031',
    subject: '소프트웨어설계',
    category: '요구사항',
    type: 'SHORT_ANSWER',
    question: '요구사항 분석 도구인 자료 흐름도(DFD)에서 데이터의 처리 및 변환 과정을 나타내는 기호의 도형 모양은 무엇인가?',
    answer: '원',
    explanation: 'DFD에서 프로세스(처리기)는 원(○), 자료 흐름은 화살표(→), 자료 저장소는 평행선(=), 단말(외부 엔티티)은 사각형(□)으로 표기합니다.',
    difficulty: 'EASY',
    keywords: ['원', 'DFD', '프로세스기호'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-requirements',
  },
  {
    id: 'EXP_SE2_032',
    subject: '소프트웨어설계',
    category: '요구사항',
    type: 'SHORT_ANSWER',
    question: '자료 흐름도(DFD)에서 데이터가 저장되어 있는 파일이나 데이터베이스 같은 자료 저장소를 나타내는 기호의 형태는 무엇인가?',
    answer: '평행선',
    explanation: '자료 저장소(Data Store)는 두 줄의 평행선(=)으로 표현합니다.',
    difficulty: 'EASY',
    keywords: ['평행선', '자료저장소', 'DFD기호'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-requirements',
  },
  {
    id: 'EXP_SE2_033',
    subject: '소프트웨어설계',
    category: '요구사항',
    type: 'SHORT_ANSWER',
    question: '자료 흐름도(DFD)에 등장하는 모든 데이터 항목, 데이터 흐름, 저장소의 정의를 체계적으로 정리하여 누구나 동일하게 이해하도록 만든 사전을 무엇이라 하는가?',
    answer: '자료 사전',
    explanation: '자료 사전(DD, Data Dictionary)은 메타데이터의 집합체로 정의 기호(=, +, {}, [], (), **)를 사용해 데이터의 의미와 구조를 명세합니다.',
    difficulty: 'EASY',
    keywords: ['자료 사전', 'Data Dictionary', '자료흐름도'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-requirements',
  },
  {
    id: 'EXP_SE2_034',
    subject: '소프트웨어설계',
    category: '요구사항',
    type: 'SHORT_ANSWER',
    question: '자료 사전(Data Dictionary) 작성 시 특정 데이터 항목의 0회 이상 무한 반복(Repetition)을 나타낼 때 사용하는 기호는 무엇인가?',
    answer: '{}',
    explanation: '중괄호 {}는 반복을 의미합니다. 대괄호 []는 선택, 소괄호 ()는 생략 가능(선택적), 등호 =는 정의, 플러스 +는 연결을 나타냅니다.',
    difficulty: 'EASY',
    keywords: ['{}', '중괄호', '자료사전기호', '반복'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-requirements',
  },
  {
    id: 'EXP_SE2_035',
    subject: '소프트웨어설계',
    category: '요구사항',
    type: 'SHORT_ANSWER',
    question: '자료 사전(Data Dictionary) 기호 중 나열된 여러 데이터 항목 중 오직 하나만을 택하는 선택(Selection)을 표현할 때 사용하는 기호는 무엇인가?',
    answer: '[]',
    explanation: '대괄호 [A | B | C]는 목록 중 하나를 선택함을 의미합니다.',
    difficulty: 'EASY',
    keywords: ['[]', '대괄호', '자료사전기호', '선택'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-requirements',
  },
  {
    id: 'EXP_SE2_036',
    subject: '소프트웨어설계',
    category: '요구사항',
    type: 'SHORT_ANSWER',
    question: '자료 사전(Data Dictionary) 기호 중 데이터 항목이 있을 수도 있고 없을 수도 있음을 나타내는 생략 가능(Optional) 기호는 무엇인가?',
    answer: '()',
    explanation: '소괄호 ()는 해당 항목이 선택적으로 생략 가능함을 나타냅니다.',
    difficulty: 'EASY',
    keywords: ['()', '소괄호', '자료사전기호', '생략'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-requirements',
  },
  {
    id: 'EXP_SE2_037',
    subject: '소프트웨어설계',
    category: '인터페이스 설계',
    type: 'SHORT_ANSWER',
    question: '인터페이스 보안을 위해 통신 구간의 암호화를 제공하는 표준 보안 프로토콜로, HTTP의 80번 포트 대신 443번 포트를 사용하는 기술은 무엇인가?',
    answer: 'HTTPS',
    explanation: 'HTTPS는 HTTP에 SSL/TLS 보안 계층을 결합하여 데이터의 도청과 변조를 방지합니다.',
    difficulty: 'EASY',
    keywords: ['HTTPS', 'SSL/TLS', '443번포트'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-interface',
  },
  {
    id: 'EXP_SE2_038',
    subject: '소프트웨어설계',
    category: '인터페이스 설계',
    type: 'SHORT_ANSWER',
    question: '네트워크 통신 계층 중 IP 계층에서 보안 서비스를 제공하여 패킷의 기밀성, 무결성, 인증을 보장하는 표준 프로토콜 세트의 명칭은 무엇인가?',
    answer: 'IPsec',
    explanation: 'IPsec은 네트워크 계층(L3)에서 AH(인증)와 ESP(암호화/기밀성) 프로토콜을 사용해 안전한 터널링을 구축합니다.',
    difficulty: 'EASY',
    keywords: ['IPsec', 'IP보안프로토콜', 'AH', 'ESP'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-interface',
  },
  {
    id: 'EXP_SE2_039',
    subject: '소프트웨어설계',
    category: '시스템 연계',
    type: 'SHORT_ANSWER',
    question: '웹 브라우저와 웹 서버 간에 별도의 추가 연결 수립 없이 단일 TCP 연결 상에서 실시간 전이중(Full-Duplex) 양방향 통신을 제공하는 프로토콜은 무엇인가?',
    answer: '웹소켓',
    explanation: '웹소켓(WebSocket, ws://)은 핸드셰이크 후 지속적인 양방향 채널을 열어 채팅이나 실시간 데이터 스트리밍에 사용됩니다.',
    difficulty: 'EASY',
    keywords: ['웹소켓', 'WebSocket', '전이중양방향통신'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-interface',
  },
  {
    id: 'EXP_SE2_040',
    subject: '소프트웨어설계',
    category: '소프트웨어 공학',
    type: 'SHORT_ANSWER',
    question: '소프트웨어 프로젝트 관리를 구성하는 3대 핵심 관리 요소(3P)는 People(인력), Problem(문제), 그리고 무엇인가?',
    answer: 'Process',
    explanation: '프로젝트 관리의 3P는 People(사람), Problem(문제/목표), Process(절차/과정)입니다.',
    difficulty: 'EASY',
    keywords: ['Process', '프로세스', '3P', '프로젝트관리'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-management',
  },
  {
    id: 'EXP_SE2_041',
    subject: '소프트웨어설계',
    category: '소프트웨어 공학',
    type: 'SHORT_ANSWER',
    question: '폭포수 모델의 선형 순차적 접근 방식의 단점을 보완하여 프로젝트 전체 범위를 계층적으로 분할하고(Work Breakdown Structure) 관리하는 도구의 약칭은 무엇인가?',
    answer: 'WBS',
    explanation: 'WBS(Work Breakdown Structure, 작업 분할 구조도)는 프로젝트의 전체 목표를 달성 가능한 소규모 작업 패키지로 계층 분할합니다.',
    difficulty: 'EASY',
    keywords: ['WBS', 'Work Breakdown Structure', '작업분할구조도'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-management',
  },
  {
    id: 'EXP_SE2_042',
    subject: '소프트웨어설계',
    category: '소프트웨어 개발 모델',
    type: 'SHORT_ANSWER',
    question: '보헴(Boehm)이 제안한 소프트웨어 개발 모델로, 폭포수와 프로토타입의 장점을 수용하고 계획 수립 → 위험 분석 → 개발 및 검증 → 고객 평가의 4단계를 점진적으로 반복하는 모델은 무엇인가?',
    answer: '나선형 모델',
    explanation: '나선형 모델(Spiral Model)의 가장 핵심적인 특징은 나선을 돌 때마다 "위험 분석(Risk Analysis)"을 집중 수행한다는 점입니다.',
    difficulty: 'EASY',
    keywords: ['나선형 모델', 'Spiral Model', '위험분석'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-sdlc',
  },
  {
    id: 'EXP_SE2_043',
    subject: '소프트웨어설계',
    category: '소프트웨어 개발 모델',
    type: 'SHORT_ANSWER',
    question: '고전적 소프트웨어 개발 모델 중 요구사항 분석부터 유지보수까지 각 단계가 이전 단계의 완료를 전제로 엄격히 순차 진행되는 가장 오래된 모델은 무엇인가?',
    answer: '폭포수 모델',
    explanation: '폭포수 모델(Waterfall Model)은 하향식 순차 진행 모델로, 문서화가 잘 되지만 요구사항 변경 수용이 어렵습니다.',
    difficulty: 'EASY',
    keywords: ['폭포수 모델', 'Waterfall Model', '순차적모델'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-sdlc',
  },
  {
    id: 'EXP_SE2_044',
    subject: '소프트웨어설계',
    category: '애자일',
    type: 'SHORT_ANSWER',
    question: 'XP(eXtreme Programming)의 12대 기본 실천 사항 중 모든 비즈니스 로직에 대해 실제 구현 코드를 작성하기 전에 실패하는 자동화 테스트 케이스를 먼저 작성하는 기법의 약칭은 무엇인가?',
    answer: 'TDD',
    explanation: 'TDD(Test-Driven Development, 테스트 주도 개발)는 "Red(실패) → Green(통과) → Refactor(개선)" 주기를 반복합니다.',
    difficulty: 'EASY',
    keywords: ['TDD', 'Test-Driven Development', '테스트주도개발'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-agile',
  },
  {
    id: 'EXP_SE2_045',
    subject: '소프트웨어설계',
    category: '애자일',
    type: 'SHORT_ANSWER',
    question: 'XP의 12대 기본 실천 사항 중 두 명의 개발자가 한 컴퓨터에 나란히 앉아 한 명은 코드를 작성하고(드라이버) 다른 한 명은 코드를 검토하는(내비게이터) 기법은 무엇인가?',
    answer: '페어 프로그래밍',
    explanation: '페어 프로그래밍(Pair Programming, 짝 프로그래밍)은 코드 품질을 즉시 향상시키고 팀 내 지식 공유를 극대화합니다.',
    difficulty: 'EASY',
    keywords: ['페어 프로그래밍', 'Pair Programming', '짝프로그래밍'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-agile',
  },
  {
    id: 'EXP_SE2_046',
    subject: '소프트웨어설계',
    category: '애자일',
    type: 'SHORT_ANSWER',
    question: 'XP의 12대 기본 실천 사항 중 개발자가 작업한 소스코드를 하루에도 수차례씩 중앙 공유 리포지토리에 지속적으로 빌드하고 통합하는 원칙의 약칭은 무엇인가?',
    answer: 'CI',
    explanation: '지속적 통합(CI, Continuous Integration)은 빈번한 머지와 자동 빌드/테스트를 통해 통합 지옥(Integration Hell)을 방지합니다.',
    difficulty: 'EASY',
    keywords: ['CI', 'Continuous Integration', '지속적통합'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-agile',
  },
  {
    id: 'EXP_SE2_047',
    subject: '소프트웨어설계',
    category: '인터페이스 설계',
    type: 'SHORT_ANSWER',
    question: '인터페이스 설계 시 분산 시스템 컴포넌트 간에 동기적 방식이 아닌 큐를 통해 송신자와 수신자의 실행 타이밍을 분리하는 통신 방식을 무엇이라 하는가?',
    answer: '비동기 통신',
    explanation: '비동기(Asynchronous) 통신은 송신자가 응답을 기다리지 않고 다음 작업을 즉시 수행할 수 있어 시스템 처리량이 높아집니다.',
    difficulty: 'EASY',
    keywords: ['비동기 통신', 'Asynchronous', '메시지큐'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-interface',
  },
  {
    id: 'EXP_SE2_048',
    subject: '소프트웨어설계',
    category: '소프트웨어 공학',
    type: 'SHORT_ANSWER',
    question: '소프트웨어 개발 프로젝트의 조직 형태 중 소프트웨어 프로젝트가 완료되면 해산되는 임시 TF팀 형태로 프로젝트 관리자에게 전권이 부여되는 조직 구조는 무엇인가?',
    answer: '프로젝트형 조직',
    explanation: '프로젝트형 조직(Projectized Organization)은 PM에게 자원과 예산의 통제 전권이 있으며 프로젝트 집중도가 높습니다. 부서별 기능 전문성을 유지하는 것은 기능형 조직입니다.',
    difficulty: 'MEDIUM',
    keywords: ['프로젝트형 조직', 'Projectized', '조직구조'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-management',
  },
  {
    id: 'EXP_SE2_049',
    subject: '소프트웨어설계',
    category: '소프트웨어 공학',
    type: 'SHORT_ANSWER',
    question: '기존 기능 조직의 수직적 전문성과 프로젝트 조직의 수평적 유연성을 결합하여 팀원이 원래 부서와 프로젝트 양쪽에 소속되는 하이브리드 조직 형태는 무엇인가?',
    answer: '매트릭스 조직',
    explanation: '매트릭스 조직(Matrix Organization)은 팀원이 기능 부서장과 프로젝트 관리자 2명에게 이중 보고하는 구조를 갖습니다.',
    difficulty: 'MEDIUM',
    keywords: ['매트릭스 조직', 'Matrix Organization', '이중보고'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-management',
  },
  {
    id: 'EXP_SE2_050',
    subject: '소프트웨어설계',
    category: '소프트웨어 공학',
    type: 'SHORT_ANSWER',
    question: '소프트웨어 제품의 라이프사이클 전반에 걸쳐 요구사항 명세서, 소스코드, 테스트 케이스 간의 일관성과 추적 가능성을 보장하기 위해 작성하는 표를 무엇이라 하는가?',
    answer: '추적성 매트릭스',
    explanation: '추적성 매트릭스(Traceability Matrix, RTM)는 요구사항이 설계, 구현, 테스트 케이스로 온전히 누락 없이 연결되었는지 교차 추적합니다.',
    difficulty: 'MEDIUM',
    keywords: ['추적성 매트릭스', 'Traceability Matrix', 'RTM'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-management',
  },
];
