import { Question } from '../../src/types/question';

export const BATCH_8_QUESTIONS: Question[] = [
  {
    id: 'EXP_NET_001',
    subject: '신기술/보안',
    category: '네트워크 프로토콜',
    type: 'SHORT_ANSWER',
    question: '논리적인 IP 주소를 컴퓨터 네트워크 카드의 물리적인 하드웨어 MAC 주소로 변환해 주는 프로토콜의 약칭은 무엇인가?',
    answer: 'ARP',
    explanation: 'ARP(Address Resolution Protocol)는 브로드캐스트 질의를 통해 상대방의 MAC 주소를 알아냅니다. 반대로 MAC으로 IP를 찾는 것은 RARP입니다.',
    difficulty: 'EASY',
    keywords: ['ARP', 'Address Resolution Protocol', 'MAC주소변환'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-protocols',
  },
  {
    id: 'EXP_NET_002',
    subject: '신기술/보안',
    category: '네트워크 프로토콜',
    type: 'SHORT_ANSWER',
    question: '하드디스크가 없는 디스크리스 컴퓨터가 부팅 시 자신의 MAC 주소를 이용해 서버로부터 IP 주소를 요청할 때 사용하는 역주소 변환 프로토콜의 약칭은 무엇인가?',
    answer: 'RARP',
    explanation: 'RARP(Reverse ARP)는 물리 주소를 IP 주소로 매핑합니다. 현대에는 DHCP와 BOOTP로 대체되었습니다.',
    difficulty: 'EASY',
    keywords: ['RARP', 'Reverse ARP', '역주소변환'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-protocols',
  },
  {
    id: 'EXP_NET_003',
    subject: '신기술/보안',
    category: '네트워크 프로토콜',
    type: 'SHORT_ANSWER',
    question: 'IP 프로토콜의 비신뢰적인 데이터그램 전송을 보완하여 네트워크 에러 보고 및 전송 상태 진단(Ping, Traceroute)에 사용되는 프로토콜의 약칭은 무엇인가?',
    answer: 'ICMP',
    explanation: 'ICMP(Internet Control Message Protocol)는 에러 메시지(도달 불가, 시간 초과 등)를 발신지 IP로 전송합니다.',
    difficulty: 'EASY',
    keywords: ['ICMP', 'Internet Control Message Protocol', 'Ping'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-protocols',
  },
  {
    id: 'EXP_NET_004',
    subject: '신기술/보안',
    category: '네트워크 프로토콜',
    type: 'SHORT_ANSWER',
    question: 'IP 멀티캐스트 호스트가 자신이 속한 멀티캐스트 그룹의 가입, 유지, 탈퇴 정보를 인접한 라우터에 알리기 위해 사용하는 프로토콜의 약칭은 무엇인가?',
    answer: 'IGMP',
    explanation: 'IGMP(Internet Group Management Protocol)는 멀티캐스트 수신 그룹을 관리하는 네트워크 계층 프로토콜입니다.',
    difficulty: 'MEDIUM',
    keywords: ['IGMP', 'Internet Group Management Protocol', '멀티캐스트그룹'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-protocols',
  },
  {
    id: 'EXP_NET_005',
    subject: '신기술/보안',
    category: '네트워크 프로토콜',
    type: 'SHORT_ANSWER',
    question: '네트워크 상의 클라이언트 PC들에게 IP 주소, 서브넷 마스크, 기본 게이트웨이, DNS 주소를 동적으로 자동 할당해주는 프로토콜의 약칭은 무엇인가?',
    answer: 'DHCP',
    explanation: 'DHCP(Dynamic Host Configuration Protocol)는 DORA(Discover-Offer-Request-Ack) 과정을 거쳐 IP를 대여합니다.',
    difficulty: 'EASY',
    keywords: ['DHCP', 'Dynamic Host Configuration Protocol', 'IP자동할당'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-protocols',
  },
  {
    id: 'EXP_NET_006',
    subject: '신기술/보안',
    category: '라우팅 프로토콜',
    type: 'SHORT_ANSWER',
    question: '내부 게이트웨이 라우팅 프로토콜(IGP) 중 벨만-포드 거리 벡터 알고리즘을 사용하며, 최대 홉 수(Hop Count)가 15로 제한되는 프로토콜의 약칭은 무엇인가?',
    answer: 'RIP',
    explanation: 'RIP(Routing Information Protocol)는 소규모망에 적합하며 16홉은 도달 불가능(Infinity)으로 판단합니다.',
    difficulty: 'EASY',
    keywords: ['RIP', 'Routing Information Protocol', '15홉제한'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-routing',
  },
  {
    id: 'EXP_NET_007',
    subject: '신기술/보안',
    category: '라우팅 프로토콜',
    type: 'SHORT_ANSWER',
    question: '다익스트라(Dijkstra)의 최단 경로 알고리즘(SPF)에 기반한 링크 상태 라우팅 프로토콜로, 홉 수 제한이 없고 네트워크 대역폭(비용)을 기준으로 경로를 설정하는 프로토콜의 약칭은 무엇인가?',
    answer: 'OSPF',
    explanation: 'OSPF(Open Shortest Path First)는 링크 상태 변경 시에만 멀티캐스트로 갱신하여 대규모 기업망에 표준으로 쓰입니다.',
    difficulty: 'EASY',
    keywords: ['OSPF', 'Open Shortest Path First', '다익스트라'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-routing',
  },
  {
    id: 'EXP_NET_008',
    subject: '신기술/보안',
    category: '라우팅 프로토콜',
    type: 'SHORT_ANSWER',
    question: '서로 다른 자율 시스템(AS, Autonomous System) 간에 경로 벡터(Path Vector) 알고리즘을 사용하여 인터넷 백본 라우팅을 수행하는 외부 게이트웨이 프로토콜의 약칭은 무엇인가?',
    answer: 'BGP',
    explanation: 'BGP(Border Gateway Protocol)는 ISP 간의 상호 연결에 사용되는 인터넷 표준 EGP 라우팅 프로토콜입니다.',
    difficulty: 'MEDIUM',
    keywords: ['BGP', 'Border Gateway Protocol', 'AS간라우팅'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-routing',
  },
  {
    id: 'EXP_NET_009',
    subject: '신기술/보안',
    category: '전송 제어 프로토콜',
    type: 'SHORT_ANSWER',
    question: 'TCP 연결을 수립하기 위해 클라이언트와 서버가 주고받는 3단계 핸드셰이크의 플래그 순서는 SYN → (       ) → ACK 이다. 괄호에 들어갈 플래그는 무엇인가?',
    answer: 'SYN+ACK',
    explanation: 'TCP 3-way Handshake 순서는 1단계: SYN, 2단계: SYN+ACK, 3단계: ACK 순으로 상호 연결을 확립합니다.',
    difficulty: 'EASY',
    keywords: ['SYN+ACK', '3-way Handshake', 'TCP연결'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-tcp',
  },
  {
    id: 'EXP_NET_010',
    subject: '신기술/보안',
    category: '전송 제어 프로토콜',
    type: 'SHORT_ANSWER',
    question: 'TCP 통신에서 이미 수립된 연결을 안전하게 종료(해제)하기 위해 양측이 주고받는 핸드셰이크는 몇 번(몇 way)으로 이루어지는가?',
    answer: '4-way Handshake',
    explanation: 'TCP 연결 해제는 FIN → ACK → FIN → ACK 총 4단계(4-way Handshake)를 거쳐 양방향 세션을 모두 안전하게 종료합니다.',
    difficulty: 'EASY',
    keywords: ['4-way Handshake', 'TCP연결해제', 'FIN'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-tcp',
  },
  {
    id: 'EXP_NET_011',
    subject: '신기술/보안',
    category: '전송 제어 프로토콜',
    type: 'SHORT_ANSWER',
    question: 'TCP 흐름 제어(Flow Control) 기법 중 수신 측의 수신 버퍼 여유 공간 크기에 맞춰 송신 측이 한 번에 보낼 수 있는 데이터 패킷의 범위를 동적으로 조절하는 기법은 무엇인가?',
    answer: '슬라이딩 윈도우',
    explanation: '슬라이딩 윈도우(Sliding Window)는 ACK를 일일이 기다리지 않고 윈도우 크기만큼 패킷을 연속 전송하여 통신 효율을 극대화합니다.',
    difficulty: 'EASY',
    keywords: ['슬라이딩 윈도우', 'Sliding Window', '흐름제어'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-tcp',
  },
  {
    id: 'EXP_NET_012',
    subject: '신기술/보안',
    category: '전송 제어 프로토콜',
    type: 'SHORT_ANSWER',
    question: 'TCP 혼잡 제어(Congestion Control) 알고리즘 중 네트워크의 혼잡을 피하기 위해 송신 윈도우 크기를 1부터 시작하여 ACK가 올 때마다 2배씩 지수적으로 증가시키는 기법은 무엇인가?',
    answer: 'Slow Start',
    explanation: '느린 시작(Slow Start)은 혼잡 임계치(ssthresh)에 도달할 때까지 지수 함수적으로 윈도우를 키웁니다.',
    difficulty: 'MEDIUM',
    keywords: ['Slow Start', '느린시작', '혼잡제어'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-tcp',
  },
  {
    id: 'EXP_NET_013',
    subject: '신기술/보안',
    category: 'IP 주소 체계',
    type: 'SHORT_ANSWER',
    question: 'IPv4 주소는 몇 비트 길이로 구성되어 있는가?',
    answer: '32비트',
    explanation: 'IPv4는 8비트씩 4개 옥텟, 총 32비트로 표현됩니다. IPv6는 128비트입니다.',
    difficulty: 'EASY',
    keywords: ['32비트', 'IPv4길이', 'IP주소'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-ip',
  },
  {
    id: 'EXP_NET_014',
    subject: '신기술/보안',
    category: 'IP 주소 체계',
    type: 'SHORT_ANSWER',
    question: 'IPv6 주소는 몇 비트 길이로 구성되어 있는가?',
    answer: '128비트',
    explanation: 'IPv6는 16비트씩 8개 블록(16진수)으로 표기되며 총 128비트의 방대한 주소 공간을 제공합니다.',
    difficulty: 'EASY',
    keywords: ['128비트', 'IPv6길이', 'IP주소'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-ip',
  },
  {
    id: 'EXP_NET_015',
    subject: '신기술/보안',
    category: 'IP 주소 체계',
    type: 'SHORT_ANSWER',
    question: 'IPv6 주소 전송 방식 중 IPv4의 브로드캐스트(Broadcast) 방식을 완전히 대체하여 네트워크 부하를 줄이기 위해 사용하는 전송 방식은 무엇인가?',
    answer: '멀티캐스트',
    explanation: 'IPv6에는 브로드캐스트가 없으며, 유니캐스트, 멀티캐스트(Multicast), 애니캐스트(Anycast) 3가지만 존재합니다.',
    difficulty: 'EASY',
    keywords: ['멀티캐스트', 'Multicast', 'IPv6전송방식'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-ip',
  },
  {
    id: 'EXP_NET_016',
    subject: '신기술/보안',
    category: 'IP 주소 체계',
    type: 'SHORT_ANSWER',
    question: 'IPv6의 3대 전송 방식 중 단일 송신자와 가장 가까운 위치에 있는 단일 수신자 인터페이스(1:1 중 가장 가까운 노드)로 패킷을 전송하는 방식은 무엇인가?',
    answer: '애니캐스트',
    explanation: '애니캐스트(Anycast)는 동일 주소를 가진 노드들 중 라우팅 거리상 가장 가까운 노드로 데이터를 전송합니다.',
    difficulty: 'MEDIUM',
    keywords: ['애니캐스트', 'Anycast', '가장가까운노드'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-ip',
  },
  {
    id: 'EXP_NET_017',
    subject: '신기술/보안',
    category: '서브넷팅 계산',
    type: 'SHORT_ANSWER',
    question: 'IPv4 C클래스 네트워크(서브넷 마스크: 255.255.255.0, /24)에서 1개의 서브넷 내에 실제로 단말 PC들에 할당 가능한 유효 호스트 IP 주소의 최대 개수는 몇 개인가?',
    answer: '254',
    explanation: '호스트 비트가 8비트이므로 총 256개(2^8) 중 네트워크 대표 주소(0번)와 브로드캐스트 주소(255번) 2개를 제외한 254개입니다.',
    difficulty: 'EASY',
    keywords: ['254', '서브넷호스트수', 'C클래스'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-subnet',
  },
  {
    id: 'EXP_NET_018',
    subject: '신기술/보안',
    category: '서브넷팅 계산',
    type: 'SHORT_ANSWER',
    question: 'IP 주소 192.168.1.0/26 대역에서 서브넷 마스크를 10진수로 표기했을 때 마지막 4번째 옥텟의 값은 얼마인가?',
    answer: '192',
    explanation: '/26은 상위 26비트가 1입니다. 4번째 옥텟은 상위 2비트가 1이므로 128 + 64 = 192입니다 (255.255.255.192).',
    difficulty: 'MEDIUM',
    keywords: ['192', '서브넷마스크', '/26'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-subnet',
  },
  {
    id: 'EXP_NET_019',
    subject: '신기술/보안',
    category: '서브넷팅 계산',
    type: 'SHORT_ANSWER',
    question: '어떤 서브넷의 네트워크 주소가 192.168.10.0/26 일 때, 이 서브넷 내부에서 사용 가능한 호스트 IP의 최대 개수는 몇 개인가?',
    answer: '62',
    explanation: '호스트 비트는 32 - 26 = 6비트이므로 2^6 = 64개에서 네트워크(0)와 브로드캐스트(63) 2개를 빼면 62개입니다.',
    difficulty: 'MEDIUM',
    keywords: ['62', '유효호스트수', '/26서브넷팅'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-subnet',
  },
  {
    id: 'EXP_NET_020',
    subject: '신기술/보안',
    category: '네트워크 장비',
    type: 'SHORT_ANSWER',
    question: 'OSI 7계층 중 2계층(데이터링크 계층)에서 동작하며 수신된 프레임의 목적지 MAC 주소를 학습하여 해당 포트로만 스위칭해주는 대표적인 네트워크 장비는 무엇인가?',
    answer: 'L2 스위치',
    explanation: 'L2 스위치(Switch)는 MAC 주소 테이블을 바탕으로 하드웨어 기반 고속 프레임 포워딩을 수행합니다.',
    difficulty: 'EASY',
    keywords: ['L2 스위치', 'Switch', '데이터링크장비'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-devices',
  },
  {
    id: 'EXP_NET_021',
    subject: '신기술/보안',
    category: '네트워크 장비',
    type: 'SHORT_ANSWER',
    question: 'OSI 7계층 중 3계층(네트워크 계층)에서 동작하며 서로 다른 네트워크 간에 패킷을 최적의 경로로 전송해주는 라우팅 장비는 무엇인가?',
    answer: '라우터',
    explanation: '라우터(Router, L3 장비)는 IP 헤더를 분석하여 라우팅 테이블을 기반으로 패킷을 목적지로 전달합니다.',
    difficulty: 'EASY',
    keywords: ['라우터', 'Router', 'L3장비'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-devices',
  },
  {
    id: 'EXP_NET_022',
    subject: '신기술/보안',
    category: '네트워크 장비',
    type: 'SHORT_ANSWER',
    question: '전송 계층(L4)의 TCP/UDP 포트 번호를 분석하여 웹 서버나 애플리케이션 서버들에 트래픽 부하를 분산(Load Balancing)시켜주는 장비는 무엇인가?',
    answer: 'L4 스위치',
    explanation: 'L4 스위치는 IP와 포트 번호를 기반으로 서버 팜(Server Farm)의 부하 분산과 헬스 체크를 수행합니다.',
    difficulty: 'EASY',
    keywords: ['L4 스위치', '로드밸런서', '부하분산'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-devices',
  },
  {
    id: 'EXP_NET_023',
    subject: '신기술/보안',
    category: '네트워크 주소 변환',
    type: 'SHORT_ANSWER',
    question: '공인 IP 주소 고갈 문제를 해결하고 사내망 보안을 위해 사설 IP 주소를 공인 IP 주소로 상호 변환해주는 기술의 약칭은 무엇인가?',
    answer: 'NAT',
    explanation: 'NAT(Network Address Translation)는 사설 IP를 외부 인터넷용 공인 IP로 변환합니다. 포트 번호까지 변환하는 기술은 NAPT(PAT)입니다.',
    difficulty: 'EASY',
    keywords: ['NAT', 'Network Address Translation', 'IP변환'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-protocols',
  },
  {
    id: 'EXP_NET_024',
    subject: '신기술/보안',
    category: '네트워크 주소 체계',
    type: 'SHORT_ANSWER',
    question: '컴퓨터가 자기 자신을 가리키는 루프백(Loopback) IP 주소로, "localhost"와 대응되는 표준 IPv4 주소는 무엇인가?',
    answer: '127.0.0.1',
    explanation: '127.0.0.1은 로컬 호스트 테스트용 루프백 주소입니다. IPv6의 루프백 주소는 ::1 입니다.',
    difficulty: 'EASY',
    keywords: ['127.0.0.1', '루프백주소', 'localhost'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-ip',
  },
  {
    id: 'EXP_NET_025',
    subject: '신기술/보안',
    category: '도메인 네임 시스템',
    type: 'SHORT_ANSWER',
    question: '사람이 이해하기 쉬운 문자형 도메인 이름(예: www.naver.com)을 컴퓨터가 통신할 수 있는 숫자형 IP 주소로 변환해주는 시스템의 약칭은 무엇인가?',
    answer: 'DNS',
    explanation: 'DNS(Domain Name System)는 전 세계 분산 계층 데이터베이스를 통해 도메인 질의를 IP 주소로 매핑합니다.',
    difficulty: 'EASY',
    keywords: ['DNS', 'Domain Name System', '도메인변환'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-protocols',
  },
  {
    id: 'EXP_NET_026',
    subject: '신기술/보안',
    category: '응용 계층 프로토콜',
    type: 'SHORT_ANSWER',
    question: '인터넷 전자우편(E-Mail)을 클라이언트가 작성하여 메일 서버로 발송(송신)하거나 서버 간에 메일을 중계할 때 사용하는 프로토콜의 약칭은 무엇인가?',
    answer: 'SMTP',
    explanation: 'SMTP(Simple Mail Transfer Protocol, 기본 25번 포트)는 메일 발송용 프로토콜입니다. 메일을 서버에서 읽어올 때는 POP3나 IMAP을 씁니다.',
    difficulty: 'EASY',
    keywords: ['SMTP', 'Simple Mail Transfer Protocol', '메일발송'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-protocols',
  },
  {
    id: 'EXP_NET_027',
    subject: '신기술/보안',
    category: '응용 계층 프로토콜',
    type: 'SHORT_ANSWER',
    question: '메일 서버에 도착한 전자우편을 사용자의 클라이언트로 다운로드하여 가져올 때 사용하는 프로토콜로, 메일을 가져온 후 서버에서 삭제하는 것이 기본 설정인 프로토콜의 약칭은 무엇인가?',
    answer: 'POP3',
    explanation: 'POP3(Post Office Protocol v3, 110번 포트)는 메일을 로컬 PC로 다운로드합니다. 서버에 보관하고 동기화하는 것은 IMAP(143번 포트)입니다.',
    difficulty: 'EASY',
    keywords: ['POP3', 'Post Office Protocol', '메일수신'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-protocols',
  },
  {
    id: 'EXP_NET_028',
    subject: '신기술/보안',
    category: '응용 계층 프로토콜',
    type: 'SHORT_ANSWER',
    question: '원격 서버에 안전하게 접속하기 위해 기존의 보안에 취약한 Telnet(평문 전송)을 대체하여 모든 패킷을 강력히 암호화하는 원격 터미널 접속 프로토콜의 약칭은 무엇인가?',
    answer: 'SSH',
    explanation: 'SSH(Secure Shell, 기본 22번 포트)는 공개키 기반 암호화를 적용하여 원격 쉘과 파일 전송(SFTP)을 안전하게 지원합니다.',
    difficulty: 'EASY',
    keywords: ['SSH', 'Secure Shell', '원격접속'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-protocols',
  },
  {
    id: 'EXP_NET_029',
    subject: '신기술/보안',
    category: '네트워크 관리 프로토콜',
    type: 'SHORT_ANSWER',
    question: '네트워크 상의 라우터, 스위치, 서버 등의 장비 상태와 트래픽 정보를 모니터링하고 원격 관리하기 위해 사용하는 표준 네트워크 관리 프로토콜의 약칭은 무엇인가?',
    answer: 'SNMP',
    explanation: 'SNMP(Simple Network Management Protocol)는 MIB(관리정보베이스)와 에이전트를 통해 네트워크 자원을 감시합니다.',
    difficulty: 'EASY',
    keywords: ['SNMP', 'Simple Network Management Protocol', '네트워크관리'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-protocols',
  },
  {
    id: 'EXP_NET_030',
    subject: '신기술/보안',
    category: '전송 계층 비교',
    type: 'SHORT_ANSWER',
    question: '전송 계층 프로토콜 중 TCP와 비교했을 때 연결 설정 절차(Handshake)가 없고 수신 확인(ACK)을 하지 않아 오버헤드가 적고 실시간 방송에 적합한 비연결형 프로토콜의 약칭은 무엇인가?',
    answer: 'UDP',
    explanation: 'UDP(User Datagram Protocol)는 신뢰성보다 전송 속도와 실시간성이 중요한 DNS, 스트리밍, 온라인 게임 등에 널리 쓰입니다.',
    difficulty: 'EASY',
    keywords: ['UDP', 'User Datagram Protocol', '비연결형'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-tcp',
  },
  {
    id: 'EXP_NET_031',
    subject: '신기술/보안',
    category: '네트워크 가상화',
    type: 'SHORT_ANSWER',
    question: '물리적인 하나의 LAN 스위치 네트워크를 여러 개의 서로 격리된 논리적인 브로드캐스트 도메인으로 분할하여 보안과 대역폭을 최적화하는 가상 근거리 통신망의 약칭은 무엇인가?',
    answer: 'VLAN',
    explanation: 'VLAN(Virtual LAN)은 물리적 위치와 무관하게 부서별로 네트워크를 논리적으로 분리합니다.',
    difficulty: 'EASY',
    keywords: ['VLAN', 'Virtual LAN', '가상LAN'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-devices',
  },
  {
    id: 'EXP_NET_032',
    subject: '신기술/보안',
    category: '네트워크 토폴로지',
    type: 'SHORT_ANSWER',
    question: '네트워크 토폴로지 구조 중 중앙에 허브(스위치)가 위치하고 모든 노드가 1:1로 포인트 투 포인트 연결된 별 모양의 구조로, 설치는 쉽지만 중앙 장비 고장 시 전체가 마비되는 형태는 무엇인가?',
    answer: '성형 토폴로지',
    explanation: '성형(Star, 성형 구조) 토폴로지는 현대 이더넷 LAN의 표준 물리 구조입니다.',
    difficulty: 'EASY',
    keywords: ['성형 토폴로지', 'Star Topology', '중앙집중형'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-topology',
  },
  {
    id: 'EXP_NET_033',
    subject: '신기술/보안',
    category: '네트워크 토폴로지',
    type: 'SHORT_ANSWER',
    question: '모든 네트워크 노드들이 서로 1:1로 모두 직접 연결되어 장애 내구성(신뢰성)은 최고이지만 케이블 설치 비용과 포트 소요가 가장 큰 그물망 구조는 무엇인가?',
    answer: '망형 토폴로지',
    explanation: '망형(Mesh Topology)은 n(n-1)/2개의 링크가 필요하며 군사용이나 핵심 백본망에 쓰입니다.',
    difficulty: 'EASY',
    keywords: ['망형 토폴로지', 'Mesh Topology', '그물망구조'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-topology',
  },
  {
    id: 'EXP_NET_034',
    subject: '신기술/보안',
    category: '무선 네트워크 기술',
    type: 'SHORT_ANSWER',
    question: '근거리 무선 통신 기술 중 10cm 이내의 매우 가까운 거리에서 비접촉식으로 단말 간 데이터를 교환하여 교통카드나 모바일 간편결제에 활용되는 기술의 약칭은 무엇인가?',
    answer: 'NFC',
    explanation: 'NFC(Near Field Communication)는 13.56MHz 주파수를 이용하는 차세대 비접촉 통신 규격입니다.',
    difficulty: 'EASY',
    keywords: ['NFC', 'Near Field Communication', '근거리무선통신'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-wireless',
  },
  {
    id: 'EXP_NET_035',
    subject: '신기술/보안',
    category: '무선 네트워크 기술',
    type: 'SHORT_ANSWER',
    question: '사물인터넷(IoT) 센서 네트워크를 위해 저전력, 저가격, 저속 통신을 목표로 설계된 IEEE 802.15.4 표준 기반의 근거리 무선 메쉬 네트워크 기술은 무엇인가?',
    answer: '지그비',
    explanation: '지그비(ZigBee)는 스마트 홈, 센서 네트워크 등 배터리 수명이 중요한 초소형 IoT 기기에 최적화되어 있습니다.',
    difficulty: 'EASY',
    keywords: ['지그비', 'ZigBee', '저전력센서네트워크'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-wireless',
  },
  {
    id: 'EXP_NET_036',
    subject: '신기술/보안',
    category: '소프트웨어 정의 네트워크',
    type: 'SHORT_ANSWER',
    question: '네트워크 장비의 제어부(Control Plane)와 데이터 전송부(Data Plane)를 물리적으로 분리하여 중앙 소프트웨어 컨트롤러가 네트워크를 프로그래밍 방식으로 제어하는 개념의 약칭은 무엇인가?',
    answer: 'SDN',
    explanation: 'SDN(Software Defined Networking)은 오픈플로우(OpenFlow) 프로토콜을 통해 하위 스위치들의 흐름을 중앙 제어합니다.',
    difficulty: 'EASY',
    keywords: ['SDN', 'Software Defined Networking', '제어부분리'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-sdn',
  },
  {
    id: 'EXP_NET_037',
    subject: '신기술/보안',
    category: '소프트웨어 정의 네트워크',
    type: 'SHORT_ANSWER',
    question: 'SDN 환경에서 중앙의 SDN 컨트롤러와 물리적 스위치(데이터 평면) 장비 간에 통신하며 흐름 제어 테이블을 전송하는 대표적인 표준 통신 프로토콜의 이름은 무엇인가?',
    answer: 'OpenFlow',
    explanation: '오픈플로우(OpenFlow)는 SDN 구현의 핵심 사우스바운드(Southbound) 표준 인터페이스 프로토콜입니다.',
    difficulty: 'MEDIUM',
    keywords: ['OpenFlow', '오픈플로우', 'SDN표준프로토콜'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-sdn',
  },
  {
    id: 'EXP_NET_038',
    subject: '신기술/보안',
    category: '라우팅 알고리즘',
    type: 'SHORT_ANSWER',
    question: '거리 벡터(Distance Vector) 라우팅 알고리즘의 기초가 되며, 인접 노드 간의 거리 정보를 주기적으로 교환하여 최단 거리를 갱신하는 대표적인 알고리즘의 이름은 무엇인가?',
    answer: '벨만 포드',
    explanation: '벨만-포드(Bellman-Ford) 알고리즘은 음수 가중치 간선도 처리할 수 있으며 RIP 프로토콜의 근간이 됩니다.',
    difficulty: 'MEDIUM',
    keywords: ['벨만 포드', 'Bellman-Ford', '거리벡터'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-routing',
  },
  {
    id: 'EXP_NET_039',
    subject: '신기술/보안',
    category: '다중화 기술',
    type: 'SHORT_ANSWER',
    question: '광섬유 통신 회선 하나에 서로 다른 파장(색상)을 가진 여러 개의 광신호를 묶어 동시에 다중 전송함으로써 전송 대역폭을 극대화하는 광 다중화 기술의 약칭은 무엇인가?',
    answer: 'WDM',
    explanation: 'WDM(Wavelength Division Multiplexing, 파장 분할 다중화)은 단일 광섬유의 전송 용량을 획기적으로 확장합니다.',
    difficulty: 'MEDIUM',
    keywords: ['WDM', 'Wavelength Division Multiplexing', '파장분할다중화'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-physical',
  },
  {
    id: 'EXP_NET_040',
    subject: '신기술/보안',
    category: '통신 회선 제어',
    type: 'SHORT_ANSWER',
    question: '데이터 통신망에서 송수신 측 사이에 전용 통신 경로를 물리적으로 수립한 후 데이터를 교환하며, 연결 동안 대역폭이 독점되는 교환 방식은 회선 교환 방식인가 패킷 교환 방식인가?',
    answer: '회선 교환 방식',
    explanation: '회선 교환(Circuit Switching, 예: 전통 전화망)은 경로를 독점합니다. 데이터를 일정 크기 블록(패킷)으로 나누어 공유 회선으로 보내는 것은 패킷 교환 방식입니다.',
    difficulty: 'EASY',
    keywords: ['회선 교환 방식', 'Circuit Switching', '전용경로'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-switching',
  },
  {
    id: 'EXP_NET_041',
    subject: '신기술/보안',
    category: '전송 에러 검출',
    type: 'SHORT_ANSWER',
    question: '네트워크 프레임 전송 시 집단 오류(Burst Error)를 고속으로 검출하기 위해 다항식(Polynomial) 연산 코드를 프레임 끝부분(FCS)에 붙여 검사하는 에러 검출 기법의 약칭은 무엇인가?',
    answer: 'CRC',
    explanation: 'CRC(Cyclic Redundancy Check, 순환 중복 검사)는 이더넷 2계층 FCS 필드에서 에러 검출용으로 사용됩니다.',
    difficulty: 'EASY',
    keywords: ['CRC', 'Cyclic Redundancy Check', '순환중복검사'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-datalink',
  },
  {
    id: 'EXP_NET_042',
    subject: '신기술/보안',
    category: '전송 에러 제어',
    type: 'SHORT_ANSWER',
    question: '수신 측이 데이터 전송 오류를 검출하는 것뿐만 아니라, 1비트의 에러가 발생했을 때 재전송 요청 없이 수신 측 스스로 직접 에러 위치를 찾아 정정할 수 있는 코드는 무엇인가?',
    answer: '해밍 코드',
    explanation: '해밍 코드(Hamming Code)는 패리티 비트를 추가하여 1비트 오류 자동 정정(ECC)을 제공합니다.',
    difficulty: 'EASY',
    keywords: ['해밍 코드', 'Hamming Code', '오류정정코드'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-datalink',
  },
  {
    id: 'EXP_NET_043',
    subject: '신기술/보안',
    category: '네트워크 보안 프로토콜',
    type: 'SHORT_ANSWER',
    question: '원격 네트워크 컴퓨터 간에 전용 암호화 터널을 수립하여 공용 인터넷망을 마치 사설 전용선처럼 안전하게 이용할 수 있도록 해주는 가상 사설망의 약칭은 무엇인가?',
    answer: 'VPN',
    explanation: 'VPN(Virtual Private Network)은 IPsec이나 SSL/TLS 프로토콜을 사용해 안전한 가상 터널링을 구현합니다.',
    difficulty: 'EASY',
    keywords: ['VPN', 'Virtual Private Network', '가상사설망'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-vpn',
  },
  {
    id: 'EXP_NET_044',
    subject: '신기술/보안',
    category: '이더넷 충돌 제어',
    type: 'SHORT_ANSWER',
    question: '유선 유선 이더넷(IEEE 802.3)에서 공유 매체 접근 시 회선을 감지(Carrier Sense)하고 데이터 충돌(Collision)이 발생하면 임의 시간 대기 후 재전송하는 다중 접속 방식의 약칭은 무엇인가?',
    answer: 'CSMA/CD',
    explanation: 'CSMA/CD(Carrier Sense Multiple Access with Collision Detection)는 충돌 검출 방식입니다. 무선 LAN(802.11)에서 충돌을 회피하는 것은 CSMA/CA입니다.',
    difficulty: 'EASY',
    keywords: ['CSMA/CD', '충돌검출', '이더넷접근제어'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-datalink',
  },
  {
    id: 'EXP_NET_045',
    subject: '신기술/보안',
    category: '무선 LAN 충돌 제어',
    type: 'SHORT_ANSWER',
    question: '무선 LAN(Wi-Fi, IEEE 802.11) 환경에서 무선 매체의 특성상 충돌 검출이 불가능하여 RTS/CTS 프레임을 교환하고 충돌을 사전에 회피(Collision Avoidance)하는 접속 방식의 약칭은 무엇인가?',
    answer: 'CSMA/CA',
    explanation: 'CSMA/CA는 무선 환경에서 충돌을 사전에 회피합니다.',
    difficulty: 'EASY',
    keywords: ['CSMA/CA', '충돌회피', '무선LAN접근제어'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-wireless',
  },
  {
    id: 'EXP_NET_046',
    subject: '신기술/보안',
    category: '사설 IP 대역',
    type: 'SHORT_ANSWER',
    question: 'RFC 1918에 정의된 IPv4 사설 IP 대역 중 192.168.0.0 ~ 192.168.255.255 대역에 해당하는 네트워크 클래스는 A, B, C 중 어느 클래스인가?',
    answer: 'C클래스',
    explanation: '10.0.0.0/8은 A클래스, 172.16.0.0/12는 B클래스, 192.168.0.0/16은 C클래스 사설 IP 대역입니다.',
    difficulty: 'EASY',
    keywords: ['C클래스', '사설IP대역', '192.168'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-ip',
  },
  {
    id: 'EXP_NET_047',
    subject: '신기술/보안',
    category: '네트워크 서비스',
    type: 'SHORT_ANSWER',
    question: '네트워크 상에 분산되어 있는 컴퓨터와 서버들의 시스템 시계를 정확한 원자 시계 기준 시간에 맞춰 밀리초 단위로 동기화하는 네트워크 시간 프로토콜의 약칭은 무엇인가?',
    answer: 'NTP',
    explanation: 'NTP(Network Time Protocol, UDP 123번 포트)는 분산 시스템의 타임스탬프와 로그 동기화에 필수적입니다.',
    difficulty: 'EASY',
    keywords: ['NTP', 'Network Time Protocol', '시간동기화'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-protocols',
  },
  {
    id: 'EXP_NET_048',
    subject: '신기술/보안',
    category: '네트워크 보안',
    type: 'SHORT_ANSWER',
    question: '네트워크에 접속을 시도하는 모든 사용자 단말(PC, 모바일)의 백신 설치 여부, OS 패치 상태 등을 사전에 검증하여 정책 위반 기기의 내부망 접근을 차단하는 기술의 약칭은 무엇인가?',
    answer: 'NAC',
    explanation: 'NAC(Network Access Control, 네트워크 접근 제어)는 내부망 보안 위협을 사전 차단합니다.',
    difficulty: 'EASY',
    keywords: ['NAC', 'Network Access Control', '단말보안검증'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-security',
  },
  {
    id: 'EXP_NET_049',
    subject: '신기술/보안',
    category: '응용 계층 프로토콜',
    type: 'SHORT_ANSWER',
    question: '인터넷에서 대용량 파일을 고속으로 업로드하고 다운로드하기 위해 제어 포트(21번)와 데이터 전송 포트(20번) 2개의 채널을 분리 운영하는 프로토콜의 약칭은 무엇인가?',
    answer: 'FTP',
    explanation: 'FTP(File Transfer Protocol)는 명령 제어용 연결(21번)과 실제 파일 전송용 연결(20번)을 분리하여 사용합니다.',
    difficulty: 'EASY',
    keywords: ['FTP', 'File Transfer Protocol', '21번포트'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-protocols',
  },
  {
    id: 'EXP_NET_050',
    subject: '신기술/보안',
    category: 'IP 주소 체계',
    type: 'SHORT_ANSWER',
    question: 'IPv4 주소 클래스 중 특정 그룹에 속한 다수의 호스트들에게 동시에 패킷을 전달하기 위한 멀티캐스트(Multicast) 전용 주소 대역(224.0.0.0 ~ 239.255.255.255)으로 할당된 클래스는 무엇인가?',
    answer: 'D클래스',
    explanation: 'A, B, C클래스는 유니캐스트, D클래스는 멀티캐스트, E클래스는 연구 및 실험용 예약 주소입니다.',
    difficulty: 'EASY',
    keywords: ['D클래스', '멀티캐스트대역', 'IPv4클래스'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-net-ip',
  },
];
