import { Question } from '../../src/types/question';

export const BATCH_7_QUESTIONS: Question[] = [
  {
    id: 'EXP_IS_001',
    subject: '정보시스템구축관리',
    category: '품질 표준',
    type: 'SHORT_ANSWER',
    question: 'ISO/IEC 9126 소프트웨어 품질 특성 중 명시된 조건에서 시스템이 오류 없이 지속적으로 정상 동작을 유지할 수 있는 정도를 나타내는 품질 특성은 무엇인가?',
    answer: '신뢰성',
    explanation: '신뢰성(Reliability)은 성숙성, 고장 허용성, 회복성 등의 세부 부특성을 포함합니다.',
    difficulty: 'EASY',
    keywords: ['신뢰성', 'Reliability', 'ISO 9126'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-quality',
  },
  {
    id: 'EXP_IS_002',
    subject: '정보시스템구축관리',
    category: '품질 표준',
    type: 'SHORT_ANSWER',
    question: 'ISO/IEC 9126 소프트웨어 품질 특성 중 소프트웨어를 다른 하드웨어나 운영체제 환경으로 쉽게 변환하거나 이전하여 실행할 수 있는 능력을 나타내는 특성은 무엇인가?',
    answer: '이식성',
    explanation: '이식성(Portability)은 적용성, 설치성, 대체성, 공존성 등의 부특성을 가집니다.',
    difficulty: 'EASY',
    keywords: ['이식성', 'Portability', '환경이전'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-quality',
  },
  {
    id: 'EXP_IS_003',
    subject: '정보시스템구축관리',
    category: '품질 표준',
    type: 'SHORT_ANSWER',
    question: 'ISO/IEC 25010(SQuaRE) 표준에서 기존 ISO/IEC 9126의 6대 품질 특성에 새롭게 독립적인 주특성으로 추가된 2가지 품질 특성은 호환성과 무엇인가?',
    answer: '보안성',
    explanation: 'ISO/IEC 25010은 보안성(Security)과 호환성(Compatibility)을 주특성으로 신설하여 총 8대 품질 모델을 구성했습니다.',
    difficulty: 'MEDIUM',
    keywords: ['보안성', 'Security', 'ISO 25010'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-quality',
  },
  {
    id: 'EXP_IS_004',
    subject: '정보시스템구축관리',
    category: '프로세스 성숙도',
    type: 'SHORT_ANSWER',
    question: 'CMMI(통합 능력 성숙도 모델)의 5단계 성숙도 레벨 중 조직 차원의 표준 프로세스가 문서화되어 전사적으로 체계화된 3단계의 명칭은 무엇인가?',
    answer: '정의됨',
    explanation: 'CMMI 5단계는 1단계 초기(Initial) → 2단계 관리됨(Managed) → 3단계 정의됨(Defined) → 4단계 정량적 관리됨 → 5단계 최적화 순서입니다.',
    difficulty: 'MEDIUM',
    keywords: ['정의됨', 'Defined', 'CMMI 3단계'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-cmmi',
  },
  {
    id: 'EXP_IS_005',
    subject: '정보시스템구축관리',
    category: '프로세스 성숙도',
    type: 'SHORT_ANSWER',
    question: 'CMMI 5단계 중 프로젝트 목표 달성을 위해 통계적 기법과 정량적 데이터 측정을 활용하여 프로세스를 예측하고 통제하는 4단계의 명칭은 무엇인가?',
    answer: '정량적 관리됨',
    explanation: '4단계 정량적 관리됨(Quantitatively Managed)은 측정 지표와 통계적 기법을 프로세스 통제에 활용합니다.',
    difficulty: 'MEDIUM',
    keywords: ['정량적 관리됨', 'Quantitatively Managed', 'CMMI 4단계'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-cmmi',
  },
  {
    id: 'EXP_IS_006',
    subject: '정보시스템구축관리',
    category: '프로세스 성숙도',
    type: 'SHORT_ANSWER',
    question: 'CMMI 최고 단계인 5단계로, 지속적인 프로세스 혁신과 피드백을 통해 프로세스를 지속적으로 개선해 나가는 단계의 명칭은 무엇인가?',
    answer: '최적화',
    explanation: '5단계 최적화(Optimizing)는 신기술 도입과 결함 원인 분석을 통해 프로세스를 끊임없이 자체 혁신합니다.',
    difficulty: 'EASY',
    keywords: ['최적화', 'Optimizing', 'CMMI 5단계'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-cmmi',
  },
  {
    id: 'EXP_IS_007',
    subject: '정보시스템구축관리',
    category: '프로세스 평가',
    type: 'SHORT_ANSWER',
    question: '소프트웨어 프로세스 평가 및 개선을 위한 국제 표준 규격으로 ISO/IEC 15504라는 명칭으로도 불리는 표준의 이름은 무엇인가?',
    answer: 'SPICE',
    explanation: 'SPICE(Software Process Improvement and Capability dEtermination)는 0~5단계의 6개 프로세스 수행 수준을 제시합니다.',
    difficulty: 'EASY',
    keywords: ['SPICE', 'ISO 15504', '프로세스평가'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-spice',
  },
  {
    id: 'EXP_IS_008',
    subject: '정보시스템구축관리',
    category: '형상 관리',
    type: 'SHORT_ANSWER',
    question: '소프트웨어 형상 관리(SCM) 4대 활동 중 소프트웨어 개발 주기 동안 만들어지는 각종 산출물에 고유 번호를 부여하고 형상 항목을 식별하는 활동은 무엇인가?',
    answer: '형상 식별',
    explanation: '형상 식별(Configuration Identification)은 베이스라인(기준선)을 수립하고 형상 항목의 명칭과 버전을 부여합니다.',
    difficulty: 'EASY',
    keywords: ['형상 식별', '베이스라인', '형상관리활동'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-scm',
  },
  {
    id: 'EXP_IS_009',
    subject: '정보시스템구축관리',
    category: '형상 관리',
    type: 'SHORT_ANSWER',
    question: '소프트웨어 형상 변경 요청이 들어왔을 때 형상 통제 위원회(CCB)가 그 타당성을 검토하고 승인, 변경 작업을 관리하는 활동은 무엇인가?',
    answer: '형상 통제',
    explanation: '형상 통제(Configuration Control)는 베이스라인의 무단 변경을 방지하고 공식 변경 승인 절차를 관리합니다.',
    difficulty: 'EASY',
    keywords: ['형상 통제', 'CCB', '변경승인'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-scm',
  },
  {
    id: 'EXP_IS_010',
    subject: '정보시스템구축관리',
    category: '형상 관리',
    type: 'SHORT_ANSWER',
    question: '베이스라인의 무결성을 평가하기 위해 소프트웨어 형상 항목들이 요구사항과 일치하게 온전히 작성되었는지 공식적으로 검증하는 활동은 무엇인가?',
    answer: '형상 감사',
    explanation: '형상 감사(Configuration Audit)는 기능적/물리적 감사를 수행하여 형상 항목의 무결성을 보증합니다.',
    difficulty: 'EASY',
    keywords: ['형상 감사', 'Configuration Audit', '무결성검증'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-scm',
  },
  {
    id: 'EXP_IS_011',
    subject: '정보시스템구축관리',
    category: '형상 관리',
    type: 'SHORT_ANSWER',
    question: '형상 관리에서 소프트웨어 개발 과정 중 특정 시점에 모든 팀원이 공식적으로 합의하고 승인하여 변경을 엄격히 통제하는 기준점을 무엇이라 하는가?',
    answer: '베이스라인',
    explanation: '베이스라인(Baseline, 기준선)은 이후 변경 사항을 추적하고 비교하는 기준이 됩니다.',
    difficulty: 'EASY',
    keywords: ['베이스라인', 'Baseline', '기준선'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-scm',
  },
  {
    id: 'EXP_IS_012',
    subject: '정보시스템구축관리',
    category: '형상 관리',
    type: 'SHORT_ANSWER',
    question: '형상 항목의 변경 요구를 공식적으로 접수하여 변경의 타당성, 위험도, 영향도를 심의하고 승인 여부를 결정하는 대표 기구의 약칭은 무엇인가?',
    answer: 'CCB',
    explanation: 'CCB(Configuration Control Board, 형상 통제 위원회)는 형상 변경의 승인과 통제를 총괄하는 의사결정 협의체입니다.',
    difficulty: 'EASY',
    keywords: ['CCB', '형상통제위원회', 'Configuration Control Board'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-scm',
  },
  {
    id: 'EXP_IS_013',
    subject: '정보시스템구축관리',
    category: '버전 관리',
    type: 'SHORT_ANSWER',
    question: '버전 관리 도구 중 Git이나 Mercurial처럼 중앙 서버가 다운되어도 개발자의 로컬 저장소에서 독립적으로 커밋과 브랜치 작업을 완벽히 수행할 수 있는 저장소 유형은 무엇인가?',
    answer: '분산 저장소 방식',
    explanation: '분산 버전 관리(DVCS)는 모든 개발자가 전체 프로젝트 히스토리를 로컬에 복제하므로 오프라인 작업이 가능합니다.',
    difficulty: 'EASY',
    keywords: ['분산 저장소 방식', 'DVCS', 'Git'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-scm',
  },
  {
    id: 'EXP_IS_014',
    subject: '정보시스템구축관리',
    category: '버전 관리',
    type: 'SHORT_ANSWER',
    question: '버전 관리 도구 중 SVN이나 CVS처럼 하나의 중앙 원격 서버에 모든 리포지토리가 집중되어 클라이언트가 중앙 서버에 접속해야만 커밋할 수 있는 유형은 무엇인가?',
    answer: '클라이언트 서버 방식',
    explanation: '클라이언트/서버 방식(CVCS)은 중앙 서버에 변경 사항이 집중되므로 서버 장애 시 원격 커밋 작업이 중단됩니다.',
    difficulty: 'EASY',
    keywords: ['클라이언트 서버 방식', 'CVCS', 'SVN'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-scm',
  },
  {
    id: 'EXP_IS_015',
    subject: '정보시스템구축관리',
    category: '개발 방법론 테일러링',
    type: 'SHORT_ANSWER',
    question: '프로젝트 특성에 맞게 소프트웨어 개발 방법론의 절차나 산출물을 조정하는 테일러링(Tailoring) 시 법적 규제나 정부 표준 가이드라인은 내부적 요인인가 외부적 요인인가?',
    answer: '외부적 요인',
    explanation: '법적 규제, 국제 표준, 고객사의 컴플라이언스는 외부적 요인에 속합니다. 개발팀의 역량, 기술 환경, 납기는 내부적 요인입니다.',
    difficulty: 'EASY',
    keywords: ['외부적 요인', '테일러링요인', '법적규제'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-tailoring',
  },
  {
    id: 'EXP_IS_016',
    subject: '정보시스템구축관리',
    category: '재해 복구',
    type: 'SHORT_ANSWER',
    question: '재해 복구(DR) 목표 지표 중 시스템에 중단 장애가 발생한 시점부터 다시 정상적으로 업무 서비스를 재개할 때까지 걸리는 최대 허용 시간의 약칭은 무엇인가?',
    answer: 'RTO',
    explanation: 'RTO(Recovery Time Objective, 목표 복구 시간)는 업무 복구까지 허용되는 최대 시간입니다.',
    difficulty: 'EASY',
    keywords: ['RTO', 'Recovery Time Objective', '목표복구시간'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-dr',
  },
  {
    id: 'EXP_IS_017',
    subject: '정보시스템구축관리',
    category: '재해 복구',
    type: 'SHORT_ANSWER',
    question: '재해 복구 목표 지표 중 데이터 백업 주기와 관련하여 재해 발생 시 최대로 허용 가능한 데이터 유실 시점(시간적 범위)을 나타내는 약칭은 무엇인가?',
    answer: 'RPO',
    explanation: 'RPO(Recovery Point Objective, 목표 복구 시점)는 유실되어도 무방하다고 감내할 수 있는 데이터의 과거 시점입니다.',
    difficulty: 'EASY',
    keywords: ['RPO', 'Recovery Point Objective', '목표복구시점'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-dr',
  },
  {
    id: 'EXP_IS_018',
    subject: '정보시스템구축관리',
    category: '재해 복구',
    type: 'SHORT_ANSWER',
    question: '재해 복구 센터 유형 중 주 센터와 완전히 동일한 인프라를 구축하고 데이터를 실시간 동기 복제(Active-Active)하여 RTO를 0에 가깝게 유지하는 센터는 무엇인가?',
    answer: '미러 사이트',
    explanation: '미러 사이트(Mirror Site)는 구축 비용이 가장 비싸지만 무중단 즉각 복구가 가능합니다.',
    difficulty: 'EASY',
    keywords: ['미러 사이트', 'Mirror Site', 'RTO 0'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-dr',
  },
  {
    id: 'EXP_IS_019',
    subject: '정보시스템구축관리',
    category: '재해 복구',
    type: 'SHORT_ANSWER',
    question: '재해 복구 센터 유형 중 주 센터와 동일한 하드웨어를 갖추고 대기(Active-Standby)하면서 수 시간 이내에 서비스를 복구 가능한 센터는 무엇인가?',
    answer: '핫 사이트',
    explanation: '핫 사이트(Hot Site)는 상시 대기 상태로 수 시간 이내에 전환 가능합니다.',
    difficulty: 'EASY',
    keywords: ['핫 사이트', 'Hot Site', '수시간복구'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-dr',
  },
  {
    id: 'EXP_IS_020',
    subject: '정보시스템구축관리',
    category: '재해 복구',
    type: 'SHORT_ANSWER',
    question: '재해 복구 센터 유형 중 전산실 공간, 전력 등 최소한의 필수 기반 시설만 갖추고 재해 발생 시 장비를 반입하여 복구하는 비용이 가장 저렴한 센터는 무엇인가?',
    answer: '콜드 사이트',
    explanation: '콜드 사이트(Cold Site)는 장비와 소프트웨어를 재해 후 설치하므로 복구에 수주~수개월이 소요됩니다.',
    difficulty: 'EASY',
    keywords: ['콜드 사이트', 'Cold Site', '최저비용'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-dr',
  },
  {
    id: 'EXP_IS_021',
    subject: '정보시스템구축관리',
    category: '스토리지 시스템',
    type: 'SHORT_ANSWER',
    question: '서버와 저장 장치(디스크)를 전용 케이블(SATA, SAS 등)로 직접 1:1 연결하는 가장 전통적인 직접 연결 저장 장치 방식의 약칭은 무엇인가?',
    answer: 'DAS',
    explanation: 'DAS(Direct Attached Storage)는 속도가 빠르지만 다른 서버와 스토리지 공유가 불가능합니다.',
    difficulty: 'EASY',
    keywords: ['DAS', 'Direct Attached Storage', '직접연결'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-storage',
  },
  {
    id: 'EXP_IS_022',
    subject: '정보시스템구축관리',
    category: '스토리지 시스템',
    type: 'SHORT_ANSWER',
    question: '기존의 일반 이더넷 LAN 네트워크를 통해 여러 서버들이 TCP/IP로 파일 단위(NFS, CIFS) 데이터 공유를 수행하는 네트워크 연결 스토리지의 약칭은 무엇인가?',
    answer: 'NAS',
    explanation: 'NAS(Network Attached Storage)는 파일 레벨 스토리지 공유를 지원합니다.',
    difficulty: 'EASY',
    keywords: ['NAS', 'Network Attached Storage', '이더넷파일공유'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-storage',
  },
  {
    id: 'EXP_IS_023',
    subject: '정보시스템구축관리',
    category: '스토리지 시스템',
    type: 'SHORT_ANSWER',
    question: '광채널(Fibre Channel) 스위치를 사용한 초고속 전용 네트워크망을 구성하여 서버들에 블록(Block) 단위 초고속 I/O를 제공하는 스토리지 영역 네트워크의 약칭은 무엇인가?',
    answer: 'SAN',
    explanation: 'SAN(Storage Area Network)은 전용 광채널 망을 통해 블록 스토리지 공유를 지원합니다.',
    difficulty: 'EASY',
    keywords: ['SAN', 'Storage Area Network', '광채널'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-storage',
  },
  {
    id: 'EXP_IS_024',
    subject: '정보시스템구축관리',
    category: '스토리지 시스템',
    type: 'SHORT_ANSWER',
    question: 'RAID 레벨 중 데이터를 여러 디스크에 연속적으로 분산 기록하는 스트라이핑(Striping)을 사용해 읽기/쓰기 속도는 극대화되지만 결함 허용(내고장성)이 전혀 없는 레벨은 무엇인가?',
    answer: 'RAID 0',
    explanation: 'RAID 0은 디스크 하나만 고장 나도 전체 데이터가 유실됩니다.',
    difficulty: 'EASY',
    keywords: ['RAID 0', '스트라이핑', '결함허용없음'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-storage',
  },
  {
    id: 'EXP_IS_025',
    subject: '정보시스템구축관리',
    category: '스토리지 시스템',
    type: 'SHORT_ANSWER',
    question: 'RAID 레벨 중 동일한 데이터를 2개 이상의 디스크에 완벽히 복제하여 기록하는 미러링(Mirroring) 방식을 사용하여 안정성은 높지만 유효 디스크 용량이 50%로 줄어드는 레벨은 무엇인가?',
    answer: 'RAID 1',
    explanation: 'RAID 1은 한 디스크가 파손되어도 다른 디스크로 무중단 서비스를 제공합니다.',
    difficulty: 'EASY',
    keywords: ['RAID 1', '미러링', '용량50%'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-storage',
  },
  {
    id: 'EXP_IS_026',
    subject: '정보시스템구축관리',
    category: '스토리지 시스템',
    type: 'SHORT_ANSWER',
    question: 'RAID 레벨 중 최소 3개 이상의 디스크가 필요하며, 패리티(Parity) 정보를 모든 디스크에 분산 저장하여 1개의 디스크 고장 시 복구 가능한 가장 널리 쓰이는 레벨은 무엇인가?',
    answer: 'RAID 5',
    explanation: 'RAID 5는 분산 패리티를 사용하여 성능과 가용성을 균형 있게 충족합니다.',
    difficulty: 'EASY',
    keywords: ['RAID 5', '분산패리티', '최소3개디스크'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-storage',
  },
  {
    id: 'EXP_IS_027',
    subject: '정보시스템구축관리',
    category: '스토리지 시스템',
    type: 'SHORT_ANSWER',
    question: 'RAID 5의 안정성을 한층 강화하여 서로 다른 2개의 분산 패리티를 유지함으로써 동시에 2개의 디스크가 고장 나더라도 데이터를 복구할 수 있는 레벨은 무엇인가?',
    answer: 'RAID 6',
    explanation: 'RAID 6는 듀얼 패리티를 적용하여 최소 4개의 디스크가 필요합니다.',
    difficulty: 'EASY',
    keywords: ['RAID 6', '듀얼패리티', '동시2개고장극복'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-storage',
  },
  {
    id: 'EXP_IS_028',
    subject: '정보시스템구축관리',
    category: 'IT 서비스 관리',
    type: 'SHORT_ANSWER',
    question: '서비스 제공자와 고객 간에 제공될 서비스의 품질 수준(가동률, 응답 시간, 장애 복구 시간 등)을 정량적으로 명시하고 위반 시 보상 기준을 정의한 계약서는 무엇인가?',
    answer: 'SLA',
    explanation: 'SLA(Service Level Agreement, 서비스 수준 협약서)는 IT 서비스 품질의 기준이 됩니다.',
    difficulty: 'EASY',
    keywords: ['SLA', 'Service Level Agreement', '서비스수준협약'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-itsm',
  },
  {
    id: 'EXP_IS_029',
    subject: '정보시스템구축관리',
    category: 'IT 서비스 관리',
    type: 'SHORT_ANSWER',
    question: 'IT 서비스 관리(ITSM)의 사실상 표준 프레임워크로, 영국 정부가 제정한 IT 서비스 우수 실천 사례(Best Practice) 라이브러리의 명칭은 무엇인가?',
    answer: 'ITIL',
    explanation: 'ITIL(IT Infrastructure Library)은 인시던트 관리, 문제 관리, 변경 관리 등의 지침을 제공합니다.',
    difficulty: 'EASY',
    keywords: ['ITIL', 'IT Infrastructure Library', 'ITSM'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-itsm',
  },
  {
    id: 'EXP_IS_030',
    subject: '정보시스템구축관리',
    category: 'IT 서비스 관리',
    type: 'SHORT_ANSWER',
    question: 'ITIL 프로세스 중 시스템에 비정상적인 장애나 서비스 중단(인시던트)이 발생했을 때 가장 우선적으로 서비스의 빠른 정상화를 목표로 처리하는 프로세스는 무엇인가?',
    answer: '인시던트 관리',
    explanation: '인시던트 관리(Incident Management)는 근본 원인 규명보다 "신속한 서비스 복구"가 최우선 목표입니다.',
    difficulty: 'EASY',
    keywords: ['인시던트 관리', 'Incident Management', '신속복구'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-itsm',
  },
  {
    id: 'EXP_IS_031',
    subject: '정보시스템구축관리',
    category: 'IT 서비스 관리',
    type: 'SHORT_ANSWER',
    question: 'ITIL 프로세스 중 반복적으로 발생하는 인시던트들의 근본적인 기저 원인(Root Cause)을 규명하고 이를 영구 제거하여 재발을 방지하는 프로세스는 무엇인가?',
    answer: '문제 관리',
    explanation: '문제 관리(Problem Management)는 인시던트의 근본 원인을 분석하여 영구 조치합니다.',
    difficulty: 'EASY',
    keywords: ['문제 관리', 'Problem Management', '근본원인제거'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-itsm',
  },
  {
    id: 'EXP_IS_032',
    subject: '정보시스템구축관리',
    category: '비즈니스 연속성',
    type: 'SHORT_ANSWER',
    question: '재난이나 재해 발생 시 비즈니스의 핵심 핵심 기능을 신속히 복구하고 업무를 지속하기 위해 수립하는 종합적인 비즈니스 연속성 계획의 약칭은 무엇인가?',
    answer: 'BCP',
    explanation: 'BCP(Business Continuity Planning)는 재해 발생 시 기업 비즈니스를 지속하기 위한 종합 계획입니다.',
    difficulty: 'EASY',
    keywords: ['BCP', 'Business Continuity Planning', '업무연속성'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-dr',
  },
  {
    id: 'EXP_IS_033',
    subject: '정보시스템구축관리',
    category: '비즈니스 연속성',
    type: 'SHORT_ANSWER',
    question: 'BCP 수립 단계 중 재난 발생 시 특정 업무의 중단이 기업의 재무, 법적, 운영 측면에 미칠 손실 규모와 핵심 업무의 우선순위를 정량/정성 평가하는 분석 기법의 약칭은 무엇인가?',
    answer: 'BIA',
    explanation: 'BIA(Business Impact Analysis, 업무 영향 분석)는 RTO와 RPO를 결정하는 기초 분석 단계입니다.',
    difficulty: 'MEDIUM',
    keywords: ['BIA', 'Business Impact Analysis', '업무영향분석'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-dr',
  },
  {
    id: 'EXP_IS_034',
    subject: '정보시스템구축관리',
    category: '인프라 가상화',
    type: 'SHORT_ANSWER',
    question: '인프라 자원을 프로그래밍 코드(설정 파일)로 정의하고 버전 관리하여 서버 배포와 설정을 완전 자동화하는 개념의 약칭은 무엇인가?',
    answer: 'IaC',
    explanation: 'IaC(Infrastructure as Code, 코드형 인프라)는 테라폼(Terraform)이나 앤서블(Ansible)을 통해 인프라를 코드로 프로비저닝합니다.',
    difficulty: 'EASY',
    keywords: ['IaC', 'Infrastructure as Code', '코드형인프라'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-infra',
  },
  {
    id: 'EXP_IS_035',
    subject: '정보시스템구축관리',
    category: '인프라 가상화',
    type: 'SHORT_ANSWER',
    question: '호스트 운영체제 위에 하이퍼바이저와 게스트 OS 없이 OS 커널을 공유하며 프로세스를 격리 실행하는 리눅스 컨테이너 기반 오픈소스 가상화 플랫폼은 무엇인가?',
    answer: '도커',
    explanation: '도커(Docker)는 컨테이너 기술로 실행 환경을 이미지화하여 가볍고 빠르게 배포합니다.',
    difficulty: 'EASY',
    keywords: ['도커', 'Docker', '컨테이너'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-infra',
  },
  {
    id: 'EXP_IS_036',
    subject: '정보시스템구축관리',
    category: '인프라 가상화',
    type: 'SHORT_ANSWER',
    question: '대규모 컨테이너들의 배포, 자동 확장(오토스케일링), 로드 밸런싱, 롤백을 총괄 관리해주는 대표적인 컨테이너 오케스트레이션 도구는 무엇인가?',
    answer: '쿠버네티스',
    explanation: '쿠버네티스(Kubernetes, K8s)는 구글이 오픈소스로 공개한 컨테이너 오케스트레이션 표준 플랫폼입니다.',
    difficulty: 'EASY',
    keywords: ['쿠버네티스', 'Kubernetes', 'K8s', '오케스트레이션'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-infra',
  },
  {
    id: 'EXP_IS_037',
    subject: '정보시스템구축관리',
    category: '소프트웨어 테스팅',
    type: 'SHORT_ANSWER',
    question: '테스트 설계 기법 중 소프트웨어에 결함이 발생할 가능성이 가장 높은 경계값(최솟값 직전, 최솟값, 최댓값, 최댓값 직후 등)을 집중적으로 테스트 케이스로 추출하는 기법은 무엇인가?',
    answer: '경계값 분석',
    explanation: '경계값 분석(Boundary Value Analysis)은 동등 분할과 함께 대표적인 블랙박스 테스트 기법입니다.',
    difficulty: 'EASY',
    keywords: ['경계값 분석', 'Boundary Value', '블랙박스테스트'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-testing',
  },
  {
    id: 'EXP_IS_038',
    subject: '정보시스템구축관리',
    category: '소프트웨어 테스팅',
    type: 'SHORT_ANSWER',
    question: '프로그램의 소스코드 내부 구조를 들여다보지 않고 외부 명세서만을 바탕으로 입력 값에 따른 올바른 출력이 나오는지 검증하는 테스트 방식은 무엇인가?',
    answer: '블랙박스 테스트',
    explanation: '블랙박스 테스트(Black-box Test)는 기능 명세를 검증하며 동등 분할, 경계값 분석, 원인-결과 그래프 등이 있습니다.',
    difficulty: 'EASY',
    keywords: ['블랙박스 테스트', 'Black-box Test', '명세기반'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-testing',
  },
  {
    id: 'EXP_IS_039',
    subject: '정보시스템구축관리',
    category: '소프트웨어 테스팅',
    type: 'SHORT_ANSWER',
    question: '프로그램의 원시 소스코드 로직과 제어 흐름 구조를 직접 분석하여 모든 실행 경로가 올바르게 수행되는지 검증하는 테스트 방식은 무엇인가?',
    answer: '화이트박스 테스트',
    explanation: '화이트박스 테스트(White-box Test)는 구문, 분기, 조건, 경로 커버리지 등을 측정합니다.',
    difficulty: 'EASY',
    keywords: ['화이트박스 테스트', 'White-box Test', '구조기반'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-testing',
  },
  {
    id: 'EXP_IS_040',
    subject: '정보시스템구축관리',
    category: '소프트웨어 테스팅',
    type: 'SHORT_ANSWER',
    question: '화이트박스 테스트 커버리지 중 소스코드 내의 모든 실행 가능한 문장(구문)들이 최소 한 번은 실행되도록 설계하는 가장 기본적인 커버리지는 무엇인가?',
    answer: '구문 커버리지',
    explanation: '구문 커버리지(Statement Coverage, 라인 커버리지)는 모든 실행 명령문을 1회 이상 통과하는지 검증합니다.',
    difficulty: 'EASY',
    keywords: ['구문 커버리지', 'Statement Coverage', '문장커버리지'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-testing',
  },
  {
    id: 'EXP_IS_041',
    subject: '정보시스템구축관리',
    category: '소프트웨어 테스팅',
    type: 'SHORT_ANSWER',
    question: '화이트박스 테스트 커버리지 중 프로그램 내의 모든 조건문(if문 등)의 결과가 참(True)과 거짓(False)을 최소 한 번씩은 모두 수행하도록 보장하는 커버리지는 무엇인가?',
    answer: '분기 커버리지',
    explanation: '분기 커버리지(Branch Coverage, 결정 커버리지)는 조건문 전체의 참/거짓 분기를 1회 이상 실행합니다.',
    difficulty: 'EASY',
    keywords: ['분기 커버리지', 'Branch Coverage', '결정커버리지'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-testing',
  },
  {
    id: 'EXP_IS_042',
    subject: '정보시스템구축관리',
    category: '소프트웨어 테스팅',
    type: 'SHORT_ANSWER',
    question: '조건문 전체의 결과와 무관하게, 조건문 내부를 구성하는 개별 단일 조건식(예: A > 0) 각각이 독립적으로 참과 거짓을 최소 한 번씩 갖도록 설계하는 커버리지는 무엇인가?',
    answer: '조건 커버리지',
    explanation: '조건 커버리지(Condition Coverage)는 개별 조건식의 참/거짓만을 만족하면 되므로 전체 분기가 참/거짓을 만족하지 못할 수 있습니다.',
    difficulty: 'MEDIUM',
    keywords: ['조건 커버리지', 'Condition Coverage', '개별조건식'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-testing',
  },
  {
    id: 'EXP_IS_043',
    subject: '정보시스템구축관리',
    category: '소프트웨어 테스팅',
    type: 'SHORT_ANSWER',
    question: '복합 조건식에서 각 개별 조건식이 전체 결정 결과에 독립적으로 영향을 미치는지를 검증하여 항공/철도 등 최고 안전성이 요구되는 시스템에 쓰이는 커버리지의 약칭은 무엇인가?',
    answer: 'MC/DC',
    explanation: 'MC/DC(Modified Condition/Decision Coverage)는 조건/결정 커버리지를 보완하여 N+1개의 테스트 케이스로 높은 신뢰성을 달성합니다.',
    difficulty: 'HARD',
    keywords: ['MC/DC', 'Modified Condition', '항공기소프트웨어'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-testing',
  },
  {
    id: 'EXP_IS_044',
    subject: '정보시스템구축관리',
    category: '소프트웨어 테스팅',
    type: 'SHORT_ANSWER',
    question: '테스트 오라클(Test Oracle) 종류 중 모든 가능한 입력 값에 대해 100% 완벽한 기대 결과를 사전에 모두 알고 있는 특수한 상황에 적용하는 오라클은 무엇인가?',
    answer: '참 오라클',
    explanation: '참 오라클(True Oracle)은 모든 입력에 대해 정답을 정확히 산출하는 오라클입니다. 일부 샘플만 검증하는 것은 샘플링 오라클입니다.',
    difficulty: 'EASY',
    keywords: ['참 오라클', 'True Oracle', '완벽한결과'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-testing',
  },
  {
    id: 'EXP_IS_045',
    subject: '정보시스템구축관리',
    category: '소프트웨어 테스팅',
    type: 'SHORT_ANSWER',
    question: '테스트 오라클 종류 중 특정 주요 몇 개의 입력 값들에 대해서만 정답을 확인하고, 나머지는 추정치로 판단하는 오라클은 무엇인가?',
    answer: '샘플링 오라클',
    explanation: '샘플링 오라클(Sampling Oracle)은 대표 샘플 테스트 케이스들만 완전 검증합니다.',
    difficulty: 'EASY',
    keywords: ['샘플링 오라클', 'Sampling Oracle', '일부검증'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-testing',
  },
  {
    id: 'EXP_IS_046',
    subject: '정보시스템구축관리',
    category: '소프트웨어 테스팅',
    type: 'SHORT_ANSWER',
    question: '하향식 통합 테스트(Top-down Test) 수행 시 아직 개발되지 않은 하위 모듈의 역할을 흉내 내어 호출 결과를 반환해주는 가상 임시 모듈을 무엇이라 하는가?',
    answer: '스텁',
    explanation: '스텁(Stub)은 하향식 테스트에서 하위 모듈의 대역으로 쓰입니다. 상향식 테스트에서 상위 모듈 역할을 하는 것은 드라이버(Driver)입니다.',
    difficulty: 'EASY',
    keywords: ['스텁', 'Stub', '하향식테스트'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-testing',
  },
  {
    id: 'EXP_IS_047',
    subject: '정보시스템구축관리',
    category: '소프트웨어 테스팅',
    type: 'SHORT_ANSWER',
    question: '상향식 통합 테스트(Bottom-up Test) 수행 시 이미 개발된 최하위 모듈들을 시험 구동하기 위해 상위 호출자 역할을 흉내 내는 가상 제어 소프트웨어를 무엇이라 하는가?',
    answer: '테스트 드라이버',
    explanation: '테스트 드라이버(Test Driver)는 상향식 통합 시 데이터를 전달하고 하위 모듈의 출력을 수신하는 상위 제어 모듈입니다.',
    difficulty: 'EASY',
    keywords: ['테스트 드라이버', 'Driver', '상향식테스트'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-testing',
  },
  {
    id: 'EXP_IS_048',
    subject: '정보시스템구축관리',
    category: '소프트웨어 테스팅',
    type: 'SHORT_ANSWER',
    question: '소프트웨어에 버그 수정이나 기능 추가 등 소스코드 변경이 발생했을 때, 기존에 잘 동작하던 기능에 새로운 결함(사이드 이펙트)이 생기지 않았는지 재검증하는 테스트는 무엇인가?',
    answer: '회귀 테스트',
    explanation: '회귀 테스트(Regression Test)는 코드 수정 후 기존 기능의 퇴보를 방지하기 위해 수행하는 재시험입니다.',
    difficulty: 'EASY',
    keywords: ['회귀 테스트', 'Regression Test', '사이드이펙트방지'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-testing',
  },
  {
    id: 'EXP_IS_049',
    subject: '정보시스템구축관리',
    category: '소프트웨어 테스팅',
    type: 'SHORT_ANSWER',
    question: '테스트의 기본 원칙 중 동일한 테스트 케이스로 반복 테스트를 수행하면 더 이상 새로운 결함을 찾아낼 수 없으므로 케이스를 지속적으로 갱신해야 한다는 원칙은 무엇인가?',
    answer: '살충제 패러독스',
    explanation: '살충제 패러독스(Pesticide Paradox)는 테스트 케이스를 정기적으로 개선하고 리뷰해야 함을 강조합니다.',
    difficulty: 'EASY',
    keywords: ['살충제 패러독스', 'Pesticide Paradox', '테스트원칙'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-testing',
  },
  {
    id: 'EXP_IS_050',
    subject: '정보시스템구축관리',
    category: '소프트웨어 테스팅',
    type: 'SHORT_ANSWER',
    question: '소프트웨어 결함의 80%는 전체 시스템의 특정 20% 모듈에 집중되어 발생한다는 파레토 법칙에 기반한 테스트 원칙은 무엇인가?',
    answer: '결함 집중',
    explanation: '결함 집중(Defect Clustering) 원칙은 복잡도가 높고 핵심 로직이 위치한 일부 모듈에 결함이 집중된다는 원리입니다.',
    difficulty: 'EASY',
    keywords: ['결함 집중', 'Defect Clustering', '파레토법칙'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-is-testing',
  },
];
