import { Question } from '../../src/types/question';

export const BATCH_5_QUESTIONS: Question[] = [
  {
    id: 'EXP_DB1_001',
    subject: '데이터베이스구축',
    category: 'SQL 제약조건',
    type: 'SHORT_ANSWER',
    question: '관계형 데이터베이스에서 테이블 생성 시 특정 컬럼에 입력될 수 있는 값의 범위나 조건을 제한식으로 검증하는 무결성 제약조건 키워드는 무엇인가?',
    answer: 'CHECK',
    explanation: 'CHECK 제약조건은 데이터 입력/수정 시 특정 논리식(예: CHECK(age >= 0 AND age <= 150))을 만족하는지 검사합니다.',
    difficulty: 'EASY',
    keywords: ['CHECK', '제약조건', '범위검증'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-constraints',
  },
  {
    id: 'EXP_DB1_002',
    subject: '데이터베이스구축',
    category: 'SQL 제약조건',
    type: 'SHORT_ANSWER',
    question: '외래키(FOREIGN KEY) 제약조건 설정 시 부모 테이블의 행이 삭제되면 이를 참조하는 자식 테이블의 모든 관련 행도 연쇄적으로 자동 삭제되도록 지정하는 옵션은 무엇인가?',
    answer: 'CASCADE',
    explanation: 'ON DELETE CASCADE는 부모 행 삭제 시 외래키로 참조하는 모든 자식 행들을 함께 삭제하여 참조 무결성을 유지합니다.',
    difficulty: 'EASY',
    keywords: ['CASCADE', 'ON DELETE CASCADE', '참조무결성'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-constraints',
  },
  {
    id: 'EXP_DB1_003',
    subject: '데이터베이스구축',
    category: 'SQL 제약조건',
    type: 'SHORT_ANSWER',
    question: '외래키 제약조건 설정 시 자식 테이블에서 해당 행을 참조하고 있는 경우 부모 테이블의 행을 삭제하지 못하도록 차단(거절)하는 기본 동작 옵션은 무엇인가?',
    answer: 'RESTRICT',
    explanation: 'ON DELETE RESTRICT(또는 NO ACTION)는 자식 행이 존재할 때 부모 행 삭제를 금지하여 참조 무결성 위반을 방지합니다.',
    difficulty: 'EASY',
    keywords: ['RESTRICT', 'ON DELETE RESTRICT', '삭제차단'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-constraints',
  },
  {
    id: 'EXP_DB1_004',
    subject: '데이터베이스구축',
    category: 'SQL 제약조건',
    type: 'SHORT_ANSWER',
    question: '외래키 설정 시 부모 테이블의 튜플이 삭제되면 이를 참조하던 자식 테이블 외래키 속성 값을 자동으로 NULL로 변경하는 옵션은 무엇인가?',
    answer: 'SET NULL',
    explanation: 'ON DELETE SET NULL 옵션은 부모 튜플 삭제 시 자식 튜플의 참조 컬럼 값을 NULL로 갱신합니다.',
    difficulty: 'EASY',
    keywords: ['SET NULL', 'ON DELETE SET NULL', '외래키옵션'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-constraints',
  },
  {
    id: 'EXP_DB1_005',
    subject: '데이터베이스구축',
    category: 'SQL 제약조건',
    type: 'SHORT_ANSWER',
    question: '테이블 정의 시 INSERT 문에서 특정 컬럼의 값을 생략했을 때 자동으로 들어갈 기본값을 사전에 지정하는 제약조건 키워드는 무엇인가?',
    answer: 'DEFAULT',
    explanation: 'DEFAULT 키워드는 컬럼 값이 명시되지 않았을 때 지정된 기본값(예: DEFAULT 0, DEFAULT SYSDATE)을 입력합니다.',
    difficulty: 'EASY',
    keywords: ['DEFAULT', '기본값설정', 'SQL제약조건'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-constraints',
  },
  {
    id: 'EXP_DB1_006',
    subject: '데이터베이스구축',
    category: 'SQL 제약조건',
    type: 'SHORT_ANSWER',
    question: '테이블의 속성에 중복된 값이 들어올 수 없도록 고유성을 보장하되, 기본키(PK)와 달리 NULL 값의 저장은 허용하는 제약조건 키워드는 무엇인가?',
    answer: 'UNIQUE',
    explanation: 'UNIQUE 제약조건은 고유성을 강제하지만 NULL 값은 허용(DBMS에 따라 여러 NULL 허용)합니다. 기본키(PRIMARY KEY)는 UNIQUE + NOT NULL 입니다.',
    difficulty: 'EASY',
    keywords: ['UNIQUE', '고유키', 'NULL허용'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-constraints',
  },
  {
    id: 'EXP_DB1_007',
    subject: '데이터베이스구축',
    category: 'SQL DDL',
    type: 'SHORT_ANSWER',
    question: '기존에 생성되어 있는 테이블의 구조를 변경하기 위해 컬럼을 추가하거나 수정, 삭제할 때 사용하는 DDL 명령어는 무엇인가?',
    answer: 'ALTER TABLE',
    explanation: 'ALTER TABLE 문은 ADD(컬럼 추가), MODIFY/ALTER(컬럼 타입 변경), DROP(컬럼 삭제) 등의 세부 명령과 함께 쓰입니다.',
    difficulty: 'EASY',
    keywords: ['ALTER TABLE', '테이블구조변경', 'DDL'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-ddl',
  },
  {
    id: 'EXP_DB1_008',
    subject: '데이터베이스구축',
    category: 'SQL DDL',
    type: 'SHORT_ANSWER',
    question: '테이블 삭제 시 해당 테이블을 다른 테이블에서 외래키로 참조하고 있더라도 연관된 모든 제약조건을 강제로 함께 제거하고 테이블을 삭제시키는 DROP 문 옵션은 무엇인가?',
    answer: 'CASCADE CONSTRAINTS',
    explanation: 'DROP TABLE 테이블명 CASCADE CONSTRAINTS 옵션은 참조하고 있는 외래키 제약조건을 먼저 삭제한 뒤 테이블을 성공적으로 제거합니다.',
    difficulty: 'MEDIUM',
    keywords: ['CASCADE CONSTRAINTS', '테이블삭제', 'DROP'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-ddl',
  },
  {
    id: 'EXP_DB1_009',
    subject: '데이터베이스구축',
    category: 'SQL DDL vs DML',
    type: 'SHORT_ANSWER',
    question: '테이블의 모든 행(데이터)을 고속으로 삭제하되 트랜잭션 로그를 거의 남기지 않고 즉시 자동 커밋(Auto Commit)되어 ROLLBACK으로 되돌릴 수 없는 DDL 명령어는 무엇인가?',
    answer: 'TRUNCATE',
    explanation: 'TRUNCATE는 테이블의 구조는 남기고 모든 레코드를 빠르게 비우는 DDL입니다. 행 단위로 삭제 로그를 남겨 ROLLBACK이 가능한 것은 DML인 DELETE입니다.',
    difficulty: 'EASY',
    keywords: ['TRUNCATE', '테이블초기화', '롤백불가'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-ddl',
  },
  {
    id: 'EXP_DB1_010',
    subject: '데이터베이스구축',
    category: 'SQL 집계 함수',
    type: 'SHORT_ANSWER',
    question: 'SQL 집계 함수 중 특정 컬럼 속성에 NULL 값이 들어있는 행까지 포함하여 전체 행의 총 개수를 셀 때 사용하는 표현식은 COUNT(컬럼명)인가 COUNT(*)인가?',
    answer: 'COUNT(*)',
    explanation: 'COUNT(*)는 NULL을 포함한 모든 행을 세며, COUNT(컬럼명)은 해당 컬럼 값이 NULL인 행을 제외하고 셉니다.',
    difficulty: 'EASY',
    keywords: ['COUNT(*)', '집계함수', 'NULL포함'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-aggregate',
  },
  {
    id: 'EXP_DB1_011',
    subject: '데이터베이스구축',
    category: 'SQL NULL 함수',
    type: 'SHORT_ANSWER',
    question: 'SQL 표준 함수 중 인자로 나열된 여러 개의 값 중에서 NULL이 아닌 최초의(첫 번째) 값을 반환하는 함수의 이름은 무엇인가?',
    answer: 'COALESCE',
    explanation: 'COALESCE(val1, val2, val3, ...)는 앞에서부터 검사하여 처음 만나는 NULL이 아닌 값을 반환합니다.',
    difficulty: 'MEDIUM',
    keywords: ['COALESCE', 'NULL처리', '표준함수'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-functions',
  },
  {
    id: 'EXP_DB1_012',
    subject: '데이터베이스구축',
    category: 'SQL NULL 함수',
    type: 'SHORT_ANSWER',
    question: 'SQL 함수 중 두 개의 인자(expr1, expr2)를 비교하여 두 값이 같으면 NULL을 반환하고, 다르면 expr1을 반환하는 함수의 이름은 무엇인가?',
    answer: 'NULLIF',
    explanation: 'NULLIF(a, b)는 a와 b가 같을 때 NULL을 반환하여 0으로 나누기(Divide by Zero) 에러 등을 방지할 때 유용합니다.',
    difficulty: 'MEDIUM',
    keywords: ['NULLIF', '동등비교NULL', 'SQL함수'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-functions',
  },
  {
    id: 'EXP_DB1_013',
    subject: '데이터베이스구축',
    category: 'SQL 윈도우 함수',
    type: 'SHORT_ANSWER',
    question: 'SQL 윈도우 순위 함수 중 동일한 점수가 나오면 같은 순위를 부여하고, 그 다음 순위는 동점자 수만큼 건너뛰어 부여하는(예: 1등, 2등, 2등, 4등) 함수는 무엇인가?',
    answer: 'RANK',
    explanation: 'RANK() 함수는 동순위 발생 시 순위를 건너뜁니다. 순위를 건너뛰지 않고 1등, 2등, 2등, 3등으로 매기는 것은 DENSE_RANK()입니다.',
    difficulty: 'EASY',
    keywords: ['RANK', '순위함수', '순위건너뜀'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-window',
  },
  {
    id: 'EXP_DB1_014',
    subject: '데이터베이스구축',
    category: 'SQL 윈도우 함수',
    type: 'SHORT_ANSWER',
    question: 'SQL 윈도우 순위 함수 중 점수의 동일 여부와 상관없이 무조건 각 행마다 1부터 시작하여 유일하고 고유한 연속 일련번호(1, 2, 3, 4, ...)를 부여하는 함수는 무엇인가?',
    answer: 'ROW_NUMBER',
    explanation: 'ROW_NUMBER()는 동점자가 존재하더라도 정렬 기준에 따라 고유한 연속 번호를 할당합니다.',
    difficulty: 'EASY',
    keywords: ['ROW_NUMBER', '일련번호부여', '윈도우함수'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-window',
  },
  {
    id: 'EXP_DB1_015',
    subject: '데이터베이스구축',
    category: 'SQL 윈도우 함수',
    type: 'SHORT_ANSWER',
    question: 'SQL 윈도우 순위 함수 중 동일한 값에 대해 같은 순위를 매기되, 바로 다음 순위를 건너뛰지 않고 연속된 번호로 부여하는(예: 1등, 2등, 2등, 3등) 함수는 무엇인가?',
    answer: 'DENSE_RANK',
    explanation: 'DENSE_RANK()는 빈틈없이(dense) 순위를 매겨 동점자 다음 순위를 연속된 숫자로 이어갑니다.',
    difficulty: 'EASY',
    keywords: ['DENSE_RANK', '연속순위', '윈도우함수'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-window',
  },
  {
    id: 'EXP_DB1_016',
    subject: '데이터베이스구축',
    category: 'SQL 그룹 함수',
    type: 'SHORT_ANSWER',
    question: 'GROUP BY 절과 함께 쓰여 명시된 컬럼들의 소계(Subtotal)와 총계(Grand Total)를 계층적 단계별로 자동 산출해주는 그룹 함수는 무엇인가?',
    answer: 'ROLLUP',
    explanation: 'ROLLUP(A, B)은 (A, B)별 집계, A별 소계, 전체 총계를 계층적으로 생성합니다. 나열 순서에 따라 집계 결과가 달라집니다.',
    difficulty: 'EASY',
    keywords: ['ROLLUP', '소계총계', '그룹함수'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-group',
  },
  {
    id: 'EXP_DB1_017',
    subject: '데이터베이스구축',
    category: 'SQL 그룹 함수',
    type: 'SHORT_ANSWER',
    question: 'GROUP BY 절과 함께 쓰여 결합 가능한 모든 다차원 조합(2^N)에 대해 집계를 산출하여 다각적 데이터 분석을 지원하는 그룹 함수는 무엇인가?',
    answer: 'CUBE',
    explanation: 'CUBE(A, B)는 (A, B), (A), (B), () 전체의 모든 가능한 경우의 수로 집계를 생성합니다.',
    difficulty: 'EASY',
    keywords: ['CUBE', '다차원집계', '모든조합'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-group',
  },
  {
    id: 'EXP_DB1_018',
    subject: '데이터베이스구축',
    category: 'SQL 그룹 함수',
    type: 'SHORT_ANSWER',
    question: 'GROUP BY 절에서 원하는 개별 집계 대상 컬럼들을 튜플 목록으로 직접 지정하여 각각 독립적으로 집계하는 그룹 집합 함수는 무엇인가?',
    answer: 'GROUPING SETS',
    explanation: 'GROUPING SETS(A, B)는 A 기준 집계와 B 기준 집계의 결과를 UNION ALL 한 것과 동일한 효과를 냅니다.',
    difficulty: 'MEDIUM',
    keywords: ['GROUPING SETS', '개별그룹집계', '그룹함수'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-group',
  },
  {
    id: 'EXP_DB1_019',
    subject: '데이터베이스구축',
    category: 'SQL 서브쿼리',
    type: 'SHORT_ANSWER',
    question: 'SQL 문장 중 메인 쿼리의 SELECT 절에 위치하여 매 행마다 단 하나의 단일 값(1행 1열)만을 반환해야 하는 서브쿼리를 무엇이라 하는가?',
    answer: '스칼라 서브쿼리',
    explanation: '스칼라 서브쿼리(Scalar Subquery)는 SELECT 절에서 사용되며 반드시 1개의 값만 반환해야 합니다.',
    difficulty: 'EASY',
    keywords: ['스칼라 서브쿼리', 'Scalar Subquery', 'SELECT절서브쿼리'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-subquery',
  },
  {
    id: 'EXP_DB1_020',
    subject: '데이터베이스구축',
    category: 'SQL 서브쿼리',
    type: 'SHORT_ANSWER',
    question: 'SQL 문장 중 메인 쿼리의 FROM 절 내부에 작성되어 마치 가상의 테이블처럼 임시로 사용되는 서브쿼리를 무엇이라 하는가?',
    answer: '인라인 뷰',
    explanation: '인라인 뷰(Inline View)는 FROM 절에 위치하는 동적 뷰 역할을 수행하는 서브쿼리입니다.',
    difficulty: 'EASY',
    keywords: ['인라인 뷰', 'Inline View', 'FROM절서브쿼리'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-subquery',
  },
  {
    id: 'EXP_DB1_021',
    subject: '데이터베이스구축',
    category: 'SQL 서브쿼리',
    type: 'SHORT_ANSWER',
    question: '서브쿼리가 메인 쿼리의 특정 컬럼 값을 가져와서 비교 연산에 사용함으로써, 메인 쿼리의 행 수만큼 반복 실행되는 종속적인 서브쿼리는 무엇인가?',
    answer: '상관 서브쿼리',
    explanation: '상관 서브쿼리(Correlated Subquery)는 메인 쿼리와 종속 관계를 가지며 EXISTS 조건 등과 함께 자주 쓰입니다.',
    difficulty: 'MEDIUM',
    keywords: ['상관 서브쿼리', 'Correlated Subquery', '메인쿼리참조'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-subquery',
  },
  {
    id: 'EXP_DB1_022',
    subject: '데이터베이스구축',
    category: 'SQL 서브쿼리',
    type: 'SHORT_ANSWER',
    question: '다중 행 서브쿼리 연산자 중 서브쿼리의 반환 결과에 해당하는 레코드가 최소 1건이라도 존재하는지 여부만을 판단하여 참/거짓을 반환하는 연산자는 무엇인가?',
    answer: 'EXISTS',
    explanation: 'EXISTS 연산자는 조건에 맞는 행이 1개라도 발견되면 즉시 스캔을 멈추고 TRUE를 반환하므로 성능상 매우 유리합니다.',
    difficulty: 'EASY',
    keywords: ['EXISTS', '존재여부확인', '다중행연산자'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-subquery',
  },
  {
    id: 'EXP_DB1_023',
    subject: '데이터베이스구축',
    category: 'SQL 조인',
    type: 'SHORT_ANSWER',
    question: '두 테이블을 조인할 때 조인 조건에 일치하지 않는 왼쪽 테이블의 모든 행도 버리지 않고 결과에 포함시키는 외부 조인(Outer Join)의 명칭은 무엇인가?',
    answer: 'LEFT OUTER JOIN',
    explanation: 'LEFT OUTER JOIN은 왼쪽 테이블의 모든 행을 유지하며, 일치하지 않는 오른쪽 테이블의 컬럼은 NULL로 채웁니다.',
    difficulty: 'EASY',
    keywords: ['LEFT OUTER JOIN', '왼쪽외부조인', '조인'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-join',
  },
  {
    id: 'EXP_DB1_024',
    subject: '데이터베이스구축',
    category: 'SQL 조인',
    type: 'SHORT_ANSWER',
    question: '조인 조건절(ON) 없이 두 테이블을 단순 연결하여 왼쪽 테이블 m개 행과 오른쪽 테이블 n개 행의 모든 조합인 m x n개의 행을 반환하는 조인은 무엇인가?',
    answer: 'CROSS JOIN',
    explanation: 'CROSS JOIN(카티션 프로덕트, 교차 조인)은 두 테이블 간의 모든 카티션 곱 조합을 산출합니다.',
    difficulty: 'EASY',
    keywords: ['CROSS JOIN', '카티션곱', '교차조인'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-join',
  },
  {
    id: 'EXP_DB1_025',
    subject: '데이터베이스구축',
    category: 'SQL 조인',
    type: 'SHORT_ANSWER',
    question: '동일한 하나의 테이블을 서로 다른 별칭(Alias)을 부여하여 자기 자신과 결합하는 형태의 조인을 무엇이라 하는가?',
    answer: '셀프 조인',
    explanation: '셀프 조인(Self Join)은 사원과 관리자 관계처럼 계층 구조나 부모-자식 관계가 한 테이블 내에 있을 때 사용합니다.',
    difficulty: 'EASY',
    keywords: ['셀프 조인', 'Self Join', '자가조인'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-join',
  },
  {
    id: 'EXP_DB1_026',
    subject: '데이터베이스구축',
    category: 'SQL DML',
    type: 'SHORT_ANSWER',
    question: '기존 테이블에 조건에 따라 행이 이미 존재하면 UPDATE를 수행하고, 존재하지 않으면 신규 행으로 INSERT를 한 번에 처리하는 SQL 문장은 무엇인가?',
    answer: 'MERGE',
    explanation: 'MERGE(Upsert) 문은 WHEN MATCHED THEN UPDATE와 WHEN NOT MATCHED THEN INSERT 절을 결합해 병합합니다.',
    difficulty: 'EASY',
    keywords: ['MERGE', 'Upsert', '병합문'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-dml',
  },
  {
    id: 'EXP_DB1_027',
    subject: '데이터베이스구축',
    category: 'SQL DML',
    type: 'SHORT_ANSWER',
    question: 'SELECT 문에서 검색 결과의 중복 행을 제거하고 유일한 고유값만 출력하도록 지시하는 키워드는 무엇인가?',
    answer: 'DISTINCT',
    explanation: 'DISTINCT 키워드는 중복 행을 정렬 및 필터링하여 유일한 행들만 반환합니다.',
    difficulty: 'EASY',
    keywords: ['DISTINCT', '중복제거', 'SELECT문'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-dml',
  },
  {
    id: 'EXP_DB1_028',
    subject: '데이터베이스구축',
    category: 'SQL DML',
    type: 'SHORT_ANSWER',
    question: 'SQL 집계 함수 결과에 대한 필터링 조건(예: 부서별 인원수가 5명 이상)을 지정할 때 WHERE 절 대신 반드시 사용해야 하는 절은 무엇인가?',
    answer: 'HAVING',
    explanation: 'HAVING 절은 GROUP BY로 묶인 그룹 집계 결과에 조건을 부여할 때 씁니다. 개별 행 조건은 WHERE 절에 씁니다.',
    difficulty: 'EASY',
    keywords: ['HAVING', '그룹조건', '집계함수필터'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-dml',
  },
  {
    id: 'EXP_DB1_029',
    subject: '데이터베이스구축',
    category: 'SQL DCL',
    type: 'SHORT_ANSWER',
    question: '데이터베이스 사용자에게 특정 권한(SELECT, INSERT 등)을 부여할 때 사용하는 DCL 명령어는 무엇인가?',
    answer: 'GRANT',
    explanation: 'GRANT는 권한을 부여하고, 부여된 권한을 회수할 때는 REVOKE 명령어를 씁니다.',
    difficulty: 'EASY',
    keywords: ['GRANT', '권한부여', 'DCL'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-dcl',
  },
  {
    id: 'EXP_DB1_030',
    subject: '데이터베이스구축',
    category: 'SQL DCL',
    type: 'SHORT_ANSWER',
    question: '데이터베이스 사용자에게 부여했던 특정 권한을 다시 회수(취소)할 때 사용하는 DCL 명령어는 무엇인가?',
    answer: 'REVOKE',
    explanation: 'REVOKE는 권한을 회수하며 CASCADE 옵션을 주면 해당 사용자가 다른 사용자에게 연쇄 부여한 권한도 함께 회수됩니다.',
    difficulty: 'EASY',
    keywords: ['REVOKE', '권한회수', 'DCL'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-dcl',
  },
  {
    id: 'EXP_DB1_031',
    subject: '데이터베이스구축',
    category: 'SQL DCL',
    type: 'SHORT_ANSWER',
    question: 'GRANT 문으로 권한을 부여할 때 권한을 부여받은 사용자가 자신이 받은 권한을 다른 제3의 사용자에게도 재부여할 수 있도록 허용하는 옵션은 무엇인가?',
    answer: 'WITH GRANT OPTION',
    explanation: 'WITH GRANT OPTION은 일반 객체 권한을 다른 사용자에게 위임할 수 있는 전파 권한 옵션입니다.',
    difficulty: 'MEDIUM',
    keywords: ['WITH GRANT OPTION', '권한전파', 'DCL'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-dcl',
  },
  {
    id: 'EXP_DB1_032',
    subject: '데이터베이스구축',
    category: 'SQL TCL',
    type: 'SHORT_ANSWER',
    question: '트랜잭션 실행 중 오류가 발생했을 때 전체를 취소하지 않고 특정 지정 시점까지만 부분 취소(Rollback)할 수 있도록 설정하는 저장점 지정 명령어는 무엇인가?',
    answer: 'SAVEPOINT',
    explanation: 'SAVEPOINT 저장점명을 선언해두면 ROLLBACK TO 저장점명 명령으로 해당 지점까지의 작업만 부분 취소할 수 있습니다.',
    difficulty: 'EASY',
    keywords: ['SAVEPOINT', '저장점', '부분롤백'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-tcl',
  },
  {
    id: 'EXP_DB1_033',
    subject: '데이터베이스구축',
    category: 'SQL 내장 함수',
    type: 'SHORT_ANSWER',
    question: 'SQL 문자열 함수 중 특정 문자열에서 원하는 시작 위치부터 지정한 개수만큼의 부분 문자열을 잘라내어 추출하는 함수의 이름은 무엇인가?',
    answer: 'SUBSTR',
    explanation: 'SUBSTR(str, pos, len)은 pos 위치부터 len개의 문자를 추출합니다.',
    difficulty: 'EASY',
    keywords: ['SUBSTR', '부분문자열', '문자열함수'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-functions',
  },
  {
    id: 'EXP_DB1_034',
    subject: '데이터베이스구축',
    category: 'SQL 내장 함수',
    type: 'SHORT_ANSWER',
    question: 'SQL 문자열의 양쪽 끝에 존재하는 불필요한 공백 문자나 특정 지정 문자를 잘라내어 제거하는 함수의 이름은 무엇인가?',
    answer: 'TRIM',
    explanation: 'TRIM(str)은 앞뒤 공백을 제거합니다. 왼쪽만 제거는 LTRIM, 오른쪽만 제거는 RTRIM입니다.',
    difficulty: 'EASY',
    keywords: ['TRIM', '공백제거', '문자열함수'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-functions',
  },
  {
    id: 'EXP_DB1_035',
    subject: '데이터베이스구축',
    category: 'SQL 조건 표현식',
    type: 'SHORT_ANSWER',
    question: 'SQL에서 프로그래밍 언어의 if-else 조건문과 유사하게 조건에 따라 분기하여 다른 값을 반환할 때 사용하는 표준 표현식은 무엇인가?',
    answer: 'CASE',
    explanation: 'CASE WHEN 조건 THEN 결과 ELSE 기본값 END 구조로 조건 분기를 처리합니다.',
    difficulty: 'EASY',
    keywords: ['CASE', 'CASE WHEN', '조건식'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-functions',
  },
  {
    id: 'EXP_DB1_036',
    subject: '데이터베이스구축',
    category: 'SQL 뷰',
    type: 'SHORT_ANSWER',
    question: '뷰(View)를 정의할 때 WHERE 절의 조건에 위배되는 튜플의 INSERT나 UPDATE 연산이 실행되지 못하도록 차단하는 뷰 생성 옵션은 무엇인가?',
    answer: 'WITH CHECK OPTION',
    explanation: 'CREATE VIEW ... WITH CHECK OPTION은 뷰 정의 조건식을 벗어나는 데이터 변경을 원천 거절하여 데이터 무결성을 보장합니다.',
    difficulty: 'MEDIUM',
    keywords: ['WITH CHECK OPTION', '뷰제약옵션', '무결성'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-view',
  },
  {
    id: 'EXP_DB1_037',
    subject: '데이터베이스구축',
    category: 'SQL 뷰',
    type: 'SHORT_ANSWER',
    question: '뷰(View) 생성 시 사용자가 뷰를 통해 기본 테이블의 데이터를 조회(SELECT)만 할 수 있고 INSERT, UPDATE, DELETE 수정은 절대 하지 못하도록 강제하는 옵션은 무엇인가?',
    answer: 'WITH READ ONLY',
    explanation: 'WITH READ ONLY 옵션을 추가하면 해당 뷰는 읽기 전용으로 설정되어 데이터 변경 시도가 차단됩니다.',
    difficulty: 'EASY',
    keywords: ['WITH READ ONLY', '읽기전용뷰', '뷰옵션'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-view',
  },
  {
    id: 'EXP_DB1_038',
    subject: '데이터베이스구축',
    category: '데이터베이스 객체',
    type: 'SHORT_ANSWER',
    question: '데이터베이스에서 테이블의 특정 컬럼(예: 사원번호, 주문번호)에 자동으로 고유한 연속 번호를 생성해주는 객체의 이름은 무엇인가?',
    answer: '시퀀스',
    explanation: '시퀀스(Sequence)는 일련번호를 자동으로 생성하며 .NEXTVAL로 다음 번호를 발급받습니다.',
    difficulty: 'EASY',
    keywords: ['시퀀스', 'Sequence', '일련번호생성'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-objects',
  },
  {
    id: 'EXP_DB1_039',
    subject: '데이터베이스구축',
    category: '데이터베이스 객체',
    type: 'SHORT_ANSWER',
    question: '데이터베이스 객체(테이블, 뷰 등)에 영구적인 별칭을 붙여 긴 스키마명을 생략하거나 보안상 실제 테이블명을 감출 때 사용하는 데이터베이스 객체는 무엇인가?',
    answer: '동의어',
    explanation: '동의어(Synonym)는 실제 객체에 별칭을 부여하여 객체 접근의 투명성과 보안성을 높입니다.',
    difficulty: 'MEDIUM',
    keywords: ['동의어', 'Synonym', '객체별칭'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-objects',
  },
  {
    id: 'EXP_DB1_040',
    subject: '데이터베이스구축',
    category: 'SQL 연산자',
    type: 'SHORT_ANSWER',
    question: 'SQL WHERE 절에서 와일드카드 문자 중 임의의 문자 단 1글자와 매칭될 때 사용하는 기호는 무엇인가?',
    answer: '_',
    explanation: '_(언더스코어)는 정확히 1글자와 매칭되며, 0개 이상의 모든 문자열과 매칭되는 것은 %(퍼센트)입니다.',
    difficulty: 'EASY',
    keywords: ['_', '언더스코어', '와일드카드'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-dml',
  },
  {
    id: 'EXP_DB1_041',
    subject: '데이터베이스구축',
    category: 'SQL 연산자',
    type: 'SHORT_ANSWER',
    question: 'SQL WHERE 절에서 특정 속성의 값이 NULL인지 확인할 때 = NULL 대신 반드시 사용해야 하는 올바른 연산 구문은 무엇인가?',
    answer: 'IS NULL',
    explanation: 'NULL은 알 수 없는(Unknown) 값이므로 = 연산자로 비교할 수 없으며 IS NULL 또는 IS NOT NULL 구문을 써야 합니다.',
    difficulty: 'EASY',
    keywords: ['IS NULL', 'NULL비교연산자'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-dml',
  },
  {
    id: 'EXP_DB1_042',
    subject: '데이터베이스구축',
    category: 'SQL 연산자',
    type: 'SHORT_ANSWER',
    question: 'SQL WHERE 절에서 특정 컬럼의 값이 주어진 범위(하한값 이상, 상한값 이하)에 속하는지 검사할 때 사용하는 연산자는 무엇인가?',
    answer: 'BETWEEN',
    explanation: '컬럼명 BETWEEN a AND b 구문은 a 이상 b 이하의 범위를 나타내며 양 끝값(a, b)을 모두 포함합니다.',
    difficulty: 'EASY',
    keywords: ['BETWEEN', '범위연산자', 'BETWEEN AND'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-dml',
  },
  {
    id: 'EXP_DB1_043',
    subject: '데이터베이스구축',
    category: 'SQL 연산자',
    type: 'SHORT_ANSWER',
    question: 'SQL WHERE 절에서 특정 컬럼의 값이 나열된 리스트 안의 값 중 하나와 일치하는지 검사할 때 사용하는 다중 OR 대체 연산자는 무엇인가?',
    answer: 'IN',
    explanation: '컬럼명 IN (val1, val2, val3) 연산자는 목록 내 일치하는 값이 있는지 검사합니다.',
    difficulty: 'EASY',
    keywords: ['IN', '리스트일치연산자'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-dml',
  },
  {
    id: 'EXP_DB1_044',
    subject: '데이터베이스구축',
    category: 'SQL 집합 연산자',
    type: 'SHORT_ANSWER',
    question: '두 SELECT 문의 실행 결과를 합치되 중복 행을 제거하지 않고 모든 행을 그대로 유지하여 출력하는 집합 연산자는 무엇인가?',
    answer: 'UNION ALL',
    explanation: 'UNION ALL은 중복 제거를 위한 정렬 작업을 수행하지 않으므로 UNION보다 실행 속도가 훨씬 빠릅니다.',
    difficulty: 'EASY',
    keywords: ['UNION ALL', '중복포함합집합', '집합연산자'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-set',
  },
  {
    id: 'EXP_DB1_045',
    subject: '데이터베이스구축',
    category: 'SQL 집합 연산자',
    type: 'SHORT_ANSWER',
    question: '첫 번째 SELECT 문의 결과에서 두 번째 SELECT 문의 결과에 포함된 공통 행들을 제외한 차집합 결과를 반환하는 표준 연산자(Oracle의 MINUS와 동등)는 무엇인가?',
    answer: 'EXCEPT',
    explanation: 'SQL 표준에서 차집합 연산자는 EXCEPT이며 오라클에서는 MINUS 키워드를 지원합니다.',
    difficulty: 'EASY',
    keywords: ['EXCEPT', 'MINUS', '차집합연산자'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-set',
  },
  {
    id: 'EXP_DB1_046',
    subject: '데이터베이스구축',
    category: 'SQL 집합 연산자',
    type: 'SHORT_ANSWER',
    question: '두 SELECT 문의 결과에서 양쪽에 공통으로 존재하는 교집합 행들만을 중복을 제거하여 반환하는 SQL 집합 연산자는 무엇인가?',
    answer: 'INTERSECT',
    explanation: 'INTERSECT는 두 쿼리 결과의 공통 행만을 추출하는 교집합 연산자입니다.',
    difficulty: 'EASY',
    keywords: ['INTERSECT', '교집합연산자', '집합연산자'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-set',
  },
  {
    id: 'EXP_DB1_047',
    subject: '데이터베이스구축',
    category: 'SQL 조인',
    type: 'SHORT_ANSWER',
    question: '두 테이블에서 공통으로 존재하는 동일한 이름과 타입을 가진 모든 컬럼을 기준으로 자동으로 등가(=) 조인을 수행하는 조인 구문은 무엇인가?',
    answer: 'NATURAL JOIN',
    explanation: 'NATURAL JOIN은 동일한 이름의 컬럼들을 자동으로 매칭하여 조인하며 별도의 ON이나 USING 절을 쓸 수 없습니다.',
    difficulty: 'EASY',
    keywords: ['NATURAL JOIN', '자연조인', '동일컬럼자동조인'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-join',
  },
  {
    id: 'EXP_DB1_048',
    subject: '데이터베이스구축',
    category: 'SQL 조인',
    type: 'SHORT_ANSWER',
    question: '조인 조건으로 등호(=) 연산자 대신 부등호(<, >, <=, >=)나 BETWEEN 연산자 등을 사용하는 조인을 무엇이라 하는가?',
    answer: '비등가 조인',
    explanation: '비등가 조인(Non-Equi Join)은 급여 등급 테이블처럼 값이 특정 구간 범위에 들어맞는지 비교할 때 사용합니다.',
    difficulty: 'EASY',
    keywords: ['비등가 조인', 'Non-Equi Join', '부등호조인'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-join',
  },
  {
    id: 'EXP_DB1_049',
    subject: '데이터베이스구축',
    category: '데이터베이스 언어',
    type: 'SHORT_ANSWER',
    question: 'SQL을 관계대수와 관계해석의 관점에서 분류할 때, 사용자가 "무엇(What)"을 원하는지만 선언하고 "어떻게(How)" 유도할지는 기술하지 않는 비절차적 특성을 갖는 기초 이론은 무엇인가?',
    answer: '관계해석',
    explanation: '관계해석(Relational Calculus)은 원하는 결과(What)만을 명시하는 비절차적 언어입니다. 절차적 연산 순서를 명시하는 것은 관계대수(Relational Algebra)입니다.',
    difficulty: 'MEDIUM',
    keywords: ['관계해석', '비절차적언어', 'What'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-theory',
  },
  {
    id: 'EXP_DB1_050',
    subject: '데이터베이스구축',
    category: 'SQL DML',
    type: 'SHORT_ANSWER',
    question: 'SELECT 문에서 정렬 기준을 명시하는 ORDER BY 절에서 오름차순과 내림차순 정렬을 지정할 때 각각 사용하는 예약어 2가지는 무엇인가?',
    answer: 'ASC, DESC',
    explanation: 'ASC는 오름차순(기본값), DESC는 내림차순 정렬 예약어입니다.',
    difficulty: 'EASY',
    keywords: ['ASC, DESC', 'ORDER BY', '정렬예약어'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-db-dml',
  },
];
