import { Question } from '../../src/types/question';

export const BATCH_3_QUESTIONS: Question[] = [
  {
    id: 'EXP_SE1_001',
    subject: '소프트웨어설계',
    category: '요구사항',
    type: 'SHORT_ANSWER',
    question: '요구사항 검증 기법 중 작성자가 요구사항 명세서를 설명하고 동료들이 결함을 찾아내는 비공식적이고 가장 친숙한 검토 회의 기법은 무엇인가?',
    answer: '워크스루',
    explanation: '워크스루(Walkthrough)는 개발자 주도의 비공식적 결함 검출 회의입니다. 정해진 절차와 역할을 맡아 체크리스트로 공식 검토하는 것은 인스펙션(Inspection)입니다.',
    difficulty: 'EASY',
    keywords: ['워크스루', 'Walkthrough', '요구사항검증'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-requirements',
  },
  {
    id: 'EXP_SE1_002',
    subject: '소프트웨어설계',
    category: '요구사항',
    type: 'SHORT_ANSWER',
    question: '소프트웨어 개발 표준에 맞춰 작성된 명세서의 결함을 체크리스트를 기반으로 정형화된 공식 절차에 따라 저작자를 제외한 전문가들이 팀을 이뤄 검토하는 기법은 무엇인가?',
    answer: '인스펙션',
    explanation: '인스펙션(Inspection, 파간 인스펙션)은 주재자(Moderator), 낭독자, 기록자 등의 역할을 나누어 결함을 공식적으로 기록/측정하는 최고 수준의 정형 검토 기법입니다.',
    difficulty: 'EASY',
    keywords: ['인스펙션', 'Inspection', '공식검토'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-requirements',
  },
  {
    id: 'EXP_SE1_003',
    subject: '소프트웨어설계',
    category: '요구사항',
    type: 'SHORT_ANSWER',
    question: '요구사항 검토 방법 중 2~3명의 동료 개발자가 명세서 작성자와 함께 편안한 분위기에서 명세서를 읽으며 오류를 찾는 검토 기법은 무엇인가?',
    answer: '동료 검토',
    explanation: '동료 검토(Peer Review)는 작성자가 동료들에게 작업물을 설명하고 피드백을 받는 비공식 검토 방식입니다.',
    difficulty: 'EASY',
    keywords: ['동료 검토', 'Peer Review', '요구사항검토'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-requirements',
  },
  {
    id: 'EXP_SE1_004',
    subject: '소프트웨어설계',
    category: '디자인 패턴',
    type: 'SHORT_ANSWER',
    question: 'GoF 디자인 패턴 중 문법 규칙을 클래스로 표현하여 특정 언어나 표기법으로 작성된 문장을 해석하고 평가하는 행위 패턴은 무엇인가?',
    answer: '인터프리터',
    explanation: '인터프리터(Interpreter, 해석자) 패턴은 SQL 파서나 정규식 파서처럼 언어의 문법 정의를 클래스로 캡슐화하여 문장을 구문 분석할 때 쓰입니다.',
    difficulty: 'MEDIUM',
    keywords: ['인터프리터', 'Interpreter', 'GoF행위패턴'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-design-patterns',
  },
  {
    id: 'EXP_SE1_005',
    subject: '소프트웨어설계',
    category: '디자인 패턴',
    type: 'SHORT_ANSWER',
    question: 'GoF 디자인 패턴 중 요청을 처리할 수 있는 객체들을 체인(사슬) 형태로 연결해두고 요청을 처리할 때까지 순차적으로 넘기는 행위 패턴은 무엇인가?',
    answer: '책임 연쇄',
    explanation: '책임 연쇄(Chain of Responsibility) 패턴은 송신자와 수신자의 결합도를 낮추고 다수의 처리 객체가 요청을 다음 객체로 전달할 수 있게 합니다.',
    difficulty: 'MEDIUM',
    keywords: ['책임 연쇄', 'Chain of Responsibility', '사슬패턴'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-design-patterns',
  },
  {
    id: 'EXP_SE1_006',
    subject: '소프트웨어설계',
    category: '소프트웨어 아키텍처',
    type: 'SHORT_ANSWER',
    question: '소프트웨어 아키텍처 4+1 뷰 중 시스템의 비기능적 요구사항인 동시성, 병렬 처리, 스레드, 성능, 동기화 관점을 표현하는 뷰는 무엇인가?',
    answer: '프로세스 뷰',
    explanation: '프로세스 뷰(Process View)는 런타임 시점의 프로세스 흐름, 스레드 제어, 시스템 통합 성능을 다룹니다.',
    difficulty: 'MEDIUM',
    keywords: ['프로세스 뷰', 'Process View', '동시성'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-architecture',
  },
  {
    id: 'EXP_SE1_007',
    subject: '소프트웨어설계',
    category: '소프트웨어 아키텍처',
    type: 'SHORT_ANSWER',
    question: '소프트웨어 아키텍처 4+1 뷰 중 소스코드의 정적 조직 구조, 컴포넌트, 모듈, 서브시스템의 물리적 구성과 패키징 관점을 다루는 뷰는 무엇인가?',
    answer: '구현 뷰',
    explanation: '구현 뷰(Implementation View, 개발 뷰)는 개발자 관점에서 소프트웨어 모듈들의 물리적 구조와 형상을 표현합니다.',
    difficulty: 'MEDIUM',
    keywords: ['구현 뷰', 'Implementation View', '개발뷰'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-architecture',
  },
  {
    id: 'EXP_SE1_008',
    subject: '소프트웨어설계',
    category: '소프트웨어 아키텍처',
    type: 'SHORT_ANSWER',
    question: '소프트웨어 아키텍처 4+1 뷰 중 소프트웨어 컴포넌트가 실제 서버 노드, 하드웨어 장비, 물리적 네트워크에 어떻게 배치되는지 표현하는 뷰는 무엇인가?',
    answer: '배포 뷰',
    explanation: '배포 뷰(Deployment View)는 인프라 및 시스템 엔지니어 관점에서 물리적 노드와 네트워크 구성을 표현합니다.',
    difficulty: 'MEDIUM',
    keywords: ['배포 뷰', 'Deployment View', '하드웨어매핑'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-architecture',
  },
  {
    id: 'EXP_SE1_009',
    subject: '소프트웨어설계',
    category: '소프트웨어 아키텍처',
    type: 'SHORT_ANSWER',
    question: '소프트웨어 아키텍처 4+1 뷰에서 나머지 4개의 뷰(논리, 프로세스, 구현, 배포)를 검증하고 통합하는 기준이 되는 중심 뷰는 무엇인가?',
    answer: '유스케이스 뷰',
    explanation: '유스케이스 뷰(Use Case View, 시나리오 뷰)는 최종 사용자의 관점에서 시스템의 핵심 요구 기능을 시나리오로 표현하며 나머지 4개 뷰의 중심 축(1)이 됩니다.',
    difficulty: 'EASY',
    keywords: ['유스케이스 뷰', 'Use Case View', '4+1뷰'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-architecture',
  },
  {
    id: 'EXP_SE1_010',
    subject: '소프트웨어설계',
    category: 'UI 설계',
    type: 'SHORT_ANSWER',
    question: 'UI 설계 4대 원칙 중 사용자가 UI의 기능과 조작법을 초보자라도 별도의 학습 부담 없이 쉽고 빠르게 익힐 수 있어야 한다는 원칙은 무엇인가?',
    answer: '학습성',
    explanation: '학습성(Learnability)은 누구나 쉽게 시스템 사용법을 배울 수 있어야 한다는 원칙입니다.',
    difficulty: 'EASY',
    keywords: ['학습성', 'Learnability', 'UI원칙'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-ui',
  },
  {
    id: 'EXP_SE1_011',
    subject: '소프트웨어설계',
    category: 'UI 설계',
    type: 'SHORT_ANSWER',
    question: 'UI 설계 4대 원칙 중 사용자의 다양한 요구사항을 최대한 수용하고 인터랙션 과정의 실수를 쉽게 수정할 수 있어야 한다는 원칙은 무엇인가?',
    answer: '유연성',
    explanation: '유연성(Flexibility)은 사용자의 인터랙션 스타일을 유연하게 포용하고 오류 발생 시 손쉽게 되돌릴 수 있어야 한다는 원칙입니다.',
    difficulty: 'EASY',
    keywords: ['유연성', 'Flexibility', 'UI원칙'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-ui',
  },
  {
    id: 'EXP_SE1_012',
    subject: '소프트웨어설계',
    category: 'UML',
    type: 'SHORT_ANSWER',
    question: 'UML 유스케이스 다이어그램에서 한 유스케이스가 정상 동작하기 위해 다른 유스케이스를 조건 없이 반드시 실행해야 하는 관계를 나타내는 스테레오타입은 무엇인가?',
    answer: '<<include>>',
    explanation: '포함 관계(<<include>>)는 필수적인 공통 기능을 재사용할 때 쓰입니다. 특정 조건 만족 시에만 선택적으로 확장되는 것은 <<extend>> 입니다.',
    difficulty: 'EASY',
    keywords: ['<<include>>', '포함관계', '스테레오타입'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-uml',
  },
  {
    id: 'EXP_SE1_013',
    subject: '소프트웨어설계',
    category: 'UML',
    type: 'SHORT_ANSWER',
    question: 'UML 유스케이스 다이어그램에서 특정 예외 상황이나 확장 조건을 만족할 때만 선택적으로 기본 유스케이스에 기능을 덧붙이는 관계를 나타내는 스테레오타입은 무엇인가?',
    answer: '<<extend>>',
    explanation: '확장 관계(<<extend>>)는 부가적이고 선택적인 기능을 분리할 때 사용합니다.',
    difficulty: 'EASY',
    keywords: ['<<extend>>', '확장관계', '스테레오타입'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-uml',
  },
  {
    id: 'EXP_SE1_014',
    subject: '소프트웨어설계',
    category: 'UML',
    type: 'SHORT_ANSWER',
    question: 'UML 관계 중 하위 요소가 상위 일반화된 요소의 속성과 연산을 물려받는 상속 관계를 나타내는 관계 유형의 이름은 무엇인가?',
    answer: '일반화 관계',
    explanation: '일반화 관계(Generalization)는 객체지향의 상속(is-a) 관계를 뜻하며 속이 빈 삼각형 실선 화살표로 표현합니다.',
    difficulty: 'EASY',
    keywords: ['일반화 관계', 'Generalization', '상속관계'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-uml',
  },
  {
    id: 'EXP_SE1_015',
    subject: '소프트웨어설계',
    category: 'UML',
    type: 'SHORT_ANSWER',
    question: 'UML 관계 중 한 클래스가 다른 클래스를 메서드의 매개변수나 로컬 변수로 잠시 참조하여 짧은 기간만 영향을 주고받는 관계를 나타내는 유형은 무엇인가?',
    answer: '의존 관계',
    explanation: '의존 관계(Dependency)는 한 클래스의 변화가 일시적으로 다른 클래스에 영향을 미치는 관계이며 점선 화살표로 표시합니다.',
    difficulty: 'EASY',
    keywords: ['의존 관계', 'Dependency', '점선화살표'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-uml',
  },
  {
    id: 'EXP_SE1_016',
    subject: '소프트웨어설계',
    category: 'UML',
    type: 'SHORT_ANSWER',
    question: 'UML 클래스 다이어그램에서 인터페이스에 정의된 추상 메서드를 구체 클래스가 실제로 구현하는 관계를 나타내는 관계 유형의 이름은 무엇인가?',
    answer: '실체화 관계',
    explanation: '실체화 관계(Realization)는 인터페이스 구현을 나타내며 속이 빈 삼각형 점선 화살표로 표기합니다.',
    difficulty: 'EASY',
    keywords: ['실체화 관계', 'Realization', '인터페이스구현'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-uml',
  },
  {
    id: 'EXP_SE1_017',
    subject: '소프트웨어설계',
    category: '소프트웨어 재공학',
    type: 'SHORT_ANSWER',
    question: '기존에 작성된 레거시 시스템의 소스코드나 실행 바이너리를 역으로 분석하여 설계 문서, 사양서, 데이터 모델 등을 복원 추출해내는 소프트웨어 재공학 활동은 무엇인가?',
    answer: '역공학',
    explanation: '역공학(Reverse Engineering)은 완성된 소프트웨어를 거꾸로 추적하여 상위의 설계서와 요구사항을 도출하는 기법입니다.',
    difficulty: 'EASY',
    keywords: ['역공학', 'Reverse Engineering', '소프트웨어재공학'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-reengineering',
  },
  {
    id: 'EXP_SE1_018',
    subject: '소프트웨어설계',
    category: '소프트웨어 재공학',
    type: 'SHORT_ANSWER',
    question: '소프트웨어의 외적인 동작과 기능은 그대로 유지하면서 내부 구조(소스코드)를 개선하여 가독성과 유지보수성을 향상시키는 재공학 활동은 무엇인가?',
    answer: '리팩토링',
    explanation: '리팩토링(Refactoring) 또는 코드 재구성은 결과 동작을 바꾸지 않고 코드 악취(Code Smell)를 제거하는 내부 구조 개선 활동입니다.',
    difficulty: 'EASY',
    keywords: ['리팩토링', 'Refactoring', '코드개선'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-reengineering',
  },
  {
    id: 'EXP_SE1_019',
    subject: '소프트웨어설계',
    category: '소프트웨어 재공학',
    type: 'SHORT_ANSWER',
    question: '기존 소프트웨어 시스템을 완전히 새로운 운영체제, 하드웨어 플랫폼, 데이터베이스 환경으로 옮겨 설치하고 실행할 수 있도록 변환하는 재공학 활동은 무엇인가?',
    answer: '이관',
    explanation: '이관(Migration)은 소프트웨어의 본래 가치를 유지하면서 새 플랫폼 환경으로 옮기는 활동입니다.',
    difficulty: 'EASY',
    keywords: ['이관', 'Migration', '플랫폼이전'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-reengineering',
  },
  {
    id: 'EXP_SE1_020',
    subject: '소프트웨어설계',
    category: '럼바우 분석',
    type: 'SHORT_ANSWER',
    question: '럼바우(Rumbaugh) 객체지향 분석 기법의 3대 모델링 중 자료 흐름도(DFD)를 주 도구로 사용하여 입력에 따른 데이터 처리와 계산 과정을 표현하는 모델링은 무엇인가?',
    answer: '기능 모델링',
    explanation: '기능 모델링(Functional Modeling)은 DFD를 사용합니다. 상태 다이어그램을 쓰는 것은 동적 모델링, ERD/객체도를 쓰는 것은 객체 모델링입니다.',
    difficulty: 'EASY',
    keywords: ['기능 모델링', 'DFD', '자료흐름도'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-rumbaugh',
  },
  {
    id: 'EXP_SE1_021',
    subject: '소프트웨어설계',
    category: '애자일',
    type: 'SHORT_ANSWER',
    question: '스크럼(Scrum)에서 스프린트 기간 동안 매일 서서 짧게(15분 내외) 어제 한 일, 오늘 할 일, 문제점을 공유하는 일일 회의의 명칭은 무엇인가?',
    answer: '데일리 스크럼',
    explanation: '데일리 스크럼(Daily Scrum, 일일 스탠드업 미팅)은 팀원 간의 진행 상황을 빠르게 동기화하고 장애물을 조기 식별합니다.',
    difficulty: 'EASY',
    keywords: ['데일리 스크럼', 'Daily Scrum', '스탠드업미팅'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-agile',
  },
  {
    id: 'EXP_SE1_022',
    subject: '소프트웨어설계',
    category: '애자일',
    type: 'SHORT_ANSWER',
    question: '애자일 프로젝트에서 시간의 흐름에 따라 남아있는 작업량(남은 스토리 포인트나 시간)이 줄어드는 추세를 시각적으로 추적하는 차트의 명칭은 무엇인가?',
    answer: '번다운 차트',
    explanation: '번다운 차트(Burn-down Chart)는 계획된 작업 대비 실제 소진 속도를 비교하여 스프린트 완료 가능성을 예측합니다.',
    difficulty: 'EASY',
    keywords: ['번다운 차트', 'Burn-down Chart', '애자일차트'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-agile',
  },
  {
    id: 'EXP_SE1_023',
    subject: '소프트웨어설계',
    category: '애자일',
    type: 'SHORT_ANSWER',
    question: '스크럼에서 하나의 스프린트가 완료되었을 때 팀이 모여 프로세스상의 좋았던 점과 개선할 점을 솔직하게 되돌아보고 다음 스프린트에 반영하는 회의는 무엇인가?',
    answer: '스프린트 회고',
    explanation: '스프린트 회고(Sprint Retrospective)는 팀의 지속적인 성장과 프로세스 개선을 위한 정기 피드백 미팅입니다.',
    difficulty: 'EASY',
    keywords: ['스프린트 회고', 'Retrospective', '회고회의'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-agile',
  },
  {
    id: 'EXP_SE1_024',
    subject: '소프트웨어설계',
    category: 'UI 설계',
    type: 'SHORT_ANSWER',
    question: 'UI 설계 도구 중 기획 초기 단계에 레이아웃, 버튼 위치 등 화면의 골격을 흑백 선과 상자로 단순하게 스케치하는 정적 산출물은 무엇인가?',
    answer: '와이어프레임',
    explanation: '와이어프레임(Wireframe)은 UI의 뼈대 구조를 잡는 초기 설계도입니다. 색상과 실제 디자인이 들어간 완성형 정적 화면은 목업(Mockup)입니다.',
    difficulty: 'EASY',
    keywords: ['와이어프레임', 'Wireframe', 'UI골격'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-ui',
  },
  {
    id: 'EXP_SE1_025',
    subject: '소프트웨어설계',
    category: 'UI 설계',
    type: 'SHORT_ANSWER',
    question: '와이어프레임에 실제 색상, 폰트, 그래픽 비주얼 디자인을 적용하여 최종 화면과 거의 유사하지만 클릭 인터랙션은 없는 정적 모형은 무엇인가?',
    answer: '목업',
    explanation: '목업(Mockup)은 비주얼 디자인이 완성된 정적 화면입니다. 실제 클릭하고 동작할 수 있게 만든 동적 모형은 프로토타입입니다.',
    difficulty: 'EASY',
    keywords: ['목업', 'Mockup', 'UI설계'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-ui',
  },
  {
    id: 'EXP_SE1_026',
    subject: '소프트웨어설계',
    category: '요구사항',
    type: 'SHORT_ANSWER',
    question: '요구사항 개발 프로세스 4단계는 도출(Elicitation) → (   ) → 명세(Specification) → 확인(Validation) 순서이다. 괄호에 들어갈 단계는 무엇인가?',
    answer: '분석',
    explanation: '요구사항 개발 4단계는 "도출 → 분석(Analysis) → 명세 → 확인"입니다. 분석 단계에서는 타당성 검토와 모델링이 이루어집니다.',
    difficulty: 'EASY',
    keywords: ['분석', '요구사항분석', '요구사항개발프로세스'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-requirements',
  },
  {
    id: 'EXP_SE1_027',
    subject: '소프트웨어설계',
    category: '요구사항',
    type: 'SHORT_ANSWER',
    question: '요구사항의 종류 중 시스템의 응답 속도, 처리량, 보안성, 가용성, 신뢰성 등 품질적 속성이나 제약 조건을 기술하는 요구사항은 무엇인가?',
    answer: '비기능적 요구사항',
    explanation: '비기능적 요구사항(Non-functional Requirements)은 시스템이 제공해야 할 성능, 보안, 제약조건 등을 정의합니다. 실제 제공할 기능을 명시하는 것은 기능적 요구사항입니다.',
    difficulty: 'EASY',
    keywords: ['비기능적 요구사항', 'Non-functional', '품질속성'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-requirements',
  },
  {
    id: 'EXP_SE1_028',
    subject: '소프트웨어설계',
    category: '객체지향 설계',
    type: 'SHORT_ANSWER',
    question: 'SOLID 원칙 중 객체는 자신이 사용하지 않는 메서드에 의존하지 않아야 하므로 거대한 인터페이스보다 명확한 다수의 작은 인터페이스로 분리하라는 원칙은 무엇인가?',
    answer: '인터페이스 분리 원칙',
    explanation: '인터페이스 분리 원칙(ISP, Interface Segregation Principle)은 클라이언트에 특화된 세분화된 인터페이스를 지향합니다.',
    difficulty: 'EASY',
    keywords: ['인터페이스 분리 원칙', 'ISP', 'SOLID'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-solid',
  },
  {
    id: 'EXP_SE1_029',
    subject: '소프트웨어설계',
    category: '객체지향 설계',
    type: 'SHORT_ANSWER',
    question: 'SOLID 원칙 중 상위 모듈은 하위 모듈의 구체 클래스에 직접 의존하면 안 되며, 양쪽 모두 추상화(인터페이스)에 의존해야 한다는 원칙은 무엇인가?',
    answer: '의존 역전 원칙',
    explanation: '의존 역전 원칙(DIP, Dependency Inversion Principle)은 변하기 쉬운 구체 클래스 대신 변하기 어려운 추상 클래스나 인터페이스에 의존하게 합니다.',
    difficulty: 'EASY',
    keywords: ['의존 역전 원칙', 'DIP', '추상화의존'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-solid',
  },
  {
    id: 'EXP_SE1_030',
    subject: '소프트웨어설계',
    category: '객체지향 설계',
    type: 'SHORT_ANSWER',
    question: 'SOLID 원칙 중 하위 클래스는 상위 클래스의 인스턴스를 대신하여 프로그램의 정확성을 해치지 않고 어디서든 교체될 수 있어야 한다는 원칙은 무엇인가?',
    answer: '리스코프 치환 원칙',
    explanation: '리스코프 치환 원칙(LSP, Liskov Substitution Principle)은 올바른 상속 구조를 설계하여 다형성을 보장하는 규칙입니다.',
    difficulty: 'EASY',
    keywords: ['리스코프 치환 원칙', 'LSP', '하위클래스대체'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-solid',
  },
  {
    id: 'EXP_SE1_031',
    subject: '소프트웨어설계',
    category: '객체지향 설계',
    type: 'SHORT_ANSWER',
    question: 'SOLID 원칙 중 소프트웨어 개체(클래스, 모듈 등)는 기능 확장에 대해서는 열려 있어야(Open) 하고, 기존 코드 수정에 대해서는 닫혀 있어야(Closed) 한다는 원칙은 무엇인가?',
    answer: '개방 폐쇄 원칙',
    explanation: '개방 폐쇄 원칙(OCP, Open-Closed Principle)은 기존 코드를 손대지 않고 새로운 기능을 추가할 수 있도록 인터페이스를 활용하는 원칙입니다.',
    difficulty: 'EASY',
    keywords: ['개방 폐쇄 원칙', 'OCP', '기능확장'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-solid',
  },
  {
    id: 'EXP_SE1_032',
    subject: '소프트웨어설계',
    category: '객체지향 설계',
    type: 'SHORT_ANSWER',
    question: 'SOLID 원칙 중 하나의 클래스는 단 하나의 책임만을 가져야 하며, 클래스가 변경되는 이유는 단 하나뿐이어야 한다는 원칙은 무엇인가?',
    answer: '단일 책임 원칙',
    explanation: '단일 책임 원칙(SRP, Single Responsibility Principle)은 높은 응집도와 낮은 결합도를 유지하기 위한 객체지향의 기본 설계 원칙입니다.',
    difficulty: 'EASY',
    keywords: ['단일 책임 원칙', 'SRP', '단일책임'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-solid',
  },
  {
    id: 'EXP_SE1_033',
    subject: '소프트웨어설계',
    category: '모듈화',
    type: 'SHORT_ANSWER',
    question: '모듈 내부의 모든 기능 요소들이 하나의 단일한 목적이나 기능을 수행하기 위해 밀접하게 뭉쳐있는 가장 이상적이고 응집도가 높은 단계는 무엇인가?',
    answer: '기능적 응집도',
    explanation: '기능적 응집도(Functional Cohesion)는 모듈의 모든 구성요소가 오직 하나의 고유 기능만을 수행하는 가장 이상적인 응집도입니다.',
    difficulty: 'EASY',
    keywords: ['기능적 응집도', 'Functional Cohesion', '최고응집도'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-cohesion',
  },
  {
    id: 'EXP_SE1_034',
    subject: '소프트웨어설계',
    category: '모듈화',
    type: 'SHORT_ANSWER',
    question: '모듈 내부의 요소들이 서로 아무런 관련성 없이 우연히 한 모듈 안에 모여 있는 응집도가 가장 낮고 나쁜 단계는 무엇인가?',
    answer: '우연적 응집도',
    explanation: '우연적 응집도(Coincidental Cohesion)는 전혀 관련 없는 작업들이 단지 모듈 크기를 줄이기 위해 묶인 가장 나쁜 상태입니다.',
    difficulty: 'EASY',
    keywords: ['우연적 응집도', 'Coincidental Cohesion', '최저응집도'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-cohesion',
  },
  {
    id: 'EXP_SE1_035',
    subject: '소프트웨어설계',
    category: '모듈화',
    type: 'SHORT_ANSWER',
    question: '한 모듈의 출력 결과가 다음 모듈이나 요소의 입력 데이터로 순차적으로 전달되는 형태의 응집도 단계는 무엇인가?',
    answer: '순차적 응집도',
    explanation: '순차적 응집도(Sequential Cohesion)는 이전 활동의 출력이 다음 활동의 입력으로 파이프라인처럼 연결되는 응집도입니다.',
    difficulty: 'MEDIUM',
    keywords: ['순차적 응집도', 'Sequential Cohesion', '파이프라인'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-cohesion',
  },
  {
    id: 'EXP_SE1_036',
    subject: '소프트웨어설계',
    category: '모듈화',
    type: 'SHORT_ANSWER',
    question: '동일한 입력 데이터를 사용하여 서로 다른 여러 기능을 수행하거나, 동일한 출력 데이터를 산출해내는 모듈의 응집도 단계는 무엇인가?',
    answer: '통신적 응집도',
    explanation: '통신적 응집도(Communicational Cohesion, 교환적 응집도)는 모듈 내 구성요소들이 동일한 입출력 데이터를 공유할 때 나타납니다.',
    difficulty: 'MEDIUM',
    keywords: ['통신적 응집도', '교환적 응집도', '입출력공유'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-cohesion',
  },
  {
    id: 'EXP_SE1_037',
    subject: '소프트웨어설계',
    category: '모듈화',
    type: 'SHORT_ANSWER',
    question: '모듈 간에 주고받는 인터페이스가 단순한 파라미터(인자) 값으로만 구성되어 결합도가 가장 낮고 가장 좋은 단계는 무엇인가?',
    answer: '자료 결합도',
    explanation: '자료 결합도(Data Coupling)는 모듈 간 오직 필요한 단순 데이터만 값으로 전달하여 독립성이 가장 높습니다.',
    difficulty: 'EASY',
    keywords: ['자료 결합도', 'Data Coupling', '최저결합도'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-coupling',
  },
  {
    id: 'EXP_SE1_038',
    subject: '소프트웨어설계',
    category: '모듈화',
    type: 'SHORT_ANSWER',
    question: '한 모듈이 다른 모듈의 내부 코드, 지역 변수, 논리적 제어 흐름을 직접 참조하거나 수정하여 결합도가 가장 높고 가장 위험한 단계는 무엇인가?',
    answer: '내용 결합도',
    explanation: '내용 결합도(Content Coupling)는 모듈 내부를 직접 침범하는 최악의 결합도입니다.',
    difficulty: 'EASY',
    keywords: ['내용 결합도', 'Content Coupling', '최악결합도'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-coupling',
  },
  {
    id: 'EXP_SE1_039',
    subject: '소프트웨어설계',
    category: '모듈화',
    type: 'SHORT_ANSWER',
    question: '여러 모듈이 동일한 전역 변수나 글로벌 데이터 영역을 함께 공유하여 참조하고 갱신하는 모듈 간 결합도 단계는 무엇인가?',
    answer: '공통 결합도',
    explanation: '공통 결합도(Common Coupling)는 전역 변수 공유로 인해 한 모듈의 수정이 다른 모든 모듈에 파급될 위험이 큽니다.',
    difficulty: 'EASY',
    keywords: ['공통 결합도', 'Common Coupling', '전역변수'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-coupling',
  },
  {
    id: 'EXP_SE1_040',
    subject: '소프트웨어설계',
    category: '모듈화',
    type: 'SHORT_ANSWER',
    question: '두 모듈 간에 레코드나 구조체 같은 복합 자료구조 전체가 인자로 전달될 때, 호출받은 모듈이 그중 일부 필드만 사용하더라도 성립하는 결합도 단계는 무엇인가?',
    answer: '스탬프 결합도',
    explanation: '스탬프 결합도(Stamp Coupling)는 전체 데이터 구조를 통째로 전달할 때 발생합니다.',
    difficulty: 'MEDIUM',
    keywords: ['스탬프 결합도', 'Stamp Coupling', '자료구조전달'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-coupling',
  },
  {
    id: 'EXP_SE1_041',
    subject: '소프트웨어설계',
    category: '모듈화',
    type: 'SHORT_ANSWER',
    question: '한 모듈이 다른 모듈에게 무엇을 어떻게 실행할지 결정하는 제어 신호(Control Flag, 제어 파라미터)를 넘겨 흐름을 제어하는 결합도 단계는 무엇인가?',
    answer: '제어 결합도',
    explanation: '제어 결합도(Control Coupling)는 상위 모듈이 하위 모듈의 세부 내부 로직을 지시할 때 발생합니다.',
    difficulty: 'EASY',
    keywords: ['제어 결합도', 'Control Coupling', '제어플래그'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-coupling',
  },
  {
    id: 'EXP_SE1_042',
    subject: '소프트웨어설계',
    category: '소프트웨어 아키텍처',
    type: 'SHORT_ANSWER',
    question: '아키텍처 패턴 중 비동기 메시지 기반으로 복잡한 문제 해결을 위해 공유 메모리 공간에 전문 지식을 가진 에이전트들이 정보를 기록하고 소통하는 패턴은 무엇인가?',
    answer: '블랙보드 패턴',
    explanation: '블랙보드 패턴(Blackboard Pattern)은 음성 인식, 신호 처리 등 결정적 해결 알고리즘이 없는 영역에서 전문가 모듈들이 공유 칠판(블랙보드)을 통해 협력합니다.',
    difficulty: 'MEDIUM',
    keywords: ['블랙보드 패턴', 'Blackboard', '공유메모리'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-architecture',
  },
  {
    id: 'EXP_SE1_043',
    subject: '소프트웨어설계',
    category: '소프트웨어 아키텍처',
    type: 'SHORT_ANSWER',
    question: '분산 시스템에서 컴포넌트 간의 원격 서비스 요청과 통신을 중개(브로커)하여 분산 객체 환경의 투명성을 제공하는 아키텍처 패턴은 무엇인가?',
    answer: '브로커 패턴',
    explanation: '브로커 패턴(Broker Pattern)은 클라이언트와 서버 사이에서 원격 통신 요청을 전달하고 바인딩을 조정하는 중개자 패턴(대표 예: CORBA)입니다.',
    difficulty: 'MEDIUM',
    keywords: ['브로커 패턴', 'Broker Pattern', '분산객체중개'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-architecture',
  },
  {
    id: 'EXP_SE1_044',
    subject: '소프트웨어설계',
    category: 'UML',
    type: 'SHORT_ANSWER',
    question: 'UML 다이어그램 중 시간 경과에 따른 객체 간의 메시지 송수신 순서를 생명선(Lifeline)과 활성 막대를 이용해 수직 시간축으로 표현하는 다이어그램은 무엇인가?',
    answer: '시퀀스 다이어그램',
    explanation: '시퀀스 다이어그램(Sequence Diagram)은 동적 상호작용을 시간 순서에 따라 시각화합니다.',
    difficulty: 'EASY',
    keywords: ['시퀀스 다이어그램', 'Sequence Diagram', '생명선'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-uml',
  },
  {
    id: 'EXP_SE1_045',
    subject: '소프트웨어설계',
    category: 'UML',
    type: 'SHORT_ANSWER',
    question: 'UML 다이어그램 중 하나의 객체가 특정 외부 이벤트나 자극을 받아 상태가 어떻게 바뀌는지 상태 전이와 진입/탈출 동작을 표현하는 다이어그램은 무엇인가?',
    answer: '상태 다이어그램',
    explanation: '상태 다이어그램(State Diagram)은 객체의 전체 생명주기 동안의 상태 변화를 모델링합니다.',
    difficulty: 'EASY',
    keywords: ['상태 다이어그램', 'State Diagram', '상태전이'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-uml',
  },
  {
    id: 'EXP_SE1_046',
    subject: '소프트웨어설계',
    category: 'UML',
    type: 'SHORT_ANSWER',
    question: 'UML 다이어그램 중 시스템이 수행하는 처리 과정의 로직 흐름이나 비즈니스 프로세스 워크플로우를 처리 상자와 분기 기호로 도식화한 다이어그램은 무엇인가?',
    answer: '활동 다이어그램',
    explanation: '활동 다이어그램(Activity Diagram)은 순서도(Flowchart)를 객체지향적으로 확장한 동적 모델링 도구입니다.',
    difficulty: 'EASY',
    keywords: ['활동 다이어그램', 'Activity Diagram', '워크플로우'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-uml',
  },
  {
    id: 'EXP_SE1_047',
    subject: '소프트웨어설계',
    category: 'UML',
    type: 'SHORT_ANSWER',
    question: 'UML 클래스 관계 중 전체(Whole)와 부분(Part)의 관계이지만, 전체 객체가 소멸하더라도 부분 객체는 독립적으로 생존할 수 있는 약한 결합의 집약 관계 기호는 무엇인가?',
    answer: '속이 빈 다이아몬드',
    explanation: '집약 관계(Aggregation)는 속이 빈 마름모(다이아몬드)로 표기하며 독립 생존이 가능합니다. 전체와 수명을 함께하는 합성 관계는 속이 찬 마름모입니다.',
    difficulty: 'EASY',
    keywords: ['속이 빈 다이아몬드', '집약관계', '마름모기호'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-uml',
  },
  {
    id: 'EXP_SE1_048',
    subject: '소프트웨어설계',
    category: 'UML',
    type: 'SHORT_ANSWER',
    question: 'UML 클래스 관계 중 전체 객체가 소멸하면 부분 객체도 메모리에서 함께 소멸하는 강한 결합을 갖는 합성 관계 기호는 무엇인가?',
    answer: '속이 찬 다이아몬드',
    explanation: '합성 관계(Composition)는 강한 라이프사이클 종속성을 가지며 속이 찬 검은 마름모로 표현합니다.',
    difficulty: 'EASY',
    keywords: ['속이 찬 다이아몬드', '합성관계', '검은마름모'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-uml',
  },
  {
    id: 'EXP_SE1_049',
    subject: '소프트웨어설계',
    category: '객체지향 설계',
    type: 'SHORT_ANSWER',
    question: '객체지향 기법에서 객체의 상세한 내부 데이터와 구현 로직을 외부로부터 숨기고, 오직 공개된 메서드 인터페이스를 통해서만 상호작용하도록 보호하는 특성은 무엇인가?',
    answer: '캡슐화',
    explanation: '캡슐화(Encapsulation)는 데이터 보호(정보 은닉)와 높은 응집도를 실현하는 핵심 특성입니다.',
    difficulty: 'EASY',
    keywords: ['캡슐화', 'Encapsulation', '정보은닉'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-oop',
  },
  {
    id: 'EXP_SE1_050',
    subject: '소프트웨어설계',
    category: '객체지향 설계',
    type: 'SHORT_ANSWER',
    question: '객체지향 기법에서 동일한 이름의 연산(메서드)이 서로 다른 클래스의 객체에서 각자의 방식에 맞게 서로 다르게 동작할 수 있는 능력을 무엇이라 하는가?',
    answer: '다형성',
    explanation: '다형성(Polymorphism)은 오버로딩과 오버라이딩을 통해 실현되며, 코드의 유연성과 재사용성을 극대화합니다.',
    difficulty: 'EASY',
    keywords: ['다형성', 'Polymorphism', '객체지향특성'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-se-oop',
  },
];
