import { Question } from '../../src/types/question';

export const BATCH_1_QUESTIONS: Question[] = [
  {
    id: 'EXP_PR_001',
    subject: '프로그래밍언어활용',
    category: 'C언어',
    type: 'SHORT_ANSWER',
    question: 'C언어에서 동적으로 힙(Heap) 영역에 메모리를 할당할 때 사용하는 표준 라이브러리 함수는 무엇인가?',
    answer: 'malloc',
    explanation: 'malloc은 힙 영역에 지정된 바이트 크기만큼 메모리를 동적으로 할당하고 시작 주소를 void 포인터로 반환합니다. 할당 해제는 free를 사용합니다.',
    difficulty: 'EASY',
    keywords: ['malloc', '동적할당', 'C언어', '힙'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-c-memory',
  },
  {
    id: 'EXP_PR_002',
    subject: '프로그래밍언어활용',
    category: 'C언어',
    type: 'SHORT_ANSWER',
    question: 'C언어에서 malloc이나 calloc으로 동적 할당된 힙 영역의 메모리를 운영체제에 반환하여 메모리 누수를 방지하는 함수는 무엇인가?',
    answer: 'free',
    explanation: 'free 함수는 동적 할당된 메모리를 해제합니다. 해제하지 않고 참조를 잃어버리면 메모리 누수(Memory Leak)가 발생합니다.',
    difficulty: 'EASY',
    keywords: ['free', '메모리해제', '메모리누수'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-c-memory',
  },
  {
    id: 'EXP_PR_003',
    subject: '프로그래밍언어활용',
    category: 'C언어',
    type: 'SHORT_ANSWER',
    question: 'C언어에서 변수 또는 데이터 타입의 메모리 크기를 바이트 단위로 계산하여 반환하는 연산자는 무엇인가?',
    answer: 'sizeof',
    explanation: 'sizeof 연산자는 피연산자의 크기를 바이트 단위로 반환하며 컴파일 시점에 평가됩니다.',
    difficulty: 'EASY',
    keywords: ['sizeof', '바이트크기', '연산자'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-c-syntax',
  },
  {
    id: 'EXP_PR_004',
    subject: '프로그래밍언어활용',
    category: 'C언어',
    type: 'SHORT_ANSWER',
    question: 'C언어에서 일반 변수의 주소값을 구하기 위해 변수명 앞에 붙이는 주소 연산자 기호는 무엇인가?',
    answer: '&',
    explanation: '&(앰퍼샌드)는 피연산자의 메모리 주소를 반환하는 주소 연산자입니다. 포인터가 가리키는 값을 참조할 때는 *(역참조)를 사용합니다.',
    difficulty: 'EASY',
    keywords: ['&', '주소연산자', '앰퍼샌드'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-c-pointer',
  },
  {
    id: 'EXP_PR_005',
    subject: '프로그래밍언어활용',
    category: 'C언어',
    type: 'SHORT_ANSWER',
    question: 'C언어 포인터 변수가 어떤 유효한 메모리 주소도 가리키고 있지 않음을 명시적으로 나타내는 상수는 무엇인가?',
    answer: 'NULL',
    explanation: 'NULL은 가리키는 대상이 없는 포인터를 초기화할 때 사용하며 일반적으로 0으로 정의됩니다.',
    difficulty: 'EASY',
    keywords: ['NULL', '널포인터', '초기화'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-c-pointer',
  },
  {
    id: 'EXP_PR_006',
    subject: '프로그래밍언어활용',
    category: 'C언어',
    type: 'SHORT_ANSWER',
    question: 'C언어에서 서로 다른 데이터 타입을 하나의 묶음으로 묶어 새로운 사용자 정의 자료형을 만들 때 사용하는 키워드는 무엇인가?',
    answer: 'struct',
    explanation: 'struct(구조체)는 서로 다른 타입의 변수들을 하나의 단위로 묶는 사용자 정의 자료형입니다. 모든 멤버가 메모리를 공유하는 union(공용체)과 구별해야 합니다.',
    difficulty: 'EASY',
    keywords: ['struct', '구조체', '사용자정의형'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-c-struct',
  },
  {
    id: 'EXP_PR_007',
    subject: '프로그래밍언어활용',
    category: 'C언어',
    type: 'SHORT_ANSWER',
    question: 'C언어 구조체 포인터 변수를 통해 해당 구조체의 멤버 변수에 접근할 때 사용하는 화살표 모양의 멤버 접근 연산자 기호는 무엇인가?',
    answer: '->',
    explanation: '구조체 포인터에서 멤버를 직접 접근할 때 -> 연산자를 사용합니다. (*ptr).member 와 동일한 의미입니다.',
    difficulty: 'EASY',
    keywords: ['->', '화살표연산자', '구조체포인터'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-c-struct',
  },
  {
    id: 'EXP_PR_008',
    subject: '프로그래밍언어활용',
    category: 'C언어',
    type: 'SHORT_ANSWER',
    question: 'C언어에서 기존 데이터 타입에 새로운 별칭(alias)을 부여할 때 사용하는 키워드는 무엇인가?',
    answer: 'typedef',
    explanation: 'typedef는 기존 자료형에 짧고 직관적인 새 이름을 붙여 가독성을 높이고 코드 수정을 용이하게 만듭니다.',
    difficulty: 'EASY',
    keywords: ['typedef', '타입별칭'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-c-syntax',
  },
  {
    id: 'EXP_PR_009',
    subject: '프로그래밍언어활용',
    category: 'C언어',
    type: 'SHORT_ANSWER',
    question: 'C언어 컴파일 전 소스코드 내에서 특정 기호 상수를 치환하거나 매크로를 정의할 때 사용하는 전처리기 지시자는 무엇인가?',
    answer: '#define',
    explanation: '#define 지시자는 상수를 정의하거나 매크로 함수를 만들 때 사용하며, 컴파일 전에 단순 문자열 치환 방식으로 동작합니다.',
    difficulty: 'EASY',
    keywords: ['#define', '전처리기', '매크로'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-c-syntax',
  },
  {
    id: 'EXP_PR_010',
    subject: '프로그래밍언어활용',
    category: 'C언어',
    type: 'SHORT_ANSWER',
    question: '함수 호출 시 인자의 실제 값을 복사하여 전달하므로 호출된 함수 내부에서 값을 변경해도 호출한 원래 변수에는 영향이 없는 매개변수 전달 방식은 무엇인가?',
    answer: 'Call by Value',
    explanation: '값에 의한 호출(Call by Value)은 인자의 복사본을 넘겨 원본이 안전하게 보존됩니다. 원본을 수정하려면 주소를 넘기는 Call by Reference를 써야 합니다.',
    difficulty: 'MEDIUM',
    keywords: ['Call by Value', '값에의한호출'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-c-function',
  },
  {
    id: 'EXP_PR_011',
    subject: '프로그래밍언어활용',
    category: 'C언어',
    type: 'SHORT_ANSWER',
    question: '함수 호출 시 실인자의 메모리 주소를 전달하여 호출된 함수 내부에서 원본 변수의 값을 직접 변경할 수 있는 매개변수 전달 방식은 무엇인가?',
    answer: 'Call by Reference',
    explanation: '참조에 의한 호출(Call by Reference)은 주소값을 넘겨 함수 내에서 원본 변수를 조작합니다. C언어에서는 포인터를 활용하여 이를 흉내냅니다.',
    difficulty: 'MEDIUM',
    keywords: ['Call by Reference', '참조에의한호출'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-c-function',
  },
  {
    id: 'EXP_PR_012',
    subject: '프로그래밍언어활용',
    category: 'C언어',
    type: 'SHORT_ANSWER',
    question: 'C언어 printf 서식 문자열에서 16진수 정수를 소문자 형태로 출력할 때 사용하는 서식 지정자는 무엇인가?',
    answer: '%x',
    explanation: '%x는 16진수 소문자 출력, %X는 대문자 출력 서식 지정자입니다. 8진수는 %o, 10진수 정수는 %d입니다.',
    difficulty: 'EASY',
    keywords: ['%x', '서식지정자', '16진수'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-c-syntax',
  },
  {
    id: 'EXP_PR_013',
    subject: '프로그래밍언어활용',
    category: 'C언어',
    type: 'SHORT_ANSWER',
    question: 'C언어 printf 서식 지정자 중 메모리 주소값(포인터 값)을 16진수 형태로 출력할 때 사용하는 지정자는 무엇인가?',
    answer: '%p',
    explanation: '%p는 포인터 변수가 담고 있는 주소값을 출력하는 서식 지정자입니다.',
    difficulty: 'EASY',
    keywords: ['%p', '서식지정자', '포인터주소'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-c-syntax',
  },
  {
    id: 'EXP_PR_014',
    subject: '프로그래밍언어활용',
    category: 'C언어',
    type: 'SHORT_ANSWER',
    question: 'C언어 비트 연산자 중 두 비트가 서로 다를 때만 1을 반환하는 배타적 논리합(XOR) 연산자 기호는 무엇인가?',
    answer: '^',
    explanation: '^(캐럿)은 XOR 연산자로서 두 비트가 다를 때 1, 같을 때 0을 반환합니다. &(AND)와 |(OR)와 구분해야 합니다.',
    difficulty: 'EASY',
    keywords: ['^', 'XOR', '비트연산자'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-c-bitwise',
  },
  {
    id: 'EXP_PR_015',
    subject: '프로그래밍언어활용',
    category: 'C언어',
    type: 'SHORT_ANSWER',
    question: 'C언어 비트 연산자 중 모든 비트를 0은 1로, 1은 0으로 반전시키는 1의 보수(비트 NOT) 연산자 기호는 무엇인가?',
    answer: '~',
    explanation: '~(물결)은 비트 단위 NOT 연산자입니다. 논리 부정(!)과 기호를 혼동하지 않도록 주의해야 합니다.',
    difficulty: 'EASY',
    keywords: ['~', '비트NOT', '1의보수'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-c-bitwise',
  },
  {
    id: 'EXP_PR_016',
    subject: '프로그래밍언어활용',
    category: 'C언어',
    type: 'SHORT_ANSWER',
    question: 'C언어 비트 연산에서 피연산자의 비트들을 왼쪽으로 n칸 이동시키고 빈자리를 0으로 채우는 비트 시프트 연산자 기호는 무엇인가?',
    answer: '<<',
    explanation: '<< 연산자는 왼쪽으로 1비트 이동할 때마다 2를 곱한 효과(2^n)를 냅니다. 오른쪽 시프트는 >>입니다.',
    difficulty: 'EASY',
    keywords: ['<<', '왼쪽시프트', '비트연산자'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-c-bitwise',
  },
  {
    id: 'EXP_PR_017',
    subject: '프로그래밍언어활용',
    category: 'C언어',
    type: 'SHORT_ANSWER',
    question: '함수 호출 시 생성되는 지역 변수, 매개변수, 반환 주소 등이 임시 저장되는 메모리 영역의 이름은 무엇인가?',
    answer: '스택',
    explanation: '스택(Stack) 영역은 함수 호출 시 할당되고 함수 종료 시 자동으로 소멸하는 LIFO 구조의 메모리 영역입니다. 힙(Heap)은 프로그래머가 동적 할당합니다.',
    difficulty: 'EASY',
    keywords: ['스택', 'Stack', '메모리영역', '지역변수'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-c-memory',
  },
  {
    id: 'EXP_PR_018',
    subject: '프로그래밍언어활용',
    category: 'C언어',
    type: 'SHORT_ANSWER',
    question: '전역 변수와 정적(static) 변수가 저장되며 프로그램 시작 시 할당되고 프로그램 종료 시 소멸하는 메모리 영역의 이름은 무엇인가?',
    answer: '데이터 영역',
    explanation: '데이터(Data) 영역은 전역 변수와 static 변수가 저장되는 공간으로 프로그램 실행 중 상주합니다.',
    difficulty: 'MEDIUM',
    keywords: ['데이터 영역', 'Data', '전역변수'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-c-memory',
  },
  {
    id: 'EXP_PR_019',
    subject: '프로그래밍언어활용',
    category: 'Java',
    type: 'SHORT_ANSWER',
    question: 'Java에서 동일한 클래스 내에 이름이 같은 메서드를 매개변수의 타입이나 개수를 다르게 하여 여러 개 정의하는 객체지향 기법은 무엇인가?',
    answer: '오버로딩',
    explanation: '오버로딩(Overloading)은 같은 이름의 메서드를 매개변수 목록을 다르게 정의하는 기법입니다. 상속 관계에서 부모 메서드를 재정의하는 오버라이딩(Overriding)과 구별해야 합니다.',
    difficulty: 'EASY',
    keywords: ['오버로딩', 'Overloading', '다형성'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-java-oop',
  },
  {
    id: 'EXP_PR_020',
    subject: '프로그래밍언어활용',
    category: 'Java',
    type: 'SHORT_ANSWER',
    question: 'Java에서 자식 클래스가 상속받은 부모 클래스의 메서드를 동일한 이름, 매개변수, 반환형으로 본문(로직)만 재정의하는 기법은 무엇인가?',
    answer: '오버라이딩',
    explanation: '오버라이딩(Overriding)은 상위 클래스의 메서드를 하위 클래스에서 재정의하는 동적 바인딩 기법입니다. @Override 어노테이션으로 검증할 수 있습니다.',
    difficulty: 'EASY',
    keywords: ['오버라이딩', 'Overriding', '메서드재정의'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-java-oop',
  },
  {
    id: 'EXP_PR_021',
    subject: '프로그래밍언어활용',
    category: 'Java',
    type: 'SHORT_ANSWER',
    question: 'Java에서 한 클래스가 다른 부모 클래스를 상속받을 때 클래스 선언부에 사용하는 상속 키워드는 무엇인가?',
    answer: 'extends',
    explanation: 'extends는 클래스 상속 시 사용하며 Java는 단일 상속만 허용합니다. 인터페이스 구현에는 implements를 사용합니다.',
    difficulty: 'EASY',
    keywords: ['extends', '상속키워드', 'Java'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-java-syntax',
  },
  {
    id: 'EXP_PR_022',
    subject: '프로그래밍언어활용',
    category: 'Java',
    type: 'SHORT_ANSWER',
    question: 'Java에서 클래스가 인터페이스의 추상 메서드들을 구현하겠다고 선언할 때 사용하는 키워드는 무엇인가?',
    answer: 'implements',
    explanation: 'implements는 인터페이스를 클래스에서 다중 구현할 때 사용합니다. 인터페이스끼리 상속할 때는 extends를 씁니다.',
    difficulty: 'EASY',
    keywords: ['implements', '인터페이스구현', 'Java'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-java-syntax',
  },
  {
    id: 'EXP_PR_023',
    subject: '프로그래밍언어활용',
    category: 'Java',
    type: 'SHORT_ANSWER',
    question: 'Java 자식 클래스 내부에서 부모 클래스의 생성자나 멤버 변수/메서드를 명시적으로 호출할 때 사용하는 키워드는 무엇인가?',
    answer: 'super',
    explanation: 'super 키워드는 부모 객체를 가리킵니다. 부모 생성자 호출은 super(), 자신의 멤버를 가리킬 때는 this를 씁니다.',
    difficulty: 'EASY',
    keywords: ['super', '부모클래스참조', '생성자'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-java-syntax',
  },
  {
    id: 'EXP_PR_024',
    subject: '프로그래밍언어활용',
    category: 'Java',
    type: 'SHORT_ANSWER',
    question: 'Java에서 인스턴스 생성 없이 클래스 이름만으로 직접 접근할 수 있는 클래스 변수나 정적 메서드를 선언할 때 사용하는 키워드는 무엇인가?',
    answer: 'static',
    explanation: 'static 키워드로 선언된 멤버는 클래스 로딩 시 메서드 영역(Method Area)에 생성되어 모든 인스턴스가 공유합니다.',
    difficulty: 'EASY',
    keywords: ['static', '정적키워드', '클래스변수'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-java-syntax',
  },
  {
    id: 'EXP_PR_025',
    subject: '프로그래밍언어활용',
    category: 'Java',
    type: 'SHORT_ANSWER',
    question: 'Java에서 변수를 상수로 만들어 값의 변경을 금지하거나, 메서드의 오버라이딩을 금지하고 클래스의 상속을 금지할 때 사용하는 키워드는 무엇인가?',
    answer: 'final',
    explanation: 'final 변수는 상수, final 메서드는 오버라이딩 불가, final 클래스는 상속 불가를 의미합니다.',
    difficulty: 'EASY',
    keywords: ['final', '상수', '오버라이딩금지'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-java-syntax',
  },
  {
    id: 'EXP_PR_026',
    subject: '프로그래밍언어활용',
    category: 'Java',
    type: 'SHORT_ANSWER',
    question: 'Java 4대 접근 제어자 중 해당 클래스가 정의된 동일 패키지 내부와 다른 패키지의 자식 클래스에서만 접근을 허용하는 제어자는 무엇인가?',
    answer: 'protected',
    explanation: 'protected는 동일 패키지 및 상속받은 하위 클래스에 접근을 허용합니다. 같은 클래스만 허용하는 것은 private, 전체 공개는 public입니다.',
    difficulty: 'MEDIUM',
    keywords: ['protected', '접근제어자', '상속'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-java-syntax',
  },
  {
    id: 'EXP_PR_027',
    subject: '프로그래밍언어활용',
    category: 'Java',
    type: 'SHORT_ANSWER',
    question: 'Java 예외 처리 구문 중 예외 발생 여부와 상관없이 무조건 마지막에 반드시 실행되는 코드 블록을 지정하는 키워드는 무엇인가?',
    answer: 'finally',
    explanation: 'finally 블록은 try-catch 실행 후 파일 스트림이나 DB 연결 닫기 같은 리소스 해제 작업을 무조건 보장하기 위해 사용합니다.',
    difficulty: 'EASY',
    keywords: ['finally', '예외처리', '리소스해제'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-java-syntax',
  },
  {
    id: 'EXP_PR_028',
    subject: '프로그래밍언어활용',
    category: 'Java',
    type: 'SHORT_ANSWER',
    question: 'Java JVM 힙 영역에서 더 이상 어떤 참조도 닿지 않는 쓰레기 객체들을 주기적으로 탐색하여 메모리를 자동으로 회수하는 시스템 프로세스는 무엇인가?',
    answer: '가비지 컬렉터',
    explanation: '가비지 컬렉터(Garbage Collector, GC)는 도달 불가능(unreachable) 객체를 자동 수거하여 프로그래머가 수동으로 메모리를 해제하지 않도록 돕습니다.',
    difficulty: 'EASY',
    keywords: ['가비지 컬렉터', 'GC', 'Garbage Collector'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-java-jvm',
  },
  {
    id: 'EXP_PR_029',
    subject: '프로그래밍언어활용',
    category: 'Java',
    type: 'SHORT_ANSWER',
    question: 'Java 컬렉션 프레임워크 중 순서를 보장하지 않고 데이터의 중복 저장을 절대 허용하지 않는 인터페이스는 무엇인가?',
    answer: 'Set',
    explanation: 'Set은 중복을 허용하지 않는 집합 컬렉션(대표 구현체: HashSet, TreeSet)입니다. 순서와 중복을 허용하는 것은 List입니다.',
    difficulty: 'EASY',
    keywords: ['Set', '컬렉션', '중복불가'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-java-collections',
  },
  {
    id: 'EXP_PR_030',
    subject: '프로그래밍언어활용',
    category: 'Java',
    type: 'SHORT_ANSWER',
    question: 'Java 컬렉션 프레임워크 중 키(Key)와 값(Value)의 쌍으로 데이터를 관리하며, 키는 중복될 수 없는 인터페이스는 무엇인가?',
    answer: 'Map',
    explanation: 'Map은 Key-Value 매핑 컬렉션(대표 구현체: HashMap, TreeMap)으로 키의 중복은 불허하지만 값의 중복은 허용합니다.',
    difficulty: 'EASY',
    keywords: ['Map', 'Key-Value', 'HashMap'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-java-collections',
  },
  {
    id: 'EXP_PR_031',
    subject: '프로그래밍언어활용',
    category: 'Python',
    type: 'SHORT_ANSWER',
    question: 'Python에서 한 번 생성된 후 내부 요소의 추가, 삭제, 수정이 불가능한 불변(Immutable) 시퀀스 자료형으로 소괄호 ()로 표현하는 것은 무엇인가?',
    answer: '튜플',
    explanation: '튜플(Tuple)은 불변 자료형으로 요소를 변경할 수 없습니다. 대괄호 []로 감싸 수정 가능한 것은 리스트(List)입니다.',
    difficulty: 'EASY',
    keywords: ['튜플', 'Tuple', '불변자료형'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-py-datatype',
  },
  {
    id: 'EXP_PR_032',
    subject: '프로그래밍언어활용',
    category: 'Python',
    type: 'SHORT_ANSWER',
    question: 'Python에서 키(Key)와 값(Value)의 쌍으로 구성되며 중괄호 {}를 사용해 선언하는 가변 매핑 자료형은 무엇인가?',
    answer: '딕셔너리',
    explanation: '딕셔너리(Dictionary)는 키 기반 검색을 지원하는 매핑 자료형입니다. 키는 해시 가능한 불변 타입이어야 합니다.',
    difficulty: 'EASY',
    keywords: ['딕셔너리', 'dict', 'Dictionary'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-py-datatype',
  },
  {
    id: 'EXP_PR_033',
    subject: '프로그래밍언어활용',
    category: 'Python',
    type: 'SHORT_ANSWER',
    question: 'Python에서 별도의 def 함수 선언 없이 이름이 없는 한 줄짜리 인라인 익명 함수를 정의할 때 사용하는 키워드는 무엇인가?',
    answer: 'lambda',
    explanation: 'lambda 키워드는 인라인 익명 함수를 만들며 `lambda x: x * 2` 형태로 작성합니다.',
    difficulty: 'EASY',
    keywords: ['lambda', '익명함수', '파이썬'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-py-syntax',
  },
  {
    id: 'EXP_PR_034',
    subject: '프로그래밍언어활용',
    category: 'Python',
    type: 'SHORT_ANSWER',
    question: 'Python 문자열이나 리스트 s에 대해 슬라이싱 기법을 이용하여 전체 시퀀스를 뒤에서부터 역순으로 뒤집을 때 사용하는 슬라이스 표기식은 무엇인가?',
    answer: '[::-1]',
    explanation: '`[::-1]`은 start와 end를 생략하고 step을 -1로 지정하여 전체 시퀀스를 역순으로 뒤집는 파이썬 관용구입니다.',
    difficulty: 'MEDIUM',
    keywords: ['[::-1]', '슬라이싱', '역순'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-py-syntax',
  },
  {
    id: 'EXP_PR_035',
    subject: '프로그래밍언어활용',
    category: 'Python',
    type: 'SHORT_ANSWER',
    question: 'Python 리스트나 딕셔너리 등 시퀀스의 전체 요소 개수(길이)를 구할 때 사용하는 표준 내장 함수는 무엇인가?',
    answer: 'len',
    explanation: 'len() 함수는 객체의 원소 개수를 반환합니다.',
    difficulty: 'EASY',
    keywords: ['len', '길이반환', '파이썬내장함수'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-py-syntax',
  },
  {
    id: 'EXP_PR_036',
    subject: '프로그래밍언어활용',
    category: 'Python',
    type: 'SHORT_ANSWER',
    question: 'Python에서 여러 반복 가능한(iterable) 객체들을 인자로 받아 동일 인덱스의 요소들을 튜플로 묶어주는 내장 함수는 무엇인가?',
    answer: 'zip',
    explanation: 'zip() 함수는 2개 이상의 리스트나 튜플에서 동일 위치의 원소들을 묶어 튜플의 이터레이터를 생성합니다.',
    difficulty: 'MEDIUM',
    keywords: ['zip', '내장함수', '튜플묶기'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-py-syntax',
  },
  {
    id: 'EXP_PR_037',
    subject: '프로그래밍언어활용',
    category: 'Python',
    type: 'SHORT_ANSWER',
    question: 'Python 딕셔너리에서 존재하지 않는 키를 조회할 때 KeyError 예외를 발생시키지 않고 안전하게 기본값을 반환받는 메서드는 무엇인가?',
    answer: 'get',
    explanation: 'dict.get(key, default) 메서드는 키가 없을 때 기본값(지정 안 하면 None)을 안전하게 반환합니다.',
    difficulty: 'MEDIUM',
    keywords: ['get', '딕셔너리메서드', '예외방지'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-py-syntax',
  },
  {
    id: 'EXP_PR_038',
    subject: '프로그래밍언어활용',
    category: 'Python',
    type: 'SHORT_ANSWER',
    question: 'Python 세트(set) 자료형에서 중복 요소를 제거하고 두 집합의 공통 원소만을 구할 때 사용하는 교집합 연산자 기호는 무엇인가?',
    answer: '&',
    explanation: '파이썬 집합 자료형에서 &(앰퍼샌드)는 교집합 연산자입니다. 합집합은 |, 차집합은 - 기호를 사용합니다.',
    difficulty: 'EASY',
    keywords: ['&', '교집합', '세트연산자'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-py-datatype',
  },
  {
    id: 'EXP_PR_039',
    subject: '프로그래밍언어활용',
    category: 'C언어',
    type: 'SHORT_ANSWER',
    question: 'C언어 문자열의 끝을 컴퓨터가 식별하기 위해 모든 문자열의 마지막에 자동으로 추가되는 널 문자 표기는 무엇인가?',
    answer: '\\0',
    explanation: '\\0(널 문자, ASCII 0)은 C언어 문자열의 종료를 알리는 센티널 값입니다. 문자 "0"(ASCII 48)과 구별해야 합니다.',
    difficulty: 'EASY',
    keywords: ['\\0', '널문자', '문자열종료'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-c-syntax',
  },
  {
    id: 'EXP_PR_040',
    subject: '프로그래밍언어활용',
    category: 'C언어',
    type: 'SHORT_ANSWER',
    question: 'C언어 표준 라이브러리 <string.h>에서 두 문자열이 사전순으로 일치하는지 비교하는 함수의 이름은 무엇인가?',
    answer: 'strcmp',
    explanation: 'strcmp(s1, s2)는 두 문자열이 같으면 0, s1이 크면 양수, s2가 크면 음수를 반환합니다.',
    difficulty: 'EASY',
    keywords: ['strcmp', '문자열비교', 'string.h'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-c-string',
  },
  {
    id: 'EXP_PR_041',
    subject: '프로그래밍언어활용',
    category: 'C언어',
    type: 'SHORT_ANSWER',
    question: 'C언어 표준 라이브러리 <string.h>에서 원본 문자열을 대상 버퍼에 복사하는 함수의 이름은 무엇인가?',
    answer: 'strcpy',
    explanation: 'strcpy(dest, src)는 src 문자열을 dest 버퍼에 널 문자까지 복사합니다. 버퍼 오버플로우 방지를 위해 strncpy 사용이 권장됩니다.',
    difficulty: 'EASY',
    keywords: ['strcpy', '문자열복사', 'string.h'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-c-string',
  },
  {
    id: 'EXP_PR_042',
    subject: '프로그래밍언어활용',
    category: 'C언어',
    type: 'SHORT_ANSWER',
    question: 'C언어 표준 라이브러리 <string.h>에서 하나의 문자열 뒤에 다른 문자열을 덧붙이는(연결하는) 함수의 이름은 무엇인가?',
    answer: 'strcat',
    explanation: 'strcat(dest, src)는 dest 문자열 끝에 src를 덧붙입니다.',
    difficulty: 'EASY',
    keywords: ['strcat', '문자열연결', 'string.h'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-c-string',
  },
  {
    id: 'EXP_PR_043',
    subject: '프로그래밍언어활용',
    category: 'C언어',
    type: 'SHORT_ANSWER',
    question: 'C언어 표준 라이브러리 <string.h>에서 널 문자를 제외한 순수 문자열의 글자 수를 계산해 반환하는 함수는 무엇인가?',
    answer: 'strlen',
    explanation: 'strlen(str)은 시작점부터 \\0 직전까지의 바이트/문자 수를 계산합니다. sizeof(배열)은 할당된 전체 버퍼 크기를 반환하므로 다릅니다.',
    difficulty: 'EASY',
    keywords: ['strlen', '문자열길이', 'string.h'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-c-string',
  },
  {
    id: 'EXP_PR_044',
    subject: '프로그래밍언어활용',
    category: 'Java',
    type: 'SHORT_ANSWER',
    question: 'Java에서 두 문자열 객체의 내용(값)이 동일한지 비교할 때 == 연산자 대신 반드시 호출해야 하는 메서드는 무엇인가?',
    answer: 'equals',
    explanation: 'Java에서 == 연산자는 객체의 주소값(참조)을 비교하므로, 문자열의 실제 내용을 비교하려면 equals() 메서드를 호출해야 합니다.',
    difficulty: 'EASY',
    keywords: ['equals', '문자열비교', '내용비교'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-java-syntax',
  },
  {
    id: 'EXP_PR_045',
    subject: '프로그래밍언어활용',
    category: 'Java',
    type: 'SHORT_ANSWER',
    question: 'Java String 클래스는 불변(Immutable) 객체이므로 문자열을 빈번히 결합할 때 성능 저하를 방지하기 위해 사용하는 가변(Mutable) 버퍼 클래스는 무엇인가?',
    answer: 'StringBuilder',
    explanation: 'StringBuilder는 가변 버퍼를 지원하여 append() 시 새로운 객체를 매번 생성하지 않고 기존 버퍼를 확장합니다. 멀티스레드 동기화가 필요한 경우 StringBuffer를 씁니다.',
    difficulty: 'MEDIUM',
    keywords: ['StringBuilder', '문자열결합', '가변객체'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-java-syntax',
  },
  {
    id: 'EXP_PR_046',
    subject: '프로그래밍언어활용',
    category: 'Java',
    type: 'SHORT_ANSWER',
    question: 'Java에서 컴파일 타임에 다양한 타입을 일반화하여 타입 안전성(Type Safety)을 보장하고 형변환의 번거로움을 줄여주는 기법은 무엇인가?',
    answer: '제네릭',
    explanation: '제네릭(Generics, `<T>`)은 클래스나 메서드에서 사용할 데이터 타입을 파라미터화하여 컴파일 시 엄격한 타입 체크를 수행합니다.',
    difficulty: 'MEDIUM',
    keywords: ['제네릭', 'Generics', '타입안전성'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-java-syntax',
  },
  {
    id: 'EXP_PR_047',
    subject: '프로그래밍언어활용',
    category: 'Python',
    type: 'SHORT_ANSWER',
    question: 'Python 리스트에서 [표현식 for 항목 in 반복가능객체 if 조건문] 형태로 간결하게 새로운 리스트를 생성하는 문법 표기법은 무엇인가?',
    answer: '리스트 컴프리헨션',
    explanation: '리스트 컴프리헨션(List Comprehension)은 반복문과 조건문을 축약하여 한 줄로 새 리스트를 필터링/가공하는 파이썬 고유 문법입니다.',
    difficulty: 'MEDIUM',
    keywords: ['리스트 컴프리헨션', 'List Comprehension'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-py-syntax',
  },
  {
    id: 'EXP_PR_048',
    subject: '프로그래밍언어활용',
    category: 'C언어',
    type: 'SHORT_ANSWER',
    question: 'C언어 삼항 조건 연산자(조건 ? 수식1 : 수식2)에서 조건식이 참(True)일 때 평가되는 수식은 수식1인가 수식2인가?',
    answer: '수식1',
    explanation: '삼항 연산자 `condition ? expr1 : expr2`는 조건이 참이면 expr1, 거짓이면 expr2를 평가합니다.',
    difficulty: 'EASY',
    keywords: ['수식1', '삼항연산자', '조건연산자'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-c-syntax',
  },
  {
    id: 'EXP_PR_049',
    subject: '프로그래밍언어활용',
    category: 'Java',
    type: 'SHORT_ANSWER',
    question: 'Java switch-case 문에서 특정 case 문을 실행한 후 아래쪽 case 문들로 계속 흘러내리는(Fall-through) 현상을 막고 switch 문을 탈출하기 위해 쓰는 제어문 키워드는 무엇인가?',
    answer: 'break',
    explanation: 'break 문은 switch 문이나 반복문(for, while)을 즉시 종료하고 블록을 빠져나옵니다.',
    difficulty: 'EASY',
    keywords: ['break', 'switch-case', '루프탈출'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-java-syntax',
  },
  {
    id: 'EXP_PR_050',
    subject: '프로그래밍언어활용',
    category: 'C언어',
    type: 'SHORT_ANSWER',
    question: 'C언어나 Java 반복문(for, while) 내부에서 현재 반복 회차의 나머지 코드를 건너뛰고 다음 반복 회차의 조건 검사로 즉시 건너뛰게 만드는 제어문 키워드는 무엇인가?',
    answer: 'continue',
    explanation: 'continue는 현재 회차의 남은 실행문을 건너뛰고 루프의 다음 증감/조건식으로 이동합니다. 루프를 완전히 끝내는 break와 다릅니다.',
    difficulty: 'EASY',
    keywords: ['continue', '반복문제어', '건너뛰기'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-c-syntax',
  },
];
