import { Question } from '../../src/types/question';

export const BATCH_10_QUESTIONS: Question[] = [
  {
    id: 'EXP_SEC2_001',
    subject: '신기술/보안',
    category: '웹 취약점 방어',
    type: 'SHORT_ANSWER',
    question: 'SQL Injection 공격을 원천 방지하기 위해 사용자 입력을 동적 문자열 결합 대신 쿼리 구조를 미리 컴파일하고 바인딩 변수(?)를 사용하는 데이터베이스 프로그래밍 객체는 무엇인가?',
    answer: 'PreparedStatement',
    explanation: 'PreparedStatement(바인딩 쿼리)는 사용자 입력을 단순 데이터 리터럴로만 취급하여 SQL 문법 구조가 변조되는 것을 차단합니다.',
    difficulty: 'EASY',
    keywords: ['PreparedStatement', 'SQL인젝션방어', '바인딩변수'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-webvuln',
  },
  {
    id: 'EXP_SEC2_002',
    subject: '신기술/보안',
    category: '웹 취약점',
    type: 'SHORT_ANSWER',
    question: 'XSS 공격 유형 중 공격자가 악의적인 스크립트를 게시판이나 댓글 등 웹 애플리케이션 데이터베이스에 영구 저장시켜 불특정 다수의 방문자 브라우저에서 실행되게 만드는 공격은 무엇인가?',
    answer: 'Stored XSS',
    explanation: '저장형 XSS(Stored XSS)는 스크립트가 DB에 저장되어 지속적으로 다수의 사용자 세션 쿠키를 탈취합니다.',
    difficulty: 'EASY',
    keywords: ['Stored XSS', '저장형XSS', '게시판스크립트'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-webvuln',
  },
  {
    id: 'EXP_SEC2_003',
    subject: '신기술/보안',
    category: '웹 취약점',
    type: 'SHORT_ANSWER',
    question: 'XSS 공격 유형 중 악성 스크립트가 포함된 피싱 URL 링크를 피해자가 클릭했을 때 서버의 검색 결과 화면 등을 통해 즉시 브라우저로 반사되어 실행되는 공격은 무엇인가?',
    answer: 'Reflected XSS',
    explanation: '반사형 XSS(Reflected XSS)는 서버 DB에 저장되지 않고 요청 파라미터가 응답 화면에 그대로 노출될 때 발생합니다.',
    difficulty: 'EASY',
    keywords: ['Reflected XSS', '반사형XSS', '피싱링크'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-webvuln',
  },
  {
    id: 'EXP_SEC2_004',
    subject: '신기술/보안',
    category: '웹 취약점 방어',
    type: 'SHORT_ANSWER',
    question: '웹 브라우저에서 스크립트(JavaScript)가 document.cookie를 통해 세션 쿠키에 직접 접근하지 못하도록 차단하여 XSS 쿠키 탈취를 방지하는 쿠키 보안 플래그는 무엇인가?',
    answer: 'HttpOnly',
    explanation: 'HttpOnly 플래그가 설정된 쿠키는 HTTP 통신으로만 전송되며 자바스크립트 브라우저 API로는 읽을 수 없습니다.',
    difficulty: 'EASY',
    keywords: ['HttpOnly', '쿠키보안플래그', 'XSS방어'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-webvuln',
  },
  {
    id: 'EXP_SEC2_005',
    subject: '신기술/보안',
    category: '웹 취약점 방어',
    type: 'SHORT_ANSWER',
    question: 'XSS 방어를 위해 사용자가 입력한 HTML 특수문자(<, >, &, ", \' 등)를 안전한 문자 엔티티(&lt;, &gt; 등)로 변환하는 기법을 무엇이라 하는가?',
    answer: 'HTML 엔티티 치환',
    explanation: 'HTML 인코딩(치환)은 브라우저가 스크립트 태그를 실행 코드로 해석하지 않고 단순 텍스트로 렌더링하게 만듭니다.',
    difficulty: 'EASY',
    keywords: ['HTML 엔티티 치환', 'HTML인코딩', '특수문자치환'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-webvuln',
  },
  {
    id: 'EXP_SEC2_006',
    subject: '신기술/보안',
    category: '웹 취약점',
    type: 'SHORT_ANSWER',
    question: '로그인 인증이 완료된 피해자의 브라우저 권한을 도용하여 피해자가 의도하지 않은 악의적인 요청(비밀번호 변경, 계좌 이체 등)을 서버로 전송시키는 위조 공격의 약칭은 무엇인가?',
    answer: 'CSRF',
    explanation: 'CSRF(Cross-Site Request Forgery)는 희생자의 유효한 세션 인증 정보를 악용하여 서버에 조작된 요청을 보냅니다.',
    difficulty: 'EASY',
    keywords: ['CSRF', 'Cross-Site Request Forgery', '요청위조'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-webvuln',
  },
  {
    id: 'EXP_SEC2_007',
    subject: '신기술/보안',
    category: '웹 취약점 방어',
    type: 'SHORT_ANSWER',
    question: 'CSRF 공격을 방어하기 위해 매 폼(Form) 요청마다 서버가 생성한 예측 불가능한 고유 난수 값을 세션과 폼 데이터에 일치시키도록 검증하는 방어 수단은 무엇인가?',
    answer: 'CSRF 토큰',
    explanation: 'CSRF 토큰은 공격자가 외부 사이트에서 피해자 브라우저로 위조 요청을 보내더라도 토큰 값을 알 수 없어 서버에서 거절됩니다.',
    difficulty: 'EASY',
    keywords: ['CSRF 토큰', 'CSRF방어', '난수토큰'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-webvuln',
  },
  {
    id: 'EXP_SEC2_008',
    subject: '신기술/보안',
    category: '웹 취약점 방어',
    type: 'SHORT_ANSWER',
    question: '웹 브라우저의 보안 정책 중 어떤 출처(도메인, 프로토콜, 포트)에서 불러온 문서나 스크립트가 다른 출처의 리소스와 상호작용하는 것을 기본적으로 격리 제한하는 정책의 약칭은 무엇인가?',
    answer: 'SOP',
    explanation: 'SOP(Same-Origin Policy, 동일 출처 정책)는 출처가 다른 리소스 접근을 차단합니다. 필요한 경우 CORS를 통해 허용합니다.',
    difficulty: 'EASY',
    keywords: ['SOP', 'Same-Origin Policy', '동일출처정책'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-webvuln',
  },
  {
    id: 'EXP_SEC2_009',
    subject: '신기술/보안',
    category: '웹 브라우저 통신',
    type: 'SHORT_ANSWER',
    question: 'SOP 정책의 제약을 넘어 다른 출처(도메인)의 리소스를 안전하게 요청할 수 있도록 추가 HTTP 헤더를 사용하여 서버가 권한을 허용하는 메커니즘의 약칭은 무엇인가?',
    answer: 'CORS',
    explanation: 'CORS(Cross-Origin Resource Sharing, 교차 출처 리소스 공유)는 Access-Control-Allow-Origin 헤더로 교차 요청을 허용합니다.',
    difficulty: 'EASY',
    keywords: ['CORS', 'Cross-Origin Resource Sharing', '교차출처공유'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-webvuln',
  },
  {
    id: 'EXP_SEC2_010',
    subject: '신기술/보안',
    category: '메모리 보안 공격',
    type: 'SHORT_ANSWER',
    question: 'C언어 등에서 메모리 버퍼의 크기를 초과하여 데이터를 입력함으로써 함수의 반환 주소(Return Address)를 덮어써서 공격자의 쉘코드를 실행시키는 공격은 무엇인가?',
    answer: '버퍼 오버플로우',
    explanation: '버퍼 오버플로우(Buffer Overflow)는 경계 검사(Boundary Check)를 수행하지 않는 함수(strcpy, gets 등)를 사용할 때 발생합니다.',
    difficulty: 'EASY',
    keywords: ['버퍼 오버플로우', 'Buffer Overflow', '반환주소변조'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-sysvuln',
  },
  {
    id: 'EXP_SEC2_011',
    subject: '신기술/보안',
    category: '메모리 보호 기법',
    type: 'SHORT_ANSWER',
    question: '프로그램이 실행될 때마다 스택, 힙, 공유 라이브러리가 적재되는 메모리 시작 주소를 무작위로 변경하여 공격자가 쉘코드 주소를 예측하지 못하게 방어하는 기술의 약칭은 무엇인가?',
    answer: 'ASLR',
    explanation: 'ASLR(Address Space Layout Randomization)은 메모리 주소 무작위화로 버퍼 오버플로우 공격을 무력화합니다.',
    difficulty: 'EASY',
    keywords: ['ASLR', 'Address Space Layout Randomization', '메모리주소무작위화'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-sysvuln',
  },
  {
    id: 'EXP_SEC2_012',
    subject: '신기술/보안',
    category: '메모리 보호 기법',
    type: 'SHORT_ANSWER',
    question: '버퍼 오버플로우 방어를 위해 스택의 지역 변수와 반환 주소 사이에 무작위 카나리(Canary) 값을 삽입하고 함수 종료 시 카나리 변조를 검사하는 보호 기술은 무엇인가?',
    answer: '스택 가드',
    explanation: '스택 가드(StackGuard, 스택 카나리)는 카나리 값이 손상되면 시스템을 강제 종료하여 공격 코드 실행을 막습니다.',
    difficulty: 'MEDIUM',
    keywords: ['스택 가드', 'StackGuard', '스택카나리'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-sysvuln',
  },
  {
    id: 'EXP_SEC2_013',
    subject: '신기술/보안',
    category: '메모리 보호 기법',
    type: 'SHORT_ANSWER',
    question: '스택이나 힙 같은 데이터 저장 전용 메모리 영역에 실행(Execute) 권한을 박탈하여 해당 영역에 주입된 악성 코드가 실행되지 못하도록 차단하는 하드웨어/OS 보호 기술의 약칭은 무엇인가?',
    answer: 'DEP',
    explanation: 'DEP(Data Execution Prevention, 데이터 실행 방지 / NX bit)는 데이터 영역을 실행 불가능(No-Execute) 상태로 만듭니다.',
    difficulty: 'EASY',
    keywords: ['DEP', 'Data Execution Prevention', 'NX bit'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-sysvuln',
  },
  {
    id: 'EXP_SEC2_014',
    subject: '신기술/보안',
    category: '시큐어 코딩',
    type: 'SHORT_ANSWER',
    question: 'printf() 함수 등에 사용자 입력 문자열을 포맷 스트링 파라미터 없이 직접 넘겼을 때(%x, %s 등을 악용), 메모리 내용을 무단 조회하거나 변조할 수 있는 취약점은 무엇인가?',
    answer: '포맷 스트링 공격',
    explanation: '포맷 스트링 취약점(Format String Vulnerability)은 printf("%s", input) 대신 printf(input)을 사용했을 때 발생합니다.',
    difficulty: 'MEDIUM',
    keywords: ['포맷 스트링 공격', 'Format String', 'printf취약점'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-sysvuln',
  },
  {
    id: 'EXP_SEC2_015',
    subject: '신기술/보안',
    category: '시큐어 코딩',
    type: 'SHORT_ANSWER',
    question: '자원(파일, 메모리 등)의 접근 권한을 확인하는 시점(Check)과 실제로 자원을 사용하는 시점(Use) 사이의 시간차를 노려 공격자가 심볼릭 링크를 바꿔치기하는 취약점의 약칭은 무엇인가?',
    answer: 'TOCTOU',
    explanation: 'TOCTOU(Time of Check to Time of Use)는 레이스 컨디션(경쟁 상태)을 악용한 대표적인 권한 우회 취약점입니다.',
    difficulty: 'MEDIUM',
    keywords: ['TOCTOU', 'Time of Check to Time of Use', '경쟁상태취약점'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-sysvuln',
  },
  {
    id: 'EXP_SEC2_016',
    subject: '신기술/보안',
    category: 'DoS 공격',
    type: 'SHORT_ANSWER',
    question: 'TCP 연결 수립 과정에서 SYN 패킷을 대량으로 서버에 전송한 뒤 마지막 ACK를 보내지 않고 대기하여 서버의 백로그 큐(Backlog Queue)를 고갈시키는 서비스 거부 공격은 무엇인가?',
    answer: 'SYN Flooding',
    explanation: 'SYN Flooding은 서버의 하프 오픈(Half-Open) 연결 자원을 고갈시키며 SYN Cookie 기법으로 방어합니다.',
    difficulty: 'EASY',
    keywords: ['SYN Flooding', 'TCP연결지연', '백로그큐고갈'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-dos',
  },
  {
    id: 'EXP_SEC2_017',
    subject: '신기술/보안',
    category: 'DoS 공격',
    type: 'SHORT_ANSWER',
    question: '공격자가 패킷의 출발지 IP 주소를 피해자 서버의 IP로 위조한 후, 다이렉트 브로드캐스트 주소로 대량의 ICMP Echo Request를 전송하여 네트워크 내의 모든 호스트가 피해자에게 동시에 응답(Reply)을 쏟아붓게 만드는 DoS 공격은 무엇인가?',
    answer: '스머프',
    explanation: '스머핑(Smurfing)은 ICMP 증폭 공격으로 라우터에서 다이렉트 브로드캐스트 차단을 통해 방어합니다.',
    difficulty: 'EASY',
    keywords: ['스머프', 'Smurf', 'ICMP증폭공격'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-dos',
  },
  {
    id: 'EXP_SEC2_018',
    subject: '신기술/보안',
    category: 'DoS 공격',
    type: 'SHORT_ANSWER',
    question: '규격 허용 최대 크기(65,535 바이트)를 초과하는 거대한 ICMP 패킷을 수많은 작은 조각(Fragment)으로 분할 전송하여 수신 측이 이를 재조합하는 과정에서 버퍼 오버플로우와 다운을 유발하는 공격은 무엇인가?',
    answer: 'Ping of Death',
    explanation: 'Ping of Death(죽음의 핑)는 거대 ICMP 패킷의 재조합 취약점을 악용합니다.',
    difficulty: 'EASY',
    keywords: ['Ping of Death', '죽음의핑', '거대패킷공격'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-dos',
  },
  {
    id: 'EXP_SEC2_019',
    subject: '신기술/보안',
    category: 'DoS 공격',
    type: 'SHORT_ANSWER',
    question: 'IP 패킷 분할(Fragmentation) 시 오프셋(Fragment Offset) 값들을 의도적으로 서로 중복(Overlap)되거나 빈틈이 생기도록 조작하여 수신 시스템이 패킷 재조합 시 크래시(블루스크린)를 일으키게 하는 공격은 무엇인가?',
    answer: '티어드롭',
    explanation: '티어드롭(Teardrop) 공격은 패킷 조각 오프셋 조작으로 인한 수신 측 OS 재조합 알고리즘의 결함을 노립니다.',
    difficulty: 'EASY',
    keywords: ['티어드롭', 'Teardrop', '오프셋조작공격'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-dos',
  },
  {
    id: 'EXP_SEC2_020',
    subject: '신기술/보안',
    category: 'DoS 공격',
    type: 'SHORT_ANSWER',
    question: '패킷의 출발지 IP 주소와 포트 번호를 피해자의 대상 서버 IP 주소 및 포트 번호와 완벽히 똑같이 조작하여, 수신 서버가 자기 자신에게 계속 무한 응답 루프를 돌게 만드는 DoS 공격은 무엇인가?',
    answer: '랜드 어택',
    explanation: '랜드 어택(Land Attack)은 출발지와 목적지가 동일한 패킷을 드롭(차단)하도록 필터링하여 방어합니다.',
    difficulty: 'EASY',
    keywords: ['랜드 어택', 'Land Attack', '출발지목적지동일'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-dos',
  },
  {
    id: 'EXP_SEC2_021',
    subject: '신기술/보안',
    category: 'DoS 공격',
    type: 'SHORT_ANSWER',
    question: 'HTTP 헤더의 끝을 알리는 빈 줄(\\r\\n\\r\\n)을 고의로 전송하지 않고, 극소량의 가짜 헤더를 비정상적으로 느린 속도로 지속 전송하여 웹 서버의 동시 연결 커넥션을 모두 고갈시키는 공격은 무엇인가?',
    answer: '슬로로리스',
    explanation: '슬로로리스(Slowloris)는 저대역폭 애플리케이션 계층 DoS 공격으로 웹 서버의 Keep-Alive 연결 제한으로 대응합니다.',
    difficulty: 'EASY',
    keywords: ['슬로로리스', 'Slowloris', '헤더지연공격'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-dos',
  },
  {
    id: 'EXP_SEC2_022',
    subject: '신기술/보안',
    category: '스푸핑 공격',
    type: 'SHORT_ANSWER',
    question: '동일 로컬 네트워크(LAN) 상에서 위조된 ARP 응답 패킷을 지속적으로 희생자에게 전송하여 희생자의 ARP 캐시 테이블의 게이트웨이 MAC 주소를 공격자의 MAC 주소로 변조하는 공격은 무엇인가?',
    answer: 'ARP 스푸핑',
    explanation: 'ARP 스푸핑(ARP Spoofing)은 중간자(MITM) 공격의 기반이 되며 정적 ARP(Static ARP) 테이블 설정으로 방어합니다.',
    difficulty: 'EASY',
    keywords: ['ARP 스푸핑', 'ARP Spoofing', 'MAC주소변조'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-spoofing',
  },
  {
    id: 'EXP_SEC2_023',
    subject: '신기술/보안',
    category: '네트워크 도청',
    type: 'SHORT_ANSWER',
    question: '네트워크 인터페이스 카드(NIC)를 수신 주소와 무관하게 모든 패킷을 무차별 수신하는 무차별(Promiscuous) 모드로 설정하여 네트워크를 통과하는 평문 패킷(비밀번호 등)을 몰래 도청하는 공격은 무엇인가?',
    answer: '스니핑',
    explanation: '스니핑(Sniffing)은 수동적 도청 공격으로 데이터 전송 구간 암호화(HTTPS, SSH)로 방어합니다.',
    difficulty: 'EASY',
    keywords: ['스니핑', 'Sniffing', '무차별모드도청'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-sniffing',
  },
  {
    id: 'EXP_SEC2_024',
    subject: '신기술/보안',
    category: '세션 탈취',
    type: 'SHORT_ANSWER',
    question: 'TCP 통신에서 클라이언트와 서버 간에 정상적으로 수립된 연결 세션의 시퀀스 번호(Sequence Number)를 도청 및 예측하여 통신 흐름을 가로채고 세션 제어권을 탈취하는 공격은 무엇인가?',
    answer: '세션 하이재킹',
    explanation: 'TCP 세션 하이재킹은 시퀀스 번호 동기화를 깨뜨리고 공격자가 정상 사용자로 위장하여 명령을 실행합니다.',
    difficulty: 'MEDIUM',
    keywords: ['세션 하이재킹', 'Session Hijacking', '시퀀스번호탈취'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-hijacking',
  },
  {
    id: 'EXP_SEC2_025',
    subject: '신기술/보안',
    category: '지능형 위협',
    type: 'SHORT_ANSWER',
    question: '특정 대상 기업이나 국가 기관을 사전에 명확히 타깃으로 설정하고 장기간에 걸쳐 소셜 엔지니어링, 제로데이 취약점 등 다양한 기법을 동원해 은밀히 잠복하여 정보를 빼내는 공격의 약칭은 무엇인가?',
    answer: 'APT',
    explanation: 'APT(Advanced Persistent Threat, 지능형 지속 위협)는 지속적이고 은밀한 다단계 침투를 특징으로 합니다.',
    difficulty: 'EASY',
    keywords: ['APT', 'Advanced Persistent Threat', '지능형지속위협'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-apt',
  },
  {
    id: 'EXP_SEC2_026',
    subject: '신기술/보안',
    category: '지능형 위협',
    type: 'SHORT_ANSWER',
    question: '표적 공격 대상이 자주 방문하는 웹 사이트를 사전에 해킹하여 악성코드를 심어둔 뒤, 대상자가 해당 사이트에 접속할 때 브라우저 취약점을 이용해 감염시키는 공격 기법은 무엇인가?',
    answer: '워터링 홀',
    explanation: '워터링 홀(Watering Hole)은 맹수가 물웅덩이에 매복하듯 타깃이 즐겨 찾는 사이트를 감염 통로로 악용합니다.',
    difficulty: 'EASY',
    keywords: ['워터링 홀', 'Watering Hole', '표적매복공격'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-apt',
  },
  {
    id: 'EXP_SEC2_027',
    subject: '신기술/보안',
    category: '보안 취약점',
    type: 'SHORT_ANSWER',
    question: '소프트웨어 제조사나 개발자가 취약점의 존재를 인지하여 공식 보안 패치를 출시하기도 전에 공격자가 이를 악용하여 감행하는 보안 공격은 무엇인가?',
    answer: '제로데이 공격',
    explanation: '제로데이 공격(Zero-Day Attack)은 방어 대책이 없는 상태에서 기습 공격하므로 차단이 매우 어렵습니다.',
    difficulty: 'EASY',
    keywords: ['제로데이 공격', 'Zero-Day', '패치이전공격'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-apt',
  },
  {
    id: 'EXP_SEC2_028',
    subject: '신기술/보안',
    category: '악성 소프트웨어',
    type: 'SHORT_ANSWER',
    question: '피해자 컴퓨터 시스템의 주요 파일들을 강력한 알고리즘으로 암호화하여 접근할 수 없게 인질로 잡은 뒤, 복호화 키를 제공하는 대가로 비트코인 등 금전을 요구하는 악성코드는 무엇인가?',
    answer: '랜섬웨어',
    explanation: '랜섬웨어(Ransomware)는 몸값(Ransom)과 소프트웨어의 합성어로 중요 파일 암호화를 수행합니다.',
    difficulty: 'EASY',
    keywords: ['랜섬웨어', 'Ransomware', '파일암호화악성코드'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-malware',
  },
  {
    id: 'EXP_SEC2_029',
    subject: '신기술/보안',
    category: '보안 솔루션',
    type: 'SHORT_ANSWER',
    question: '일반 네트워크 방화벽과 달리 웹 트래픽(HTTP/HTTPS)을 패킷 레벨뿐만 아니라 애플리케이션 계층(L7)까지 심층 분석하여 SQL Injection, XSS 등을 전문 차단하는 웹 전용 방화벽의 약칭은 무엇인가?',
    answer: 'WAF',
    explanation: 'WAF(Web Application Firewall)는 웹 애플리케이션 특화 공격을 실시간 탐지/차단합니다.',
    difficulty: 'EASY',
    keywords: ['WAF', 'Web Application Firewall', '웹방화벽'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-solutions',
  },
  {
    id: 'EXP_SEC2_030',
    subject: '신기술/보안',
    category: '보안 솔루션',
    type: 'SHORT_ANSWER',
    question: '네트워크에 침입하는 이상 트래픽이나 공격 징후를 실시간으로 탐지할 뿐만 아니라, 방화벽 규칙을 동적 연동하여 즉각 패킷을 능동적으로 차단하는 침입 차단 시스템의 약칭은 무엇인가?',
    answer: 'IPS',
    explanation: 'IPS(Intrusion Prevention System, 침입 방지 시스템)는 단순 모니터링/경고에 그치는 IDS(침입 탐지 시스템)와 달리 능동적 차단을 수행합니다.',
    difficulty: 'EASY',
    keywords: ['IPS', 'Intrusion Prevention System', '침입차단시스템'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-solutions',
  },
  {
    id: 'EXP_SEC2_031',
    subject: '신기술/보안',
    category: '보안 솔루션',
    type: 'SHORT_ANSWER',
    question: '사내 PC에서 기업의 핵심 기밀 문서나 고객 개인정보가 이메일, 메신저, USB 출력 등을 통해 외부로 무단 유출되는 것을 감시하고 원천 차단하는 데이터 유출 방지 솔루션의 약칭은 무엇인가?',
    answer: 'DLP',
    explanation: 'DLP(Data Loss Prevention)는 내부자에 의한 정보 유출을 모니터링하고 통제합니다.',
    difficulty: 'EASY',
    keywords: ['DLP', 'Data Loss Prevention', '정보유출방지'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-solutions',
  },
  {
    id: 'EXP_SEC2_032',
    subject: '신기술/보안',
    category: '보안 솔루션',
    type: 'SHORT_ANSWER',
    question: '방화벽, IDS/IPS, 웹서버, 엔드포인트 등 사내의 모든 보안 장비와 시스템 로그를 실시간 빅데이터로 중앙 수집하여 상관 분석하고 위협을 조기 경보하는 통합 보안 관제 시스템의 약칭은 무엇인가?',
    answer: 'SIEM',
    explanation: 'SIEM(Security Information and Event Management)은 이기종 로그의 상관관계 분석을 수행합니다.',
    difficulty: 'EASY',
    keywords: ['SIEM', '통합보안관제', '로그상관분석'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-solutions',
  },
  {
    id: 'EXP_SEC2_033',
    subject: '신기술/보안',
    category: '보안 속임수',
    type: 'SHORT_ANSWER',
    question: '공격자를 유인하기 위해 일부러 취약하게 구성해 둔 가상의 덫 시스템으로, 해커의 공격 패턴, 도구, 행위를 분석하고 내부 핵심 자원을 보호하는 유인 시스템의 이름은 무엇인가?',
    answer: '허니팟',
    explanation: '허니팟(Honeypot)은 꿀단지처럼 공격자를 유혹하여 침해 기법을 수집하는 디코이(Decoy) 시스템입니다.',
    difficulty: 'EASY',
    keywords: ['허니팟', 'Honeypot', '유인시스템'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-solutions',
  },
  {
    id: 'EXP_SEC2_034',
    subject: '신기술/보안',
    category: '시큐어 코딩',
    type: 'SHORT_ANSWER',
    question: '소프트웨어 개발 보안(시큐어 코딩) 3단계 중 개발된 소스코드의 실행 없이 규칙 기반 정적 분석 도구(SonarQube 등)를 이용해 보안 약점을 찾아내는 점검 방식은 무엇인가?',
    answer: '정적 분석',
    explanation: '정적 분석(Static Analysis, SAST)은 코드 실행 없이 잠재 결함을 전수 검사합니다. 실행 중에 점검하는 것은 동적 분석(DAST)입니다.',
    difficulty: 'EASY',
    keywords: ['정적 분석', 'Static Analysis', 'SAST'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-securecoding',
  },
  {
    id: 'EXP_SEC2_035',
    subject: '신기술/보안',
    category: '시큐어 코딩',
    type: 'SHORT_ANSWER',
    question: '소프트웨어 실행 중에 실제 다양한 모의 해킹 페이로드와 악의적인 입력을 전송하여 취약점을 점검하는 동적 애플리케이션 보안 테스트의 약칭은 무엇인가?',
    answer: 'DAST',
    explanation: 'DAST(Dynamic Application Security Testing)는 런타임 환경에서 시스템의 실제 취약성을 점검합니다.',
    difficulty: 'MEDIUM',
    keywords: ['DAST', '동적분석', '모의해킹'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-securecoding',
  },
  {
    id: 'EXP_SEC2_036',
    subject: '신기술/보안',
    category: '클라우드 컴퓨팅',
    type: 'SHORT_ANSWER',
    question: '클라우드 서비스 모델 중 가상 서버, 스토리지, 가상 네트워크 등 순수 물리적 하드웨어 인프라 자원만을 사용자에게 대여해주는 서비스 모델의 약칭은 무엇인가?',
    answer: 'IaaS',
    explanation: 'IaaS(Infrastructure as a Service, 예: AWS EC2)는 OS 설치부터 미들웨어 구성을 사용자가 직접 관리합니다.',
    difficulty: 'EASY',
    keywords: ['IaaS', 'Infrastructure as a Service', '클라우드모델'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-cloud',
  },
  {
    id: 'EXP_SEC2_037',
    subject: '신기술/보안',
    category: '클라우드 컴퓨팅',
    type: 'SHORT_ANSWER',
    question: '클라우드 서비스 모델 중 OS, 미들웨어, 런타임 환경을 클라우드가 미리 구축해두고 개발자는 소스코드 애플리케이션만 배포하여 실행할 수 있게 해주는 플랫폼 서비스 모델의 약칭은 무엇인가?',
    answer: 'PaaS',
    explanation: 'PaaS(Platform as a Service)는 인프라 관리 부담 없이 개발과 배포에만 집중할 수 있게 합니다.',
    difficulty: 'EASY',
    keywords: ['PaaS', 'Platform as a Service', '플랫폼서비스'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-cloud',
  },
  {
    id: 'EXP_SEC2_038',
    subject: '신기술/보안',
    category: '클라우드 컴퓨팅',
    type: 'SHORT_ANSWER',
    question: '클라우드 서비스 모델 중 완성된 완성형 소프트웨어 애플리케이션을 인터넷 웹 브라우저를 통해 구독 방식으로 최종 사용자에게 완제품으로 제공하는 서비스 모델의 약칭은 무엇인가?',
    answer: 'SaaS',
    explanation: 'SaaS(Software as a Service, 예: 구글 독스, 노션)는 인스톨 없이 웹에서 즉시 사용하는 완성형 소프트웨어입니다.',
    difficulty: 'EASY',
    keywords: ['SaaS', 'Software as a Service', '소프트웨어구독'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-cloud',
  },
  {
    id: 'EXP_SEC2_039',
    subject: '신기술/보안',
    category: '클라우드 네이티브',
    type: 'SHORT_ANSWER',
    question: '개발자가 서버의 프로비저닝이나 OS 패치 등을 전혀 관리할 필요 없이, 이벤트 발생 시에만 함수(Function) 단위로 코드가 실행되고 실행 시간만큼만 과금되는 클라우드 컴퓨팅 모델은 무엇인가?',
    answer: '서버리스',
    explanation: '서버리스(Serverless, FaaS, 예: AWS Lambda)는 유휴 상태에서는 비용이 발생하지 않고 이벤트 주도형으로 동작합니다.',
    difficulty: 'EASY',
    keywords: ['서버리스', 'Serverless', 'FaaS', 'Lambda'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-cloud',
  },
  {
    id: 'EXP_SEC2_040',
    subject: '신기술/보안',
    category: 'IT 신기술',
    type: 'SHORT_ANSWER',
    question: '데이터가 발생하는 센서나 사용자 단말 장치(스마트폰, 공장 센서)와 물리적으로 가까운 위치의 엣지(Edge) 서버에서 데이터를 분산 실시간 처리하는 컴퓨팅 기술은 무엇인가?',
    answer: '엣지 컴퓨팅',
    explanation: '엣지 컴퓨팅(Edge Computing)은 중앙 클라우드로 데이터를 전송하는 대기 시간(Latency)과 네트워크 대역폭 부담을 줄여 자율주행, 스마트팩토리에 쓰입니다.',
    difficulty: 'EASY',
    keywords: ['엣지 컴퓨팅', 'Edge Computing', '실시간분산처리'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-trends',
  },
  {
    id: 'EXP_SEC2_041',
    subject: '신기술/보안',
    category: '블록체인 기술',
    type: 'SHORT_ANSWER',
    question: '블록체인 분산 원장에서 제3의 신뢰 중개자(은행, 공증인 등) 없이도 미리 합의된 계약 조건이 충족되면 프로그램 코드가 자동으로 계약을 집행하는 기능을 무엇이라 하는가?',
    answer: '스마트 계약',
    explanation: '스마트 계약(Smart Contract, 이더리움 가상머신 EVM)은 위변조가 불가능한 블록체인 코드에 의해 강제 집행됩니다.',
    difficulty: 'EASY',
    keywords: ['스마트 계약', 'Smart Contract', '블록체인계약'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-trends',
  },
  {
    id: 'EXP_SEC2_042',
    subject: '신기술/보안',
    category: '블록체인 합의 알고리즘',
    type: 'SHORT_ANSWER',
    question: '블록체인 합의 알고리즘 중 컴퓨터의 고성능 연산 능력을 투입하여 목표 난이도의 암호화 해시값을 가장 먼저 찾아내는 작업(채굴)을 통해 블록 생성 권한을 얻는 방식의 약칭은 무엇인가?',
    answer: 'PoW',
    explanation: 'PoW(Proof of Work, 작업 증명)는 막대한 전력 소모가 단점입니다. 코인 지분량에 비례해 권한을 주는 것은 PoS(Proof of Stake, 지분 증명)입니다.',
    difficulty: 'EASY',
    keywords: ['PoW', 'Proof of Work', '작업증명'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-trends',
  },
  {
    id: 'EXP_SEC2_043',
    subject: '신기술/보안',
    category: '시스템 보안 취약점',
    type: 'SHORT_ANSWER',
    question: '관리자나 개발자가 유지보수 및 디버깅 편의를 위해 시스템 인증 절차를 우회할 수 있도록 고의로 숨겨둔 비밀 통로 또는 침해 사고 후 재침투를 위해 남겨둔 통로는 무엇인가?',
    answer: '백도어',
    explanation: '백도어(Backdoor, 트랩도어)는 정상 인증 없이 시스템 관리자 권한을 획득할 수 있는 치명적 보안 위협입니다.',
    difficulty: 'EASY',
    keywords: ['백도어', 'Backdoor', '트랩도어'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-sysvuln',
  },
  {
    id: 'EXP_SEC2_044',
    subject: '신기술/보안',
    category: '소프트웨어 보안 공학',
    type: 'SHORT_ANSWER',
    question: '소프트웨어 개발(Dev)과 운영(Ops)의 협업 문화에 개발 초기 단계부터 보안(Sec)을 통합하여 자동화된 보안 검증을 상시 수행하는 개발 패러다임은 무엇인가?',
    answer: 'DevSecOps',
    explanation: 'DevSecOps는 보안을 개발 마지막 단계가 아닌 전 생명주기에 걸쳐 조기 적용(Shift-Left)합니다.',
    difficulty: 'EASY',
    keywords: ['DevSecOps', '보안통합', 'Shift-Left'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-securecoding',
  },
  {
    id: 'EXP_SEC2_045',
    subject: '신기술/보안',
    category: '웹 취약점',
    type: 'SHORT_ANSWER',
    question: '웹 브라우저의 주소창 URL이나 즐겨찾기를 정교하게 변조하거나 DNS 호스트 파일을 조작하여 피해자가 정상 주소를 입력하더라도 가짜 파밍 사이트로 강제 유인하는 금융 사기 수법은 무엇인가?',
    answer: '파밍',
    explanation: '파밍(Pharming)은 DNS 스푸핑이나 hosts 파일 변조를 이용해 정상 URL 입력 시에도 가짜 피싱 사이트로 납치합니다.',
    difficulty: 'EASY',
    keywords: ['파밍', 'Pharming', 'DNS변조사기'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-fraud',
  },
  {
    id: 'EXP_SEC2_046',
    subject: '신기술/보안',
    category: '사회공학 공격',
    type: 'SHORT_ANSWER',
    question: '문자메시지(SMS) 내에 악성 URL 링크를 첨부하여 전송하고 사용자가 클릭 시 소액결제를 유도하거나 악성 앱을 자동 다운로드시키는 사기 공격은 무엇인가?',
    answer: '스미싱',
    explanation: '스미싱(Smishing)은 SMS와 피싱(Phishing)의 합성어로 모바일 금융 피해의 주범입니다.',
    difficulty: 'EASY',
    keywords: ['스미싱', 'Smishing', 'SMS사기'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-fraud',
  },
  {
    id: 'EXP_SEC2_047',
    subject: '신기술/보안',
    category: '취약점 관리',
    type: 'SHORT_ANSWER',
    question: '미국 MITRE 사가 관리하며 공개적으로 알려진 소프트웨어 보안 취약점들에 부여하는 표준화된 고유 식별 번호 체계(예: CVE-2024-1234)의 약칭은 무엇인가?',
    answer: 'CVE',
    explanation: 'CVE(Common Vulnerabilities and Exposures)는 전 세계 취약점 정보를 공유하고 추적하기 위한 표준 식별자입니다.',
    difficulty: 'MEDIUM',
    keywords: ['CVE', 'Common Vulnerabilities and Exposures', '취약점식별자'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-vulnmgmt',
  },
  {
    id: 'EXP_SEC2_048',
    subject: '신기술/보안',
    category: '취약점 심각도 평가',
    type: 'SHORT_ANSWER',
    question: '발견된 소프트웨어 취약점의 위험도와 심각성을 기본 점수, 시간 점수, 환경 점수를 종합하여 0.0 ~ 10.0의 표준 점수로 계량화하는 범용 취약점 평가 시스템의 약칭은 무엇인가?',
    answer: 'CVSS',
    explanation: 'CVSS(Common Vulnerability Scoring System)는 취약점의 파급력을 객관적 수치로 표준 평가합니다.',
    difficulty: 'MEDIUM',
    keywords: ['CVSS', 'Common Vulnerability Scoring System', '취약점점수'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-vulnmgmt',
  },
  {
    id: 'EXP_SEC2_049',
    subject: '신기술/보안',
    category: '클라우드 보안',
    type: 'SHORT_ANSWER',
    question: '클라우드 책임 공유 모델(Shared Responsibility Model)에서 IaaS를 이용할 때, 운영체제(OS) 패치 및 애플리케이션 보안 설정의 책임 주체는 클라우드 제공업체인가 고객(사용자)인가?',
    answer: '고객',
    explanation: 'IaaS에서 클라우드 제공사는 물리 인프라와 하이퍼바이저만 책임지며, 게스트 OS, 런타임, 애플리케이션의 보안 책임은 전적으로 고객에게 있습니다.',
    difficulty: 'EASY',
    keywords: ['고객', '책임공유모델', 'IaaS책임'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-cloud',
  },
  {
    id: 'EXP_SEC2_050',
    subject: '신기술/보안',
    category: '암호화폐 및 핀테크',
    type: 'SHORT_ANSWER',
    question: '블록체인의 블록 헤더에 저장되는 값으로, 블록 내의 모든 트랜잭션(거래)들의 해시값을 2개씩 짝지어 상위로 해싱해 올라가며 최종적으로 도출된 단 하나의 루트 해시값을 무엇이라 하는가?',
    answer: '머클 루트',
    explanation: '머클 루트(Merkle Root, 머클 트리)는 단 하나의 루트 해시만으로 수천 건의 거래 데이터 무결성을 초고속 검증합니다.',
    difficulty: 'EASY',
    keywords: ['머클 루트', 'Merkle Root', '머클트리'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-trends',
  },
];
