import { Question } from '../../src/types/question';

export const BATCH_9_QUESTIONS: Question[] = [
  {
    id: 'EXP_SEC1_001',
    subject: '신기술/보안',
    category: '블록 암호 모드',
    type: 'SHORT_ANSWER',
    question: '블록 암호 운영 모드 중 평문 블록들을 각각 독립적으로 동일한 비밀키로 암호화하여 동일한 평문 블록이 항상 동일한 암호문 블록을 생성하므로 패턴 노출에 가장 취약한 모드는 무엇인가?',
    answer: 'ECB',
    explanation: 'ECB(Electronic Codebook, 전자 코드북) 모드는 블록 간의 연쇄가 없어 가장 단순하지만 보안성이 매우 취약합니다.',
    difficulty: 'EASY',
    keywords: ['ECB', 'Electronic Codebook', '블록암호모드'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-modes',
  },
  {
    id: 'EXP_SEC1_002',
    subject: '신기술/보안',
    category: '블록 암호 모드',
    type: 'SHORT_ANSWER',
    question: '블록 암호 운영 모드 중 이전 암호문 블록과 현재 평문 블록을 XOR 연산한 후 암호화하며, 첫 번째 평문 블록 암호화를 위해 고유한 초기화 벡터(IV)를 반드시 사용하는 모드는 무엇인가?',
    answer: 'CBC',
    explanation: 'CBC(Cipher Block Chaining, 암호 블록 연쇄) 모드는 평문 패턴을 완벽히 은폐하며 가장 널리 쓰이는 표준 모드입니다.',
    difficulty: 'EASY',
    keywords: ['CBC', 'Cipher Block Chaining', '초기화벡터'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-modes',
  },
  {
    id: 'EXP_SEC1_003',
    subject: '신기술/보안',
    category: '블록 암호 모드',
    type: 'SHORT_ANSWER',
    question: '블록 암호 모드 중 1씩 증가하는 고유한 카운터(Counter) 값을 블록 암호기로 암호화한 키 스트림을 평문과 XOR 연산하여 병렬 암호화/복호화가 가능한 고속 모드는 무엇인가?',
    answer: 'CTR',
    explanation: 'CTR(Counter, 카운터) 모드는 블록 암호를 스트림 암호처럼 구동하며 멀티코어 환경에서 병렬 처리가 가능합니다.',
    difficulty: 'MEDIUM',
    keywords: ['CTR', 'Counter', '병렬암호화'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-modes',
  },
  {
    id: 'EXP_SEC1_004',
    subject: '신기술/보안',
    category: '블록 암호 모드',
    type: 'SHORT_ANSWER',
    question: '블록 암호 모드 중 암호기의 출력(Output) 값을 다음 단계 암호기의 입력으로 직접 피드백하여 전송 채널 상의 1비트 오류가 후속 암호 블록으로 전파되지 않는 모드는 무엇인가?',
    answer: 'OFB',
    explanation: 'OFB(Output Feedback, 출력 피드백) 모드는 에러 전파(Error Propagation)가 발생하지 않는 특징이 있습니다.',
    difficulty: 'MEDIUM',
    keywords: ['OFB', 'Output Feedback', '에러전파없음'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-modes',
  },
  {
    id: 'EXP_SEC1_005',
    subject: '신기술/보안',
    category: '대칭키 암호',
    type: 'SHORT_ANSWER',
    question: '미국 표준국(NIST)의 구 표준 블록 암호화 알고리즘으로 64비트 평문 블록을 56비트 유효 키를 사용해 16라운드 Feistel 구조로 암호화하는 알고리즘은 무엇인가?',
    answer: 'DES',
    explanation: 'DES(Data Encryption Standard)는 56비트의 짧은 키 길이로 인해 현재는 전수 조사(Brute Force) 공격에 취약하여 사용이 권장되지 않습니다.',
    difficulty: 'EASY',
    keywords: ['DES', 'Data Encryption Standard', '56비트키'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-ciphers',
  },
  {
    id: 'EXP_SEC1_006',
    subject: '신기술/보안',
    category: '대칭키 암호',
    type: 'SHORT_ANSWER',
    question: 'DES의 취약한 키 길이를 보완하기 위해 2개 또는 3개의 서로 다른 키를 사용하여 "암호화 → 복호화 → 암호화(EDE)" 과정을 3번 반복 적용하는 알고리즘은 무엇인가?',
    answer: '3DES',
    explanation: 'Triple DES(3DES)는 기존 DES 하드웨어를 재활용하면서 보안성을 높인 과도기적 알고리즘입니다.',
    difficulty: 'EASY',
    keywords: ['3DES', 'Triple DES', 'EDE방식'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-ciphers',
  },
  {
    id: 'EXP_SEC1_007',
    subject: '신기술/보안',
    category: '대칭키 암호',
    type: 'SHORT_ANSWER',
    question: '미국 NIST가 DES를 대체하기 위해 공모를 통해 표준으로 선정한 현대의 대표 블록 암호로, 128비트 블록 크기와 SPN(치환-순열망) 구조를 갖는 알고리즘은 무엇인가?',
    answer: 'AES',
    explanation: 'AES(Advanced Encryption Standard, 레인달 Rijndael 알고리즘)는 128/192/256비트 키 길이를 지원하는 전 세계 표준 대칭키 암호입니다.',
    difficulty: 'EASY',
    keywords: ['AES', 'Advanced Encryption Standard', 'SPN구조'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-ciphers',
  },
  {
    id: 'EXP_SEC1_008',
    subject: '신기술/보안',
    category: '대칭키 암호',
    type: 'SHORT_ANSWER',
    question: '한국인터넷진흥원(KISA)이 전자상거래와 공공 보안을 위해 개발한 국내 표준 블록 암호 알고리즘으로, 128비트 블록 크기와 16라운드 Feistel 구조를 사용하는 것은 무엇인가?',
    answer: 'SEED',
    explanation: 'SEED는 대한민국의 국가 표준 대칭키 블록 암호 알고리즘입니다.',
    difficulty: 'EASY',
    keywords: ['SEED', 'KISA', '국내표준암호'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-ciphers',
  },
  {
    id: 'EXP_SEC1_009',
    subject: '신기술/보안',
    category: '대칭키 암호',
    type: 'SHORT_ANSWER',
    question: '국가정보원과 국가보안기술연구소(NSRI)가 주도하여 개발한 128비트 블록 크기의 국가 표준 암호로, AES와 동일한 SPN(치환-순열망) 구조를 채택한 국내 알고리즘은 무엇인가?',
    answer: 'ARIA',
    explanation: 'ARIA(Academy Research Institute Agency)는 경량 하드웨어 및 범용 프로세서에서 고속 동작하는 대한민국 표준 암호입니다.',
    difficulty: 'EASY',
    keywords: ['ARIA', '국정원암호', 'SPN구조'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-ciphers',
  },
  {
    id: 'EXP_SEC1_010',
    subject: '신기술/보안',
    category: '대칭키 암호',
    type: 'SHORT_ANSWER',
    question: '초소형 사물인터넷(IoT) 기기, RFID 태그, 스마트카드 등 자원이 극도로 제한된 환경을 위해 개발된 64비트 블록 크기의 초경량 블록 암호 알고리즘은 무엇인가?',
    answer: 'HIGHT',
    explanation: 'HIGHT(HIGh security and lightweigHT)는 저전력 초경량 환경을 위한 한국 표준 암호입니다.',
    difficulty: 'MEDIUM',
    keywords: ['HIGHT', '초경량암호', 'RFID암호'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-ciphers',
  },
  {
    id: 'EXP_SEC1_011',
    subject: '신기술/보안',
    category: '비대칭키 암호',
    type: 'SHORT_ANSWER',
    question: '1977년 라이베스트, 샤미르, 애들먼이 발표한 대표적인 공개키 암호 알고리즘으로, 아주 큰 두 소수의 곱을 소인수분해하기 어렵다는 수학적 난제에 기반한 알고리즘은 무엇인가?',
    answer: 'RSA',
    explanation: 'RSA는 전 세계 전자서명 및 공개키 암호화의 사실상 표준입니다.',
    difficulty: 'EASY',
    keywords: ['RSA', '소인수분해난제', '공개키암호'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-ciphers',
  },
  {
    id: 'EXP_SEC1_012',
    subject: '신기술/보안',
    category: '비대칭키 암호',
    type: 'SHORT_ANSWER',
    question: '타원곡선 상의 이산대수 문제에 기반하여 RSA보다 훨씬 짧은 키 길이(256비트가 RSA 3072비트 수준)로 동일한 보안 강도를 제공하여 모바일 기기에 최적화된 공개키 암호는 무엇인가?',
    answer: 'ECC',
    explanation: 'ECC(Elliptic Curve Cryptography)는 적은 연산량과 짧은 키 길이로 스마트폰 및 IoT 암호화의 핵심 기술입니다.',
    difficulty: 'EASY',
    keywords: ['ECC', 'Elliptic Curve', '타원곡선암호'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-ciphers',
  },
  {
    id: 'EXP_SEC1_013',
    subject: '신기술/보안',
    category: '비대칭키 암호',
    type: 'SHORT_ANSWER',
    question: '공개된 안전하지 않은 통신 채널 상에서 사전 비밀 공유 없이 두 사용자가 안전하게 동일한 대칭 비밀키를 공유할 수 있도록 고안된 최초의 비밀키 교환 프로토콜은 무엇인가?',
    answer: '디피 헬만',
    explanation: '디피-헬만(Diffie-Hellman) 키 교환 알고리즘은 이산대수 문제에 기반하지만, 상호 인증 기능이 없어 중간자 공격(MITM)에 취약합니다.',
    difficulty: 'EASY',
    keywords: ['디피 헬만', 'Diffie-Hellman', '키교환프로토콜'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-ciphers',
  },
  {
    id: 'EXP_SEC1_014',
    subject: '신기술/보안',
    category: '해시 함수',
    type: 'SHORT_ANSWER',
    question: '미국 국가안보국(NSA)이 설계한 표준 해시 함수 계열 중 임의 길이의 평문을 입력받아 256비트(32바이트) 고정 길이의 고유 다이제스트를 출력하는 해시 알고리즘은 무엇인가?',
    answer: 'SHA-256',
    explanation: 'SHA-256은 블록체인 비트코인 및 현대 웹 보안 인증서에 널리 사용되는 안전한 단방향 해시 함수입니다.',
    difficulty: 'EASY',
    keywords: ['SHA-256', '해시함수', '단방향해시'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-hash',
  },
  {
    id: 'EXP_SEC1_015',
    subject: '신기술/보안',
    category: '해시 함수 보안',
    type: 'SHORT_ANSWER',
    question: '사전에 미리 계산해 둔 대규모의 해시값 역추적 조회표(레인보우 테이블)를 무력화하기 위해, 사용자의 패스워드 원문에 임의의 난수 문자열을 덧붙여 해싱하는 기법은 무엇인가?',
    answer: '솔트',
    explanation: '솔트(Salt, 솔팅)는 동일한 패스워드라도 서로 다른 다이제스트가 생성되도록 만들어 무차별 대입 공격을 차단합니다.',
    difficulty: 'EASY',
    keywords: ['솔트', 'Salt', '레인보우테이블방어'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-hash',
  },
  {
    id: 'EXP_SEC1_016',
    subject: '신기술/보안',
    category: '보안 통제 모델',
    type: 'SHORT_ANSWER',
    question: '군사적 기밀성을 보장하기 위해 고안된 보안 모델로, 자신의 보안 등급보다 높은 문서는 읽을 수 없고(No Read Up) 낮은 문서에는 쓸 수 없는(No Write Down) 모델은 무엇인가?',
    answer: '벨 라파듈라',
    explanation: '벨-라파듈라(BLP, Bell-LaPadula) 모델은 기밀성(Confidentiality) 유지가 최우선 목표입니다.',
    difficulty: 'EASY',
    keywords: ['벨 라파듈라', 'BLP', '기밀성모델', 'No Read Up'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-models',
  },
  {
    id: 'EXP_SEC1_017',
    subject: '신기술/보안',
    category: '보안 통제 모델',
    type: 'SHORT_ANSWER',
    question: '데이터의 무결성(Integrity)을 최우선으로 보장하기 위해 고안된 보안 모델로, 자신의 등급보다 낮은 문서는 읽을 수 없고(No Read Down) 높은 문서에는 쓸 수 없는(No Write Up) 모델은 무엇인가?',
    answer: '비바',
    explanation: '비바(Biba) 모델은 잘못된 하위 데이터가 상위 신뢰 데이터를 오염시키는 것을 방지하여 무결성을 지킵니다.',
    difficulty: 'EASY',
    keywords: ['비바', 'Biba', '무결성모델', 'No Read Down'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-models',
  },
  {
    id: 'EXP_SEC1_018',
    subject: '신기술/보안',
    category: '보안 통제 모델',
    type: 'SHORT_ANSWER',
    question: '금융이나 전자상거래 같은 상업적 환경을 위해 고안된 무결성 모델로, 직무 분리(Separation of Duties)와 감사 추적을 바탕으로 허가된 절차를 통해서만 데이터를 변환시키는 모델은 무엇인가?',
    answer: '클락 윌슨',
    explanation: '클락-윌슨(Clark-Wilson) 모델은 CDI, UDI, TP(변환절차), IVP(검증절차)를 통해 데이터의 변조를 막는 상업용 무결성 모델입니다.',
    difficulty: 'MEDIUM',
    keywords: ['클락 윌슨', 'Clark-Wilson', '직무분리', '상업무결성'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-models',
  },
  {
    id: 'EXP_SEC1_019',
    subject: '신기술/보안',
    category: '접근 통제 정책',
    type: 'SHORT_ANSWER',
    question: '접근 통제 정책 중 데이터 소유자(Owner)가 자신의 판단에 따라 특정 사용자에 대한 접근 권한(읽기, 쓰기 등)을 자율적으로 부여하거나 회수하는 방식의 약칭은 무엇인가?',
    answer: 'DAC',
    explanation: 'DAC(Discretionary Access Control, 임의적 접근 통제)는 유연하지만 소유자의 실수로 권한이 남용될 수 있습니다.',
    difficulty: 'EASY',
    keywords: ['DAC', 'Discretionary Access Control', '임의적접근통제'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-access',
  },
  {
    id: 'EXP_SEC1_020',
    subject: '신기술/보안',
    category: '접근 통제 정책',
    type: 'SHORT_ANSWER',
    question: '관리자나 시스템이 설정한 보안 등급(Secret, Top Secret 등)과 주체의 인가 등급을 중앙에서 비교하여 규칙 기반으로 접근을 강제 통제하는 방식의 약칭은 무엇인가?',
    answer: 'MAC',
    explanation: 'MAC(Mandatory Access Control, 강제적 접근 통제)는 보안 관리자만 권한을 설정할 수 있어 군사/정부 시스템에 쓰입니다.',
    difficulty: 'EASY',
    keywords: ['MAC', 'Mandatory Access Control', '강제적접근통제'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-access',
  },
  {
    id: 'EXP_SEC1_021',
    subject: '신기술/보안',
    category: '접근 통제 정책',
    type: 'SHORT_ANSWER',
    question: '사용자 개인에게 직접 권한을 주지 않고, 조직 내에서 사용자가 맡은 역할(Role)에 권한을 매핑한 후 사용자에게 해당 역할을 배정하는 접근 통제 방식의 약칭은 무엇인가?',
    answer: 'RBAC',
    explanation: 'RBAC(Role-Based Access Control, 역할 기반 접근 통제)는 인사 이동이 잦은 기업 환경에서 권한 관리가 매우 효율적입니다.',
    difficulty: 'EASY',
    keywords: ['RBAC', 'Role-Based Access Control', '역할기반'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-access',
  },
  {
    id: 'EXP_SEC1_022',
    subject: '신기술/보안',
    category: '접근 통제 정책',
    type: 'SHORT_ANSWER',
    question: '주체의 속성, 객체의 속성, 환경 조건(시간, 위치, 디바이스 상태 등)을 동적으로 결합하여 세분화된 보안 정책을 적용하는 속성 기반 접근 통제의 약칭은 무엇인가?',
    answer: 'ABAC',
    explanation: 'ABAC(Attribute-Based Access Control)는 XACML 표준을 기반으로 상황 인지형 동적 접근 제어를 제공합니다.',
    difficulty: 'MEDIUM',
    keywords: ['ABAC', 'Attribute-Based Access Control', '속성기반'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-access',
  },
  {
    id: 'EXP_SEC1_023',
    subject: '신기술/보안',
    category: '정보보안 3대 요소',
    type: 'SHORT_ANSWER',
    question: '인가되지 않은 사용자가 정보 시스템의 자원이나 데이터 내용을 도청하거나 열람할 수 없도록 보장하는 정보보안의 기본 원칙은 무엇인가?',
    answer: '기밀성',
    explanation: '기밀성(Confidentiality)은 암호화와 접근 통제를 통해 비인가자의 정보 노출을 방지합니다.',
    difficulty: 'EASY',
    keywords: ['기밀성', 'Confidentiality', '보안3요소'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-cia',
  },
  {
    id: 'EXP_SEC1_024',
    subject: '신기술/보안',
    category: '정보보안 3대 요소',
    type: 'SHORT_ANSWER',
    question: '정보 시스템 내의 데이터나 프로그램이 인가되지 않은 방식이나 악의적인 변조, 삽입, 삭제로부터 안전하게 원본 상태를 유지함을 보장하는 보안 원칙은 무엇인가?',
    answer: '무결성',
    explanation: '무결성(Integrity)은 해시 함수, 전자서명, 체크섬 등을 통해 데이터의 위·변조를 검증합니다.',
    difficulty: 'EASY',
    keywords: ['무결성', 'Integrity', '위변조방지'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-cia',
  },
  {
    id: 'EXP_SEC1_025',
    subject: '신기술/보안',
    category: '정보보안 3대 요소',
    type: 'SHORT_ANSWER',
    question: '인가된 적법한 사용자가 필요한 시점에 방해받지 않고 언제든지 정보 시스템과 자원을 즉시 이용할 수 있도록 보장하는 보안 원칙은 무엇인가?',
    answer: '가용성',
    explanation: '가용성(Availability)은 DoS/DDoS 방어, 이중화, 백업 등을 통해 시스템이 지속 가동되도록 보장합니다.',
    difficulty: 'EASY',
    keywords: ['가용성', 'Availability', '시스템상시가동'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-cia',
  },
  {
    id: 'EXP_SEC1_026',
    subject: '신기술/보안',
    category: '전자 서명',
    type: 'SHORT_ANSWER',
    question: '송신자가 데이터를 전송했거나 승인한 사실을 나중에 거짓으로 발뺌(부인)할 수 없도록 전자서명 등으로 증명하는 정보보안 속성은 무엇인가?',
    answer: '부인 방지',
    explanation: '부인 방지(Non-repudiation)는 송신자의 개인키로 서명하여 송신 사실과 수신 사실을 법적으로 증명합니다.',
    difficulty: 'EASY',
    keywords: ['부인 방지', 'Non-repudiation', '전자서명'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-pki',
  },
  {
    id: 'EXP_SEC1_027',
    subject: '신기술/보안',
    category: '전자 서명',
    type: 'SHORT_ANSWER',
    question: '전자서명 생성 시 송신자는 원본 문서의 해시값을 자신의 어떤 키(공개키 / 개인키)로 암호화하여 서명 값을 만들어내는가?',
    answer: '개인키',
    explanation: '전자서명은 송신자의 비밀 개인키(Private Key)로 암호화하고, 수신자는 송신자의 공개키(Public Key)로 복호화하여 서명을 검증합니다.',
    difficulty: 'EASY',
    keywords: ['개인키', 'Private Key', '전자서명생성'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-pki',
  },
  {
    id: 'EXP_SEC1_028',
    subject: '신기술/보안',
    category: '공개키 기반 구조',
    type: 'SHORT_ANSWER',
    question: '공개키의 신뢰성을 보증하기 위해 공인인증기관(CA)이 발행하는 디지털 공개키 인증서의 세계 표준 규격 명칭은 무엇인가?',
    answer: 'X.509',
    explanation: 'X.509 표준 인증서는 버전, 일련번호, 서명 알고리즘, 발행자, 유효기간, 주체 공개키 정보 등을 담고 있습니다.',
    difficulty: 'MEDIUM',
    keywords: ['X.509', '인증서표준', 'PKI'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-pki',
  },
  {
    id: 'EXP_SEC1_029',
    subject: '신기술/보안',
    category: '공개키 기반 구조',
    type: 'SHORT_ANSWER',
    question: '유효기간이 만료되기 전에 개인키 유출이나 신분 변경 등으로 인해 효력이 상실된 인증서들의 목록을 담고 있는 인증서 폐기 목록의 약칭은 무엇인가?',
    answer: 'CRL',
    explanation: 'CRL(Certificate Revocation List)은 인증기관이 주기적으로 배포하는 폐기된 인증서 목록입니다. 실시간 조회를 위한 온라인 프로토콜은 OCSP입니다.',
    difficulty: 'EASY',
    keywords: ['CRL', 'Certificate Revocation List', '인증서폐기목록'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-pki',
  },
  {
    id: 'EXP_SEC1_030',
    subject: '신기술/보안',
    category: '공개키 기반 구조',
    type: 'SHORT_ANSWER',
    question: '인증서 폐기 목록(CRL)을 매번 다운로드받는 오버헤드를 없애고, 특정 인증서의 유효/폐기 상태를 인증 서버에 실시간으로 질의하여 확인하는 온라인 프로토콜의 약칭은 무엇인가?',
    answer: 'OCSP',
    explanation: 'OCSP(Online Certificate Status Protocol)는 실시간으로 개별 인증서의 유효성을 경량 질의/응답합니다.',
    difficulty: 'MEDIUM',
    keywords: ['OCSP', 'Online Certificate Status', '실시간인증서검증'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-pki',
  },
  {
    id: 'EXP_SEC1_031',
    subject: '신기술/보안',
    category: '사용자 인증',
    type: 'SHORT_ANSWER',
    question: '한 번의 시스템 로그인 성공으로 연동된 다른 모든 웹 사이트와 애플리케이션 서비스들을 추가 인증 없이 자동으로 이용할 수 있게 해주는 통합 인증 기술의 약칭은 무엇인가?',
    answer: 'SSO',
    explanation: 'SSO(Single Sign-On)는 중앙 인증 서버(CAS 등)를 두어 사용자의 편의성과 계정 관리 효율을 극대화합니다.',
    difficulty: 'EASY',
    keywords: ['SSO', 'Single Sign-On', '통합인증'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-auth',
  },
  {
    id: 'EXP_SEC1_032',
    subject: '신기술/보안',
    category: '사용자 인증',
    type: 'SHORT_ANSWER',
    question: '사용자가 자신의 비밀번호를 제3자 앱에 직접 노출하지 않고, 구글이나 카카오 등 인증 제공자로부터 인가 토큰(Access Token)을 발급받아 자원 접근 권한을 위임하는 개방형 인가 표준은 무엇인가?',
    answer: 'OAuth',
    explanation: 'OAuth 2.0(Open Authorization)은 안전한 API 권한 위임을 위한 표준 프레임워크입니다.',
    difficulty: 'EASY',
    keywords: ['OAuth', 'Open Authorization', '권한위임'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-auth',
  },
  {
    id: 'EXP_SEC1_033',
    subject: '신기술/보안',
    category: '인증 토큰',
    type: 'SHORT_ANSWER',
    question: '헤더(Header), 내용(Payload), 서명(Signature) 3개 영역이 점(.)으로 구분되어 JSON 형식으로 클레임 정보를 안전하게 전달하는 경량 웹 토큰 표준의 약칭은 무엇인가?',
    answer: 'JWT',
    explanation: 'JWT(JSON Web Token)는 자체 완결적(Self-contained) 토큰으로 세션 저장소 없이 토큰 자체 서명 검증만으로 무상태 인증을 구현합니다.',
    difficulty: 'EASY',
    keywords: ['JWT', 'JSON Web Token', '웹토큰'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-auth',
  },
  {
    id: 'EXP_SEC1_034',
    subject: '신기술/보안',
    category: '다중 요소 인증',
    type: 'SHORT_ANSWER',
    question: '지식 기반(비밀번호), 소지 기반(스마트폰/OTP), 생체 기반(지문/홍채) 중 서로 다른 2가지 이상의 독립된 인증 요소를 결합하여 보안을 강화하는 인증 방식의 약칭은 무엇인가?',
    answer: 'MFA',
    explanation: 'MFA(Multi-Factor Authentication, 다중 요소 인증)는 단일 인증 수단 침해로 인한 계정 탈취를 방지합니다.',
    difficulty: 'EASY',
    keywords: ['MFA', 'Multi-Factor Authentication', '다중요소인증'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-auth',
  },
  {
    id: 'EXP_SEC1_035',
    subject: '신기술/보안',
    category: '인증 기술',
    type: 'SHORT_ANSWER',
    question: '매번 로그인할 때마다 고정되지 않은 무작위 6자리 일회용 비밀번호를 동적으로 생성하여 재사용 공격(Replay Attack)을 원천 차단하는 인증 기술의 약칭은 무엇인가?',
    answer: 'OTP',
    explanation: 'OTP(One Time Password)는 시간 동기 방식(TOTP)이나 이벤트 카운터 방식(HOTP)으로 매회 일회용 비밀번호를 만듭니다.',
    difficulty: 'EASY',
    keywords: ['OTP', 'One Time Password', '일회용비밀번호'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-auth',
  },
  {
    id: 'EXP_SEC1_036',
    subject: '신기술/보안',
    category: '패스워드 크래킹',
    type: 'SHORT_ANSWER',
    question: '사전에 등재된 단어 목록(사전 파일)들을 프로그램으로 순차 대입하여 취약한 패스워드를 알아내는 고전적인 공격 기법은 무엇인가?',
    answer: '사전 공격',
    explanation: '사전 공격(Dictionary Attack)은 무차별 대입 공격보다 시도 횟수를 대폭 줄여 빈출 단어 위주로 빠르게 크랙합니다.',
    difficulty: 'EASY',
    keywords: ['사전 공격', 'Dictionary Attack', '패스워드크래킹'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-attacks',
  },
  {
    id: 'EXP_SEC1_037',
    subject: '신기술/보안',
    category: '패스워드 크래킹',
    type: 'SHORT_ANSWER',
    question: '가능한 모든 문자들의 조합(영문, 숫자, 특수문자 전체)을 하나씩 빠짐없이 끝까지 대입하여 비밀번호를 찾아내는 가장 단순하지만 확실한 공격 기법은 무엇인가?',
    answer: '무차별 대입 공격',
    explanation: '무차별 대입 공격(Brute Force Attack)은 시간과 연산 자원만 충분하다면 원리상 100% 해독 가능한 공격입니다.',
    difficulty: 'EASY',
    keywords: ['무차별 대입 공격', 'Brute Force', '전수조사공격'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-attacks',
  },
  {
    id: 'EXP_SEC1_038',
    subject: '신기술/보안',
    category: '키 분배 메커니즘',
    type: 'SHORT_ANSWER',
    question: '대칭키 분배 센터(KDC) 방식을 기반으로 티켓(Ticket) 개념을 도입하여 안전하지 않은 분산 네트워크 환경에서 상호 인증을 제공하는 대표 인증 프로토콜은 무엇인가?',
    answer: '커버로스',
    explanation: '커버로스(Kerberos)는 TGT(티켓 발급 티켓)와 세션 티켓을 사용해 비밀번호의 평문 전송 없이 안전하게 클라이언트-서버 인증을 수행합니다.',
    difficulty: 'MEDIUM',
    keywords: ['커버로스', 'Kerberos', '티켓기반인증'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-auth',
  },
  {
    id: 'EXP_SEC1_039',
    subject: '신기술/보안',
    category: '보안 통제',
    type: 'SHORT_ANSWER',
    question: '데이터베이스 암호화 방식 중 데이터베이스 엔진 내부의 트리거(Trigger)나 사용자 정의 함수 패키지를 통해 암/복호화를 수행하는 방식을 무엇이라 하는가?',
    answer: 'Plug-in 방식',
    explanation: '플러그인(Plug-in) 방식은 DB 서버 내부에 모듈을 설치해 애플리케이션의 수정 없이 암호화를 적용합니다.',
    difficulty: 'MEDIUM',
    keywords: ['Plug-in 방식', '플러그인방식', 'DB암호화'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-dbsec',
  },
  {
    id: 'EXP_SEC1_040',
    subject: '신기술/보안',
    category: '보안 통제',
    type: 'SHORT_ANSWER',
    question: '데이터베이스 암호화 방식 중 애플리케이션 서버 소스코드 레벨에서 API 라이브러리를 직접 호출하여 암호화된 데이터를 DB로 전송하는 방식은 무엇인가?',
    answer: 'API 방식',
    explanation: 'API 방식은 애플리케이션 서버에서 암/복호화가 이루어지므로 DB 서버에 부하를 주지 않고 통신 구간도 안전하지만 소스 수정이 필요합니다.',
    difficulty: 'EASY',
    keywords: ['API 방식', 'DB암호화', '애플리케이션암호화'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-dbsec',
  },
  {
    id: 'EXP_SEC1_041',
    subject: '신기술/보안',
    category: '보안 통제',
    type: 'SHORT_ANSWER',
    question: '데이터베이스 암호화 방식 중 DBMS 커널 내부에서 데이터 파일이 디스크에 저장될 때 자동으로 투명하게 암호화하고 읽을 때 복호화하는 TDE 기술의 전체 명칭은 무엇인가?',
    answer: '투명한 데이터 암호화',
    explanation: 'TDE(Transparent Data Encryption)는 애플리케이션과 쿼리의 수정 없이 저장 데이터(Data at Rest)를 자동 암호화합니다.',
    difficulty: 'MEDIUM',
    keywords: ['투명한 데이터 암호화', 'TDE', 'Transparent Data Encryption'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-dbsec',
  },
  {
    id: 'EXP_SEC1_042',
    subject: '신기술/보안',
    category: '개인정보 보호',
    type: 'SHORT_ANSWER',
    question: '주민등록번호나 신용카드 번호 같은 민감한 원본 데이터를 고유한 난수 형태의 토큰(Token) 값으로 치환하여 보관함으로써 유출 시 피해를 방지하는 보안 기술은 무엇인가?',
    answer: '토큰화',
    explanation: '토큰화(Tokenization)는 원본 데이터 대신 수학적 연관성이 없는 토큰을 사용하여 보안 위험을 분리합니다.',
    difficulty: 'EASY',
    keywords: ['토큰화', 'Tokenization', '개인정보보호'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-privacy',
  },
  {
    id: 'EXP_SEC1_043',
    subject: '신기술/보안',
    category: '개인정보 보호',
    type: 'SHORT_ANSWER',
    question: '특정 개인의 데이터를 마스킹, 가명처리, 범주화 등의 방법으로 가공하여 더 이상 특정 개인을 알아볼 수 없도록 조치하는 과정을 무엇이라 하는가?',
    answer: '비식별화',
    explanation: '비식별화(De-identification)는 데이터의 활용성을 보장하면서 개인 프라이버시 침해를 예방하는 기법입니다.',
    difficulty: 'EASY',
    keywords: ['비식별화', 'De-identification', '가명정보'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-privacy',
  },
  {
    id: 'EXP_SEC1_044',
    subject: '신기술/보안',
    category: '개인정보 보호',
    type: 'SHORT_ANSWER',
    question: '프라이버시 보호 모델 중 데이터셋 내에서 특정 개인과 동일한 준식별자(나이, 성별, 지역 등) 속성 값을 가진 사람이 최소 k명 이상 존재하도록 익명화하는 모델은 무엇인가?',
    answer: 'k-익명성',
    explanation: 'k-익명성(k-Anonymity)은 재식별 위험을 1/k 이하로 낮춥니다. 동질성 공격을 막기 위해 다양성을 보장하는 것은 l-다양성입니다.',
    difficulty: 'MEDIUM',
    keywords: ['k-익명성', 'k-Anonymity', '비식별화모델'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-privacy',
  },
  {
    id: 'EXP_SEC1_045',
    subject: '신기술/보안',
    category: '개인정보 보호',
    type: 'SHORT_ANSWER',
    question: 'k-익명성 모델에서 동질적인 민감 정보가 집중되는 결함(동질성 공격)을 방지하기 위해, 동등 클래스 내의 민감한 속성 값들의 종류가 최소 l개 이상 다양하도록 보장하는 모델은 무엇인가?',
    answer: 'l-다양성',
    explanation: 'l-다양성(l-Diversity)은 k-익명성의 취약점을 보완하여 정보 누출을 방지합니다.',
    difficulty: 'MEDIUM',
    keywords: ['l-다양성', 'l-Diversity', '동질성공격방어'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-privacy',
  },
  {
    id: 'EXP_SEC1_046',
    subject: '신기술/보안',
    category: '정보보호 관리체계',
    type: 'SHORT_ANSWER',
    question: '기업의 주요 정보 자산과 개인정보를 안전하게 보호하기 위해 과학기술정보통신부와 개인정보보호위원회가 공동 운영하는 한국의 종합 정보보호 인증 제도의 약칭은 무엇인가?',
    answer: 'ISMS-P',
    explanation: 'ISMS-P는 정보보호 관리체계(ISMS)와 개인정보보호 관리체계(PIMS)를 통합한 국가 인증 제도입니다.',
    difficulty: 'EASY',
    keywords: ['ISMS-P', '정보보호관리체계', '인증제도'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-isms',
  },
  {
    id: 'EXP_SEC1_047',
    subject: '신기술/보안',
    category: '정보보호 평가 기준',
    type: 'SHORT_ANSWER',
    question: '국가마다 서로 다른 정보보호 시스템의 보안 평가 기준을 상호 인정하기 위해 제정한 다국적 국제 공통 평가 기준(ISO/IEC 15408)의 약칭은 무엇인가?',
    answer: 'CC',
    explanation: 'CC(Common Criteria, 공통평가기준)는 EAL1부터 EAL7까지 7등급의 평가 보증 등급을 규정합니다.',
    difficulty: 'EASY',
    keywords: ['CC', 'Common Criteria', '공통평가기준'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-cc',
  },
  {
    id: 'EXP_SEC1_048',
    subject: '신기술/보안',
    category: '정보보호 평가 기준',
    type: 'SHORT_ANSWER',
    question: 'CC(공통평가기준) 인증에서 평가 대상이 되는 정보보호 시스템 제품 또는 보안 소프트웨어를 가리키는 용어의 약칭은 무엇인가?',
    answer: 'TOE',
    explanation: 'TOE(Target of Evaluation, 평가 대상 제품)는 CC 인증 평가의 실제 대상체를 뜻합니다.',
    difficulty: 'MEDIUM',
    keywords: ['TOE', 'Target of Evaluation', '평가대상제품'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-cc',
  },
  {
    id: 'EXP_SEC1_049',
    subject: '신기술/보안',
    category: '정보보호 평가 기준',
    type: 'SHORT_ANSWER',
    question: 'CC 인증에서 특정 제품군(예: 방화벽 제품군)이 충족해야 하는 표준적인 보안 요구사항들을 정의해 둔 표준 문서를 무엇이라 하는가?',
    answer: '보호 프로파일',
    explanation: '보호 프로파일(PP, Protection Profile)은 소비자가 요구하는 공통 보안 명세서입니다. 특정 제조사 제품의 상세 보안 사양서는 보안 목표명세서(ST)입니다.',
    difficulty: 'MEDIUM',
    keywords: ['보호 프로파일', 'Protection Profile', 'PP'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-cc',
  },
  {
    id: 'EXP_SEC1_050',
    subject: '신기술/보안',
    category: '보안 철학',
    type: 'SHORT_ANSWER',
    question: '"아무것도 신뢰하지 말고 항상 모든 접근을 검증하라(Never Trust, Always Verify)"는 철학 아래 내부망 접근자라도 매번 엄격한 인증과 권한을 검증하는 차세대 보안 모델은 무엇인가?',
    answer: '제로 트러스트',
    explanation: '제로 트러스트(Zero Trust)는 경계 기반 보안의 한계를 극복하고 최소 권한 원칙과 지속적 검증을 적용합니다.',
    difficulty: 'EASY',
    keywords: ['제로 트러스트', 'Zero Trust', 'Always Verify'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-sec-zerotrust',
  },
];
