import { Question } from '../../src/types/question';

export const BATCH_2_QUESTIONS: Question[] = [
  {
    id: 'EXP_OS_001',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '운영체제 프로세스 상태 전이 중 준비(Ready) 상태에 있던 프로세스가 CPU를 할당받아 실행(Running) 상태로 전이되는 과정을 무엇이라 하는가?',
    answer: '디스패치',
    explanation: '디스패치(Dispatch)는 준비 큐의 맨 앞에 있던 프로세스가 CPU 스케줄러에 의해 CPU를 점유하여 실행 상태로 바뀌는 동작입니다.',
    difficulty: 'EASY',
    keywords: ['디스패치', 'Dispatch', '프로세스상태전이'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-process',
  },
  {
    id: 'EXP_OS_002',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '운영체제가 각 프로세스를 관리하고 제어하기 위해 프로세스의 식별자, 현재 상태, 레지스터 값 등을 저장하는 자료구조 블록의 약칭은 무엇인가?',
    answer: 'PCB',
    explanation: 'PCB(Process Control Block, 프로세스 제어 블록)는 운영체제가 프로세스마다 유지하는 핵심 메타데이터 저장 블록입니다.',
    difficulty: 'EASY',
    keywords: ['PCB', 'Process Control Block', '프로세스제어블록'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-process',
  },
  {
    id: 'EXP_OS_003',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '하나의 프로세스에서 다른 프로세스로 CPU의 제어권이 넘어갈 때 기존 프로세스의 상태를 PCB에 저장하고 새 프로세스의 상태를 레지스터로 복구하는 작업을 무엇이라 하는가?',
    answer: '문맥 교환',
    explanation: '문맥 교환(Context Switching)은 인터럽트나 스케줄링 시 발생하며, 잦은 문맥 교환은 시스템 오버헤드를 유발합니다.',
    difficulty: 'EASY',
    keywords: ['문맥 교환', 'Context Switching', 'PCB'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-process',
  },
  {
    id: 'EXP_OS_004',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '비선점 스케줄링 기법 중 실행 시간이 긴 프로세스가 무한정 대기하는 기아 현상(Starvation)을 방지하기 위해 대기 시간과 서비스(실행) 시간을 고려하여 에이징(Aging) 효과를 부여한 알고리즘은 무엇인가?',
    answer: 'HRN',
    explanation: 'HRN(Highest Response-ratio Next)은 우선순위 = (대기시간 + 서비스시간) / 서비스시간 공식을 사용하여 대기 시간이 길수록 우선순위를 높입니다.',
    difficulty: 'MEDIUM',
    keywords: ['HRN', '스케줄링', '기아현상해결'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-scheduling',
  },
  {
    id: 'EXP_OS_005',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '시분할 시스템을 위해 설계된 선점형 스케줄링 알고리즘으로, 각 프로세스에 동일한 크기의 CPU 시간 할당량(Time Quantum)을 부여하고 시간 초과 시 다음 프로세스로 넘기는 기법은 무엇인가?',
    answer: '라운드 로빈',
    explanation: '라운드 로빈(Round Robin, RR)은 시간 할당량이 너무 크면 FCFS처럼 작동하고, 너무 작으면 문맥 교환 오버헤드가 급증합니다.',
    difficulty: 'EASY',
    keywords: ['라운드 로빈', 'Round Robin', 'Time Quantum'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-scheduling',
  },
  {
    id: 'EXP_OS_006',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: 'SJF(최단 작업 우선) 알고리즘을 선점형 방식으로 변형한 것으로, 현재 실행 중인 프로세스의 남은 실행 시간보다 더 짧은 실행 시간을 가진 새 프로세스가 도착하면 CPU를 빼앗는 스케줄링 기법은 무엇인가?',
    answer: 'SRT',
    explanation: 'SRT(Shortest Remaining Time First)는 남은 처리 시간이 가장 짧은 프로세스에게 CPU를 선점시키는 기법입니다.',
    difficulty: 'MEDIUM',
    keywords: ['SRT', 'Shortest Remaining Time', '선점스케줄링'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-scheduling',
  },
  {
    id: 'EXP_OS_007',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '교착상태(Deadlock) 발생 4대 필요조건 중 한 번에 하나의 프로세스만이 자원을 독점적으로 사용할 수 있어야 한다는 조건은 무엇인가?',
    answer: '상호 배제',
    explanation: '상호 배제(Mutual Exclusion)는 자원을 동시에 공유할 수 없는 조건입니다. 나머지 3조건은 점유와 대기, 비선점, 환형 대기입니다.',
    difficulty: 'EASY',
    keywords: ['상호 배제', 'Mutual Exclusion', '교착상태조건'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-deadlock',
  },
  {
    id: 'EXP_OS_008',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '교착상태(Deadlock) 발생 4대 필요조건 중 다른 프로세스에 할당된 자원을 강제로 빼앗을 수 없고 점유한 프로세스가 자발적으로만 해제할 수 있다는 조건은 무엇인가?',
    answer: '비선점',
    explanation: '비선점(Non-preemption)은 강제로 자원을 회수하지 못하는 조건입니다. 선점을 허용하면 교착상태를 예방할 수 있습니다.',
    difficulty: 'EASY',
    keywords: ['비선점', 'Non-preemption', '교착상태'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-deadlock',
  },
  {
    id: 'EXP_OS_009',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '교착상태 발생 4대 필요조건 중 프로세스들이 순환 형태로 서로가 가진 자원을 요구하며 꼬리를 물고 무한 대기하는 조건은 무엇인가?',
    answer: '환형 대기',
    explanation: '환형 대기(Circular Wait)는 자원 할당 그래프에서 사이클을 형성하는 조건입니다. 자원에 번호를 매겨 한 방향으로만 요구하게 하면 예방됩니다.',
    difficulty: 'EASY',
    keywords: ['환형 대기', 'Circular Wait', '교착상태'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-deadlock',
  },
  {
    id: 'EXP_OS_010',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '교착상태 해결 방법 중 다익스트라(Dijkstra)가 제안한 기법으로, 자원 할당 전 시스템이 안전 상태(Safe State)를 유지할 수 있는지 사전에 검사하여 교착상태를 회피하는 대표 알고리즘은 무엇인가?',
    answer: '은행가 알고리즘',
    explanation: '은행가 알고리즘(Banker\'s Algorithm)은 안전 상태일 때만 자원을 할당하는 대표적인 교착상태 회피(Avoidance) 알고리즘입니다.',
    difficulty: 'MEDIUM',
    keywords: ['은행가 알고리즘', 'Banker', '교착상태회피'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-deadlock',
  },
  {
    id: 'EXP_OS_011',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '메모리 배치(Placement) 전략 중 들어갈 수 있는 빈 메모리 공간들 중 크기가 요구량에 가장 딱 맞아서 내부 단편화를 최소화할 수 있는 공간을 찾아 배치하는 기법은 무엇인가?',
    answer: 'Best Fit',
    explanation: '최적 적합(Best Fit)은 잔여 단편화 공간을 최소화하지만 매우 작은 쓸모없는 자투리 공간을 많이 남기는 단점이 있습니다. 첫 발견 공간에 넣는 것은 First Fit입니다.',
    difficulty: 'EASY',
    keywords: ['Best Fit', '최적적합', '메모리배치'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-memory',
  },
  {
    id: 'EXP_OS_012',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '메모리 배치 전략 중 메모리의 첫 주소부터 검색하여 프로세스가 들어갈 수 있는 크기의 첫 번째 빈 공간을 발견하자마자 즉시 배치하는 기법은 무엇인가?',
    answer: 'First Fit',
    explanation: '최초 적합(First Fit)은 검색 속도가 가장 빠르며 오버헤드가 적은 메모리 배치 기법입니다.',
    difficulty: 'EASY',
    keywords: ['First Fit', '최초적합', '메모리배치'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-memory',
  },
  {
    id: 'EXP_OS_013',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '가상 메모리 관리 기법 중 가상 기억장치의 프로그램을 동일한 크기의 고정된 블록 단위로 분할하여 관리하는 기법은 무엇인가?',
    answer: '페이징',
    explanation: '페이징(Paging)은 고정 크기 블록(페이지)으로 나누어 외부 단편화를 해결하지만, 마지막 페이지에서 내부 단편화가 발생할 수 있습니다. 가변 논리 단위 분할은 세그멘테이션입니다.',
    difficulty: 'EASY',
    keywords: ['페이징', 'Paging', '가상메모리'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-memory',
  },
  {
    id: 'EXP_OS_014',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '가상 메모리 관리 기법 중 프로그램을 코드, 데이터, 스택 등 논리적인 의미를 지닌 서로 다른 가변 크기의 단위로 분할하여 관리하는 기법은 무엇인가?',
    answer: '세그멘테이션',
    explanation: '세그멘테이션(Segmentation)은 가변 크기 단위로 나누어 내부 단편화를 없애지만, 외부 단편화가 발생할 수 있습니다.',
    difficulty: 'EASY',
    keywords: ['세그멘테이션', 'Segmentation', '가상메모리'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-memory',
  },
  {
    id: 'EXP_OS_015',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '페이지 교체 알고리즘 중 가장 오랫동안 참조되지 않은(가장 과거에 사용된) 페이지를 교체 대상으로 선택하는 기법의 약칭은 무엇인가?',
    answer: 'LRU',
    explanation: 'LRU(Least Recently Used)는 최근 사용 시간(시간적 참조 국부성)을 기준으로 가장 오래 참조되지 않은 페이지를 내보냅니다.',
    difficulty: 'EASY',
    keywords: ['LRU', 'Least Recently Used', '페이지교체'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-replacement',
  },
  {
    id: 'EXP_OS_016',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '페이지 교체 알고리즘 중 과거에 사용된 횟수(참조 빈도)가 가장 적은 페이지를 교체 대상으로 선택하는 기법의 약칭은 무엇인가?',
    answer: 'LFU',
    explanation: 'LFU(Least Frequently Used)는 참조 횟수를 카운트하여 가장 적게 참조된 페이지를 교체합니다.',
    difficulty: 'EASY',
    keywords: ['LFU', 'Least Frequently Used', '페이지교체'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-replacement',
  },
  {
    id: 'EXP_OS_017',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '페이지 교체 알고리즘 중 참조 비트(Reference Bit)와 변형 비트(Modified Bit)를 조합(00, 01, 10, 11)하여 교체 대상을 결정하는 알고리즘은 무엇인가?',
    answer: 'NUR',
    explanation: 'NUR(Not Used Recently, 최근 미사용) 알고리즘은 2비트를 사용하여 오버헤드를 줄이며 LRU와 유사한 성능을 냅니다.',
    difficulty: 'MEDIUM',
    keywords: ['NUR', 'Not Used Recently', '참조비트'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-replacement',
  },
  {
    id: 'EXP_OS_018',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '프로세스가 실행되는 동안 자주 발생하는 페이지 부재(Page Fault)로 인해 프로세스 실행 시간보다 페이지 교체 시간이 더 많아져 CPU 사용률이 급격히 떨어지는 현상을 무엇이라 하는가?',
    answer: '스래싱',
    explanation: '스래싱(Thrashing)은 다중 프로그래밍 정도가 너무 높아져 발생합니다. 워킹셋이나 페이지 부재 빈도(PFF) 조절로 예방합니다.',
    difficulty: 'EASY',
    keywords: ['스래싱', 'Thrashing', '페이지부재'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-memory',
  },
  {
    id: 'EXP_OS_019',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '데닝(Denning)이 제안한 기법으로, 스래싱을 방지하기 위해 프로세스가 일정 시간 동안 자주 참조하는 페이지 집합을 주기억장치에 상주시켜 유지하는 모델은 무엇인가?',
    answer: '워킹셋',
    explanation: '워킹셋(Working Set)은 프로세스가 자주 사용하는 페이지 집합을 메모리에 적재하여 페이지 부재를 최소화합니다.',
    difficulty: 'EASY',
    keywords: ['워킹셋', 'Working Set', '스래싱방지'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-memory',
  },
  {
    id: 'EXP_OS_020',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '프로세스의 페이지 부재율에 상한선과 하한선을 설정하여, 상한을 넘으면 페이지 프레임을 추가 할당하고 하한 밑으로 떨어지면 회수하는 스래싱 방지 기법의 약칭은 무엇인가?',
    answer: 'PFF',
    explanation: 'PFF(Page Fault Frequency, 페이지 부재 빈도)는 부재율을 기반으로 프로세스별 페이지 프레임 수를 동적으로 조절합니다.',
    difficulty: 'MEDIUM',
    keywords: ['PFF', 'Page Fault Frequency', '페이지부재빈도'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-memory',
  },
  {
    id: 'EXP_OS_021',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '리눅스/유닉스에서 파일이나 디렉터리의 읽기(r), 쓰기(w), 실행(x) 접근 권한 모드를 변경할 때 사용하는 명령어는 무엇인가?',
    answer: 'chmod',
    explanation: 'chmod(change mode)는 파일 접근 권한을 8진수(예: 755, 644)나 기호 모드로 변경합니다. 소유자 변경은 chown입니다.',
    difficulty: 'EASY',
    keywords: ['chmod', '권한변경', '리눅스명령어'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-unix',
  },
  {
    id: 'EXP_OS_022',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '리눅스/유닉스에서 파일이나 디렉터리의 소유자(Owner) 또는 소유 그룹을 변경할 때 사용하는 명령어는 무엇인가?',
    answer: 'chown',
    explanation: 'chown(change owner)은 파일 소유권과 그룹 소유권을 변경하는 명령어입니다.',
    difficulty: 'EASY',
    keywords: ['chown', '소유자변경', '리눅스명령어'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-unix',
  },
  {
    id: 'EXP_OS_023',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '리눅스/유닉스 시스템 호출(System Call) 중 현재 실행 중인 부모 프로세스의 메모리를 완벽히 복제하여 새로운 자식 프로세스를 생성하는 함수는 무엇인가?',
    answer: 'fork',
    explanation: 'fork()는 기존 프로세스를 복제하여 PID가 다른 새 프로세스를 생성합니다. 생성된 자식 프로세스에 새 프로그램을 덮어씌워 실행하는 것은 exec()입니다.',
    difficulty: 'EASY',
    keywords: ['fork', '자식프로세스생성', '시스템콜'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-unix',
  },
  {
    id: 'EXP_OS_024',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '리눅스/유닉스에서 현재 시스템에서 실행 중인 프로세스들의 목록과 PID, 상태 등을 조회할 때 사용하는 기본 명령어는 무엇인가?',
    answer: 'ps',
    explanation: 'ps(process status)는 현재 활성 프로세스들을 조회합니다. 실시간 모니터링은 top 명령어를 씁니다.',
    difficulty: 'EASY',
    keywords: ['ps', '프로세스조회', 'PID'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-unix',
  },
  {
    id: 'EXP_OS_025',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '리눅스/유닉스에서 지정된 프로세스 ID(PID)에 특정 시그널(예: SIGKILL 9번)을 전달하여 비정상 프로세스를 강제 종료시킬 때 사용하는 명령어는 무엇인가?',
    answer: 'kill',
    explanation: 'kill 명령어는 프로세스에 종료 시그널(kill -9 PID)을 전송하여 프로세스를 종료합니다.',
    difficulty: 'EASY',
    keywords: ['kill', '프로세스종료', '시그널'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-unix',
  },
  {
    id: 'EXP_OS_026',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '리눅스/유닉스에서 파일 내용 중 특정 정규표현식 패턴이나 문자열이 포함된 줄을 검색하여 출력해주는 필터 명령어는 무엇인가?',
    answer: 'grep',
    explanation: 'grep(global regular expression print)은 텍스트 파일이나 파이프 스트림에서 지정된 패턴을 검색하는 대표 필터입니다.',
    difficulty: 'EASY',
    keywords: ['grep', '패턴검색', '리눅스필터'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-unix',
  },
  {
    id: 'EXP_OS_027',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '리눅스/유닉스 쉘에서 현재 작업 중인 디렉터리의 절대 경로(Print Working Directory)를 화면에 출력하는 명령어는 무엇인가?',
    answer: 'pwd',
    explanation: 'pwd는 현재 작업 디렉터리의 전체 경로를 출력합니다.',
    difficulty: 'EASY',
    keywords: ['pwd', '현재디렉터리', '절대경로'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-unix',
  },
  {
    id: 'EXP_OS_028',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '리눅스 파일 접근 권한에서 소유자에게 읽기(r=4), 쓰기(w=2), 실행(x=1) 권한을 모두 부여할 때 해당하는 8진수 숫자는 무엇인가?',
    answer: '7',
    explanation: 'r(4) + w(2) + x(1) = 7 입니다. 읽기와 쓰기만 부여하면 6, 읽기와 실행만 부여하면 5가 됩니다.',
    difficulty: 'EASY',
    keywords: ['7', '8진수권한', 'chmod'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-unix',
  },
  {
    id: 'EXP_OS_029',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '페이지 부재율을 줄이기 위해 페이지 프레임 수를 늘려주었음에도 불구하고 오히려 페이지 부재 횟수가 증가하는 이상 현상을 무엇이라 하는가?',
    answer: '벨레이디의 모순',
    explanation: '벨레이디의 모순(Belady\'s Anomaly)은 주로 FIFO 페이지 교체 알고리즘에서 프레임 수를 늘릴 때 나타나는 역설적 현상입니다.',
    difficulty: 'MEDIUM',
    keywords: ['벨레이디의 모순', 'Belady', 'FIFO이상현상'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-replacement',
  },
  {
    id: 'EXP_OS_030',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '임계 영역(Critical Section)에서 둘 이상의 프로세스가 공유 자원에 동시에 접근하려고 경쟁할 때 접근 순서에 따라 실행 결과가 달라지는 상황을 무엇이라 하는가?',
    answer: '경쟁 상태',
    explanation: '경쟁 상태(Race Condition)는 동기화 메커니즘이 부재할 때 발생하며, 뮤텍스(Mutex)나 세마포어(Semaphore)로 상호 배제를 달성해야 합니다.',
    difficulty: 'MEDIUM',
    keywords: ['경쟁 상태', 'Race Condition', '동기화'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-sync',
  },
  {
    id: 'EXP_OS_031',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '공유 자원에 대한 접근을 동기화하기 위해 다익스트라가 고안한 정수형 변수 기반의 동기화 도구로 P(wait)와 V(signal) 연산을 사용하는 것은 무엇인가?',
    answer: '세마포어',
    explanation: '세마포어(Semaphore)는 정수형 변수 S를 이용해 다수의 자원 접근을 제어합니다. 단 1개의 스레드만 허용하는 락은 뮤텍스(Mutex)입니다.',
    difficulty: 'EASY',
    keywords: ['세마포어', 'Semaphore', '동기화도구'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-sync',
  },
  {
    id: 'EXP_OS_032',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '하나의 프로세스 내에서 실행 흐름의 최소 단위로, 코드/데이터/힙 영역은 공유하고 독립적인 스택과 레지스터 집합만을 갖는 경량 프로세스를 무엇이라 하는가?',
    answer: '스레드',
    explanation: '스레드(Thread)는 프로세스 자원을 공유하여 생성 및 문맥 교환 비용이 프로세스보다 훨씬 가볍습니다.',
    difficulty: 'EASY',
    keywords: ['스레드', 'Thread', '경량프로세스'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-process',
  },
  {
    id: 'EXP_OS_033',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '동일 프로세스 내에서 자원을 공유하는 다중 스레드 구조에서 한 스레드의 메모리 훼손이 전체 프로세스로 번질 수 있는 단점에도 불구하고 스레드를 사용하는 가장 큰 성능상 장점은 무엇인가?',
    answer: '문맥 교환 오버헤드 감소',
    explanation: '스레드는 코드/데이터/힙 공간을 공유하므로 캐시 메모리를 비우지 않아 문맥 교환 속도가 매우 빠릅니다.',
    difficulty: 'MEDIUM',
    keywords: ['문맥 교환 오버헤드 감소', '스레드장점'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-process',
  },
  {
    id: 'EXP_OS_034',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '자식 프로세스가 종료되었으나 부모 프로세스가 wait() 호출로 종료 상태를 회수하지 않아 프로세스 테이블에 남아있는 프로세스를 무엇이라 하는가?',
    answer: '좀비 프로세스',
    explanation: '좀비 프로세스(Zombie Process)는 실행은 끝났지만 PID와 종료 코드가 프로세스 테이블에 잔존하는 프로세스입니다.',
    difficulty: 'MEDIUM',
    keywords: ['좀비 프로세스', 'Zombie', 'wait'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-process',
  },
  {
    id: 'EXP_OS_035',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '부모 프로세스가 자식 프로세스보다 먼저 종료되어 고아가 된 프로세스를 거두어 새로운 부모가 되어주는 유닉스 최상위 1번 프로세스는 무엇인가?',
    answer: 'init',
    explanation: 'init(또는 현대 리눅스의 systemd) 프로세스는 부모를 잃은 고아 프로세스를 입양하여 종료 시 정상 회수합니다.',
    difficulty: 'MEDIUM',
    keywords: ['init', '고아프로세스', 'PID 1'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-process',
  },
  {
    id: 'EXP_OS_036',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '기억장치 단편화 해결 기법 중 흩어져 있는 작은 빈 공간들을 하나로 모아 큰 단편화 공간을 만드는 작업을 무엇이라 하는가?',
    answer: '메모리 압축',
    explanation: '메모리 압축(Compaction, 쓰레기 수집)은 외부 단편화를 해결하기 위해 프로세스들을 재배치하여 공간을 하나로 합칩니다.',
    difficulty: 'EASY',
    keywords: ['메모리 압축', 'Compaction', '단편화해결'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-memory',
  },
  {
    id: 'EXP_OS_037',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '프로세스가 기억장치 내의 특정 영역을 단기간에 집중적으로 참조하는 특성으로, 시간적 구역성과 공간적 구역성으로 나뉘는 개념은 무엇인가?',
    answer: '국부성',
    explanation: '국부성(Locality, 지역성)은 캐시 및 가상 메모리 페이징 기법의 성능 보장에 핵심이 되는 이론적 근거입니다.',
    difficulty: 'EASY',
    keywords: ['국부성', '지역성', 'Locality'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-memory',
  },
  {
    id: 'EXP_OS_038',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '최근에 한 번 참조된 메모리 위치는 가까운 미래에 곧바로 다시 참조될 가능성이 높다는 국부성(Locality)의 종류는 무엇인가?',
    answer: '시간 구역성',
    explanation: '시간 구역성(Temporal Locality)의 대표적인 예로는 루프(반복문) 제어 변수, 스택 등이 있습니다. 근처 주소를 참조하는 것은 공간 구역성입니다.',
    difficulty: 'EASY',
    keywords: ['시간 구역성', 'Temporal Locality', '지역성'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-memory',
  },
  {
    id: 'EXP_OS_039',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '프로그램 실행 시 한 메모리 위치가 참조되면 그 인접한 주소에 위치한 데이터들이 곧이어 참조될 가능성이 높다는 국부성의 종류는 무엇인가?',
    answer: '공간 구역성',
    explanation: '공간 구역성(Spatial Locality)의 대표적 예로는 배열 순차 순회, 명령 코드의 순차 실행 등이 있습니다.',
    difficulty: 'EASY',
    keywords: ['공간 구역성', 'Spatial Locality', '배열순회'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-memory',
  },
  {
    id: 'EXP_OS_040',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: 'CPU에서 물리적 주소 변환 속도를 높이기 위해 페이지 테이블의 최근 변환 항목들을 임시 캐싱해두는 고속 하드웨어 캐시 메모리의 약칭은 무엇인가?',
    answer: 'TLB',
    explanation: 'TLB(Translation Lookaside Buffer, 변환 색인 버퍼)는 가상 주소를 물리 주소로 고속 변환해 주는 연관 사상 캐시입니다.',
    difficulty: 'MEDIUM',
    keywords: ['TLB', 'Translation Lookaside Buffer', '주소변환'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-memory',
  },
  {
    id: 'EXP_OS_041',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '비선점 스케줄링 기법 중 준비 큐에 먼저 도착한 프로세스에게 CPU를 먼저 할당하여 작업이 끝날 때까지 수행시키는 가장 단순한 방식의 약칭은 무엇인가?',
    answer: 'FCFS',
    explanation: 'FCFS(First-Come First-Served)는 도착 순서대로 처리하므로 긴 작업이 먼저 오면 짧은 작업이 뒤에서 오래 기다리는 콘보이 효과(Convoy Effect)가 발생합니다.',
    difficulty: 'EASY',
    keywords: ['FCFS', 'First-Come First-Served', '콘보이효과'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-scheduling',
  },
  {
    id: 'EXP_OS_042',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '비선점 스케줄링 기법 중 CPU 요구(실행) 시간이 가장 짧은 프로세스에게 우선적으로 CPU를 할당하여 평균 대기시간을 최소화하는 방식의 약칭은 무엇인가?',
    answer: 'SJF',
    explanation: 'SJF(Shortest Job First)는 평균 대기시간을 최소화하지만, 긴 작업이 계속 밀리는 기아 현상(Starvation)이 발생할 수 있습니다.',
    difficulty: 'EASY',
    keywords: ['SJF', 'Shortest Job First', '평균대기시간최소화'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-scheduling',
  },
  {
    id: 'EXP_OS_043',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '준비 큐를 여러 개로 분할하여 각각 다른 우선순위와 스케줄링 방식을 부여하되, 프로세스가 큐 사이를 이동할 수 없는 스케줄링 기법은 무엇인가?',
    answer: '다단계 큐',
    explanation: '다단계 큐(Multilevel Queue)는 큐 간 이동이 불가합니다. 반면 하위 큐의 프로세스가 너무 오래 기다리면 상위 큐로 올려주는(Aging) 방식은 다단계 피드백 큐입니다.',
    difficulty: 'MEDIUM',
    keywords: ['다단계 큐', 'Multilevel Queue', '스케줄링'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-scheduling',
  },
  {
    id: 'EXP_OS_044',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '프로세스가 CPU를 점유 중일 때 입출력 완료나 타이머 종료와 같은 외부 사건이 발생하여 CPU에게 즉시 처리를 요청하고 제어권을 넘기는 하드웨어 신호는 무엇인가?',
    answer: '인터럽트',
    explanation: '인터럽트(Interrupt)가 발생하면 CPU는 현재 작업을 중단하고 인터럽트 서비스 루틴(ISR)을 실행합니다.',
    difficulty: 'EASY',
    keywords: ['인터럽트', 'Interrupt', 'ISR'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-interrupt',
  },
  {
    id: 'EXP_OS_045',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '프로그램 실행 중 0으로 나누기(Divide by Zero)나 잘못된 메모리 주소 참조 등 비정상적인 상황에 의해 CPU 내부에서 자체적으로 발생하는 인터럽트는 무엇인가?',
    answer: '트랩',
    explanation: '트랩(Trap) 또는 내부 인터럽트는 소프트웨어 예외 상황 시 CPU 내부에서 발생합니다. 입출력 등 하드웨어 장치에 의한 것은 외부 인터럽트입니다.',
    difficulty: 'MEDIUM',
    keywords: ['트랩', 'Trap', '내부인터럽트'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-interrupt',
  },
  {
    id: 'EXP_OS_046',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '리눅스/유닉스에서 실행 중인 프로세스의 백그라운드 작업을 포그라운드로 가져오거나 백그라운드로 전환할 때 사용하는 약어 명령어는 무엇인가?',
    answer: 'fg',
    explanation: 'fg(foreground)는 백그라운드 작업을 전면으로 가져오며, bg는 일시 정지된 작업을 백그라운드에서 재개합니다.',
    difficulty: 'EASY',
    keywords: ['fg', '포그라운드', '작업제어'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-unix',
  },
  {
    id: 'EXP_OS_047',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '리눅스/유닉스에서 파일 생성 시 기본으로 부여되는 접근 권한에서 제외할 권한 비트를 마스킹(설정)하는 명령어는 무엇인가?',
    answer: 'umask',
    explanation: 'umask는 기본 파일 생성 권한(666)이나 디렉터리 권한(777)에서 마스크 값을 차감하여 초기 권한을 결정합니다.',
    difficulty: 'MEDIUM',
    keywords: ['umask', '권한마스크', '기본권한'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-unix',
  },
  {
    id: 'EXP_OS_048',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '리눅스/유닉스에서 빈 파일을 생성하거나 기존 파일의 최종 수정 시간을 현재 시간으로 갱신할 때 사용하는 명령어는 무엇인가?',
    answer: 'touch',
    explanation: 'touch 명령어는 크기가 0인 빈 파일을 만들거나 타임스탬프를 갱신합니다.',
    difficulty: 'EASY',
    keywords: ['touch', '파일생성', '타임스탬프'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-unix',
  },
  {
    id: 'EXP_OS_049',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '리눅스/유닉스 파일 시스템의 최상위 루트 디렉터리를 나타내는 기호는 무엇인가?',
    answer: '/',
    explanation: '/(슬래시)는 유닉스 계열 파일 시스템의 최상위 루트 디렉터리를 의미합니다. 윈도우의 C:\\ 와 대응됩니다.',
    difficulty: 'EASY',
    keywords: ['/', '루트디렉터리', '파일시스템'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-unix',
  },
  {
    id: 'EXP_OS_050',
    subject: '프로그래밍언어활용',
    category: '운영체제',
    type: 'SHORT_ANSWER',
    question: '리눅스에서 명령어의 표준 출력을 다른 명령어의 표준 입력으로 직접 연결해 주는 파이프라인 기호는 무엇인가?',
    answer: '|',
    explanation: '|(파이프)는 한 명령어의 출력 결과를 다음 명령어의 입력으로 파이프라이닝할 때 사용합니다 (예: ps -ef | grep java).',
    difficulty: 'EASY',
    keywords: ['|', '파이프', '리눅스기호'],
    source: 'VERIFIED_CORE',
    chapterId: 'ch-prog-os-unix',
  },
];
